### ISSUE TITLE
API: keep both cascaded_union and unary_union functions?

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Shapely#1001]
Originally, GEOS did have `cascased_union` operation, and `unary_union` was added later with better behaviour. Since GEOS 3.3, `GEOSUnionCascaded_r` is actually deprecated in favor of the `unary_union` version.  
In Shapely, similarly a `unary_union` function was added to `shapely.ops` in addition to `cascaded_union`. But as long as you have GEOS = 3.3, the `cascaded_union` in Shapely is actually a simple alias for `unary_union`, and no longer having different behaviour/implementation:

https://github.com/Toblerity/Shapely/blob/eae4dcbedb0756f658f9982825d5fa23b0061b2a/shapely/geos.py#L838

So I am mainly opening an issue to ask: do we want to keep `cascaded_union` as an alias forever, or do we actually want to deprecate it (raise a warning) and have people move to use `unary_union` ?

(note this is only about the `shapely.ops` function, on the Geometry classes, there is only a `unary_union` attribute, not a `cascaded_union` one)

**Comment by mwtoews** [comment]
I think `ops.cascaded_union` can be deprecated with shapely-1.8. Also, note that GEOS 3.3.0 was released on 2011-05-30, so I would expect the vast majority of users to have `unary_union` available to switch/use.

**Comment by jorisvandenbossche** [comment]
> Also, note that GEOS 3.3.0 was released on 2011-05-30, so I would expect the vast majority of users to have unary_union available to switch/use.

Shapely actually requires GEOS 3.3 as a minimum to build Shapely from source:

https://github.com/Toblerity/Shapely/blob/eae4dcbedb0756f658f9982825d5fa23b0061b2a/setup.py#L140-L144

So given that, I think that even *all* users should have `unary_union` available?

**Comment by jorisvandenbossche** [comment]
But, so, also +1 on deprecating it in Shapely 1.8
