### ISSUE TITLE
nearest_points() ignoring z coordinates

### ISSUE THREAD

**Issue by Michael-P-Crisp** [Toblerity/Shapely#1016]
## Expected behavior and actual behavior.

nearest_points() would intuitively return points that contain contain z coordinate information if the source geometry has z information associated with it. However all returned points only contain x, y information. The ability to for it to retain z information would be useful for many reasons.

Note that other shapely functions like the LineString.interpolate() method do return z information.

## Steps to reproduce the problem.

Use shapely_points() on any geometry with z coordinates.

## Operating system

Windows 10

## Shapely version and provenance

1.6.4.post1

**Comment by sgillies** [comment]
@Michael-P-Crisp as pointed out in #1006 GEOS doesn't provide Z for nearest points. Z values have only limited and spotty support in GEOS. Make that support universal is out of scope for Shapely.
