### ISSUE TITLE
Rotation of Polygon leading to offset

### ISSUE THREAD

**Issue by ngodber** [Toblerity/Shapely#1029]
## Expected behavior and actual behavior.

I am rotating a polygon to be parallel to its minimum rotated rectangle, performing some processing and then taking the result and rotating it back to the original reference frame. I noticed however that there was a strange offset being introduced. Some further debugging and I confirmed that this was happening as a result of the shapely.affinity.rotate operations.

![image](https://user-images.githubusercontent.com/11834846/99360805-dc6e0700-28fc-11eb-815b-0c7fd3dc5cea.png)
 This image shows the original polygon, and then same polygon after being rotated clockwise 0.7638 radians and then counter clockwise 0.7638 radians. I noted with suprise that even the centroid _changes_ after the rotation which does not make sense. 

Testing the same process but using a simple polygon does not result in this error. The polygon itself is generated by shapely doing a polygonize_full operation. I note that the coordinate precision is excessive (units are in meters) and so suspect that maybe we are seeing some form of numerical error. But I am very surprised as to the magnitude of the effect which suggests otherwise. 

## Steps to reproduce the problem.

Script to generate error

    rotated_polygon = shapely.affinity.rotate(polygon, 0.7638, use_radians=True)
    rotated_polygon = shapely.affinity.rotate(rotated_polygon, -0.7638, use_radians=True)

    fig, ax = plt.subplots()
    ax.plot(polygon.boundary.coords.xy[0], polygon.boundary.coords.xy[1], 'b-')
    ax.plot(rotated_polygon.boundary.coords.xy[0], rotated_polygon.boundary.coords.xy[1], 'y-')
    plt.show()

I've also upload a wkb of the polygon in question to aid in reproduction. 

## Operating system

Windows 10 x64

## Shapely version and provenance

1.7.0 Anaconda

**Comment by ngodber** [comment]
[temp.zip](https://github.com/Toblerity/Shapely/files/5551998/temp.zip)

**Comment by ngodber** [comment]
Implemented my own affine rotation using the Affine library and the coordinates of the polygon (eg np.asarray(polygon.boundary)) and it doesnt suffer this issue. Depending on how things are implemented under the hood, either its a GEOS or Shapely specific issue.

**Comment by mwtoews** [comment]
Hi @ngodber , I haven't had a chance to take a close look, but I'm certain that the issue is to do with the `origin`, which has a default of `'center'` for the bounding box center. Using `origin='centroid'` should fix a stable rotation point.

**Comment by Jeremiah-England** [comment]
Sorry about the confusion, @ngodber. I hope implementing another rotation was not that difficult!

At first it seemed to me like the center of the bounding box should be the same after rotation. But that is only true when rotated by some multiple of 90 degrees. So, like @mwtoews said, this can be explained by the fact that by default we are rotating on the center of the bounding box and not the polygon itself. 

Here is a visualization. The points are at the centers of the bounding boxes. The magenda is the intermediate stage before rotating back. 

<details>
<summary>Code</summary>

```python
import shapely
from shapely import wkb
from shapely.geometry import Polygon, box
import matplotlib.pyplot as plt

with open('shapely-1029.wkb', 'rb') as f:
    polygon = wkb.loads(f.read())

rotated = shapely.affinity.rotate(polygon, 0.7638, use_radians=True)
rotated_back = shapely.affinity.rotate(rotated, -0.7638, use_radians=True)

polygon_box = box(*polygon.bounds)
rotated_box = box(*rotated.bounds)

fig, ax = plt.subplots()
ax.plot(polygon.boundary.coords.xy[0], polygon.boundary.coords.xy[1], 'b-')
ax.plot(polygon_box.boundary.coords.xy[0], polygon_box.boundary.coords.xy[1], 'b-')
ax.scatter(*polygon_box.centroid.coords[0], c='blue')
ax.plot(rotated.boundary.coords.xy[0], rotated.boundary.coords.xy[1], 'm-')
ax.plot(rotated_box.boundary.coords.xy[0], rotated_box.boundary.coords.xy[1], 'm-')
ax.scatter(*rotated_box.centroid.coords[0], c='magenta')
ax.plot(rotated_back.boundary.coords.xy[0], rotated_back.boundary.coords.xy[1], 'y-')
plt.show()
```

</details>

![image](https://user-images.githubusercontent.com/34973839/99916950-575b6700-2cdb-11eb-84a9-55cfcca11391.png)

Using `origin='centroid'` does solve the issue: 

```python
rotated_polygon = shapely.affinity.rotate(polygon, 0.7638, use_radians=True, origin='centroid')
rotated_polygon = shapely.affinity.rotate(rotated_polygon, -0.7638, use_radians=True, origin='centroid')

fig, ax = plt.subplots()
ax.plot(polygon.boundary.coords.xy[0], polygon.boundary.coords.xy[1], 'b-')
ax.plot(rotated_polygon.boundary.coords.xy[0], rotated_polygon.boundary.coords.xy[1], 'y-')
plt.show()
```

![image](https://user-images.githubusercontent.com/34973839/99917120-49f2ac80-2cdc-11eb-9f05-3a4b9f17a9cb.png)

**Comment by ngodber** [comment]
Ah I see. Given this non obvious result, perhaps it would be sensible to use 'centroid' or 'origin' as default? Anyway, nevertheless, thanks for the help!
