### ISSUE TITLE
RuntimeError: Polyfit sanity test emitted a warning

### ISSUE THREAD

**Issue by marianhlavac** [Toblerity/Shapely#1030]
Error when importing from `shapely.geometry.polygon` while running unit tests using pytest.

```
live/coap_server/pipes/geofencing.py:1: in <module>
    from shapely.geometry.polygon import Polygon
/usr/local/lib/python3.9/site-packages/shapely/geometry/__init__.py:4: in <module>
    from .base import CAP_STYLE, JOIN_STYLE
/usr/local/lib/python3.9/site-packages/shapely/geometry/base.py:35: in <module>
    import numpy as np
/usr/local/lib/python3.9/site-packages/numpy/__init__.py:286: in <module>
    raise RuntimeError(msg)
E   RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
E   RankWarning: Polyfit may be poorly conditioned
----------------------- Captured stderr -------------------------------
Python(56008,0x109815dc0) malloc: can't allocate region
:*** mach_vm_map(size=18446744072344657920, flags: 100) failed (error code=3)
Python(56008,0x109815dc0) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
```

## System

macOS 10.15.6

## Shapely version and provenance

shapely==1.7.1 using pip3
Python 3.9.0

**Comment by mahrton** [comment]
same here, have you figured it out in the meanwhile?

**Comment by Jeremiah-England** [comment]
I think this either has to do with https://github.com/numpy/numpy/issues/15947 or https://github.com/numpy/numpy/issues/17482 (a tip from https://github.com/ReagentX/purple_air_api/issues/63). All the line it's failing on in `base.py` does try to import `numpy`. 

https://github.com/Toblerity/Shapely/blob/edcb12a86150dee8c8bf61b43c76231372ca8c38/shapely/geometry/base.py#L34-L38

Shapely doesn't require that you have `numpy` installed, but it can take advantage of it if you do. So it tries to import and catches on an `ImportError` in case `numpy` is not installed. In this case, `numpy` *is* installed but installed in a way that raises a `RuntimeError` when you try to import it. 

As I see the problem there are two solutions: 

1. Fix the bad `numpy` installation. Maybe the linked issues above will help installing `numpy` so it works.
2. Remove the bad `numpy` installation and use `shapely` without it.
 
Others can correct me if I'm wrong, but I think there won't be any perfomance differences between vanilla `shapely` and `numpy` + `shapely` unless you are using the `vectorized` module (which I don't think imports without `numpy`.)

**Comment by mahrton** [comment]
> Others can correct me if I'm wrong, but I think there won't be any perfomance differences between vanilla `shapely` and `numpy` + `shapely` unless you are using the `vectorized` module (which I don't think imports without `numpy`.)

Thank you very much for the detailed answer, I appreciate it a lot. I do wonder though if this exception could be caught and then fall back to not using numpy.

I started getting this error since I have upgraded to Big Sur. Starting to seem like upgrading has not been a good idea.

**Comment by jorisvandenbossche** [comment]
> I started getting this error since I have upgraded to Big Sur. Starting to seem like upgrading has not been a good idea.

Indeed, Python itself and many of the packages are at the moment not yet fully updated to work on Big Sur.

**Comment by sgillies** [comment]
According to python.org, Python 3.9.1 is the only versions that is expected to work with macOS 11. I've had reports that the Shapely 1.7.1 wheel on PyPI works with 3.9.1.
