### ISSUE TITLE
Homogenize Collections

### ISSUE THREAD

**Issue by jamesmyatt** [Toblerity/Shapely#1074]
I have some collections of GeometryCollection objects and I'd like to simplify them to homogenous geometry types (where possible). For example:

* `GEOMETRYCOLLECTION (POINT (40 10))` --> `POINT (40 10)`
* `GEOMETRYCOLLECTION (POLYGON ((40 40, 20 45, 45 30, 40 40)))` --> `POLYGON ((40 40, 20 45, 45 30, 40 40))`
* `GEOMETRYCOLLECTION (POINT (10 40),POINT (40 30))` --> `MULTIPOINT ((10 40), (40 30))`
* `MULTIPOINT ((10 40))` --> `POINT (10 40)`
* etc

What's the easiest way to do this in Python? In PostGIS, there is a `ST_CollectionHomogenize` function: https://postgis.net/docs/ST_CollectionHomogenize.html.

Furthermore, it would also be good to be able to do this to the whole collection of geometries, e.g.:

* `[GEOMETRYCOLLECTION (POINT (40 10)), GEOMETRYCOLLECTION (POINT (10 40),POINT (40 30))]` -->`[MULTIPOINT ((40 10)), MULTIPOINT ((10 40), (40 30))]`

What do you think?

**Comment by sgillies** [comment]
Closed, like #1073.

**Comment by jamesmyatt** [comment]
Sorry. Didn't realise I'd made two issues.
