### ISSUE TITLE
QUESTION: Including additional dimensions (which are all handled like the z-axis)

### ISSUE THREAD

**Issue by rkmaddox** [Toblerity/Shapely#1091]
I am doing some work with data that have four dimensions: x, y, depth (z), and a rotation angle (a). Basically at each point (x, y) there are additional values. I am then using set operators based on just x and y, but I want z and a to "go along for the ride" and either stay or go based on their x and y values, or be interpolated as the case may be.

Is there any way to accomplish this? I have a couple ideas for potential workarounds, but they're pretty awful, whereas the way the z-axis is handled is exactly right for my needs--I just need more than one of those axes.

Any suggestions are appreciated.

**Comment by sgillies** [comment]
Shapely cannot help you with this. Z doesn't even always come along for the ride. The GEOS library is not entirely consistent about this.

**Comment by rkmaddox** [comment]
Got it. Thanks for the quick response.

**Comment by mwtoews** [comment]
While fumbly and not-so-pythonic, GDAL's `osgeo.ogr` module suppots XYZM dimensions.

**Comment by rkmaddox** [comment]
@mwtoews Thanks, I'll check that out.
