### ISSUE TITLE
Surface insert, iterate, remove features of GEOS STRtree

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#1104]
@jorisvandenbossche @mwtoews I think it could be handy to be able to walk tree nodes and update trees.

* insertion: https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in#L3099
* iteration: https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in#L3164
* removal: https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in#L3179

**Comment by jorisvandenbossche** [comment]
Related to insertion/removal, the STRtree docstrings both in Shapely and GEOS indicate that it is query-only, so once the actual tree is created (typically on first query), you cannot add or remove geometries. 
That seems to limit the usefulness of exposing insertion/removal methods?

**Comment by sgillies** [comment]
Yep, this issue has to go! I think I knew the GEOS STRtree details before but lost them due to 2020 trauma.
