### ISSUE TITLE
output type of intersection

### ISSUE THREAD

**Issue by gokhalen** [Toblerity/Shapely#1115]
This is not an 'issue' but I couldn't find a shapely mailing list. Hence, posting it here.

I am performing an intersection of a polygon with another polygon. I would like to know what the type of the object returned can be. I think it could be 

1) Point 
2) Line 
3) Polygon 
4) MultiPolygon
5) GeometryCollection 

Am I correct? Is there anything else that I have missed?

Nachiket

**Comment by jorisvandenbossche** [comment]
Yes, as far as I know, all those options are possible (and also MultiPoint and MultiLineString)
