### ISSUE TITLE
No documentation for `shapely.ops.clip_by_rect()`

### ISSUE THREAD

**Issue by bstadlbauer** [Toblerity/Shapely#1116]
Hi!

Is there a reason why `shapely.ops.clip_by_rect()` is not documented? (API not stable, etc.). Otherwise I would happily provide a PR for it :-)

**Comment by jorisvandenbossche** [comment]
I think a PR to add it to the documentation would be very welcome!

**Comment by bstadlbauer** [comment]
Ok, this should come some time this week then :-) 

@jorisvandenbossche a bit offtopic but - is there any interest in having `geopandas.clip_by_rectangle(gdf, minx, miny, maxx, maxy)` leveraging the spatial index in a similar fashion to `geopandas.clip()`? I would probably also have time (and a personal interest) for a PR on that

**Comment by jorisvandenbossche** [comment]
@bstadlbauer can you open an issue about that in the geopandas repo? (It could be nice to have this functionality, but we could also think if it can be added to the existing `geopandas.clip()` instead of adding a new function)

**Comment by bstadlbauer** [comment]
Documentation should be available as soon as https://github.com/Toblerity/Shapely/pull/1125 is merged

**Comment by jorisvandenbossche** [comment]
Closed by #1125
