### ISSUE TITLE
When projecting a point onto a line, `project` does not function properly when the reference line has a gap in it

### ISSUE THREAD

**Issue by phildias** [Toblerity/Shapely#1126]
## Expected behavior and actual behavior.

The `project` function returns the incorrect location as the closest point on a `MultiLineString` when the `MultiLineString` has a gap in it.

For example, consider a `MultiLineString` with two segments:
- [0, 0] to [1, 0]
- [2, 0] to [3, 0]

Also consider the following point: [1.999, 0]

When projecting the `Point` onto the `MultiLineString`, I would expect the resulting point to be equal to `Point (2 0)`. However, the point returned is `Point (1 0)`.

## Steps to reproduce the problem.

```python
# A simple MultiLineString element that contains two line segments: 
# one line segment that goes from [0, 0] to [0, 1] and another line 
# segment that goes from [2, 0] to [3, 0]. 
# Please note that this MultiLineString has a gap from [1, 0] to [2, 0]. 
mline = MultiLineString([[[0, 0],[1, 0]],[[2, 0],[3, 0]]])

# This point is much closer to the line segment that goes from [2, 0] 
# to [3,0] than the line segment that goes from [0, 0] to [1, 0]. 
point = Point(1.999, 0)

# Projecting the point onto the line and getting
# the WKT details of the point projected onto the line.
print(mline.interpolate(mline.project(point)).wkt)

# Output:
# POINT (1 0)
```

In the example above, I expected `POINT (2 0)` to be printed out on screen. However, I get `POINT (1 0)` instead.

## Operating system

Windows 10

## Shapely version and provenance

Shapely version 1.7.1 installed using `conda`.

**Comment by jorisvandenbossche** [comment]
If you split the two operations in separate steps:

```
>>> dist = mline.project(point)
>>> dist
1.0

>>> mline.interpolate(dist).wkt
'POINT (1 0)'
```

So it's because the first step returns a distance of 1.0 (which I think is correct?), and then the second step of interpolating gives "a" correct solution for distance of 1.0 (the `interpolate` doesn't know where your original point was located, it only gets the distance). 

So since interpolating along a MultiLineString with gaps is inherently ambiguous (last point of first linestring or first point of second linestring?), I think you would need to split your MultiLineString in simple LineStrings if you want to get the desired result here.

**Comment by phildias** [comment]
Hi there! Thanks for the response!

Ah, okay! I see where the problem is. Yes, the ambiguity arises because of the length: there are actually two points on the line that have length equal to `1.0`: `POINT (1 0)` as well as `POINT (2 0)`. This is illustrated below: 

```python
mline = MultiLineString([[[0, 0],[1, 0]],[[2, 0],[3, 0]]])

len_p1 = mline.project(Point(1,0))
len_p2 = mline.project(Point(2,0))

print(f'Length from origin to point (1,0): {len_p1}')
print(f'Length from origin to point (2,0): {len_p2}')

# Output:
#Length from origin to point (1,0): 1.0
#Length from origin to point (2,0): 1.0
```

Damn you, math!!! Hahahahaha...

Hmmm... Yeah, I don't think there's an easy way out of this hole. 

I originally filed this bug report because I was trying to find the point on a line that was closest to another external point. The only solution I had found originally was to use `project->interpolate`. I guess I'm going to have to try to develop a whole new method of finding the closest point. Crap.

This was super illuminating, though, thanks for the clarifications!

**Comment by jorisvandenbossche** [comment]
Good to hear you solved it! `nearest_point` should indeed do what you want, I think.
