### ISSUE TITLE
Extract binary mask

### ISSUE THREAD

**Issue by sama2689** [Toblerity/Shapely#1137]
I have a closed shapely polygon and now want to extract a binary mask such that points inside the polygon are 1 and are 0 otherwise (ideally in a numpy array). Is this functionalty built into Shapely or geopandas? I was unable to figure it out after looking through documentation.

Thanks in advance for any responses.

**Comment by mwtoews** [comment]
Shapely does not do this. But, take a look at [rasterio's](https://github.com/mapbox/rasterio) [`rasterio.features`](https://rasterio.readthedocs.io/en/latest/api/rasterio.features.html) module. In particular, see these functions:

* `rasterio.features.rasterize`
* `rasterio.features.geometry_mask`
