### ISSUE TITLE
Odd result of difference of polygon with itself

### ISSUE THREAD

**Issue by hhoeflin** [Toblerity/Shapely#1138]
## Expected behavior and actual behavior.

When defining a polygon and taking the difference with itself (or any larger polygon), the result is not None, but 
a polygon object with no entries. This feels very unintuitive. An empty GeometryCollection or None, would be much more
consistent in my opinion

## Steps to reproduce the problem.
```
import shapely.geometry as sg
import numpy as np
point = sg.Point(0, 0).buffer(1.0)
empty = point.difference(point)
assert isinstance(empty, sg.Polygon)                
assert len(empty.exterior.coords) == 0              
assert np.array(empty.exterior.coords).shape == (0,)
```
In addition, the output of the numpy array is unexpected. 0 rows is ok, but is should be a 2-dim array with 2 columns and 0 rows.

## Operating system

RHEL7

## Shapely version and provenance

Shapely 1.8a2 with Geos 3.9.1

**Comment by mwtoews** [comment]
Use the `is_empty` property to determine if a geometry is indeed empty.
```python
assert empty.is_empty
```

All other properties are not as reliable/available, as they depend on the version of GEOS. Empty geometries should always be a geometry type, not `None`.

For instance, using GEOS 3.9.1, `empty.wkt` shows `POLYGON EMPTY`, whereas with GEOS 3.6.2 it is `GEOMETRYCOLLECTION EMPTY` (and doesn't have `empty.exterior` etc.).

Also, there are a few inconsistencies with EMPTY not-yet-sorted-out, i.e. #742
