### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'GEOSversion'

### ISSUE THREAD

**Issue by wanghuqiang123** [Toblerity/Shapely#1142]
## Steps to reproduce the problem.

$sudo ./main

then 

When I use pyinstaller to package and publish the program, I run it and report an error:
  File "shapely/geos.py", line 200, in <module>
  File "shapely/geos.py", line 188, in _geos_version
AttributeError: 'NoneType' object has no attribute 'GEOSversion'

## Operating system

system:Ubuntu 18.04.5 LTS 64bit  
NVIDIA NANO

**Comment by sgillies** [comment]
@wanghuqiang123 please search the issue tracker for other issues related to pyinstaller. Something like this has come up before.

**Comment by Jeremiah-England** [comment]
Looks like https://github.com/Toblerity/Shapely/issues/831 is the same error. Resolution there [was](https://github.com/Toblerity/Shapely/issues/831#issuecomment-786959489): 

> I'm going to close this. The entire category of errors involving dynamic loading of GEOS is going away in 2.0 and we won't be doing anything about any of them in the meanwhile.
