### ISSUE TITLE
`is_valid` and `is_simple` are `True` on some self-intersecting Polygons, LineStrings, and LinearRings

### ISSUE THREAD

**Issue by InnovativeInventor** [Toblerity/Shapely#1147]
## Expected behavior and actual behavior
Expected behavior: All self-intersecting objects should have `is_valid` and `is_simple` return False. In particular, the documentation for `is_simple` states that it should:
> Returns True if the feature does not cross itself.

Similarly, the documentation for `is_valid` states:
> A valid LinearRing may not cross itself or touch itself at a single point. A valid Polygon may not possess any overlapping exterior or interior rings. A valid MultiPolygon may not collect any overlapping polygons. Operations on invalid features may fail.

Actual behavior: For some geometries with repeated vertices, `is_valid` and `is_simple` return True. However, geometries with repeated consecutive vertices, by definition, intersect themselves as they overlap at one point. This behavior violates user expectations and should either be documented or changed.

## Steps to reproduce the problem
```python

In [1]: from shapely.geometry import Polygon, MultiPolygon, LineString, LinearRing

In [2]: Polygon([(0,0), (0,0), (1,0), (1,1)]).is_simple
Out[2]: True

In [3]: Polygon([(0,0), (0,0), (1,0), (1,1)]).is_simple
Out[3]: True

In [4]: LineString([(0,0), (0,0), (1,0), (1,1)]).is_valid
Out[4]: True

In [5]: LineString([(0,0), (0,0), (1,0), (1,1)]).is_simple
Out[5]: True

In [6]: LinearRing([(0,0), (0,0), (1,0), (1,1)]).is_valid
Out[6]: True

In [7]: LinearRing([(0,0), (0,0), (1,0), (1,1)]).is_simple
Out[7]: True

In [8]: LinearRing([(0,0), (1,0), (1,1), (0,0)]).is_simple
Out[8]: True
```

## Notes and thoughts
This sounds like an upstream issue -- I'm not sure. There may be other circumstances where `is_simple` and `is_valid` do not behave as expected (e.g. on other shapes like MultiPolygons, etc. or on other geometries). The vertices do not have to be consecutive for unexpected behavior to occur (see last example).

Slight tangent -- Shapely is an awesome, important library -- keep up the good work!

## Operating system
Pop!_OS 20.04 LTS (Ubuntu Focal)

## Shapely version and provenance
Shapely-1.7.1-1-cp39-cp39-manylinux1_x86_64 installed from PyPI using pip on Python 3.9.4

**Comment by dr-jts** [comment]
Repeated points are considered valid and simple in JTS/GEOS by design.   This behaviour will not be changed.

**Comment by InnovativeInventor** [comment]
@dr-jts to clarify, do you mean all repeated points (the OpenGIS spec only refers to repeated endpoints). If so, I'm happy to close this issue,

**Comment by dr-jts** [comment]
> @dr-jts to clarify, do you mean all repeated points (the OpenGIS spec only refers to repeated endpoints). If so, I'm happy to close this issue,

Yes, I mean any and all repeated points, whether endpoints or points internal to a line.
