### ISSUE TITLE
A valid geojson is returning False on `is_valid`

### ISSUE THREAD

**Issue by yazeed44** [Toblerity/Shapely#1153]
First, I'd like to say thank you to all the contributors for this great project.

I'm facing an issue where a valid geojson file, when loaded in shapely is considered invalid. 

## Expected behavior and actual behavior.

(For example: the area of my geometry is `1.417` when it should be `1.414`.)

A valid [geojson object](https://gist.github.com/yazeed44/0ffc92acd2c1eee57422fb4d3890e17a) is returning `False` on `is_valid`. 
## Steps to reproduce the problem.

`shape({"type": geojson_obj["type"], "coordinates": geojson_obj["coordinates"]})`

## Operating system

Ubuntu 20.04 focal

## Shapely version and provenance

Shapely 1.7.1

**Comment by mwtoews** [comment]
You can investigate the reason why it is not valid with `shapely.validation.explain_validity`:
```python
import json
import urllib.request
from shapely import validation
from shapely.geometry import shape

url = "https://gist.githubusercontent.com/yazeed44/0ffc92acd2c1eee57422fb4d3890e17a/raw/b9191dacae9eaacb82520b98f9aba667d57d8151/should_be_valid.geojson"
with urllib.request.urlopen(url) as r:
    geom = shape(json.loads(r.read().decode()))

print(validation.explain_validity(geom))
```
shows "Hole lies outside shell[46.694725 24.940258]"

It seems there is a mix-up with exterior and interior rings. The interior rings need to be contained within the exterior rings for this geometry to be valid. What tool says the geojson is valid?

**Comment by yazeed44** [comment]
> What tool says the geojson is valid?

The file renders on [geojsonlint.com](geojsonlint.com) and on Github gist. Maybe they're correcting the file on the fly?

`validation.make_valid` did fix the geometry. Thank you for referring it to me.
