### ISSUE TITLE
Simplify Algorithm when preserve_topology=True

### ISSUE THREAD

**Issue by jan-krueger** [Toblerity/Shapely#1154]
Hello,
I would like to know what algorithm is use in the simplify method when `preserve_topology` is set to true. In the docs it only mentions the follow 

> By default a slower algorithm is used that preserves topology. If preserve topology is set to False the much quicker Douglas-Peucker algorithm 6 is used.

I am curious what this default algorithm is, and whether or not it is based on some published paper?
Thank you for your time, and potential help. :) 

~ Jan

**Comment by sgillies** [comment]
https://github.com/Toblerity/Shapely/blob/master/FAQ.rst#are-there-references-for-the-algorithms-used-by-shapely
