### ISSUE TITLE
License terms to be clarified

### ISSUE THREAD

**Issue by dinesh3367** [Toblerity/Shapely#1157]
Team,

I would like to confirm what is the appropriate license clause for shapely usage in custom applications

https://shapely.readthedocs.io/en/stable/manual.html#references says "This work is licensed under a Creative Commons Attribution 3.0 United States License."

Whereas https://shapely.readthedocs.io/en/latest/project.html says "Shapely is a BSD-licensed Python package for manipulation and analysis of planar geometric objects."

Which is the correct license term ??

Please clarify the doubt team.

Thanks

**Comment by Jeremiah-England** [comment]
Looks like the [LICENSE.txt](https://github.com/Toblerity/Shapely/blob/master/LICENSE.txt) has the [BSD-3-Clause](https://opensource.org/licenses/BSD-3-Clause). I'd go with that if you don't get a more detailed answer from someone or a confirmation of one from Sean Gillies.

The CC clause in the manual dates back to abba3b33376e1e9ccae8ec0fd8ea2cfe5e7792e6 (Dec 30, 2007), while the LICENCE.txt file dates back to 5521934edcea77b45dcf31782ad4850212aed2aa (Nov 19, 2007).

**Comment by snorfalorpagus** [comment]
@Jeremiah-England is correct. The library is licensed under the terms described in [LICENSE.txt](https://github.com/Toblerity/Shapely/blob/master/LICENSE.txt). The documentation is licensed separately under the CC-BY 3.0 licence.
