### ISSUE TITLE
Intersection of polygon with identical points outputs only unique

### ISSUE THREAD

**Issue by ozsharfr** [Toblerity/Shapely#1159]
Hi,
I'm trying to find the intersection of multiple points with a given polygon.
Some of the points are identical , but I'd still like to get all intersecting points. 

# example of simplified code:
from shapely import geometry
identical_points = geometry.MultiPoint([(0,0) , (0,0) , (0,0)])
pol = geometry.Point(0,0).buffer(1)
intersections = pol.intersection(identical_points)
#

While identical_points.geom_type is 'MultyPoint' , intersections.geom_type is 'Point' (single (0,0) point).

I can iterate over all points and check for intersection, however, it is much slower.
Can you please let me know if there's a way to overcome this issue?

Thank you

## Operating system
Ubuntu on windows 10

## Shapely version and provenance
1.7.1

**Comment by sgillies** [comment]
This is expected behavior of the underlying algorithm from GEOS. Duplicate points can be reduced by overlay operations.
