### ISSUE TITLE
Extract outest points of Multipoint

### ISSUE THREAD

**Issue by Jonas231** [Toblerity/Shapely#1167]
Hello,
I have this question:

I have this Multipoint object: 
![grafik](https://user-images.githubusercontent.com/38330725/125754124-4506ec3f-7b14-49f1-b386-2b7dacc24e03.png)

I would like to extract an other ring of points, i.e. the boundary of all the points but not the "convex_hull".
The boundary should be constituted of a line of points. 
How can I do this?
Kind regards,
Jonas

**Comment by sgillies** [comment]
@Jonas231 this issue tracker isn't for discussions on how to use shapely. You may want to try the GIS Stack Exchange to see if others have solved this problem.

Shapely doesn't have a specialized method for this. I wonder if you can, with a combination of spatial or other indexes and convex hull, filter for the points that are within a very small distance of the convex hull?
