### ISSUE TITLE
Is there any reason not to cache the reader in `wkt.loads`?

### ISSUE THREAD

**Issue by jimfulton** [Toblerity/Shapely#1178]
Currently `loads` computes a reader every time:

https://github.com/Toblerity/Shapely/blob/9a761739aea19823fcead4391ef043edafa74db6/shapely/wkt.py#L22

Computing a reader once and then just calling the read method is about 14% faster by my measurement parsing a simple polygon: `'POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))'`.

**Comment by mwtoews** [comment]
I probably thought about this too, but you may want to wait for shapely-2.0 when this will be changed entirely:
https://github.com/Toblerity/Shapely/blob/2c701950eb25744b12f251df92afd53115b2e42c/shapely/wkt.py#L24

**Comment by jimfulton** [comment]
OK.
