### ISSUE TITLE
Not  import  make_valid

### ISSUE THREAD

**Issue by adrigo02** [Toblerity/Shapely#1220]
Hello! I am using anaconda with Windows 10 and python  version is 3.8.12.
I tried to install shapely with:
conda install shapely 
and also
pip install shapely

Then I tried to import make_valid with
 from shapely.validation import make_valid
I can not import make_valid
 cannot import name 'make_valid' from 'shapely.validation' (C:\ProgramData\Anaconda3\lib\site-packages\shapely\validation.py)

I go to the path where it is the python file validation.py and this is what it is inside:
 TODO: allow for implementations using other than GEOS

from shapely.geos import lgeos

def explain_validity(ob):
    return lgeos.GEOSisValidReason(ob._geom)

Very different what there are  in the Github
https://github.com/Toblerity/Shapely/blob/main/shapely/validation.py

**Comment by jorisvandenbossche** [comment]
@adrigo02 can you check what version of Shapely you are using? (`import shapely`, `shapely.__version__`)

**Comment by adrigo02** [comment]
Yes I am using Shapely version '1.7.1'

**Comment by jorisvandenbossche** [comment]
The `make_valid` function is only available starting with shapely 1.8. So you will have to upgrade your shapely version to use this function.
