### ISSUE TITLE
Create a 3D polygon?

### ISSUE THREAD

**Issue by AI-ML-Enthusiast** [Toblerity/Shapely#1223]
Can we create 3D polygon and check a 3D point whether it is inside the polygon or not?
In the documentation you use 2D point, can we use 3D?

**Comment by jorisvandenbossche** [comment]
You can generally _create_ 3D geometries:

```python
In [24]: from shapely.geometry import Point, Polygon

In [25]: poly = Polygon([(0, 0, 1), (10, 0, 1), (10, 10, 1), (0, 10, 1)])

In [26]: print(poly)
POLYGON Z ((0 0 1, 10 0 1, 10 10 1, 0 10 1, 0 0 1))

In [27]: point = Point(5, 5, 5)

In [28]: print(point)
POINT Z (5 5 5)
```

but AFAIK most actual functions (such as the predicates to check whether the point is inside the polygon) will ignore the z dimension:

```python
In [30]: point.within(poly)
Out[30]: True
```

(this would be False if the z dimension was taken into account)

**Comment by sgillies** [comment]
Also, the functions that produce geometries generally discard Z values. https://github.com/Toblerity/Shapely/blob/main/FAQ.rst#i-used-buffer-on-a-geometry-with-z-coordinates-where-did-the-z-coordinates-go
