### ISSUE TITLE
Raise NotImplementedError for missing methods

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#216]
Currently we look optimistically for methods in [LGEOSBase.methods](https://github.com/Toblerity/Shapely/blob/master/shapely/geos.py#L721) and a KeyError gets raised if our GEOS shared library doesn't support the method. I think we can do better: a NotImplementedError would be less baffling, especially if it had a message with details about required GEOS versions.

**Comment by sgillies** [comment]
Kicking this to 1.6 since it's a breaking change. Exceptions are interface, too, I always have to remind myself.

**Comment by ddasilva** [comment]
@sgillies  Just to play devil's advocate, one could define a custom exception that inherits from both `NotImplementedError` and `KeyError` to remove breaking backwards compatibility

**Comment by sgillies** [comment]
@ddasilva Great suggestion, thank you!
