### ISSUE TITLE
Use geos-config for setup.py?

### ISSUE THREAD

**Issue by mwtoews** [Toblerity/Shapely#232]
Is the dynamic library checking in setup.py necessary? Could we instead use `geos-config` similar to rasterio? This could also help populate, `library`, `include_dirs` and `extra_link_args` from `--cflags` and `--clibs` options.

Also, by using `geos-config`, a non-standard installation location for GEOS can be used to build Cython extensions.

**Comment by mwtoews** [comment]
This is what I have in mind: https://github.com/mwtoews/shapely/commit/d65417ab0b7c65617b185bc22b732736b3e15fa7

**Comment by sgillies** [comment]
:+1:

**Comment by kynan** [comment]
It's even *much worse* than that: this check is unnecessarily repeated at *import time*, which precludes using RPATH while building the extension module, see #234.

**Comment by sgillies** [comment]
@mwtoews might you have a PR soon?

**Comment by mwtoews** [comment]
PR at #236
