### ISSUE TITLE
Import time check for libgeos precludes building with RPATH

### ISSUE THREAD

**Issue by kynan** [Toblerity/Shapely#234]
The import time check for `libgeos` requires the shared library to either be installed in a standard library path or have `LD_LIBRARY_PATH` set, which is a *very bad idea*.

I prefer to build Python extension modules by baking in the RPATH to any shared libraries the extension module links against. Unfortunately this (imho completely unnecessary) import time check precludes this and requires `LD_LIBRARY_PATH` to be always set.

Can this please be removed?

**Comment by sgillies** [comment]
Closed via #238
