### ISSUE TITLE
Remove check for required GEOS version in setup.py

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#242]
This check https://github.com/Toblerity/Shapely/blame/master/setup.py#L52-L61 that @mwtoews and I added is causing developers (@kynan in particular) pain. I propose that it be removed while we reconsider the problem. 

What I'm learning from recent Distutils and Pypa (Python packaging authority) discussions is that in the happy Pypa future we use setuptools to make packages, using setup.py, and use pip to install packages, *not* using setup.py. That future is already partially here: if you pip install a wheel the setup script is not run at all. We're steering OS X users (and soon Windows users) towards binary wheels and will fix the Shapely-GEOS mismatch problem in that way for those platforms.

Linux is a different matter. We'll be building from source distributions on Linux for some time yet. Developers building Shapely distributions and developers downloading sdists and running `setup.py install` presumably know what they are doing, it's developers who `pip install shapely` who might not have the required GEOS lib (or any GEOS lib) on their system who run into trouble. And it's the latter developers I was attempting to help.

Let's see if we can require a GEOS version check (as in https://github.com/Toblerity/Shapely/blame/master/setup.py#L52-L62) *only* for the naive `pip install shapely` case when there's no geos-config to be found or no setup.cfg file or command line options passed to the setup script.

**Comment by mwtoews** [comment]
Is this as easy as moving the GEOS version check into the main module (e.g. `shapely.lgeos`), as a runtime check? This means it can be installed regardless of GEOS library version or even availability, but raise either a warning or import error when shapely is imported while using an older GEOS library. These changes can be put on top of #241

Should there be any checks of versions in `setup.py`? And if so, for `install`, `build_ext`, `sdist`, others?
