### ISSUE TITLE
UnicodeDecodeError with version 1.5.6 wheel on MacOS X 10.10

### ISSUE THREAD

**Issue by viaregio** [Toblerity/Shapely#243]
<p>The code</p>
<pre><code>import shapely.geos
shapely.geos._lgeos</code></pre>
<p>results in</p>
<pre><code>&lt;CDLL &#39;/usr/local/lib/python3.4/site-packages/shapely/.dylibs/libgeos_c.1.dylib&#39;, handle 7fbdf49b8720 at 10c0d2400&gt;</code></pre>
<p>and the following code (A example from the Cartopy homepage)</p>
<pre><code>import cartopy
import matplotlib.pyplot as plt

def main():

    ax = plt.axes(projection=cartopy.crs.PlateCarree())

    ax.add_feature(cartopy.feature.LAND)
    ax.add_feature(cartopy.feature.OCEAN)
    ax.add_feature(cartopy.feature.COASTLINE)
    ax.add_feature(cartopy.feature.BORDERS, linestyle=&#39;:&#39;)
    ax.add_feature(cartopy.feature.LAKES, alpha=0.5)
    ax.add_feature(cartopy.feature.RIVERS)

    ax.set_extent([-20, 60, -40, 40])

    plt.show()

if __name__ == &#39;__main__&#39;:
    main()</code></pre>
<p>results in</p>
<pre><code>---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)

/Users/uli/Entwicklung/IPythonNotebooks/_ctypes/callbacks.c in &#39;calling callback function&#39;()

/usr/local/lib/python3.4/site-packages/shapely/geos.py in error_handler(fmt, *args)
    189     if sys.version_info[0] &gt;= 3:
    190         fmt = fmt.decode(&#39;ascii&#39;)
--&gt; 191         args = [arg.decode(&#39;ascii&#39;) for arg in args]
    192     LOG.error(fmt, *args)
    193 

/usr/local/lib/python3.4/site-packages/shapely/geos.py in &lt;listcomp&gt;(.0)
    189     if sys.version_info[0] &gt;= 3:
    190         fmt = fmt.decode(&#39;ascii&#39;)
--&gt; 191         args = [arg.decode(&#39;ascii&#39;) for arg in args]
    192     LOG.error(fmt, *args)
    193 

UnicodeDecodeError: &#39;ascii&#39; codec can&#39;t decode byte 0xbb in position 1: ordinal not in range(128)</code></pre>
<p>::</p>
<pre><code>---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)

/Users/uli/Entwicklung/IPythonNotebooks/_ctypes/callbacks.c in &#39;calling callback function&#39;()

/usr/local/lib/python3.4/site-packages/shapely/geos.py in error_handler(fmt, *args)
    189     if sys.version_info[0] &gt;= 3:
    190         fmt = fmt.decode(&#39;ascii&#39;)
--&gt; 191         args = [arg.decode(&#39;ascii&#39;) for arg in args]
    192     LOG.error(fmt, *args)
    193 

/usr/local/lib/python3.4/site-packages/shapely/geos.py in &lt;listcomp&gt;(.0)
    189     if sys.version_info[0] &gt;= 3:
    190         fmt = fmt.decode(&#39;ascii&#39;)
--&gt; 191         args = [arg.decode(&#39;ascii&#39;) for arg in args]
    192     LOG.error(fmt, *args)
    193 

UnicodeDecodeError: &#39;ascii&#39; codec can&#39;t decode byte 0xbb in position 1: ordinal not in range(128)</code></pre>

**Comment by viaregio** [comment]
The last version that works as expected is 1.5.2

**Comment by sgillies** [comment]
@viaregio since the offending code was added around 1.3 (see https://github.com/Toblerity/Shapely/blame/master/shapely/geos.py#L84-L87), I suspect this is an old bug surfacing due to a combination of other factors. Does Shapely work otherwise? Can you do simple operations like this one?

```
from shapely.geometry import Point
print Point(0, 0).buffer(1.0).area
```

**Comment by viaregio** [comment]
<pre>from shapely.geometry import Point
print(Point(0, 0).buffer(1.0).area)</pre>
seems to work fine
<pre>3.136548490545939</pre>

**Comment by sgillies** [comment]
@viaregio thanks for confirming.

@pelson can you confirm if there's a problem with the cartopy example? I don't see how any non-ASCII characters could be coming out of the GEOS error handlers.

**Comment by QuLogic** [comment]
Here are two examples that will not be handled correctly by the current error handler:

In [GEOSGeom_createPolygon_r](https://github.com/libgeos/libgeos/blob/svn-trunk/capi/geos_ts_c.cpp#L4037):
```c++
 handle->ERROR_MESSAGE("Shell is not a LinearRing");
```
There is no argument, so it would a) try to decode `None` (on Py 3) and b) [cause a `TypeError`](https://github.com/SciTools/cartopy/issues/375) due to extra arguments to the formatting routine (on Py 2).

In [GEOSRelateBoundaryNodeRule_r](https://github.com/libgeos/libgeos/blob/svn-trunk/capi/geos_ts_c.cpp#L734):
```c++
 handle->ERROR_MESSAGE("Invalid boundary node rule %d", bnr);
```
Here, the second argument is an integer, not a string, so who knows what `ctypes` might read and attempt to coerce into a string of bytes.

**Comment by sgillies** [comment]
@QuLogic thank you so much for digging those up. Now I get it. That one in GEOSRelateBoundaryNodeRule_r violates the message handler interface as I understand it. Luckily, it seems to be the only one:

```
$ grep -R 'ERROR_MESSAGE.*%d' *
capi/geos_ts_c.cpp:            handle->ERROR_MESSAGE("Invalid boundary node rule %d", bnr);
```
```
$ grep -R 'ERROR_MESSAGE.*%f' *
# Nothing
```

**Comment by QuLogic** [comment]
@sgillies Is there something other than the doxygen documentation that defines the message handler interface? All I can find is `typedef void (*GEOSMessageHandler)(const char *fmt, ...);` which definitely does _not_ say the second parameter is a string (or that it even exists).

**Comment by sgillies** [comment]
@viaregio I'm trying to run your script, but cannot due to absence of the cartopy datasets. I'm at an impasse without a program that will reproduce the bug.

```
/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/cartopy/io/__init__.py:261: DownloadWarning: Downloading: http://www.nacis.org/naturalearth/110m/physical/ne_110m_land.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)
Traceback (most recent call last):
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/matplotlib/figure.py", line 1085, in draw
    func(*args)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/cartopy/mpl/geoaxes.py", line 355, in draw
    inframe=inframe)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/matplotlib/axes/_base.py", line 2110, in draw
    a.draw(renderer)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/cartopy/mpl/feature_artist.py", line 103, in draw
    geoms = self._feature.intersecting_geometries(extent)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/cartopy/feature.py", line 113, in intersecting_geometries
    return (geom for geom in self.geometries() if
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/cartopy/feature.py", line 180, in geometries
    name=self.name)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/cartopy/io/shapereader.py", line 246, in natural_earth
    return ne_downloader.path(format_dict)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/cartopy/io/__init__.py", line 223, in path
    result_path = self.acquire_resource(target_path, format_dict)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/cartopy/io/shapereader.py", line 301, in acquire_resource
    shapefile_online = self._urlopen(url)
  File "/Users/sean/envs/pydotorg34/lib/python3.4/site-packages/cartopy/io/__init__.py", line 262, in _urlopen
    return urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 493, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 676, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by QuLogic** [comment]
@sgillies NACIS changed their URL a couple times. You can fix it by removing the _second_ `_NE_URL_TEMPLATE` in `cartopy/io/shapereader.py`, around line 281.

**Comment by sgillies** [comment]
@QuLogic no, I'd rather not get pulled into hacking on cartopy in order to reproduce this reported bug. As a cartopy developer, any chance you could confirm this one?

**Comment by QuLogic** [comment]
Unfortunately, I cannot reproduce this `UnicodeDecodeError` as I am not on a Mac. (It's also possible something in cartopy was fixed so that specific error is no longer triggered.) I can tell you if the `TypeError` in the issue I linked earlier is fixed.

However, Travis seems to say the PR is not ready yet.

**Comment by QuLogic** [comment]
@viaregio Also, could you add a `print(fmt, args)` to the beginning of `error_handler` in `/usr/local/lib/python3.4/site-packages/shapely/geos.py`? That would help @sgillies pin-point what error message is triggering the problem, and maybe reduce it into a simpler test case.

**Comment by snorfalorpagus** [comment]
I can reproduce this bug. The arguments to `error_handler` are:

```
b'Invalid argument (must be a Polygon)' (b'I\xbb\x18\x99\x89\t\x01',)
```

**Comment by QuLogic** [comment]
That's one of the errors that does not have any arguments. @sgillies I think you'll need to change the handler definition's second argument to be `c_void_p`, and only if there is a second argument, parse it as a string. Otherwise, it looks like `ctypes` is trying to read a garbage pointer.

**Comment by snorfalorpagus** [comment]
The following code triggers this bug, without needing any of the cartopy data.

```
from shapely.wkt import loads

from cartopy.crs import PlateCarree
crs = PlateCarree()

g1 = loads('''LINESTRING (-20 -40, 60 -40, 60 40, -20 40, -20 -40)''')

g2 = crs.project_geometry(g1, crs)
g2.bounds
```

Following this down the rabbit hole, `project_geometry` calls `cartopy.trace.project_linear`. Interesting this is written in Cython and calling GEOS directly.

https://github.com/SciTools/cartopy/blob/master/lib/cartopy/trace.pyx#L87

I suspect what is happening here is that cartopy is creating an invalid GEOSGeometry object, then manually wrapping it in a shapely python object. This passes silently, until the geometry data is accessed (in the example above with `g2.bounds`) at which point the whole system falls apart.

This is a bug in cartopy, not shapely.

**Comment by QuLogic** [comment]
> I suspect what is happening here is that cartopy is creating an invalid GEOSGeometry object, then manually wrapping it in a shapely python object. This passes silently, until the geometry data is accessed (in the example above with g2.bounds) at which point the whole system falls apart.

That's possible; I'm not really familiar with those interpolation routines but maybe @pelson could confirm.

> This is a bug in cartopy, not shapely.

Yes and no. The trigger for the error is in cartopy, but shapely is not correctly handling said error.

**Comment by sgillies** [comment]
@snorfalorpagus I tried that script but `shapely.geos.error_handler()` never gets called.

@QuLogic thank you for the c_void_p suggestion. I've got a PR with passing tests.

**Comment by QuLogic** [comment]
I tried it out on the cartopy test suite, and I _think_ that he `TypeError` is gone, but now I'm seeing this:
```
  File ".../shapely/geos.py", line 216, in notice_handler
    for spec, arg in zip(conversions, args):
TypeError: zip argument #2 must support iteration
```

**Comment by sgillies** [comment]
Fixed.
