### ISSUE TITLE
crash in shapely.geometry.mapping()

### ISSUE THREAD

**Issue by vielmetti** [Toblerity/Shapely#250]
I have a bit of code in this gist

https://gist.github.com/13f6feae14111ff1c148

which operates on this GeoJSON file

https://gist.github.com/b7e74580b7561f8f60f4

and crashes with this error:

```
Traceback (most recent call last):
  File "/Users/emv/bin/unsliver.py", line 33, in <module>
    newpolygon=mapping(fx)
  File "/Library/Python/2.7/site-packages/shapely/geometry/geo.py", line 75, in mapping
    return ob.__geo_interface__
  File "/Library/Python/2.7/site-packages/shapely/geometry/polygon.py", line 295, in __geo_interface__
    coords = [tuple(self.exterior.coords)]
```

The odd thing is that the GeoJSON file it's starting from is generated by a process that is also generating more than 2000 other similar files from similar sources, and this is the only one that crashes. This is using shapely 1.5.6, installed by "pip install shapely" on a Mac running OS X 10.9.5 and Python 2.7.5.

**Comment by jwass** [comment]
Hi @vielmetti,
Looks like that MultiPolygon in the included file, which only contains a single polygon, is invalid.

```
with open('733.union.geojson') as f:
    fc = json.load(f)
poly = shapely.geometry.shape(fc['features'][0]['geometry'])
poly.is_valid
WARNING:shapely.geos:Hole lies outside shell at or near point -82.572134000000005 36.594599000000002
False
```

As a result, I think the result of the first buffer doesn't quite do what you'd expect: https://gist.github.com/anonymous/4ac359ae3f7ea75aa350. The negative buffer then returns an empty polygon.

**Comment by jwass** [comment]
One option would be to give a more informative error if `__geo_interface__` gets an empty geometry, but not sure.

**Comment by vielmetti** [comment]
Thanks @jwass . I looked at the upstream and found an error coming out of a previous polygon cleaning attempt (from R's "rgeos")

```
> gIsValid(Z733.bounds)
[1] FALSE
Warning message:
In RGEOSUnaryPredFunc(spgeom, byid, "rgeos_isvalid") :
  Nested shells at or near point -80.519433000000006 37.131858999999999
```

so I think I can clean up this issue upstream somehow, and that's my task (somehow).

For Shapely, though, I guess the argument I'd make is that if poly.is_valid is true, then mapping(poly) should also work, and an empty polygon should be mapped into some sort of valid empty object.

**Comment by jwass** [comment]
`is_valid` only reports validity from the GEOS perspective, where empty geometries are valid. The problem is that empty geometries are not valid GeoJSON, which has no representation for them (I'm pretty sure that's true - @sgillies?). Since `mapping()` tries to create a GeoJSON-like object, I think it would have to throw an exception of some kind on empty geoms.

**Comment by snorfalorpagus** [comment]
http://geojson.org/geojson-spec.html#feature-objects

"A feature object must have a member with the name "geometry". The value of the geometry member is a geometry object as defined above **or a JSON null value**."

Perhaps this should be returning a Python `None`, e.g.:

```
>>> Point(0,0).__geo_interface__
{'type': 'Point', 'coordinates': (0.0, 0.0)}
>>> repr(Point(0,0).buffer(-1).__geo_interface__)
'None'
```

**Comment by jwass** [comment]
@snorfalorpagus Ah. I stand corrected. Thanks.

In that case, I think None would be the appropriate result for empty geometries. Although my guess is most tools will choke on features with null geometries, despite being valid GeoJSON.

**Comment by snorfalorpagus** [comment]
For comparison, QGIS returns a geometry with no coordinates:

```
QgsGeometry.fromPoint(QgsPoint(0,0)).buffer(-1, 5).__geo_interface__
{'type': 'Polygon', 'coordinates': [[]]}
```

I think I would prefer `None` to this (which I think is invalid?)

**Comment by vielmetti** [comment]
@snorfalorpagus , @jwass, I'd go back to @sgillies spec for the __geo_interface__ at

https://gist.github.com/sgillies/2217756

and note

> type (required)
> A string indicating the geospatial type. Possible values are "Feature" or a geometry type: "Point",  "LineString", "Polygon", etc.


which suggests that the QGIS approach of returning a geometry with no coordinates is correct.

**Comment by vielmetti** [comment]
FYI, I wrote up my whole map-making pipeline here: http://vielmetti.typepad.com/vacuum/2015/03/cleaning-polygons-in-r-and-shapely.html

from a first glance I'm not doing anything in R that I couldn't do in Shapely, and I'll bet it would be way faster.

**Comment by sgillies** [comment]
What's the desired action here? Is it that we want some outcome other than an exception in the reported situation and the related one below?

```python
>>> from shapely.geometry import Point
>>> from shapely.wkt import dumps
>>> dumps(Point())
'GEOMETRYCOLLECTION EMPTY'
>>> mapping(dumps(Point()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sean/code/Shapely/shapely/geometry/geo.py", line 75, in mapping
    return ob.__geo_interface__
AttributeError: 'str' object has no attribute '__geo_interface__'
```

Or a more informative exception?
