### ISSUE TITLE
Enable shapely speedups by default?

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Shapely#251]
Currently the speedups cython module is compiled (if possible) at install, but the user has to manually enable it in each script to benefit. Is there a reason for this? Why aren't they enabled by default, instead falling back to ctypes if not available?

Incidentally, we don't appear to test the `disable` function - and it's broken! (by me...)

https://github.com/Toblerity/Shapely/blob/master/shapely/speedups/__init__.py#L61

I'll put in a PR to fix this bug, but would like to open a discussion re: enabling the speedups automatically where `speedups.available == True`.

**Comment by pelson** [comment]
:+1: from me. We now test that cython implementation == ctypes implementation in all tested cases, so anywhere there isn't parity is a bug IMHO.

**Comment by sgillies** [comment]
:+1:
