### ISSUE TITLE
parallel_offset using "big" distance build unexpected result

### ISSUE THREAD

**Issue by doudz** [Toblerity/Shapely#253]
I'm trying to use parallel_offset on a LineString but with a "big" distance there's a unexpected result

see http://snag.gy/jTv87.jpg

used distance : 60000
direction : left

original LineString :
LINESTRING (2246.226976451105 4980.317472281724, 2141.332423072337 4869.748311379743, 2074.726953974462 4724.522452236556, 2015.21121905107 4577.021545876318, 1957.389102550099 4428.446903665948, 1899.70946373423 4279.783652025614, 1841.303228945745 4131.021689380281, 1782.174522594715 3983.302080210514, 1721.598384108662 3835.480921840683, 1659.954128157335 3688.828422071076, 1596.69680049683 3542.28146662158, 1531.898301179498 3396.189802127416, 1465.920796157697 3251.370417591151, 1397.088724829625 3105.477831690462, 1324.528828624296 2959.595267001574, 1254.199919332738 2827.000493148794, 1170.594993840567 2675.731620941115, 1094.893423413612 2547.174898012117, 1010.646702340426 2410.252979612043, 926.3682265974344 2280.226543977853, 830.265320935921 2141.201162435978, 722.6922692194853 2033.535606711881, 572.1574471797721 1999.913528689724, 409.1919961807115 2013.081316339079, 253.2448686430914 2044.564834503569, 107.6614614301803 2089.684057931629, -44.42418799679164 2153.819096087846, -186.3462672865645 2227.54311652745, -322.3795015495601 2310.814218717951, -452.8262043531834 2402.41750905314, -578.1458212331122 2500.868835013363, -698.7295358910404 2605.237307624225, -817.4882537632413 2716.643657677555, -922.8417741427609 2824.079196534665, -1037.7563834626 2949.879306362147, -1137.651141715502 3066.166599086452, -1238.39579074509 3192.159050465126, -1333.003926261105 3317.492573799928, -1429.382174219044 3453.906878404759, -1513.011545443019 3580.42014723009, -1596.135104648779 3712.437266141787, -1679.386386012377 3855.570104709699, -1752.810102374338 3990.73281961551, -1826.637834997402 4135.68079089206, -1895.909714860633 4285.351336392323, -1956.486178196147 4428.279860847123, -2015.211219051065 4577.021545876318, -2074.726953974458 4724.522452236556, -2141.332423072333 4869.748311379743, -2246.226976451101 4980.317472281724)

**Comment by snorfalorpagus** [comment]
The `parallel_offset` method calls the underlying GEOS library quite directly, so I suspect it's an issue with GEOS itself rather than Shapely. I had a look, and Shapely calls `GEOSSingleSidedBuffer`, which itself calls `GEOSSingleSidedBuffer_r`. Interestingly, this method is commented with `/* @deprecated in 3.3.0 */`...

https://github.com/libgeos/libgeos/blob/aa57155d18f8cbb33b5090c5ea4bae349abf4db2/capi/geos_c.cpp#L418

https://github.com/libgeos/libgeos/blob/aa57155d18f8cbb33b5090c5ea4bae349abf4db2/capi/geos_ts_c.cpp#L1802

Need to investigate further...

**Comment by sgillies** [comment]
Won't be able to get a fix for this in 1.5.8, but maybe in the next release.

**Comment by snorfalorpagus** [comment]
It looks like `GEOSSingleSidedBuffer` was first introduced in GEOS 3.2, but deprecated in favour of `GEOSOffsetCurve` in GEOS 3.3. I guess we should be using the new method in 3.3 and above. However, the new method seems to give the same result in this instance.

**Comment by sgillies** [comment]
Yeah, this is one for the GEOS tracker. It looks like numerical instability in the algorith to me. Check out what happens between distances 3305 and 3306 in this notebook: http://nbviewer.ipython.org/gist/sgillies/49506af58bf8e111731d.
