### ISSUE TITLE
Trying to package Shapely for python3 fails reading the Credits file

### ISSUE THREAD

**Issue by ocefpaf** [Toblerity/Shapely#254]
Quick question: Should that line read `>=` instead of `>`?

https://github.com/Toblerity/Shapely/blob/master/setup.py#L68

**Comment by sgillies** [comment]
@ocefpaf you are correct. A 1.5.8 release won't be necessary. Its code was a little buggy too, but because the test in the maint branch was `> (3,)` it passes. I've fixed that to be `>= (3,)` and merged to master.

**Comment by ocefpaf** [comment]
@sgillies Thanks.
