### ISSUE TITLE
Shapely using a bad geos version

### ISSUE THREAD

**Issue by odermatt** [Toblerity/Shapely#258]
Hi,

I ran into the OSX-specific issue discussed here: 
https://github.com/SciTools/cartopy/issues/481, https://github.com/Toblerity/Shapely/issues/177

I made sure there's no Homebrew GEOS on my system, installed the one by Kyngchaos and re-installed shapely using:
GEOS_CONFIG=/Library/Frameworks/GEOS.framework/Versions/3/unix/bin/geos-config pip3 install shapely

However I still get:
Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3612.

Am I missing something? Is there a way to safely build Shapely to the right GEOS without using Conda?

Sorry for bringing this issue up again and thanks your your help.

**Comment by sgillies** [comment]
@odermatt At the end of #177, @pelson says it's not a Shapely bug. So, if this is the same issue, it is also not a Shapely bug.

For what it's worth, I never use Conda. And I can't support other people's Conda packages.

I see recipes for working solutions in SciTools/cartopy#481. I suggest you follow those or use pip to install a Shapely binary wheel from PyPI like `pip install shapely` (no `GEOS_CONFIG` at all).
