### ISSUE TITLE
Assertion failed: (0), function query

### ISSUE THREAD

**Issue by phargogh** [Toblerity/Shapely#260]
Hello,

When I use `shapely.ops.cascaded_union`, I encounter this error:

    Assertion failed: (0), function query, file AbstractSTRtree.cpp, line 285.
    Abort trap: 6

It looks like it might be a compatibility issue with GDAL (which I believe uses a version of GEOS).  Here's a script that fails:

    from osgeo import ogr
    from shapely.geometry import Point
    import shapely.ops

    def synth_geom():
        polygons = [
            Point(1, 1).buffer(1),
            Point(1, 2).buffer(1),
        ]
        biggest_feature = shapely.ops.cascaded_union(polygons)
        print biggest_feature

    if __name__ == '__main__':
        synth_geom()

I noticed that if I change the order of the import statements, cascaded_union works as expected.

    from shapely.geometry import Point
    import shapely.ops
    from osgeo import ogr

Is this something that can or should be addressed by Shapely?

**Comment by sgillies** [comment]
@phargogh did you `pip install shapely`? Since December, on OS X, you'll get a binary Shapely wheel if you do and the wheel includes a GEOS shared library. It's possible that these Shapely wheels are not compatible with the Homebrew GEOS lib and that errors will occur if the GEOS lib has already been loaded by osgeo.ogr.

I've got a potential workaround for you: do a `pip uninstall shapely && pip install --no-use-wheel shapely`. This will grab the Shapely source distribution instead of a binary wheel and it should have no problems with Homebrew's GEOS.

Can you report back to me if that gets you out of this jam?

**Comment by sgillies** [comment]
Anything to report about a fresh from-source install @phargogh?

**Comment by phargogh** [comment]
Yep!  The fresh, from-source install of shapely works as expected.  Guess this should teach me to be more aware of the dependencies I've installed and am building against :)

**Comment by dfelikson** [comment]
I was having the same issue and resolved it by importing shapely before importing osgeo. I didn't need to do the "pip install --no-use-wheel shapely". Just for future reference, could someone explain what's going on when shapely is imported before osgeo and why it causes the error?

**Comment by sgillies** [comment]
@dfelikson please see https://github.com/Toblerity/Shapely/issues/262. I don't understand exactly what's going on yet. Specific details (operating system, sources of software -- Homebrew? PyPI? -- versions) will be needed to track this down.

**Comment by ozak** [comment]
@sgillies there is definitely an issue with Homebrew and the wheeled version of Shapely. I did not have the issue reported here (although I did not import shapely before osgeo) but a completely different one #273 which got resolved using ``pip uninstall shapely && pip install --no-use-wheel shapely``.

**Comment by lkilcher** [comment]
I was having this issue too, thank you!

**Comment by dmwelch** [comment]
@sgillies I was using shapely in a virtualenv - did the `pip install --no-use-wheel shapely` thing with no luck.  I added this line before importing `pyproj` just to check that I was importing from the right location:
``` 
import shapely
shapely.__file__
```

Now it works like magic... unlike @phargogh, I'm not importing `osgeo` so maybe that lends a little more light on it?

**Comment by dmwelch** [comment]
@sgillies I did some digging and tracked this down to *fiona*, and not shapely.  Here's my notebook:

# Description
When running the line:

`combined = g2.intersection(g3)`
  
the kernel will crash and Jupyter throws the error: 

    Assertion failed: (0), function query, file AbstractSTRtree.cpp, line 285.
    Abort trap: 6

A possible solution was to reinstall shapely from source: 

`pip uninstall shapely && pip install --no-binary :all: shapely`

but @guziy's suggestion on https://github.com/geoplex/elasticsearch-spatial/issues/1 got me to wonder, so I tried replacing the fiona import line.

```python
%load_ext watermark
%watermark
```
    2017-01-05T11:44:44
    
    CPython 2.7.11
    IPython 5.1.0
    
    compiler   : GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)
    system     : Darwin
    release    : 15.6.0
    machine    : x86_64
    processor  : i386
    CPU cores  : 8
    interpreter: 64bit

```
%%sh
pip uninstall -y shapely  # remove the shapely from the virtualenv and use the global package
```

```python
import shapely
shapely.__file__  # returns '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages/shapely/__init__.pyc'

import fiona  # <--- doesn't crash when commented out
from shapely.geometry import shape
scene_metadata = {u'geometry': {u'coordinates': [[[5.4438, 30.7100517],
                                                  [6.2335518, 30.6927744],
                                                  [6.2013482, 29.7034878],
                                                  [5.1922031, 29.7240552],
                                                  [5.2265358, 29.8585064],
                                                  [5.2640662, 30.0064961],
                                                  [5.3019095, 30.1543621],
                                                  [5.4438, 30.7100517]]],
                                u'type': u'Polygon'}}

g1 = shape(scene_metadata['geometry'])

from shapely import affinity
g2 = affinity.rotate(g1, 30)

combined = g2.intersection(g1)  # <----- ***CRASH***

```

**Comment by dmwelch** [comment]
Toblerity/Fiona#383

**Comment by denadai2** [comment]
I was having this issue too, thank you!
