### ISSUE TITLE
Crashes when osgeo and shapely streams are crossed

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#262]
See https://github.com/Toblerity/Shapely/issues/260.

Users shouldn't mix osgeo.* modules and Shapely. There's no need: osgeo.ogr provides the same functionality as Shapely, if not so neatly, and Fiona and Rasterio pretty much replace osgeo.ogr, osgeo.gdal and are designed to work well with Shapely.

But. It's important to understand what goes wrong between osgeo.ogr, Shapely, and GEOS in some situations.

Without very precise crash reports this is going to be a time sink, so lots of detail please!

**Comment by olt** [comment]
I can trigger an assertion in a fresh virtualenv with only Fiona and Shapely with the following script. https://gist.github.com/olt/612361b0bd6cddeff3b4

It does work if I import Shapely first. 

My environment:

* Mac OS X 10.10.2
* Python 2.7.9 (homebrew)
* Fiona-1.5.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
* Shapely-1.5.7-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl

It does also work if I install Fiona and Shapely from source (`--no-use-wheel`).

**Comment by sgillies** [comment]
Thanks for the report @olt! 

I'm using the python.org OS X Python 2.7.9 and the script runs fine for me. Your data suggests that the problem is mostly an issue of binary compatibility between the shared library in the binary wheels and Python, yes? Previously it had looked to me that different GEOS shared libraries in osgeo.ogr and Shapely (due to a mix of Homebrew and pip) were the problem.

Here's how the GEOS shared lib is built for those wheels (https://github.com/sgillies/frs-wheel-builds/blob/master/buildout.cfg#L9-L17):

```
[geos]
recipe = hexagonit.recipe.cmmi
url = http://download.osgeo.org/geos/geos-3.4.2.tar.bz2
environment =
    MACOSX_DEPLOYMENT_TARGET=10.6
configure-options =
    CFLAGS="-arch i386 -arch x86_64"
    CXXFLAGS="-arch i386 -arch x86_64"
    LDFLAGS="-arch i386 -arch x86_64"
```

This is my attempt to match python.org.

I looked into the Python Homebrew formula and see that your Python will have been compiled with

```
MACOSX_DEPLOYMENT_TARGET=10.10
CFLAGS="-arch x86_64"
```

According to https://github.com/MacPython/wiki/wiki/Spinning-wheels#question-will-pip-give-me-a-broken-wheel, the 10.6 Python SDK should be compatible with 10.9, and I hoped it would be with 10.10. Apparently, it's breaking down in a weird way.

At the very least, it looks like I should not tag those wheels for intel.macosx-10.10-x86_64, yes?

**Comment by olt** [comment]
> At the very least, it looks like I should not tag those wheels for intel.macosx-10.10-x86_64, yes?

I can't really give you any help with this wheel/binary business. 


I just did a few more tests. Shapely is loading the right lib files from .dylibs.
The .dylib files have the same size, but they differ.

    % diff shapely/.dylibs/libgeos-3.4.2.dylib fiona/.dylibs/libgeos-3.4.2.dylib
    Binary files shapely/.dylibs/libgeos-3.4.2.dylib and fiona/.dylibs/libgeos-3.4.2.dylib differ

And it does work if I copy the GEOS libs from Shapely to Fiona.

**Comment by sgillies** [comment]
@olt Would you be willing to try some new wheels? I'll link them here in 15 minutes or so.

**Comment by sgillies** [comment]
@olt Update: I *can* (wasn't properly testing the wheels before) reproduce the problem, and on 10.9. Deleting my previous comment, will report back soon.

**Comment by snorfalorpagus** [comment]
I can also reproduce this. Homebrew Python 3.4.3, OS X 10.10.3. Copying either the geos libraries from shapely to fiona or fiona to shapely fixes the issue. No idea what is going wrong.

**Comment by snorfalorpagus** [comment]
Same error reported here on GEOS bug tracker (closed, unresolved): 
http://trac.osgeo.org/geos/ticket/468

Problem reported with Basemap and shapely:
http://stackoverflow.com/a/27693844/1300519

**Comment by snorfalorpagus** [comment]
You don't need to import fiona itself. Having the GEOS library loaded using ctypes is enough:

```
import ctypes
lib = ctypes.CDLL('fiona/.dylibs/libgeos_c.1.dylib')
import shapely.geometry
...
s.is_valid
```
It doesn't seem to be the fiona library specifically either. Throwing my build of libgeos_c into the mix triggers the problem also.

**Comment by snorfalorpagus** [comment]
Trying to distill this down to the simplest test case that fails, I've written this:

https://gist.github.com/snorfalorpagus/ae655e91ffa56ff9111c

I'm not convinced that there is actually a problem with the build of libgeos in either shapely or fiona (although I'm not sure why they are different). The problem is triggered if you call `GEOSisValid` on this particular geometry, using the version of GEOS that wasn't loaded first. This is why it crashes when you load fiona first, but not if you load shapely first. I guess it's quite an unusual situation to have two copies of the same library loaded into a single process.

**Comment by sgillies** [comment]
@snorfalorpagus the GEOS libraries start out exactly the same, but are modified slightly by the OS X install_name_tool (via [delocate](https://github.com/matthew-brett/delocate)). You've already noted that Shapely doesn't care which is which, and that's what I expect: they are practically identical.

My understanding of what happens when we `import fiona; import shapely` is this:

1. importing fiona causes import of C extension modules (ogrext.so etc) and those load libgeos_c.dylib and libgeos-3.4.2.dylib from the files in the Fiona wheels (due to work of delocate).
2. importing shapely leads to ctypes loading libgeos_c.dylib as well, but as it is already loaded, ctypes.CDLL should just give us a handle to Fiona's library. As if there was only one GEOS DLL on the system (/usr/local/lib or somewhere).

Apparently my understanding is wrong. I was reading the man page for `dlopen()` yesterday and there are a number of options. Maybe ctypes isn't using the ones I think it is. Time for a deeper look.

**Comment by snorfalorpagus** [comment]
I tried changing RTLD_GLOBAL and RTLD_LOCAL, to no effect.

I can replicate the problem in C, so perhaps we can bring this issue to the GEOS bug tracker?

https://gist.github.com/snorfalorpagus/ae655e91ffa56ff9111c#file-issue262-c

**Comment by sgillies** [comment]
@snorfalorpagus Fantastic, I'm going to put this to use. Before I report anything to GEOS, I'm trying different options when building the library.

**Comment by sgillies** [comment]
@snorfalorpagus I've built GEOS using the `--disable-cassert` option (extract from the buildout config below)

```
[geos]
recipe = hexagonit.recipe.cmmi
url = http://download.osgeo.org/geos/geos-3.4.2.tar.bz2
environment =
    MACOSX_DEPLOYMENT_TARGET=10.6
configure-options =
    --disable-dependency-tracking
    --disable-cassert
    CFLAGS="-arch i386 -arch x86_64"
    CXXFLAGS="-arch i386 -arch x86_64"
    LDFLAGS="-arch i386 -arch x86_64"
```

and @olt's script succeeds. Do you have any insight into this, @hobu? Why the hell are assertions allowed to be disabled, and if this is the solution, why aren't disabled assertions the default?

**Comment by oztalha** [comment]
+1. `networkx`'s `read_shp` uses gdal and causes this error. I got this error when I upgraded pypi's shapely (1.5.7) with the github's master (1.6b4). I solved the problem by having
`from osgeo import ogr` before importing shapely.

**Comment by sgillies** [comment]
See also #553.
