### ISSUE TITLE
polygon.py example at http://toblerity.org/shapely/manual.html#polygons doesn't work 

### ISSUE THREAD

**Issue by xotrs** [Toblerity/Shapely#272]
from matplotlib import pyplot
from matplotlib.patches import Circle
from shapely.geometry import Polygon
from descartes.patch import PolygonPatch

from figures import SIZE

----------------------------------------------------------------
from figures import SIZE
ImportError: No module named figures
----------------------------------------------------------------

I installed shapely, matplotlib, descartes

**Comment by snorfalorpagus** [comment]
The `figures` module is used by scripts in the manual for a few constants, such as figure size and colours:

https://github.com/Toblerity/Shapely/blob/master/docs/code/figures.py

**Comment by xotrs** [comment]
@snorfalorpagus thx:) i will check
