### ISSUE TITLE
Point within LinearRing returns False?

### ISSUE THREAD

**Issue by shongololo** [Toblerity/Shapely#275]
Checking if the following point is within a LinearRing returns False:
 
<code>
sq = geometry.LinearRing([[0,0], [1,0], [1,1], [0,1]]) 
print(geometry.Point([0.5, 0.5]).within(sq))
</code>
Whereas something similar as a Polygon instead, returns True:
<code>
sq = geometry.Polygon([[0,0], [1,0], [1,1], [0,1]]) 
print(geometry.Point([0.5, 0.5]).within(sq))
</code>

Is this an issue, or is there something I'm missing?

**Comment by bixb0012** [comment]
The results are as expected.  A LinearRing is a LineString.  The interior of a LineString is the line itself, so a point would have to be on a line to be within a line.  Even though a LinearRing is closed, the enclosed space within the ring is still the LinearRing's exterior.  With your Polygon example, the enclosed space is the Polygon's interior, so your point is within the Polygon.

**Comment by shongololo** [comment]
OK, thanks for clarifying.

**Comment by shongololo** [comment]
I've been thinking about this some more and wish to suggest that this behaviour be revised. I realise the strict geometric interpretation behind this rationale, but it is counterintuitive and possibly results in more steps being required to get things done from the point of view of working with the actual geometries in python.

For example, to check if a point is within an interior hole inside a polygon, one first has to convert the interior LinearRing to a Polygon, then do the check.

Similarly, to find a representative_point() of an interior hole, then it is necessary to first cast to a Polygon, and then deduce the point.

I imagine there are use cases for the current methodology, but I struggle to think what these are?

Thanks.

**Comment by bixb0012** [comment]
For the most part, this is a [GEOS](http://trac.osgeo.org/geos) issue and not a Shapely issue.  Shapely is based on GEOS, and the behavior you would like to see changed has been implemented in GEOS.  Beyond that, the behavior you would like to see changed is defined within the OGC Simple Feature standards \[[Part 1: Common Architecture](http://www.opengeospatial.org/standards/sfa), [Part 2: SQL Option](http://www.opengeospatial.org/standards/sfs)\].

I think it is unlikely this behavior will be changed in the OGC standards or GEOS, which leaves a couple of options on the Shapely table.  First, Shapely could redefine or do some kind of overloading/overriding of what is implemented in the OGC standards and GEOS.  I don't speak for the active contributors, but I also think this would be unlikely.  Second, Shapely could add some above-and-beyond functionality that isn't in conflict with standards or OGC.

The latter approach is the path that [OpenLayers](http://openlayers.org) went down by creating a [containsPoint](http://dev.openlayers.org/docs/files/OpenLayers/Geometry/LinearRing-js.html#OpenLayers.Geometry.LinearRing.containsPoint) function for the LinearRing geometry.  From a performance perspective, would `ring.containsPoint(pt)` perform any better than `Polygon(ring).contains(pt)` that already works?  I don't know.

**Comment by shongololo** [comment]
Thanks, quite helpful for larger context. Since this is based on GEOS it makes sense to leave as is and just do the casting to Polygon when needed.

**Comment by terryspitz** [comment]
I eventually found this issue when i went to raise a bug report (for LinearRing.contains(LinearRing)==False).  Perhaps this behaviour could be called out in the documentation to avoid further confusion.

**Comment by sgillies** [comment]
I would be happy to review a documentation PR but can't otherwise spend the time on this now.
