### ISSUE TITLE
shape.buffer(0.0) returns empty polygon

### ISSUE THREAD

**Issue by willholley** [Toblerity/Shapely#277]
I'm attempting to clean invalid geometries (generated from potrace) using the buffer(0.0) mechanism. Some examples of the geometries in GeoJSON:

    {"type": "Polygon", "coordinates": [[[-7.993744, 54.52575], [-7.9938, 54.525728], [-7.9938, 54.525556], [-7.9938, 54.525385], [-7.993729, 54.525357], [-7.993658, 54.52533], [-7.99347, 54.525331], [-7.993283, 54.525331], [-7.993229, 54.525365], [-7.993175, 54.5254], [-7.993431, 54.525399], [-7.993688, 54.525397], [-7.993688, 54.525589], [-7.993688, 54.52578], [-7.993688, 54.525777], [-7.993688, 54.525773], [-7.993744, 54.52575]]]}

   {"type": "Polygon", "coordinates": [[[-8.060614, 54.369195], [-8.06067, 54.369172], [-8.06067, 54.369064], [-8.06067, 54.368955], [-8.060614, 54.368955], [-8.060557, 54.368955], [-8.060557, 54.36909], [-8.060557, 54.369225], [-8.060557, 54.369221], [-8.060557, 54.369218], [-8.060614, 54.369195]]]}

These geometries, when loaded, appear to be invalid (shapely doesn't tell me why but http://geojsonlint.com/ suggests that both these examples fold back on themselves), so I use the buffer(0.0) function to clean them:

    >>> s = shapely.geometry.shape(json_data)
    >>> s.is_valid
    False
    >>> clean = s.buffer(0.0)
    >>> clean.is_valid
    True

However, the generated geometry is empty:

    >>> clean.area
    0.0
    >>> clean.exterior.coords[:]
    Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
    AttributeError: 'NoneType' object has no attribute 'coords'
   
This seems like a bug in the buffer(0.0) function? 99% of the geometries I use this method for are cleansed correctly but there are enough failures that I will have to look at other solutions.

**Comment by bixb0012** [comment]
The polygon isn't valid because it self-intersects in the upper right corner around vertices 8, 9, and 10:
![geojson_invalid_polygon](https://cloud.githubusercontent.com/assets/11165430/7817584/8b229186-039b-11e5-955e-018f5026e3d7.PNG)
Have you thought about or tried using [object.simplify](http://toblerity.org/shapely/manual.html#object.simplify) instead of [object.buffer](http://toblerity.org/shapely/manual.html#object.buffer)?

Cleaning invalid geometries is messy business because there are so many ways a geometry can be invalid.  If you are frequently running into invalid geometries, maybe addressing the issue upstream would be better than waiting to clean up an invalid geometry after it has been created with Shapely.

**Comment by bixb0012** [comment]
A quick check in PostGIS shows the same result, i.e., empty polygon.  Interestingly enough, SQL Server returns the exact same invalid geometry when using buffer.

Thinking of your comment that [object.is_valid](http://toblerity.org/shapely/manual.html#object.is_valid) only returns False, with no additional information, it would be helpful if more information could be accessible through GEOSisValidReason like GeoDjango.

Unfortunately, I don't think GEOS has implemented a MakeValid function yet.

**Comment by mabl** [comment]
You *can* get a reason for the invalidity of an object, try ``shapely.validation.explain_validity``

**Comment by sgillies** [comment]
@willholley as I understand the GEOS buffer algorithm, it buffers valid geometries, and incidentally can be used to fix *some* invalid geometries like classic bowties. It is not designed to clean arbitrary invalid geometries and so `buffer(0.0)` will let you down sometimes.

**Comment by bixb0012** [comment]
@mabl, thanks.  I don't think `shapely.validation.explain_validity` is as intuitive as `ST_IsValidDetail` in PostGIS or `GEOSGeometry.valid_reason` in GeoDjango, but it functionally meets the need.

**Comment by willholley** [comment]
Thank you everybody for chipping in. I'll look into improving the GeoJSON output from potrace and it's good to know I can get the validation failure from shapely if needed.

**Comment by damonmaria** [comment]
Just in case this helps anyone else. I too was having problems with a polygons where buffer(0) was returning empty. I have no control over the source of these polygons (OpenCV). simplify(0) did not work, nor did simplify(1). But higher values did. This didn't seem robust as what would be high enough in all situations?

In the end I went with buffer(0.1). Which doesn't affect me much as I end up converting back to OpenCV and therefore integers.
