### ISSUE TITLE
Review and update README

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#281]
The doc is old. I want to review that it's still current and still addresses the right audience.

**Comment by snorfalorpagus** [comment]
I've always thought that the figure at the top of the README (from `dissolve.py`) was a little too abstract. Particularly when the opening statement is quite technical. The principal use of shapely is for geographic data, although I'm sure it has applications outside this area. It might be nice if there was some context for the figure - what are the points, why are we buffering them? At the same time I understand the desire to stay away from the obviously recognisable "world map" type figure, as shapely doesn't natively deal with coordinate systems. A couple of examples that would be similar, but with some context: identifying "green corridors" created by tree canopies between parks in an urban space; or checking for line of sight for microwave transmissions.

**Comment by mabl** [comment]
I use shapely for lithography mask design in the context of photonic chip design but examples are probably to complex...

**Comment by sgillies** [comment]
@snorfalorpagus the README could use a refresh for sure! I'm open to anything simple and compelling.

**Comment by sgillies** [comment]
@snorfalorpagus I swapped in the dilation and erosion image from the manual and think it looks better: https://github.com/Toblerity/Shapely/tree/maint-1.6.
