### ISSUE TITLE
Version string can't handle non-integer values

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Shapely#282]
The current `master` branch is failing to build because it can't handle `"1.6rc1"` as a version string:

```
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/home/travis/build/Toblerity/Shapely/setup.py", line 53, in <module>
        shapely_version = tuple(int(x) for x in version.split('.'))
      File "/home/travis/build/Toblerity/Shapely/setup.py", line 53, in <genexpr>
        shapely_version = tuple(int(x) for x in version.split('.'))
    ValueError: invalid literal for int() with base 10: '6rc1'
```

https://travis-ci.org/Toblerity/Shapely/jobs/64357932

**Comment by snorfalorpagus** [comment]
It looks like this variable is being used for version comparison, in which case we should probably be using `distutils.version`?

http://stackoverflow.com/a/11887885/1300519

```
>>> from distutils.version import LooseVersion, StrictVersion
>>> LooseVersion("2.3.1") < LooseVersion("10.1.2")
True
>>> StrictVersion("2.3.1") < StrictVersion("10.1.2")
True
>>> StrictVersion("1.3.a4")
Traceback (most recent call last):
...
ValueError: invalid version number '1.3.a4'
```

**Comment by sgillies** [comment]
Funny, I thought we were better than this. Can't wait to see who git-blame fingers... ;)

**Comment by sgillies** [comment]
@snorfalorpagus [packaging](http://packaging.readthedocs.org/en/latest/version/#usage) is another, more current, option. I'll compare it with distutils.version.

**Comment by sgillies** [comment]
distutils.version has a bug:

```python
>>> from packaging.version import Version
>>> from distutils.version import LooseVersion
>>> Version('1.6rc1') > Version('1.6.1')
False
>>> LooseVersion('1.6rc1') > LooseVersion('1.6.1')
True
```

A release candidate shouldn't eval to greater than a final or patch release.

It is worth adding packaging as a dependency, or do we just improve our own parser?

**Comment by sgillies** [comment]
I decided packaging is a positive dependency. Here's my solution: https://github.com/Toblerity/Shapely/commit/77c354a46be65a1a7ea259eff6d78d62ced44f06.

**Comment by snorfalorpagus** [comment]
@sgillies You've missed one I think. Not sure why this works in 2.x but not 3.x. I would fix, but am very busy this weekend (trying to buy a house!)

https://travis-ci.org/Toblerity/Shapely/builds/64641221

**Comment by sgillies** [comment]
I've straightened it out. 

I went overboard on using packaging's Version class, applying it to the GEOS version, but have reverted those.
