### ISSUE TITLE
Speedup build not linking GEOS library...

### ISSUE THREAD

**Issue by andyreagan** [Toblerity/Shapely#283]
I've built shapely with speedups just fine on OSX and now I'm trying to install on RHEL cluster.

GEOS is built locally, and is available:
>    (pyenv)% geos-config --ldflags
>    -L/users/a/r/areagan/usr/bin/lib

But the speedups build fails, when it can't find the header, but it's not including the above library.
Maybe I'm missing something.

>  Running setup.py install for shapely
>    building 'shapely.speedups._speedups' extension
>    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/gpfs1/arch/x86_64/python2.7.5/include -I/gpfs1/arch/x86_64/python2.7.5/include/python2.7 -c shapely/speedups/_speedups.c -o build/temp.linux-x86_64-2.7/shapely/speedups/_speedups.o
>    shapely/speedups/_speedups.c:247:20: fatal error: geos_c.h: No such file or directory
>     #include "geos_c.h"
>                        ^
>    compilation terminated.

**Comment by andyreagan** [comment]
I was able to install by downloading the source code (cloning this repository) and installing with `python setup.py install`
Not sure why this worked and pip didn't, so I'm not sure if this is an issue or not.
I'll leave it open for a few days in case.

Cheers.

**Comment by sgillies** [comment]
It looks to me like you've installed GEOS to a non-standard location. If geos-config isn't on your executable path when you run `pip install shapely`, you'll need to set a GEOS_CONFIG variable as explained in https://github.com/Toblerity/Shapely#installing-shapely.

**Comment by andyreagan** [comment]
I did have the GEOS_CONFIG variable exported, but that didn't help.

**Comment by imk1** [comment]
I am having the same problem.  I tried exporting the GEOS_CONFIG variable and then uninstalling and re-installing Shapely, and that did not solve the problem.

**Comment by imk1** [comment]
I just tried switching to Shapely version 1.5.3, and that seems to have solved the problem.
