### ISSUE TITLE
parallel_offset() returns linestring in reverse order

### ISSUE THREAD

**Issue by tomvansteijn** [Toblerity/Shapely#284]
When offsetting on the right side, the order of linestrings is reversed:

```
from shapely.geometry import LineString
line = LineString([(0, 0),(0, 100)])
lcoords = line.parallel_offset(10, 'left').coords[:]
rcoords = line.parallel_offset(10, 'right').coords[:]
[y for x,y in lcoords] == [y for x,y in reversed(rcoords)]
```
Returns ```True```. I don't see the reasoning behind this. Is it a bug?

**Comment by snorfalorpagus** [comment]
This is the behaviour of the GEOS function that is used to implement the `parallel_offset` method. I'm not sure the reason for it (it could be a side effect of the methodology, or a conscious decision I'm not aware of)

https://github.com/Toblerity/Shapely/blob/6d693e7a750cec83fe0e27ac631b85ffdae1b92a/shapely/geos.py#L666-L670
https://github.com/Toblerity/Shapely/blob/9b5a0123d64f533b61a8228448f5285422842327/shapely/geometry/linestring.py#L112-L143

**Comment by tomvansteijn** [comment]
Thank you for the links. I noticed the docstring of ```parallel_offset``` says negative distance values are supported. However this returns an empty list on my machine. I am using version 1.5.9. Perhaps another issue, or a a sign my installation (on Windows) is not working well.

**Comment by snorfalorpagus** [comment]
What version of GEOS are you using? Passing a negative distance to the function should reverse the side given, e.g. if you give `left` it does `right`.

**Comment by snorfalorpagus** [comment]
@tomvansteijn ping

**Comment by tomvansteijn** [comment]
Hi, I am using shapely 1.5.9 installed from .whl. No idea which version if GEOS comes with it.

**Comment by tomvansteijn** [comment]
```
ls = Linestring([(0,0), (0, 1)])
ls.parallel_offset(-1, 'left').coords
```
returns an empty list.

**Comment by sgillies** [comment]
With GEOS 3.4.2, I see this:

```python
>>> ls = LineString([(0,0), (0, 1)])
>>> ls.parallel_offset(-1, 'left').wkt
'LINESTRING (1 1, 1 0)'
>>> ls.parallel_offset(1, 'right').wkt
'LINESTRING (1 1, 1 0)'
```

So I'm going to close this issue.

@snorfalorpagus I'm not sure we should have two ways of specifying the offset (right/left vs postive/negative) and apparently there's some flakiness with negative buffer distances with some versions of GEOS. What would you think about my removing the note about negative distances in the docstring?

**Comment by tomvansteijn** [comment]
Using shapely 1.5.13 I can reproduce this. The issue seems solved.

**Comment by tomvansteijn** [comment]
Using shapely 1.5.13 the problem does not occur. I can reproduce the above!

**Comment by snorfalorpagus** [comment]
@sgillies In that case do we need to enforce that distance >= 0?

In GEOS 3.3.x the function does this for us (i.e. if you pass a negative distance, makes it positive and flips the side):

https://github.com/libgeos/libgeos/blob/a291393068a45150313140d57972d9c914e21f21/capi/geos_ts_c.cpp#L1914-L1917

In older versions it uses a different function: https://github.com/libgeos/libgeos/blob/a291393068a45150313140d57972d9c914e21f21/capi/geos_ts_c.cpp#L1936

**Comment by sgillies** [comment]
@snorfalorpagus thanks for pointing out this detail. I think we can and should switch to follow GEOS for backwards compatibility, but remove negative distances from documented usage.

**Comment by JayanthRR** [comment]
Hi, I still face the reverse ordering of parallel offset in Shapely 1.6.1. Below is the code and the out. 

`from shapely.geometry import LineString, Polygon
l = LineString([(1,4), (1,10)])
pr = l.parallel_offset(5, 'right')
pl = l.parallel_offset(5, 'left')
l.coords.xy, pr.coords.xy, pl.coords.xy`

The output is as follows. 
((array('d', [1.0, 1.0]), array('d', [4.0, 10.0])),
 (array('d', [6.0, 6.0]), array('d', [10.0, 4.0])),
 (array('d', [-4.0, -4.0]), array('d', [4.0, 10.0])))

The order of the y coordinates for the right shift is reversed.  This thread contains discussion regarding using a negative distance with direction as left instead of positive distance with direction as right, but I am afraid I couldn't find the solution to why the resultant line string is in the reverse order. Is there any quick fix to this or should I manually reverse it once I offset it to the right? Thanks in advance.

**Comment by rajanski** [comment]
I also have the problem of reversed linestrings, with shapely 1.6b2 and geos 3.5.1

**Comment by jeueblah** [comment]
+1 for reversed linestrings in 1.6.3, negative distance does not resolve the issue.

**Comment by aj-hitchins** [comment]
```
python 3.6.7
shapely 1.6.4.post2
geos 3.6.2
```
I also have this issue, and as @jonschwenk mentioned the negative distance did not solve the issue. I need to use both `left` and `right` in what I am using `parallel_offset` for and I am repeating the operation on the offset line each time. When running `side="left"` first, the lines duplicated as expected, then I go back to the original line and run it `side="left"` which causes the line to reverse, the second duplication of offset right causes the line to go back to the original line and this is repeated many times over.

I have this fix to repeatedly offset the lines:
```python
# Part of a loop
new_line = generated_line.parallel_offset(distance=distance_in_m, side=side)

if side == "right":
    new_line = LineString([(x, y) for x, y in zip(reversed(new_line.coords.xy[0]), reversed(new_line.coords.xy[1]))])
    generated_line = new_line
else:
    generated_line = new_line
```

**Comment by ShivKJ** [comment]
btw, is there a built in function to reverse direction of a line segment. For example, if line segment: `(0, 0) -> (1, 0)` then reversed line segment = `(1, 0) -> (0, 0)` ?

**Comment by PBrockmann** [comment]
Same pitfall... Interested in a built in function to reverse direction of a line segment.
Any news on that issue ?
