### ISSUE TITLE
INCLUDEDIR not defined on windows

### ISSUE THREAD

**Issue by groutr** [Toblerity/Shapely#285]
Setup.py will fail building the speedups module on windows because INCLUDEDIR is not defined on windows.  At least none of my windows machines I have tested this on have that variable defined.

```python
>>> from distutils.sysconfig import get_config_var
>>> get_config_var("INCLUDEDIR") == None
True
```
Is method used to find the Python headers?
If we are just trying to find the location of the Python headers, we can get that in a platform agnostic way using ```get_python_inc()``` (from distutils.sysconfig) or ```get_config_var("INCLUDEPY")```
If we also need the numpy headers, we can get those with ```numpy.get_include()```

If I can get a little more info on what include files we are needing, I can submit a PR.  As it stands, the current setup.py will cause Cython throw a cryptic error on Windows.

**Comment by sgillies** [comment]
@groutr I didn't see that INCLUDEDIR made any difference, so I removed it. Travis https://travis-ci.org/Toblerity/Shapely/builds/65193472 is all :green_heart:
