### ISSUE TITLE
Support .project on LinearRing

### ISSUE THREAD

**Issue by hyperknot** [Toblerity/Shapely#286]
It'd be great to support .project on LinearRings. Right now it's not supported. Would be useful for getting sections of country borders between two points for example.

`.distance` is supported between a Point and a LinearRing, so the needed algorithm is already done I guess, it's just hiding the projection point.

**Comment by hyperknot** [comment]
It is actually supported perfectly, the only thing limiting it is the assert line here:
https://github.com/Toblerity/Shapely/blob/master/shapely/linref.py#L11

Editing that line (or commenting it out for testing), allows `.project` and `.interpolate` to work perfectly with LinearRings.

**Comment by sgillies** [comment]
Thanks!
