### ISSUE TITLE
_geos.pxi installed into "/usr/shapely"

### ISSUE THREAD

**Issue by felixonmars** [Toblerity/Shapely#287]
It would be great if _geos.pxi could be installed in standard path like "/usr/share" or "/usr/lib" etc, instead of "/usr/shapely".

Reproduced on:
Python 3.4.3/2.7.10
Setuptools 17.1.1

Related logs: (I have `--root=/build/python-shapely/pkg/python2-shapely` specified)
```
running install_data
creating /build/python-shapely/pkg/python2-shapely/usr/shapely
copying shapely/_geos.pxi -> /build/python-shapely/pkg/python2-shapely/usr/shapely
running install_egg_info
running egg_info
writing Shapely.egg-info/PKG-INFO
writing top-level names to Shapely.egg-info/top_level.txt
writing dependency_links to Shapely.egg-info/dependency_links.txt
reading manifest file 'Shapely.egg-info/SOURCES.txt'
writing manifest file 'Shapely.egg-info/SOURCES.txt'
Copying Shapely.egg-info to /build/python-shapely/pkg/python2-shapely/usr/lib/python2.7/site-packages/Shapely-1.5.9-py2.7.egg-info
running install_scripts
```

**Comment by pelson** [comment]
The re-usability of _geos.pxi was one of the motivations for pulling it out when I put together the vectorisation functionality, so I'm definitely keen for others to make use of it (with the caveat that it *does* start with an underscore, so should not be considered stable). However, would you mind clarifying *why* it would be great if it were installed in a standard path? Does that make Cython automatically pick it up or other such like?

**Comment by felixonmars** [comment]
Not sure for cython, as the only other *.pxi files on my disk are in the twisted package, under its own hierarchy.

I would see this a good thing to do from a packager's point of view. Each distribution has its own set of rules for FHS. As I am trying to packaging the shapely package for Arch, here are the related dirs (quoting from the [Wiki page][https://wiki.archlinux.org/index.php/Namcap#Files]:

    The allowed directories are: bin/, etc/, usr/bin/, usr/sbin/, usr/lib, usr/include/, usr/share/, opt/, lib/, sbin/, srv/, var/lib/, var/opt/, var/spool/, var/lock/, var/state/, var/run/, var/log/.

So if upstream puts a file outside of the standard hierarchy, the downstream packagers will have to "fix" this themselves. This could lead to differences between a pip installation and a system packaged one, or even differences among distributions, making it less portable in the end.

**Comment by sgillies** [comment]
@pelson would you be okay if I followed Twisted's lead and put `_geos.pxi` in the package itself. Like https://github.com/twisted/twisted/blob/ed075dad7339456c47fe43a51a12ee4b5910e0fd/MANIFEST.in#L39?

**Comment by pelson** [comment]
Mi culpa on this one - I missed the fact that we were already doing this with shapely. We should totally put `_geos.pxi` in a helpful place and not the prefix root. 👍
