### ISSUE TITLE
Polygon intersection bug

### ISSUE THREAD

**Issue by tinloaf** [Toblerity/Shapely#289]
Hi. According to the documentation, "intersects()" is "the OR-ing of contains(), crosses(), equals(), touches(), and within()". Now consider this:

```
>>> p1 = Polygon(((0, 0), (1,0), (1,-1), (0,0)))
>>> p3 = Polygon(((0.5, -0.5), (0.5, 0.5), (1,1), (1,-1)))
>>> p1.intersects(p3)
True
>>> p1.contains(p3)
False
>>> p1.crosses(p3)
False
>>> p1.within(p3)
False
>>> p1.touches(p3)
False
>>> p1.equals(p3)
False
```

Obviously, that is not the case. It looks like there is one more binary predicate that evaluates to true if two objects overlap on their interior but do not contain each other, and that is also ORed into intersects().

Now, that is what I need (i.e. I need to test for overlap that is not just a touching..). It looks like I can do "p1.intersects(p3) and not p1.touches(p3)". Is that the only way or is that "missing" predicate exposed somehow?

In any case, the documentation is wrong there.

**Comment by tinloaf** [comment]
This is the documentation I'm referring to: http://toblerity.org/shapely/manual.html#object.intersects

**Comment by bixb0012** [comment]
I think `object.overlaps()` is what you are after.

I agree about the documentation missing something.  That said, if you are really interested in understanding the spatial operators, reading up on the Dimensionally Extended 9 Intersection Model [(DE-9IM)](https://en.wikipedia.org/wiki/DE-9IM) is worth the time.

**Comment by mwtoews** [comment]
You can visually interact with the relations with JTS TestBuiler, which is a Java GUI with JTS, and works on all of the OSes. E.g.

![JTS TestBuiler](http://i.imgur.com/pg5NDwb.png)

**Comment by sgillies** [comment]
@tinloaf the above suggestion of `overlap` is right on, I think. I'll improve the documentation of intersects.
