### ISSUE TITLE
getNumPoints?

### ISSUE THREAD

**Issue by bixb0012** [Toblerity/Shapely#291]
When looking at the [GEOS Geometry Class Reference](http://geos.osgeo.org/doxygen/classgeos_1_1geom_1_1Geometry.html), I see a `getNumPoints` function.  However, when I create a simple Polygon object in Shapely, that GEOS function doesn't seem to be available.  Is it not present or am I overlooking something.

**Comment by sgillies** [comment]
It's not present. One way to do it with Shapely is

```python
>>> poly = Point(0,0).buffer(1.0)
>>> len(poly.exterior.coords) + sum(len(ring.coords) for ring in poly.interiors)
66
```

**Comment by bixb0012** [comment]
If it is already present in the GEOS library, correct me if I am wrong, how much work is involved in adding its support?  (NOTE:  I come at this from an end user or scripter, not a developer).

Thanks

**Comment by mwtoews** [comment]
Another way is to use a somewhat unadvertised [`dump_coords` function](https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/base.py#L40), which returns a list of coordinates from any geometry, regardless of type:
```python
from shapely.geometry.base import dump_coords
len(dump_coords(poly))  # 66
```
