### ISSUE TITLE
ST_Split

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Shapely#293]
PostGIS implements a function called `ST_Split`, which can split a polygon by a line (as well as line by line, or line by point): http://postgis.net/docs/ST_Split.html

Is this something we'd like to be able to do with Shapely?

I think there is an issue with the fact PostGIS is licence under GPL. Given that PostGIS also uses GEOS it might be difficult to write anything that wasn't too close to a straight copy, even though the algorithm isn't especially complicated.

**Comment by sgillies** [comment]
@snorfalorpagus sure, I welcome functions like this in Shapely. Don't copy the PostGIS code and all is fine. Testing that the process is reversible using Shapely's `union` would be good to do.

**Comment by snorfalorpagus** [comment]
We don't currently wrap `GEOSRelatePatternMatch`. Any suggestions on where this should go?

`g1.relate_match(g2, '1********') == True` ?

**Comment by snorfalorpagus** [comment]
Relate was implemented 36b0e8b24541de916f48791734eacb27ddb71d4e, but I've not found the time to finish `ST_Split` yet.

**Comment by georgeouzou** [comment]
I could implement the function, if you have not the time @snorfalorpagus

**Comment by snorfalorpagus** [comment]
@georgeouzou Sure, give it a go!

https://gist.github.com/snorfalorpagus/46ef62d515e28f0a9e9f

That's as far as I got.

**Comment by snorfalorpagus** [comment]
Closed by #371.
