### ISSUE TITLE
setup.py crashes when get_config_var returns None

### ISSUE THREAD

**Issue by Andyjo07** [Toblerity/Shapely#298]
In the 1.5.9 tag, if get_config_var returns None, the built of the given extension will fail deep in the guts of searching for include files. This is found in two places, once for the _speedups extension (~line 179), and once for the _vectorized extension (~line 204).
My suggestion is to build the include_dirs lists outside of the DistutilsExtension constructor arguments, and perform None Checks, something like: 
include_dirs = [id for id in include_dirs if id is not None]

**Comment by sgillies** [comment]
@Andyjo07 since the release of 1.5.9 we've removed the use of `get_config_var()`

https://github.com/Toblerity/Shapely/commit/fddbb0d15cdc8086b168eb627e36390686312abb

I don't think a filter for `None` will be needed now.
