### ISSUE TITLE
MultiPoint.convex_hull doesn't contain all of the points

### ISSUE THREAD

**Issue by cyphar** [Toblerity/Shapely#302]
Given a setup like this (the numpy stuff just gives me a set of points inside a circle in a given coordinate system):

```
>>> xs, ys = numpy.mgrid[:20,:20]
>>> pts = np.transpose(np.where(((xs - 10)**2 + (ys - 10)**2 < 45).T))
>>> hull = shapely.geometry.MultiPoint(pts).convex_hull
```

One would assume that all of the points `pts` are contained within `hull`. However:

```
>>> all(hull.contains(shapely.geometry.Point(pt)) for pt in pts)
False
>>> sum(hull.contains(shapely.geometry.Point(pt)) for pt in pts) / len(pts)
0.7956204379562044
```

So about 20% of the points are missing. In my actual code case, almost all of the points are missing, and a whole bunch of points outside what I would define as the convex hull are included in the convex hull. Is there some explanation for what is going on?

**Comment by jwass** [comment]
`contains()` is defined such that a polygon does not "contain" a point that lies on its boundary. The missing 20% in your example are all the points that form the vertices of convex hull. `covers` will return True for points that are inside a polygon or on its boundary. Some more information here: https://en.wikipedia.org/wiki/DE-9IM

```
>>> all(hull.covers(shapely.geometry.Point(pt)) for pt in pts)
True
```

It's worth noting that the hull's exterior contains all of the missing points in this example
```
>>> points = [shapely.geometry.Point(pt) for pt in pts]
>>> not_contained = [p for p in points if not hull.contains(p)]
>>> all(hull.exterior.contains(p) for p in not_contained)
True
```

**Comment by snorfalorpagus** [comment]
This isn't a bug, but rather a misunderstanding of the specific technical meaning of the "contains" predicate. From the manual:


> *object.contains(other)*
>  Returns True if the object’s interior contains the boundary and interior of the other object and their boundaries do not touch at all.

This confusion isn't helped by the documentation for the convex hull method. The use of "contains" here isn't the DE-9IM definition, but the more casual meaning. I think that instead this should read "the smallest convex Polygon *intersecting* all the points".


> object.convex_hull
> Returns a representation of the smallest convex Polygon containing all the points in the object unless the number of points in the object is less than three. For two points, the convex hull collapses to a LineString; for 1, a Point.

The example below illustrates this. Points that are contained by the hull are coloured green, points that are not contained but do intersect (i.e. their boundaries touch) are coloured blue. Note that there are no red points (i.e. anything else).

```
import numpy as np
from shapely.geometry import MultiPoint, Point
import matplotlib.pyplot as plt

xs, ys = np.mgrid[:20,:20]
pts = np.transpose(np.where(((xs - 10)**2 + (ys - 10)**2 < 45).T))
hull = MultiPoint(pts).convex_hull

for pt in pts:
    pnt = Point(*pt)
    if hull.contains(pnt):
        style = 'og'
    elif hull.intersects(pnt):
        style = 'ob'
    else:
        style = 'or'
    plt.plot(pt[0], pt[1], style)

xs, ys = hull.exterior.xy
plt.plot(xs, ys, '-k')

plt.xlim(2, 18)
plt.ylim(2, 18)
plt.show()
```

![issue302](https://cloud.githubusercontent.com/assets/3883947/9335885/9483fb78-45ce-11e5-93b4-572bad4a0e7d.png)

**Comment by snorfalorpagus** [comment]
@jwass You beat me to it!

I do wonder if we need to correct the documentation for convex hull. From Wikipedia:
> Formally, the convex hull may be defined as the intersection of all convex sets containing X or as the set of all convex combinations of points in X.

**Comment by cyphar** [comment]
Okay, so my example was bad. My *actual* code (which isn't working at all) is more like this:

```
>>> any([shape.geometry.box(x, y, x + 1, y + 1).intersection(hull).area for x in range(pts.shape[0]) for y in range(pts.shape[1])])
False
```

Basically, I'm trying to figure out how much of every unit square in a grid is covered by the convex hull. My *actual* code gives me this output:

<img width="647" alt="screen shot 2015-08-19 at 9 51 40 am" src="https://cloud.githubusercontent.com/assets/2888411/9345780/edb5ea9c-4657-11e5-95c6-66e50c995da2.png">

The purple crosses are the pts, and the green discolouration is the output of the above list comp.

**Comment by jwass** [comment]
Hi @cyphar,
I'd expect the purple crosses in your example to be a circle centered at (10,10) like the points are in @snorfalorpagus's plot so I'd double check your plotting code.?

Also, we don't have much insight into your specific use here, but I think you're trying to use each point in `pts` as the corner of a 1x1 box. If so, that would look something like:
```
boxes = [shapely.geometry.box(x, y, x + 1, y + 1) for x, y in pts]
areas = [hull.intersection(box).area for box in boxes]
```

Probably worth pointing out that some points that get filtered out in your code have corresponding boxes that intersect the hull. This would explain why the total area of the intersections does not equal the area of the hull.

```
>>> sum(areas)
119.0
>>> hull.area
122.0
```

I'm not sure if that matters for you but either way I think we're likely straying beyond a Shapely issue. :smile:

**Comment by cyphar** [comment]
@jwass Yeah, turns out if I remove the shapely code from my code the problem still exists. I'll close this, sorry about that! Now to find out what the actual fuck is going on... :stuck_out_tongue:
