### ISSUE TITLE
ImportError: No module named packaging.version

### ISSUE THREAD

**Issue by pawl** [Toblerity/Shapely#305]
I'm getting an ImportError while installing the newest version of Shapely (1.5.10).

Running ```pip install packaging``` will resolve the issue.

**Comment by njwilson23** [comment]
I'm hitting this too on Travis build for a project. Worked fine a few days ago with 1.5.9.
An install log is here: https://travis-ci.org/njwilson23/karta/builds/76849651

**Comment by sgillies** [comment]
1.5.11 coming up in a couple minutes...

**Comment by sgillies** [comment]
Sorry for the nasty surprise in 1.5.10. I've uploaded 1.5.11.

**Comment by njwilson23** [comment]
Thanks - it's all working again for me!

**Comment by bodedra** [comment]
I face same error and resolved it with following.

[ImportError: No module named packaging.version](https://odedrabhavesh.blogspot.in/2017/02/importerror-no-module-named.html)
