### ISSUE TITLE
Installation of binary package under Windows Cpython 2 difficult

### ISSUE THREAD

**Issue by mabl** [Toblerity/Shapely#316]
It is difficult to install current shapely versions under Windows. It used to be that pypi included windows installers which included the geos library. Nowadays one is redirected to an external webpage: http://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

However there are only installers for Python 3....

**Comment by pelson** [comment]
Have you taken a look at conda, or are you trying to install Shapely into an existing Python environment?

**Comment by mabl** [comment]
I did. It is actually a Anaconda 32bit installation. However, conda search shapely did not turn up any results. Should shaply be on anaconda?

**Comment by mabl** [comment]
Okay so if i interpret https://binstar.org/anaconda/shapely correctly, anaconda contains shapely but only on linux and OSX? That's useless... never had troubles with shapely under linux and most distributions include geos.

**Comment by pelson** [comment]
Agreed. I also believe they ship a shapely which picks up the wrong GEOS if you have it installed elsewhere (e.g. with homebrew) and results in a segfault (or was it an AssertionError or some such).

Anyhow, there are shapely builds available for windows:

https://binstar.org/search?q=platform%3Awin-64+shapely

My own channel has one, as does the scitools (curated by me) and ioos (curated by @ocefpaf). At this point, if you do want to go down that route, you can install with something like:

```conda install -c ioos shapely```

Incidentally, I don't want to be that person who says "don't do it that way, use tool x instead". I'd really love to see other ways of getting Windows builds as well. If anybody wants to know one way of building Shapely for Windows, you could also take a look at https://github.com/SciTools/conda-recipes-scitools/tree/master/shapely.

**Comment by sgillies** [comment]
@mabl Shapely is a volunteer project and our Windows packaging volunteers come and go. And they've gone without leaving any working build infra (AppVeyor or whatever). If you're interested, I'm more than happy to enlist you!

**Comment by mabl** [comment]
@pelson: Thanks for jumping in. That worked flawlessly.
@sgillies: I did not want to offend. I personally use Linux a lot and love Shapely - I use it for all types of crazy things (except GIS)... Unfortunately, I'm not a windows person and I did not choose the computer (as evident by my request for Python 2 and 32bit.).

Very best,
Matthias

**Comment by sgillies** [comment]
@mabl no offense taken.

**Comment by mabl** [comment]
Okay now I know why it is so difficult:
http://stevedower.id.au/blog/building-for-python-3-5/
