### ISSUE TITLE
Flawed type comparison in __eq__()?

### ISSUE THREAD

**Issue by danielwe** [Toblerity/Shapely#317]
Perhaps this is a feature, but I was surprised to see that the type comparison part of the `__eq__()` methods for geometries uses `isinstance`. Example from `BaseGeometry`:
```python
    def __eq__(self, other):
        return (
            isinstance(other, self.__class__) and
...
```
This will evaluate to `True` if `other` is an instance of `self.__class__` *or any derived class* (https://docs.python.org/3/library/functions.html?highlight=isinstance#isinstance). Wouldn't it be more correct and to the point to simply compare the types directly?
```python
    def __eq__(self, other):
        return (
            type(other) ==  type(self) and
...
```

**Comment by jwass** [comment]
@danielwe Just curious, is there an example you're thinking of where the current implementation gives a surprising or incorrect result for `__eq__`?

**Comment by danielwe** [comment]
@jwass
```python
In [1]: from shapely import geometry

In [2]: coords = ((0, 0), (1, 0), (1, 1), (0, 0))

In [3]: ls = geometry.LineString(coords)

In [4]: lr = geometry.LinearRing(coords)

In [5]: ls.__eq__(lr)
Out[5]: True

In [6]: lr.__eq__(ls)
Out[6]: False

In [7]: ls == lr
Out[7]: False

In [8]: lr == ls
Out[8]: False
```
As shown, `__eq__` considers a `LineString` equal to a `LinearRing` with the same coordinates, but the relation is not symmetric. However, `==` comparison does not behave like this. This is explained by the following easy-to-miss line in the python 3 documentation (https://docs.python.org/3/reference/datamodel.html?highlight=__eq__#object.__eq__):
>If the operands are of different types, and right operand’s type is a direct or indirect subclass of the left operand’s type, the reflected method of the right operand has priority, otherwise the left operand’s method has priority.

That is, both `ls == lr` and `lr == ls` translate to `lr.__eq__(ls)`, since `lr.__class__` is a subclass of `ls.__class__`. As far as I can see, this behavior is not documented in python 2, but in my tests it seems to hold true for new-style objects (for old-style objects, `a == b` is always equivalent to `a.__eq__(b)`).

Thus, no one will run into problems with this as long as they use `==`. However, invoking `__eq__` directly can give funny results.

**Comment by snorfalorpagus** [comment]
Very interesting @danielwe. I had wondered why in my tests I could trigger the issue with `__eq__` but not with `==`. That quote from the documentation explains things.

**Comment by snorfalorpagus** [comment]
Could someone remind me why we are manually comparing the coordinate sequence in Python-space, rather than using the `object.equals` method?

**Comment by sgillies** [comment]
@snorfalorpagus one test is whether geometries are Python equivalent, the other is whether geometries parameterize the same (infinite) point sets.

```python
>>> LineString([(0, 0), (2, 2)]) == LineString([(0, 0), (1, 1), (2, 2)])
False
>>> LineString([(0, 0), (2, 2)]).equals(LineString([(0, 0), (1, 1), (2, 2)]))
True
```

If we collapsed these into the same predicate, we'd lose some very fine detail.

**Comment by jwass** [comment]
@danielwe Agreed, this is pretty interesting. I didn't realize the extra work Python does just to execute `x == y`. Thanks!

In any case, PR #319 should include an explicit test ensuring the LineString / LinearRing `==` comparison is False with either argument order.
