### ISSUE TITLE
Point.wkt sometimes uses exponents, unlike dumps

### ISSUE THREAD

**Issue by TomGoBravo** [Toblerity/Shapely#323]
Here's an example where my machine has different output from http://toblerity.org/shapely/manual.html

````
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import shapely
>>> from shapely.geometry import Point
>>> donut = Point(0, 0).buffer(2.0).difference(Point(0, 0).buffer(1.0))
>>> donut.centroid.wkt
'POINT (-2.26143213395106e-17 -3.945215842382012e-17)'
>>> shapely.__version__
'1.5.12'
>>> shapely.geos._lgeos.GEOSversion()
'3.4.2-CAPI-1.8.2 r3921'
````

I bumped into this because I have a script which imports GPS tracks into a SpatiaLite data base using wkt. It has worked well for years but failed after I visited the longitude 0 line next to the Royal Observatory. By default should the wkt property output the same string as dumps and to_wkt?
Also the format of wkt doesn't agree with the spec here http://docs.opengeospatial.org/is/12-063r5/12-063r5.html#13

**Comment by mwtoews** [comment]
Hi @TomGoBravo this is related to a change I did over a year ago, where I changed the output format to be trimmed. To get the same output as the manual:
```
>>> shapely.geos.WKTWriter.defaults['trim'] = False
>>> donut.centroid.wkt
'POINT (-0.0000000000000000 -0.0000000000000000)'
```
As an outstanding task (#105 for me) the documentation needs to be updated to reflect the default outputs, and to show how to modify the writer outputs.

Also, these points are almost equal:
```
>>> donut.centroid.almost_equals(Point(0, 0))
True
```
