### ISSUE TITLE
Shapely in a staticly linked environment

### ISSUE THREAD

**Issue by schwehr** [Toblerity/Shapely#328]
I've got a situation where I've got statically linked libc, libgeos etc.  Turns out that using a LoadLibrary(None) works.  I need to work up a patch.

     import ctypes
     ctypes.cdll.LoadLibrary(None).time()
     Out[3]: 1444260785

**Comment by snorfalorpagus** [comment]
How would the user indicate that they needed this? An environment variable? Or should it just fallback on this if none of the dynamic libraries work?

**Comment by schwehr** [comment]
My first thought was as a fallback.  This should also work for dynamically linked libs, but I don't know what the reliability implications are.

**Comment by snorfalorpagus** [comment]
If it's done as a fallback there needs to be a function to check if the GEOS methods are available, otherwise it will always succeed, then fall over when it tries to do anything with them.

**Comment by sgillies** [comment]
I'd love to :eyes: the patch @schwehr.
