### ISSUE TITLE
Cartopy features broken with shapely 1.5.13

### ISSUE THREAD

**Issue by ChristianP75** [Toblerity/Shapely#331]
import cartopy
import matplotlib.pyplot as plt
ax = plt.axes(projection=cartopy.crs.PlateCarree())
ax.add_feature(cartopy.feature.LAND) 
ax.set_extent([-20, 60, -40, 40])
plt.show()

works with Shapely 1.5.12 but gives 

...
TypeError: unhashable type: 'MultiPolygon'

**Comment by sgillies** [comment]
@ChristianP75 I cannot reproduce this error with the latest cartopy and shapely 1.5.13:

```python
Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
>>> import matplotlib.pyplot as plt
>>> ax = plt.axes(projection=cartopy.crs.PlateCarree())
>>> ax.add_feature(cartopy.feature.LAND)
<cartopy.mpl.feature_artist.FeatureArtist object at 0x105e5d6d0>
>>> ax.set_extent([-20, 60, -40, 40])
>>> plt.show()
>>>
>>> print cartopy.__version__
0.13.0
>>> import shapely
>>> print shapely.__version__
1.5.13
```

Which version of cartopy are you working with?

**Comment by ChristianP75** [comment]
Python 2.7.10 (default, Oct  7 2015, 09:28:07) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cartopy
>>> print cartopy.__version__
0.13.0

**Comment by QuLogic** [comment]
For cross-reference, see SciTools/cartopy#682.

**Comment by sgillies** [comment]
https://github.com/SciTools/cartopy/issues/682 is closed.
