### ISSUE TITLE
TypeError when creating multipolygon from questionable input data

### ISSUE THREAD

**Issue by jefflaing** [Toblerity/Shapely#332]
If you run the following (admittedly artificial) code:

    import shapely.geometry
    p1 = shapely.geometry.Polygon(None)
    mp = shapely.geometry.MultiPolygon([p1])

it will throw a TypeError deep in the bowels of Shapely.  

    File "...\pyide.py", line 4, in <module>
    mp = shapely.geometry.MultiPolygon([p1])
    File "...\shapely\geometry\multipolygon.py", line 57, in __init__
    self._geom, self._ndim = geos_multipolygon_from_polygons(polygons)
    File "...\shapely\geometry\multipolygon.py", line 139, in geos_multipolygon_from_polygons
    shell = obs[l][0]
    TypeError: 'Polygon' object does not support indexing

This is because of this code:

    shell = getattr(obs[l], 'exterior', None)
    if shell is None:
        shell = obs[l][0]

which assumes that "None" implies that the obs[l] does not have an 'exterior' property.  This is incorrect, for a Polygon, None is returned if the Polygon.is_empty()

    @property
    def exterior(self):
        if self.is_empty:
            return None
        elif self._exterior is None or self._exterior() is None:
            ...

I think geos_multipolygon_from_polygons() should be doing some sort of explicit type check to recognize Polygons rather than duck-typing ...

I'm currently running 1.2.17, but can't see that 1.3 has improved that particular code path at all. Note my actual applications problem is more complex than this - I'm still pursuing *how* I am coming to pass in empty polygons, but that's not Shapely's problem.

**Comment by sgillies** [comment]
Thanks for the report @jefflaing. Does the third test in PR #333's `tests/test_empty_polygons.py` look right to you?

**Comment by jefflaing** [comment]
You might want to test the case where an empty polygon is passed in amongst a bunch of other valid polygons.  ie,

    good = Point(0,0).offset(10).boundary()
    bad   = Polygon()
    assert len(MultiPolygon([good,bad])) == 1

or something like that.

**Comment by sgillies** [comment]
Done.
