### ISSUE TITLE
Documentation website is deceptively out of date

### ISSUE THREAD

**Issue by jefflaing** [Toblerity/Shapely#336]
Recently, I embarrassed myself by asserting to someone that we were not running a terribly old version of Shapely, since we were at 1.2.17 and http://toblerity.org/shapely/project.html showed that the latest version was 1.3 (check the Table of Contents).

It was only when I started browsing source that I discovered that Shapely is up to 1.5.13

Since https://github.com/Toblerity/Shapely directly links to that documentation page, it is easy to be fooled into thinking it is up to date.

**Comment by sgillies** [comment]
Agreed. I'm tracking this in #337.
