### ISSUE TITLE
Inconsistency between geometry.wkt and wkt.dumps(geometry)

### ISSUE THREAD

**Issue by rajanski** [Toblerity/Shapely#339]
Correct me if I am wrong, but I think there is still an inconsistency in the wkt/shapely-object/wkt roundtrip.

If I do not set ```WKTWriter.defaults['trim'] = False``` and then say:

```
from shapely import geometry
line = geometry.LineString([(13.51039642756912, 52.598912814414675), (13.525173800277184, 52.60620240344557)])
print line.wkt
print wkt.dumps(line)
```

I am getting two different results:

```
LINESTRING (13.51039642756912 52.59891281441467, 13.52517380027718 52.60620240344557) 
LINESTRING (13.5103964275691197 52.5989128144146747, 13.5251738002771837 52.6062024034455717)
```

A side question: Why is it that even in the wkt.dumps version of the result, the value of the original wkt coordinate has some added digits (52.598912814414675 --> 52.5989128144146747) ?

**Comment by sgillies** [comment]
@rajanski I don't understand why `setTrim(FALSE)` in GEOS removes one non-zero zero compared to the undefined trim case. I'm going to make `line.wkt` and `wkt.dumps(line)` consistent, defaulting to `trim=False` for each.

**Comment by sgillies** [comment]
@rajanski I just pushed some tests to verify that `.wkt` and `wkt.dumps()` produce the same results. I think that round tripping decimals through WKT with GEOS is just not perfect and will close this up if you don't mind.
