### ISSUE TITLE
Difference between two valid Polygons is not valid

### ISSUE THREAD

**Issue by stenci** [Toblerity/Shapely#357]
The following code creates 3 Polygons `p1`, `p2` and `p3` (using data that my app generated in previous steps) then creates `p4` as the difference between `p2` and `p3`, then `p5` as the difference between `p1` and `p4`. The first 4 objects are valid, but the last is not.

Is this a bug because an operation between valid objects should always return a valid object?
Or is my expectation about the validity wrong?

Here is the code:
```python
import shapely.geometry, shapely.validation

p1 = shapely.geometry.Polygon([
    (0.0, 0.0),
    (99.61, 0.0),
    (99.61, 50.39),
    (0.0, 50.39),
    (0.0, 0.0)])

p2 = shapely.geometry.Polygon([
    (16.43500199999831, 2.606502999999048),
    (17.860001999998303, 2.606502999999064),
    (17.860001999997845, 50.14000000000033),
    (16.43500199999785, 50.14000000000033),
    (16.43500199999785, 50.26500000000033),
    (17.860001999997845, 50.26500000000033),
    (17.86000199999783, 51.690000000000325),
    (17.98500199999783, 51.690000000000325),
    (17.985001999997845, 50.26500000000033),
    (99.3599999999999, 50.26500000000032),
    (99.3599999999999, 51.690000000000325),
    (99.4849999999999, 51.690000000000325),
    (99.4849999999999, 50.26500000000032),
    (100.9099999999999, 50.26500000000032),
    (100.9099999999999, 50.14000000000032),
    (99.4849999999999, 50.14000000000032),
    (99.4849999999999, 2.606502999999976),
    (100.9099999999999, 2.606502999999992),
    (100.9099999999999, 2.481502999999992),
    (99.4849999999999, 2.481502999999976),
    (99.4849999999999, 1.0565029999999784),
    (99.3599999999999, 1.0565029999999784),
    (99.3599999999999, 2.4815029999999747),
    (17.985001999998303, 2.481502999999065),
    (17.985001999998318, 1.0565029999990703),
    (17.860001999998318, 1.056502999999069),
    (17.860001999998303, 2.481502999999064),
    (16.43500199999831, 2.481502999999048),
    (16.43500199999831, 2.606502999999048)])

p3 = shapely.geometry.Polygon([
    (99.3599999999999, 2.606502999999975),
    (17.985001999998303, 2.6065029999990657),
    (17.98500199999785, 50.14000000000033),
    (17.985001999997845, 50.14000000000033),
    (17.985001999998303, 2.606502999999065),
    (99.3599999999999, 2.6065029999999747),
    (99.3599999999999, 2.606502999999975)])
   
p4 = p2.difference(p3)

p5 = p1.difference(p4)

for p in [p1, p2, p3, p4, p5]:
    print(shapely.validation.explain_validity(p), p.area)
```

Here is the output:
```
Valid Geometry 5019.3479
Valid Geometry 3901.7528470581587
Valid Geometry 2.2737367544323206e-13
Valid Geometry 3901.7528470581583
Ring Self-intersection[17.9850019999983 2.60650299999907] 1118.2450529418406
```

**Comment by sgillies** [comment]
Sorry for the delay, @stenci. No, operations between valid geometries can produce invalid geometries. In your case, it looks like `p5` can be straightened out using the `buffer(0.0)` trick:

![untitled](https://cloud.githubusercontent.com/assets/33697/12806221/3504e77a-cac1-11e5-83c4-79bac1bf37f1.png)

Your `p2` geometry has some interestingly shaped corners. I think these may be the cause of the self-intersections when differences to nearly-intersecting geometries are made. You might want to save `p5.svg()` (before buffering) out to a file and look at it closely in Inkscape or another SVG editor to see what's going on.

**Comment by stenci** [comment]
I don't understand why this has been closed. If the difference between two valid shapes should return one valid shape, then this is an error and should be fixed. Am I missing something?

This is my code now. It works, but it smells more like a workaround than like a fix: 

```python
self._usable_area = self._usable_area.difference(panel.shape_good_and_tool)
if not self._usable_area.is_valid:
    # something is wrong, see https://github.com/Toblerity/Shapely/issues/357
    cherrypy.log('Sheet.usable_area: not valid polygon has been fixed')
    self._usable_area = self._usable_area.buffer(0)
    assert self._usable_area.is_valid
```

The assertion never fails, which means the workaround it's working. I see about 1 failure logged every 3-400 successful differences, that is about 50-100 failures a day.

I can live with that for now, but I'm afraid that sooner or later that ```buffer(0)``` on that broken geometry will lose a loop and the program will return the wrong results.

Doesn't this error need to be fixed?

**Comment by sgillies** [comment]
@stenci Sorry, I'll try to be more clear. The GEOS library has a number of open issues with differencing, including

https://trac.osgeo.org/geos/ticket/523
https://trac.osgeo.org/geos/ticket/614
https://trac.osgeo.org/geos/ticket/737

and I think you're hitting one of these. When I said

> operations between valid geometries can produce invalid geometries

what I meant was that I'm not sure that GEOS guarantees that operations between valid geometries will produce valid geometries. And I'm not sure even sure that it can due to issues with floating point precision. If we had a fixed precision model, GEOS might be able to guarantee valid results. Shapely doesn't support the GEOS fixed precision models (we have a ticket in here, but it's a big lift and I'm not ready to start it yet), but a GEOS C program or JTS program (in Java) might reveal more about this bug.

If you don't mind, I'm going to leave this issue closed because there's no action to be taken in this project, but label it so that it isn't swept under the rug.

**Comment by stenci** [comment]
I understand now, thanks for the clarification.

I will keep the `is_valid` check and the `buffer(0)` workaround, and cross my fingers that the cnc machine will not cut some panels in half :)

Thanks for your help. Shapely is a great tool and is making my life much easier.
