### ISSUE TITLE
GeometryCollection import code missing

### ISSUE THREAD

**Issue by ewenger** [Toblerity/Shapely#358]
Would it be acceptable for a future release if I wrote code to import GeometryCollections from GeoJSON?  I would model it after the MultiPolygon support that already exists.

**Comment by sgillies** [comment]
Sure, if you need this, let's do it.

**Comment by Skippern** [comment]
I am actually looking for a way to create Polygons from a series of LineStrings, though if I could create the Polygon directly from a JSON with an OpenStreetMap relation, that would be perfect.

**Comment by sgillies** [comment]
Closing for lack of action and direction.
