### ISSUE TITLE
Add minimim_rotated_rectangle to manual

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Shapely#364]
Need an entry in the manual for #361, `Geometry.minimum_rotated_rectangle`.

@georgeouzou Do you want to give this a go? If not I can find some time for it.

https://github.com/Toblerity/Shapely/blob/master/docs/manual.rst

**Comment by georgeouzou** [comment]
Of course, i will get to it.

**Comment by georgeouzou** [comment]
Added :)

**Comment by snorfalorpagus** [comment]
Closed by #369
