### ISSUE TITLE
Shapely wheel link path for homebrew libgeos on OS X

### ISSUE THREAD

**Issue by yesimon** [Toblerity/Shapely#379]
I tried installing `pip3 install shapely` using the wheel for OS X 10.11 and found that the shared libraries were linked to a specified libgeos:
```
yesimon@oxygen /u/l/l/p/s/s/speedups> otool -L _speedups.cpython-35m-darwin.so 
_speedups.cpython-35m-darwin.so:
        @loader_path/../.dylibs/libgeos-3.4.2.dylib (compatibility version 0.0.0, current version 0.0.0)
        @loader_path/../.dylibs/libgeos_c.1.dylib (compatibility version 10.0.0, current version 10.2.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

This results in the same error as SciTools/cartopy#738 when actually running.

I was able to get it to work by doing `pip3 install --no-use-wheel shapely`, which results in a different link:
```
yesimon@oxygen /u/l/l/p/s/s/speedups> otool -L _speedups.cpython-35m-darwin.so 
_speedups.cpython-35m-darwin.so:
        /usr/local/opt/geos/lib/libgeos_c.1.dylib (compatibility version 11.0.0, current version 11.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Perhaps adding the `/usr/local/opt/geos` is a reasonable during the link or maybe this should be included as a formula in Homebrew/homebrew-python.

**Comment by sgillies** [comment]
@yesimon This is a packaging problem that will be fixed in 1.5.16 (#387).

**Comment by sgillies** [comment]
@yesimon could you do me a big favor and test the new wheel I've just uploaded to Dropbox?

https://www.dropbox.com/s/jpvvxwc69xgqpzq/Shapely-1.5.15-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl?dl=0

I've compiled the _vectorized and _speedups modules more carefully, linking only libgeos_c. It's looking good on my computer but I don't have a setup that will let me reproduce your problem with cartopy.

**Comment by yesimon** [comment]
@sgillies It seems to work installing the latest version 1.5.16 from pypi. Thanks!

**Comment by sgillies** [comment]
🎉 Thanks for your patience and thanks for following up!
