### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by Fred-Barclay** [Toblerity/Shapely#380]
Hey mates! I've been using Shapely for some code (and very good job, BTW--you saved me a lot of time!) that I've released [here on github:] (https://github.com/Fred-Barclay/PolyDist). I don't redistribute Shapely in source or binary form, but it is integrated into the code. I'm considering licensing my program under the following terms: https://github.com/Fred-Barclay/PolyDist/wiki/LICENSING

I realised shortly after writing this license that it might not correspond to yours, so I want to make sure there are no conflicts. Reading the terms of yours, it says:
`Redistribution and use in source and binary forms...are permitted provided that the following          conditions are met:`
followed by a list of conditions. 
Since I use shapely for source code, even though I don't redistribute shapely, is my understanding correct that I would need to integrate your license with mine? If so, do you have any suggestions?

Thanks!
Fred

**Comment by sgillies** [comment]
@Fred-Barclay if you include Shapely in your Python package, like I include `polyline` my Mapbox Python SDK package https://github.com/mapbox/mapbox-sdk-py/tree/master/mapbox/polyline, then you need to keep the license with the code. See how I keep polyline's license?

If you merely require Shapely and count on users installing it with pip, you don't have to worry about the license: software like pip that downloads and installs Shapely will do the right thing.

**Comment by Fred-Barclay** [comment]
I only require it and count on users installing it. :)
Thanks!
