### ISSUE TITLE
Latex/Mathjax broken in docs

### ISSUE THREAD

**Issue by cderwin** [Toblerity/Shapely#381]
https://www.dropbox.com/s/aiinpxtxl83bf4t/Screenshot%202016-04-20%2011.50.15.png?dl=0
Here's a screenshot of the current docs, and as you can see the mathjax is not rendering properly.  Not a huge deal, but thought it'd be a good idea to let y'all know.

By the way, this is under the `shapely.affinity.rotate(geom, angle, origin='center', use_radians=False)` method.

**Comment by snorfalorpagus** [comment]
Thanks for the report. This is working in the current version of the documentation. Unfortunately, the documentation build on toblerity.org is out of date. See #337.
