### ISSUE TITLE
Possible memory leak in shapely+deepcopy starting in version 1.5.11

### ISSUE THREAD

**Issue by cedricjeanty** [Toblerity/Shapely#384]
I've encountered what I think may be a memory leak when using shapely objects and deepcopy. Here is a small test script:

```
import copy
from shapely.geometry import Point
for idx in range(25):
    pt = Point()
    pts = [copy.deepcopy(pt) for _ in range(10000)]
```

When using version 1.5.0 thru 1.5.9, the memory use of my python process stabilizes at about 30 Mb, but when I test version 1.5.11 (I was not able to run 1.5.10) and above, the memory use of the process continually increases to over 50Mb.

I hope this helps!
Thanks.

**Comment by snorfalorpagus** [comment]
The difference seems to be that `Point._is_empty` is never set to `False` when creating the geometry via the `__setstate__` method (which is what deepcopy uses, and also pickle).

```
>>> from shapely.geometry import Point
>>> import pickle
>>> p1 = Point(1,2)
>>> data = pickle.dumps(p1)
>>> p2 = pickle.loads(data)
>>> p2.wkt
'POINT (1 2)'
>>> p1._is_empty
False
>>> p2._is_empty
True
```

This means that when the `__del__` method is called on the Shapely geometry `GEOSDestroy` isn't called on the underlying GEOS geometry. https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/base.py#L212-L221

I haven't looked at why this is only a problem from 1.5.11(10?) onwards. The fix seems simple enough (set `self._is_empty = False` in `__setstate__`). However, it would be good to understand the issue better first.

**Comment by snorfalorpagus** [comment]
Here's the relevant commit: https://github.com/Toblerity/Shapely/commit/4775c377977059e9f8b2532d2d7ff965e075bd3e

@thedavecollins Would you like to weigh in on this?
