### ISSUE TITLE
Geometry `equals`, `almost_equals`, `equals_exact` ignore Z coordinate.

### ISSUE THREAD

**Issue by war1025** [Toblerity/Shapely#388]
The equality functions appear to ignore Z coordinates when they do their calculations.

I couldn't find it documented anywhere that this was expected behavior, but maybe it is...

```
>>> Point(1,2,3).almost_equals(Point(1, 2.01, 3))
False
>>> Point(1,2,3).almost_equals(Point(1, 2, 223432343))
True
```

**Comment by snorfalorpagus** [comment]
To clarify @war1025, this is an expected behaviour (inherited from GEOS). Most of the geoprocessing operations in GEOS are 2D, despite having support for 3D structures. It needs documenting.

**Comment by sgillies** [comment]
It's documented at http://toblerity.org/shapely/manual.html#geometric-objects

> A third z coordinate value may be used when constructing instances, but has no effect on geometric analysis. All operations are performed in the x-y plane.

I'll reiterate in a few places, base geometry docstring for one.
