### ISSUE TITLE
How to cite Shapely?

### ISSUE THREAD

**Issue by joelostblom** [Toblerity/Shapely#389]
Hi,
Shapely has been very helpful to me in one of my projects and I would like to cite it in the corresponding paper. Is there any publication or DOI for Shapely similar to what is available for the [SciPy packages](https://scipy.org/citing.html)? If not, would you consider making one by [linking this GitHub repository to Zenodo](https://guides.github.com/activities/citable-code/)?

**Comment by sgillies** [comment]
I added a BibTex entry modeled after the one created for the Rasterio project. See the new `CITATION.txt` file.

Signing up with Zenodo wasn't hard. When Shapely has a new release, there should be a DOI for it.

**Comment by joelostblom** [comment]
Great, thank you!
