### ISSUE TITLE
Port polylabel algorithm

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#395]
I'd love to see the algorithm of https://github.com/mapbox/polylabel in Shapely.

**Comment by bixb0012** [comment]
Ostensibly, given the name, the purpose of porting over [polylabel](https://github.com/mapbox/polylabel) would be for finding an interior point to place labels.  I am not intimately familiar with all of the GEOS/JTS algorithms, but doesn't the existing `representative_point()` suffice?  Using the first test case from [polylabel](https://github.com/mapbox/polylabel) , the representative point from GEOS is fairly close to the label point from polylabel.

**Comment by snorfalorpagus** [comment]
There is quite a nice description of how the algorithm used by `representative_point` works here:

http://gis.stackexchange.com/a/76563

The only guarantee of the "point on surface" function is that the point it produces will fall inside the polygon. This is in contrast to the centroid, which for certain polygons (e.g. a "C" shape) will fall outside. However, it is by no means the most visually appealing point for labelling.

The polylabel algorithm approximates the pole of inaccessibility, which is a useful function in general as I don't think GEOS provides this natively.

**Comment by bixb0012** [comment]
Thanks for the link.

I agree that JTS/GEOS doesn't have a single function for calculating the pole of inaccessibility, but I have seen it done through a series of steps using existing functionality.  That said, I can't recall the specifics at the moment, but it involved densify and Voronoi diagrams.

Having a pole of inaccessibility function in Shapely would be handy, I can think of a couple uses, but I don't know if using such a function would provide significantly better label locations than `representative_point`.

**Comment by allanadair** [comment]
Is anyone working on this? If not, I would be interested in giving it a try.

**Comment by bixb0012** [comment]
@allanadair, I have/had the interest, I just can't quite seem to find the time in the next few weeks.  I say go for it.

**Comment by sgillies** [comment]
@allanadair before the 1.6 release we'll need to figure out how to use the tolerance value to get the best label points. See in the image below the difference between using the default (1.0) and a value of 20.0 where the polygon is roughly 20x20 units in size.

![polylabel](https://cloud.githubusercontent.com/assets/33697/17696623/e6f642c6-63af-11e6-8cdc-c57d2d818a1a.png)

**Comment by sgillies** [comment]
This is great, and so are Shapely's SVG representations in Jupyter notebooks.

![polylabel](https://cloud.githubusercontent.com/assets/33697/17696895/c0de0aa4-63b1-11e6-9db5-c8eb3f81d518.png)
