### ISSUE TITLE
Creating empty polygon from empty list fails

### ISSUE THREAD

**Issue by david-zwicker** [Toblerity/Shapely#397]
Empty polygons can be created using

```
polygon = geometry.Polygon()
polygon.is_empty
# True
```

However, creating an empty polygon from an empty list of vertices, `polygon = geometry.Polygon([])`, throws the following error

>   File "<stdin>", line 1, in <module>
>   File "[..]/python2.7/site-packages/shapely/geometry/polygon.py", line 229, in __init__
>     self._geom, self._ndim = geos_polygon_from_py(shell, holes)
>   File "[..]/python2.7/site-packages/shapely/geometry/polygon.py", line 508, in geos_polygon_from_py
>     geos_shell, ndim = geos_linearring_from_py(shell)
>   File "[..]/python2.7/site-packages/shapely/geometry/polygon.py", line 450, in geos_linearring_from_py
>     n = len(ob[0])
> IndexError: list index out of range

It would be nice if this would also just return an empty polygon.

I use shapely version 1.5.16 in case this matters.

**Comment by snorfalorpagus** [comment]
`LineString` currently behaves in the same was as `Polygon`, but gives a more useful exception:

```
>>> from shapely.geometry import *
>>> LineString()
<shapely.geometry.linestring.LineString object at 0x1012fa240>
>>> LineString([])
Traceback (most recent call last):
  File "/Users/snorf/miniconda3/lib/python3.5/site-packages/shapely/geometry/linestring.py", line 200, in geos_linestring_from_py
    array = ob.__array_interface__
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/snorf/miniconda3/lib/python3.5/site-packages/shapely/geometry/linestring.py", line 49, in __init__
    self._set_coords(coordinates)
  File "/Users/snorf/miniconda3/lib/python3.5/site-packages/shapely/geometry/linestring.py", line 94, in _set_coords
    self._geom, self._ndim = geos_linestring_from_py(coordinates)
  File "/Users/snorf/miniconda3/lib/python3.5/site-packages/shapely/geometry/linestring.py", line 258, in geos_linestring_from_py
    "LineStrings must have at least 2 coordinate tuples")
ValueError: LineStrings must have at least 2 coordinate tuples
```

I think we should be consistent between classes, although I'm not sure what the correct behaviour should be: do we return an empty geometry, or raise an exception?

The current behaviour is as follows

- Polygon: exception
- LineString: helpful exception
- LinearRing: exception
- MultiPolygon: empty geometry
- MultiLineString: empty geometry

**Comment by sgillies** [comment]
@snorfalorpagus thanks for sorting out the current situation. I'm 👍 on accepting either `None` (the default) or `[]` in these constructors and returning an empty geometry in both cases.

**Comment by david-zwicker** [comment]
I think it would be most convenient if all classes accept an empty list of vertices. I don't see in what case raising an exception for any of them would be more helpful.
