### ISSUE TITLE
Support for conda library path

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Shapely#401]
When building Shapely using the Anaconda Python distribution a patch is required to correct the path of the GEOS shared library:

https://github.com/conda-forge/shapely-feedstock/blob/master/recipe/geos_c.patch

@sgillies Do you have any opposition to adding the paths into Shapely itself, so that the patch isn't required? We already do this for Kyng Chaos and macports.

This is related to #343/#400.

**Comment by snorfalorpagus** [comment]
New branch is here: https://github.com/snorfalorpagus/Shapely/tree/anaconda

Tested on:

- [x] OS X
- [ ] Linux
- [ ] Windows

**Comment by sgillies** [comment]
Closed via #413
