### ISSUE TITLE
Code duplication between buildcfg.py and geos.py

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Shapely#405]
There is a significant amount of code duplication betwen `_buildcfg.py` and `geos.py`. Can we move the functions that load the shared library into it's own module, shared by both?
#327, #400, #401

**Comment by sgillies** [comment]
I'm going to close this and mark "wontfix". These problems are going away or will be traded for other problems (that's how software works) in 2.0 and 1.8 is only about warning of upcoming changes.
