### ISSUE TITLE
GEOSGeom_createEmptyCollection

### ISSUE THREAD

**Issue by GuidoDavoli** [Toblerity/Shapely#406]
Hi everybody, 
I've installed Shapely and libgeos_c on my Ubuntu 12.04 laptop. I use python 3.5.1. 
If I run the simple code

`from shapely.geometry import Polygon`
`polygon = Polygon([(0, 0), (1, 1), (1, 0)])`

I obtain the error:

```
 "/my_path/anaconda3/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))


AttributeError: /usr/lib/libgeos_c.so.1: undefined symbol: GEOSGeom_createEmptyCollection
```
Any ideas on how to remove this error?
Thank you in advance.

**Comment by snorfalorpagus** [comment]
Hi @GuidoDavoli. How did you install Shapely and GEOS? Which versions of both?

**Comment by sgillies** [comment]
GEOSGeom_createEmptyCollection was added to GEOS in version 3.3.0, May 2011. You may need to revert to Shapely 1.4.x, Shapely 1.5.x requires GEOS >= 3.3.

**Comment by snorfalorpagus** [comment]
This is probably the issue. Ubuntu 12.04 packages GEOS 3.2.2 (http://packages.ubuntu.com/precise/libgeos-3.2.2). I see you're using anaconda - you could use a more recent version of GEOS available from conda-forge (https://github.com/conda-forge/geos-feedstock).

Do we need to catch this and call a more graceful exception?

**Comment by GuidoDavoli** [comment]
Thank you very much for your advices. I've installed GEOS as explained in [https://github.com/conda-forge/geos-feedstock](url) (thank you @snorfalorpagus ) and the error is vanished.
