### ISSUE TITLE
Memory leak when creating intersections/unions/differences

### ISSUE THREAD

**Issue by allthedata** [Toblerity/Shapely#408]
I'm running Shapely 1.5.16. The memory leak in issue #384 was fixed in this release, but I think I found another one. The script below causes the memory usage of the process to go up to 340MB.

```python
from shapely.geometry import Polygon, LineString
a = Polygon([(0, 0), (0, 1), (1, 1), (1, 0)])
b = LineString([(0, 0), (1, 1)])
for _ in range(1000000):
    c = a.intersection(b)
```

The same thing happens for the `union` and `difference` methods. Putting `del c` in the loop or running `gc.collect()` doesn't help either.

**Comment by snorfalorpagus** [comment]
I'm writing this from my phone, so can't check and say for sure, but this looks like a manifestation of the same problem. I think the geometry class needs `_is_empty = False` in `geom_factory`.

**Comment by sgillies** [comment]
@allthedata thanks for the report and @snorfalorpagus thanks for the diagnosis. I can confirm that your suggested fix lets the script run with a max memory of 15.8 MB. I'm going to make the fix in our maint-1.5 branch and make a 1.5.17 release.

**Comment by allthedata** [comment]
Hmm, I edited `base.py` with the fix and I'm still getting the same memory leak behavior. Maybe the platform matters? I'm running on Windows with Anaconda and I got the shapely wheel from http://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely.

**Comment by snorfalorpagus** [comment]
I've just tried this (Python 3.4.4, Shapely 1.5.16 from conda-forge) and I can't reproduce the memory leak. At the point I suggested the fix, `_is_empty` is already `False`.

**Comment by allthedata** [comment]
You're right, I uninstalled the shapely wheel I mentioned above and installed from conda-forge and I don't get the memory leak anymore, and `_is_empty` is already `False` without the fix. Thanks!

**Comment by cgohlke** [comment]
FWIW, I can only reproduce the leak with Python 3.5, not 2.7 or 3.4.

**Comment by cgohlke** [comment]
Rebuilding `geos_c.dll` with the latest Visual Studio 2015.3+patches fixed this issue.
