### ISSUE TITLE
geos module modifies logger configuration

### ISSUE THREAD

**Issue by mdickinson** [Toblerity/Shapely#415]
The `shapely.geos` module currently modifies logger configurations: https://github.com/Toblerity/Shapely/blob/master/shapely/geos.py#L23

We have an application that uses Shapely in one of its components; this logger modification results in spurious debug messages to the console when running the application. As a general rule, logging best practices are that libraries shouldn't modify logger configurations, but restrict themselves to creating loggers and issuing log messages; it's up to the application to decide how to handle those various log messages.

Would it be possible to remove this modification?

**Comment by rkern** [comment]
One possibility is to use the `warnings` module for these messages instead. For the `LOG.debug()` messages, you can use a custom `ShapelyDebugWarning` and ignore it by default. For the `LOG.warn()` messages, just use a plain `warnings.warn()`.

**Comment by sgillies** [comment]
Resolved by #420.

**Comment by mdickinson** [comment]
Many thanks!
