### ISSUE TITLE
exception in geos.py -- name 'super' not defined

### ISSUE THREAD

**Issue by pleasantone** [Toblerity/Shapely#421]
Found this in 1.5.17, verified the code is the same in master, I'm running python 3.5.2

Line 816 has a super on it in init... being a python 3 programmer, I'm a little unsure of the syntax for super in python 2...

It looks like we should be calling super(LGEOS340, self).__init(dll) and finding it, not entirely sure why this is happening

```
Exception ignored in: <bound method LGEOSBase.__del__ of <shapely.geos.LGEOS340 object at 0x7f147cf893a8>>
Traceback (most recent call last):
 File "/srv/prod/lib/python3.5/site-packages/shapely/geos.py", line 565, in __del__
 File "/srv/prod/lib/python3.5/site-packages/shapely/geos.py", line 816, in __init__
NameError: name 'super' is not defined
```

**Comment by snorfalorpagus** [comment]
This is very strange. I don't see why the `__init__` function would be called in `__del__`.

Relevant lines in master are:
https://github.com/Toblerity/Shapely/blob/18ae7998c24d02b91f4fd62971cf4e69c8b340a2/shapely/geos.py#L587
https://github.com/Toblerity/Shapely/blob/18ae7998c24d02b91f4fd62971cf4e69c8b340a2/shapely/geos.py#L846

Do you have a code snippet than triggers the problem?

What operating system are you using? What version of GEOS? How did you install Python / GEOS / Shapely?

**Comment by sgillies** [comment]
@pleasantone I'm developing with Python 3.5.2 and we're testing on it https://travis-ci.org/Toblerity/Shapely/jobs/165579426#L241. We've had two issues reported in the past that may be related: #106 and #264. But we haven't received any programs that will reproduce the errors, which seem to occur only in production (the worst kind of error!). In your case, it looks like the object that defines the interface to GEOS is being cleaned up after some of Python's builtins, like `super`, are already torn down. Some code that can produce this error would be super helpful.

**Comment by sgillies** [comment]
Closed due to inaction.
