### ISSUE TITLE
parallel_offset returns empty linestring in some cases

### ISSUE THREAD

**Issue by mleventi** [Toblerity/Shapely#424]
Here is one such example...

```
LineString([(321291.8,4310330.7),(321308.1,4310326.9),(321309.3,4310323.4),(321309.3,4310319.6),(321289.4,4310314.7)]).parallel_offset(12.8, 'right', join_style=2)
```

This occurs with shapely 1.6.1a and 1.5.17 with libgeos3.5.0 on MacOS

So far i have only seen cases that indicate this problem exists for 'right' transforms.

**Comment by mwtoews** [comment]
I think this is the expected result for this example. Here's another example, where the buffer folds into itself after it tips over a certain buffer size:
```python
from shapely import wkt
g = wkt.loads('LINESTRING (10 0, 0 5, 10 10)')
print(g.parallel_offset(5, 'right', join_style=2))
# LINESTRING (12.23606797749979 5.52786404500042, 11.18033988749895 5, 12.23606797749979 4.47213595499958)
print(g.parallel_offset(6, 'right', join_style=2))
# LINESTRING EMPTY
```

**Comment by sgillies** [comment]
Yes, expected as far as I can tell.

**Comment by jGaboardi** [comment]
Although this behavior is clearly expected, might it be helpful if some warning was thrown when `LINESTRING EMPTY` geometries are produced? Due to user oversight (mine in particular), it is very easy to miss the creation of `LINESTRING EMPTY` geometries in certain workflows, which later, when attempting to perform operations such as `interpolate`,  result in the dreaded `Segmentation Fault: 11`/dead kernels.

**Comment by snorfalorpagus** [comment]
I don't think the creation of an empty geometry should raise any kind of warning. It's the correct response for operations which result in an empty set. For example, the intersection of two geometries who do not intersect.

With that aside, it should _never_ be possible to cause a segmentation fault from anything you do with Shapely geometries (provided you're not deliberately messing with the internals). It sounds like you may have found a bug @jGaboardi. Please can you create a new issue, with some details on how to reproduce this issue?

**Comment by jGaboardi** [comment]
@snorfalorpagus sure thing. I will try to get a MWE up ASAP.
