### ISSUE TITLE
Support for Python 2.6

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Shapely#432]
I noticed in the Travis logs the following message:

> DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6

It looks like Python 2.6 is no longer supported. https://www.python.org/download/releases/2.6.9/

Should we drop (explicit) support for this in the next release? I think this mostly just involves dropping 2.6 from the CI. It might still work, but it's not something we should put any effort into maintaining.

**Comment by sgillies** [comment]
Let's do remove 2.6 from the build matrix. 3.3 is coming up on the end of its life, too, https://docs.python.org/devguide/#status-of-python-branches.
