### ISSUE TITLE
Speeding up Rotate and Translate

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [Toblerity/Shapely#439]
I'm calling rotate and then translate directly after on a polygon and I'm wondering if there is a way to increase the speed of this.
Is there a way to combine the the two operations so that the rotation and translation can be performed at the some time?

**Comment by snorfalorpagus** [comment]
The `affine_transform` function has a cython implementation. If you're not already you should make sure you have shapely installed with the speedups submodule. You can check this with:

```
>>> import shapely.speedups
>>> shapely.speedups.available
True
```

Both the rotate and translate methods use this function, so it's being called twice (which is inefficient). What is needed is to combine the transformation matrix for both operations, which can be done by multiplying the matrices together.

It's not currently possible to access the matrices created by Shapely. I propose that we could separate the code that generates the matrices from the actual call to affine_transform. A function could then be created to multiply the matrices to create aggregated transformations. It would look something like this:

```
def rotate(geom, ...):
    matrix = create_rotate_matrix(...)
    return affine_transform(geom, matrix)

def create_rotate_matrix(angle, origin, use_radians=False):
    ...
    return matrix

def multiply(*args):
    for matrix in args: ...
    return aggregated_matrix
```

All the code you need is in `shapely/affinity.py` if you want to give this a go. The module is very well commented. A PR would be welcome.

https://github.com/Toblerity/Shapely/blob/7b09eb777f688d9c404b0f20b80864c8e51c446e/shapely/affinity.py

**Comment by BebeSparkelSparkel** [comment]
So I've come up with a solution that I think will work check out pull request [https://github.com/Toblerity/Shapely/pull/440](url)

I'm getting a lot of integration errors that I could use some help with though.

**Comment by BebeSparkelSparkel** [comment]
Ok I've fixed the integration errors
