### ISSUE TITLE
Speedup without numpy

### ISSUE THREAD

**Issue by dethi** [Toblerity/Shapely#444]
With shapely==1.6a2, it was possible to enable speedup without numpy. The behaviour changed in 1.6b1 and 1.6b2. Now the speedups is unavailable:

```python
>>> from shapely import speedups
>>> speedups.import_error_msg
ImportError('No module named numpy',)
```

I think it comes from https://github.com/Toblerity/Shapely/commit/7ad7b435dae257eace812f496e726bc17110feb3

**Comment by sgillies** [comment]
Thanks for the report and your patience @dethi!
