### ISSUE TITLE
Polygon.buffer results in self-intersecting polygon

### ISSUE THREAD

**Issue by aleaf** [Toblerity/Shapely#445]
why does buffering of Polygons (especially geographic boundaries with acute angles) now often result in invalid polygons that self intersect? For example:
```python
from shapely.geometry import Polygon 
crds = [[  45.,  571.],
       [ 144.,  669.],
       [ 225.,  596.],
       [ 234.,  594.],
       [ 552.,  576.],
       [ 567.,  807.],
       [ 960.,  789.],
       [ 939.,  407.],
       [ 419.,   49.],
       [ 314.,   56.],
       [ 296.,  102.],
       [ 252.,  240.],
       [ 243.,  263.],
       [ 230.,  283.],
       [ 196.,  329.],
       [ 166.,  376.],
       [ 138.,  413.],
       [ 109.,  445.],
       [  73.,  496.],
       [  54.,  542.],
       [  45.,  571.]]
Polygon(crds).buffer(1000)
```
results in
![image](https://cloud.githubusercontent.com/assets/3923387/21369011/84253714-c6ca-11e6-831f-0c685724d165.png)

**Comment by mwtoews** [comment]
I've tried a few different versions of Shapely on Linux and Windows, and I can't see this result. I only get a valid buffer which looks correct. Which version of Shapely/GEOS is this with?

**Comment by aleaf** [comment]
I am using OSX; with Python 3.5.2, shapely 1.5.17 and shapely.geos 3.4.2. The problem only appears if I try to import fiona (1.7.1) first. But if I import cartopy (0.14.2), fiona, and then shapely (in that order), the buffer is valid again. On Windows, with all of the same versions, the buffer is valid in all cases.

I have had similar issues with Cartopy (related to when it is imported relative to other packages). On my OSX system, fiona and shapely are installed from pip/PyPI. I have also tried installing them from conda-forge but have not had great luck with that.

Is there a best way to install these packages together on OSX without dependency conflicts? On the Windows side, I have had good luck with installing the whole suite from the [unofficial binaries](http://www.lfd.uci.edu/~gohlke/pythonlibs/) site.

**Comment by sgillies** [comment]
@aleaf I fear that the GEOS shared libs in the Shapely 1.5.17 and Fiona 1.7.1 wheels are incompatible. Would you be willing to try the following combination to get wheels that use the same shared lib?

`pip install --force-reinstall shapely==1.6a3 fiona==1.7.1`

**Comment by aleaf** [comment]
@sgillies I tried the above command but pip couldn't find `shapely==1.6a3`. I also tried `pip install --force-reinstall shapely==1.6a2 fiona==1.7.1` but got the same invalid buffer result. I do have homebrew. Would it make more sense install geos and gdal via homebrew and then install shapely, fiona, etc. without the wheels? For now I'm just looking for a reliable solution to keep an up to date suite of these packages working. Thanks

**Comment by sgillies** [comment]
@aleaf yes, building Shapely and Fiona against a single shared GEOS lib on your system is a good way to go. Once you've installed GEOS and GDAL with Homebrew and ensured that the geos-config and gdal-config progragms are on your executable path, do `pip install shapely fiona --no-binary shapely,fiona` to specify that binary wheels are to be avoided.

**Comment by aleaf** [comment]
I tried the above, which installed geos 3.5.1 and gdal 1.11.5 but now am encountering this problem: 
```
$ python -c 'from shapely.geometry import Point; import fiona'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/aleaf/anaconda/envs/shapely/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/aleaf/anaconda/envs/shapely/lib/python3.5/site-packages/fiona/collection.py", line 8, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/aleaf/anaconda/envs/shapely/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Symbol not found: _GEOSArea
  Referenced from: /usr/local/opt/libspatialite/lib/libspatialite.7.dylib
  Expected in: flat namespace
 in /usr/local/opt/libspatialite/lib/libspatialite.7.dylib
```

**Comment by sgillies** [comment]
@aleaf that looks like a conflict between Anaconda and Homebrew GDAL installations. If you're going to use a conda environment as you are above, you have to make sure that the Homebrew libs aren't on your library path. Are you trying to pip install Shapely and Fiona into a conda environment? I don't think there's any chance of that working. If you use conda, you've got to rely on it 100% for system libraries like GDAL and GEOS, and change your library path.

**Comment by sgillies** [comment]
I can't reproduce this one here with Shapely 1.6b2 and GEOS 3.4.2. I get a convex, green polygon in my notebook. Will close. I'm sorry about the DLL issue. I've suggested a fix that the cartopy project could make so that its incompatibilities with Shapely are eliminated: https://github.com/SciTools/cartopy/issues/805.

**Comment by aleaf** [comment]
@sgillies, thanks for all of your help, and the great software. I use it almost daily. Looks like there are a few different routes for moving forward. Binary wheels are especially useful to us at the USGS, for including the GIS-related packages in our internal python course and also sharing code with less experienced users who want to minimize "DLL Hell."
