### ISSUE TITLE
Unable to suppress extra info message with geometry.Polygon.is_valid

### ISSUE THREAD

**Issue by benlaken** [Toblerity/Shapely#447]
When calling the `geometry.Polygon.is_valid` test, if the test fails, in addition to the boolean a message `Self-intersection at or near point <x>, <y>` is printed. Is there a means to suppress this info, leaving only the boolean?
(Apologies if this is more suited to the discussion list, but I am unable to access the discussion site listed on Shapley's website.)

**Comment by benlaken** [comment]
The issue can be replicated with the following:

```python
import shapely.geometry as geometry
cs = [(11, 3), (20, 12), (13, 7), (18, 4)]
poly = geometry.Polygon(cs)
poly.is_valid

>>> Self-intersection at or near point 14.25 6.25
>>>False
```
How can the `Self-intersection` message be suppressed?

**Comment by sgillies** [comment]
@benlaken it looks like you have a debug build of GEOS and code like this is writing to stderr: https://github.com/libgeos/libgeos/blob/99f187fb3fd777440acb51fff371d20a80e6e1ed/src/noding/SegmentNode.cpp#L90. There's no recourse other than to rebuild GEOS with debugging disabled.

**Comment by ismael-elatifi** [comment]
Better to set only the shapely logger, like this :
`logging.getLogger('shapely.geos').setLevel(logging.CRITICAL)`
It removes all Shapely errors/warnings messages but I was forced to do it because the message I wanted to ignore and get ride of is logged as an error.
