### ISSUE TITLE
Null geometries causing exception in split() function.

### ISSUE THREAD

**Issue by pratheekrebala** [Toblerity/Shapely#453]
Hi Sean,

I was testing out the new split() functionality introduced in 1.6a1 to split a `MultiLineString` using `MultiPoint` as a splitter. I constantly ran into the `Null geometry supports no operations` error which seemed to originate from the call to `_split_line_with_point` in [L415 in ops.py](https://github.com/Toblerity/Shapely/blob/master/shapely/ops.py#L415) where an empty chunk was being passed into the `_split_line_with_point` function. I added a `if chunk.is_empty is False` condition right before this call which seemed to resolve the issue for me.

I'm not sure if this is the correct way to address this issue but wanted to bring this to your attention.

Thank you for all your work on this project!

Best,
Pratheek

**Comment by sgillies** [comment]
Thanks for report @pratheekrebala! Sounds like a reasonable to me. Any chance you could provide a MultiLineString that results in empty chunks for me to use in a test?

**Comment by pratheekrebala** [comment]
Cleveland County in North Carolina is one such instance - I've attached a GeoJSON here for that specific county. Hope this helps!

[NC_Cleveland_County_test_geojson.txt](https://github.com/Toblerity/Shapely/files/696579/NC_Cleveland_County_test_geojson.txt)

**Comment by sgillies** [comment]
@pratheekrebala I'll need a multipoint to go with it, one that leads to the error.
