### ISSUE TITLE
Accumulation via cascaded_union lead to Assertion error

### ISSUE THREAD

**Issue by davidbgk** [Toblerity/Shapely#455]
Hello,

First, thanks for the lib :)

I want [to do that](https://github.com/davidbgk/geozones/blob/master/geo.py#L170) which used to work with prior versions (about a year ago with version 1.5.7):

```python
geom = cascaded_union(geoms)
```

Since #288, I use [a workaround](https://github.com/davidbgk/geozones/blob/2e223b84c4607ab0834e082f044b055171e57218/geo.py#L210-L217) to do that by hand:

```python
accumulated_geom = geoms[0]
for geom in geoms[1:]:
      accumulated_geom = cascaded_union([accumulated_geom, geom])
if accumulated_geom.geom_type == 'Polygon':
      accumulated_geom = MultiPolygon([accumulated_geom])
geom = accumulated_geom
```

It works but it's not efficient so I tried again my prior oneliner with version 1.6b2 and now I have this error:

```shell
Assertion failed: (!"should never be reached"), function itemsTree, file AbstractSTRtree.cpp, line 371.
```

which is referenced in #259 but I'm not sure it has something to do with my issue.

Is there something obvious I'm missing here?

**Comment by sgillies** [comment]
@davidbgk It looks like your program is using Fiona as well. Correct? Can you tell me which version and details about how you're installing Shapely and Fiona? Operating system/Anacoda or pip or whatever/etc. There are two types of problems that lead to that assert exception: GEOS bugs and GEOS shared library incompatibility between Shapely and Fiona, and I'll need more details to rule out the latter.

**Comment by davidbgk** [comment]
@sgillies thanks for your quick answer, I install both Shapely and Fiona==1.7.1 via pip.

**Comment by sgillies** [comment]
@davidbgk yes, if you can. `post1` was a rebuild of the binary wheels for compatibility with the newest Shapely 1.6b.

**Comment by davidbgk** [comment]
I confirm the `Assertion failed` issue with `Shapely==1.6b3` and `Fiona==1.7.1.post1`.

**Comment by sgillies** [comment]
@davidbgk First: sorry for the delay, I've been busy on some other projects and other parts of Shapely. Second: without a script and data that I can use to reproduce the error, I'm not going to be able to help. Do you have a small set of shapes and a program that fails?

**Comment by davidbgk** [comment]
@sgillies thanks for your answer, I finally fixed the issue with these two lines in my `requirements.txt`:

```
Fiona==1.7.5 --no-binary :all:
Shapely==1.5.17 --no-binary :all:
```

Hope it helps people with similar issues.

**Comment by sgillies** [comment]
See also #553.
