### ISSUE TITLE
interpolate segment along a line (based on start & end distance)

### ISSUE THREAD

**Issue by ewsterrenburg** [Toblerity/Shapely#456]
Does Shapely provide a way to retrieve a linesegment based on start and end distance along the line?

(equivalent of segmentAlongLine in [arcpy](http://pro.arcgis.com/en/pro-app/arcpy/classes/geometry.htm))?

I could think of something like to generate the output with the existing functions by construction a line that consists of:
1. Point created by interpolate using start distance
2. Loop over vertices of the original line and project the location of each vertex:
- ignore the vertices while the resulting distance <= start distance
- add vertex to your output geometry if start distance < result of project < end distance
- stop as soon as projected distance >= end distance
3. Point created by interpolate using end distance

Yet if a more efficient method is available in GEOS, it would be a great enhancement for Shapely :)

**Comment by sgillies** [comment]
Sounds like a useful function to me, @ewsterrenburg. Shapely's line splitter does some of the same kind of things (see https://github.com/Toblerity/Shapely/blob/master/shapely/ops.py#L368), so there is existing code to reuse. I won't have time to work on this, I have to prioritize documentation and the next release, but can be counted on for code review for sure.

**Comment by ewsterrenburg** [comment]
@sgillies Thanks for your reaction.
With the pointers supplied and code review, I should be able to give this a go.
Might take some time though.

**Comment by sgillies** [comment]
Done!
