### ISSUE TITLE
PIP ImportError: No module named packaging.version

### ISSUE THREAD

**Issue by rasinquefield** [Toblerity/Shapely#460]
I am encountering a common problem with PIP, which has a well discussed solution.
$ pip install packaging

In my case, attempting to execute pip install packaging results in the same error I am trying to solve, ie 
ImportError: No module named packaging.version

**Comment by sgillies** [comment]
I don't understand this bug report. Can you provide a script that demonstrates the problem with Shapely installation or use?

**Comment by sgillies** [comment]
Resolved in 1.6b4.
