### ISSUE TITLE
Z coordinate lost during intersection

### ISSUE THREAD

**Issue by duncanwp** [Toblerity/Shapely#461]
I'm not sure if this is the intended behaviour but it appears that an intersection between a Multipoint Z object and a polygon doesn't properly preserve the z component. Shapely seems to merge overlapping points (disregarding the Z), presumably for performance reasons.

For example:

```
from shapely.geometry import MultiPoint, Polygon

multi_point = MultiPoint(((0, 1, 0), (1, 1, 1), (1.5, 1.5, 2), (1, 1, 3)))
poly = Polygon(((1, 1), (-1, 1), (-1, -1), (1, -1), (1, 1)))

selection = multi_point.intersection(poly) # MULTIPOINT Z (0 1 0, 1 1 2)
```

Whereas I would expect a `MULTIPOINT Z (0 1 0, 1 1 1, 1 1 3)`

**Comment by sgillies** [comment]
@duncanwp unfortunately the GEOS geometry engine used by Shapely is 2D only. The Z coordinates are only along for the ride (so to speak) and are not used in spatial algorithms.
