### ISSUE TITLE
buffer(0) sometimes fails to fix bowties

### ISSUE THREAD

**Issue by bb4242** [Toblerity/Shapely#462]
The [manual](http://toblerity.org/shapely/manual.html#object.buffer) has a nice example of cleaning up a bowtie polygon using `polygon.buffer(0)`.  I have found that the `buffer(0)` approach does not always produce the expected results.  Here's one example:

```python
pts = np.array([[-1.363827  , -1.6663611 ],
               [-2.31174309,  4.31812363],
               [-2.31535246,  4.31241047],
               [ 4.91703577, -0.8280218 ],
               [ 2.43771378, -4.46979011],
               [-1.363827  , -1.6663611 ]])
bowtie = Polygon(pts)
clean = bowtie.buffer(0)
```

`bowtie` has two parts, one of which is much larger than the other.  However, `clean` only contains the small part (`type(clean)` is `Polygon`, not `MultiPolygon`).

At first, I suspected that this was a numerical precision issue, since one part of the bowtie is much larger than the other.  However, by modifying the above coordinates a bit so that both parts are roughly equal in area, `buffer(0)` still yields only one half of the bowtie.  See the attached notebook for more details.

I have observed this behavior in shapely `1.6b3` and `1.5.13`.

[bowties.pdf](https://github.com/Toblerity/Shapely/files/749252/bowties.1.pdf)

**Comment by sgillies** [comment]
@bb4242 thanks for the great report. The `buffer(0)` trick is one of open source GIS's "folk remedies." It wasn't designed to fix bowties, but often works. One of my co-workers at Mapbox is getting better results in some cases with very small buffer values, like `1e-9`, but I haven't tested that approach. Maybe it's worth a try?

**Comment by bb4242** [comment]
Thanks @sgillies!  I wasn't aware that the `buffer(0)` trick wasn't actually designed to fix bowties.  Since that's the case, could I suggest putting a note to that effect in the manual?  I think the current language is "Passed a distance of 0, buffer() can be used to “clean” self-touching or self-crossing polygons such as the classic bowtie", which gave me the impression that this was intended to be a supported feature.

Regarding your suggestion to try very small buffer values, I just tried this:
```
for e in range(-20, -3):
    print bowtie.buffer(10**e).area
```
The result was still the same for all values (it captured only the tiny part of the bowtie).

Are there any other ways to clean self-intersecting polygons in shapely?  If not, are you aware of any other algorithms or open source libraries that can be used for this purpose?

**Comment by sgillies** [comment]
Documentation updated by 4d67a74.

**Comment by guyarad** [comment]
See #599 for possible solutions
