### ISSUE TITLE
Handle Invalid Geometries Gracefully

### ISSUE THREAD

**Issue by ab-tools** [Toblerity/Shapely#467]
I'm using a QGIS plug-in that is based on Shapely. Everything works perfectly most of the time, but for some bigger shapefiles the process stops suddenly giving an exception in "geometry/base.py" at function "deserialize_wkb(data)":
"Could not create geometry because of errors while reading input."

I've also reported the problem in the plug-in issue tracker, too
https://github.com/albertferras/simplipy/issues/37
but probably it belongs more to Shapely itself.

My question is:
I understand that there seem to be an issue in the shapefile itself, but is there no way to handle this issue more gracefully like just skipping this geometry or return a dummy/empty one?

There are like 500,000 geometries in this shapefile, so I would be fine if a "broken" one would just be skipped instead of stopping the whole process completely with an exception.

Maybe there is also a work-around for this problem - that would be great!

Thanks in advance for any ideas on that
Andreas

**Comment by perrygeo** [comment]
This is the expected behavior for Shapely - when an bad geometry is encounted, an exception should be raised. The solution is to use a `try`/`except` block in the plugin code. So in `simplipy` line 947, something like:

```
try:
    geometry = shapely.wkb.loads(wkb)
except ReadingError:
    pass  # or otherwise skip that geometry as appropriate to the code
```

**Comment by ab-tools** [comment]
Thinking about it you are absolutely right.

And although Python is not my programming language I managed to build a small work-around by creating an empty geometry in Simplipy in case of this exception.

Thanks for pointing me to the right direction! :-)
