### ISSUE TITLE
conda install from conda-forge requires a geos downgrade

### ISSUE THREAD

**Issue by jypeter** [Toblerity/Shapely#472]
When I want to install shapely in the environment described in https://wiki.lsce.ipsl.fr/pmip3/doku.php/other:uvcdat:cdat_conda#cloning_uvcdat_to_add_specific_packages_for_lsce, **conda wants me to downgrade geos**!
```
(uvcdat-2.8.0) bash-4.1$ conda install -n cdatm14 -c conda-forge shapely
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/share/unix_files/cdat/miniconda2/envs/cdatm14:

The following NEW packages will be INSTALLED:

    shapely: 1.5.17-np111py27_2 conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    geos:    3.6.0-0            conda-forge --> 3.5.1-1 conda-forge

Proceed ([y]/n)? n
```
If I don't specifiy conda-forge, it works but gets me a slightly older version of shapely... I will assume that's good enough
```
(uvcdat-2.8.0) bash-4.1$ conda install -n cdatm14 shapely
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/share/unix_files/cdat/miniconda2/envs/cdatm14:

The following NEW packages will be INSTALLED:

    shapely: 1.5.16-py27_0

Proceed ([y]/n)? y
```

**Comment by snorfalorpagus** [comment]
We're not responsible for the conda builds. If you need, you should create an issue here:

https://github.com/conda-forge/shapely-feedstock

conda-forge does have a build of GEOS 3.6.0 so I'm not sure what's triggering the downgrade.

**Comment by sgillies** [comment]
Thanks, @snorfalorpagus. I'm going to draft an issue template based on your comment.

**Comment by jypeter** [comment]
Thanks @sgillies and @snorfalorpagus !
