### ISSUE TITLE
Polygon buffer option does not produce a right polygon using a distance of 100 meters

### ISSUE THREAD

**Issue by fgfernandez0321** [Toblerity/Shapely#474]
## Expected behavior and actual behavior.
I expected to get the same distance when I will convert Mercator to Earth projection, in this case 100 meters

## Steps to reproduce the problem.
Initial Coordinates: [{lat: 25.683358829506474, lng: -80.27368442285156}, {lat: 25.680767547232723, lng: -80.27368442285156}, {lat: 25.680767547232723, lng: -80.2708090947876}, {lat: 25.683358829506474, lng: -80.2708090947876}, {lat: 25.683358829506474, lng: -80.27368442285156}]

Scaled Coordinates using buffer function: [{lat: 25.684168391105594, lng: -80.27458273816451}, {lat: 25.684168391105594, lng: -80.26991077951816}, {lat: 25.6799579625669, lng: -80.26991077951816}, {lat: 25.6799579625669, lng: -80.27458273816451}, {lat: 25.684168391105594, lng: -80.27458273816451}]

1. Create projections
earth_projection = pyproj.Proj(init='EPSG:4326')
mercator_projection = pyproj.Proj(init='EPSG:3857')

earth_to_mercator_projection = partial(pyproj.transform, earth_projection, mercator_projection)
mercator_to_earth_projection = partial(pyproj.transform, mercator_projection, earth_projection)

2. Create Polygon using Initial Coordinates where latitude and longitude are used inverse
**polygon** = Polygon(Initial Coordinates)

3. Project polygon using transform function: Earth to Mercator
**transformed_model** = shapely.transform(earth_to_mercator_projection, **polygon**)

4. Buffer transformed model with 100 meters
**b_model_area** = **transformed_model**.buffer(distance=100, cap_style=2, join_style=2)

5. Project **b_model_area** using  transform function: Mercator to Earth
**final_shape** = shapely.transform(mercator_to_earth_projection, **b_model_area**)

So, I represented these shapes in Google Maps (Initial Shape: Polygon generated in step 2 and Final Shape: Polygon generated in step 5). When I calculate distance between corners (horizontal and vertical), the result is 90 meters instead of 100 meters defined at the beginning. The result is the same if I defined: 

**mercator_projection** = pyproj.Proj('+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs')

![screenshot from 2017-03-22 20-09-13](https://cloud.githubusercontent.com/assets/10324741/24226703/545a3c16-0f3e-11e7-8e34-ba7ce371c6b3.png)

Horizontal and Vertical Distances are 90 instead of 100 meters.

![screenshot from 2017-03-22 20-31-37](https://cloud.githubusercontent.com/assets/10324741/24226738/93c4e11c-0f3e-11e7-8b7f-e230ab26523b.png)

## Operating system
Ubuntu 16.04.2 LTS

## Shapely version and provenance
Version 1.5.13

**Comment by sgillies** [comment]
I'm unable to reproduce the problem. Both `shapely.ops.transform()` and `buffer()` are doing the right thing within limits of floating point precision.

<img width="923" alt="untitled" src="https://cloud.githubusercontent.com/assets/33697/24248393/7bb8da60-0fcf-11e7-8dd4-758cdd82e710.png">

I suspect the problem is in measuring the distances in Google Earth. Can you double check the math there?
