### ISSUE TITLE
LGEOS340 object has no attribute GEOSGeom_createCollection

### ISSUE THREAD

**Issue by denadai2** [Toblerity/Shapely#476]
## Expected behavior and actual behavior.
I'm using Shapely in a pyspark enviroment, and it seems there is a problem with it but I don't understand the cause.

## Steps to reproduce the problem.

	from shapely.geometry import shape, Point
	from shapely.ops import unary_union
	import json
	from pyspark.sql.functions import udf
	from pyspark.sql.types import BooleanType

	# Return True or False
	def point_in_poly(x,y):
	    poly = getShape()
	    p = Point(4,22)
	    return poly.contains(p)

	def getShape():
	    with open('cerved/milano.geojson') as data_file:
	        feature_collection = json.loads(data_file.read())['features']
	        poly = [shape(x['geometry']) for x in feature_collection]
	        poly = unary_union(poly)
	    return poly

	contains_udf = udf(point_in_poly, BooleanType())
	df2 = df.filter(contains_udf(df.longCellBarycenter, df.latCellBarycenter))
	df2.count()

This results in:

      File "<ipython-input-10-a19dfccafd21>", line 3, in point_in_poly
      File "<ipython-input-10-a19dfccafd21>", line 11, in getShape
      File "/home/nadai/.local/lib/python3.4/site-packages/shapely/ops.py", line 147, in unary_union
    collection = lgeos.GEOSGeom_createCollection(6, subs, L)
    AttributeError: 'LGEOS340' object has no attribute 'GEOSGeom_createCollection'

but getShape works and the toy example Point(4,22).contains(p) works as well :)

## Operating system
Ubuntu

## Shapely version and provenance
shapely-1.5.17.post1

**Comment by sgillies** [comment]
@denadai2 I'm unable to reproduce the problem. Can you provide the Ubuntu version and GEOS version of the system you're running this on. If you're running this script on a cluster, can you verify that all the nodes have the GEOS library on them?

**Comment by denadai2** [comment]
Unfortunately, I changed the environment and I can't reproduce the error, so I also close the issue :) 

thx
