### ISSUE TITLE
Which polygon (in a list of polygons) contains another polygon?

### ISSUE THREAD

**Issue by dmitry-saritasa** [Toblerity/Shapely#480]
Across multiple polygons I need to find what specific polygons contains 'inner' polygon. Is it possible?

```python
from shapely.geometry import Polygon   
outer1 = Polygon(((0,0), (0, 10), (10, 10), (10, 0), (0,0)))
outer2 = Polygon(((1,0), (0, 10), (10, 10), (10, 0), (0,0)))
outer3 = Polygon(((1,0), (0, 10), (10, 10), (10, 0), (0,0)))
inner = Polygon(((0,0), (0,5), (5, 5), (5,0), (0,0)))
outer.contains(inner)
```

Right now I can do sequential check across multiple polygons - but is there a better way to find out what polygons contain inner?

**Comment by sgillies** [comment]
Yes, see this post for tips on using a spatial index: http://gis.stackexchange.com/questions/120955/understanding-the-use-of-spatial-indexes/120974#120974.
