### ISSUE TITLE
Assertion failed: (0), function query, file AbstractSTRtree.cpp, line 287.

### ISSUE THREAD

**Issue by sahil210695** [Toblerity/Shapely#490]
I'm using shape.intersection(b) and while running is jupyter getting this error.

already tried 
pip uninstall shapely && pip install shapely --no-binary :all: shapely
pip uninstall shapely && pip install shapely --no-binary :all: fiona

**OS**: macOS Sierra
**python packages**
affine (2.0.0.post1)
alabaster (0.7.9)
anaconda-client (1.6.0)
anaconda-navigator (1.5.2)
anaconda-project (0.4.1)
appnope (0.1.0)
appscript (1.0.1)
argcomplete (1.0.0)
astroid (1.4.9)
astropy (1.3)
Babel (2.3.4)
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.5.3)
bitarray (0.8.1)
blaze (0.10.1)
bokeh (0.12.4)
boto (2.45.0)
Bottleneck (1.2.0)
cdecimal (2.3)
cffi (1.9.1)
chardet (2.3.0)
chest (0.2.3)
click (6.7)
click-plugins (1.0.3)
cligj (0.4.0)
cloudpickle (0.2.2)
clyent (1.2.2)
colorama (0.3.7)
conda (4.3.18)
configobj (5.0.6)
configparser (3.5.0)
contextlib2 (0.5.4)
cryptography (1.7.1)
cycler (0.10.0)
Cython (0.25.2)
cytoolz (0.8.2)
dask (0.13.0)
datashape (0.5.4)
decorator (4.0.11)
descartes (1.1.0)
dill (0.2.5)
docutils (0.13.1)
enum34 (1.1.6)
et-xmlfile (1.0.1)
fastcache (1.0.2)
Fiona (1.7.6)
Flask (0.12)
Flask-Cors (3.0.2)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.0.5)
GDAL (2.1.0)
geopy (1.11.0)
gevent (1.2.1)
greenlet (0.4.11)
grin (1.2.1)
h5py (2.6.0)
HeapDict (1.0.0)
idna (2.2)
imagesize (0.7.1)
ipaddress (1.0.18)
ipykernel (4.5.2)
ipyleaflet (0.3.0)
ipython (5.1.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
isort (4.2.5)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.9.0)
Jinja2 (2.9.4)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.3.0)
jupyterthemes (0.15.0)
lazy-object-proxy (1.2.2)
lesscpy (0.12.0)
leveldb (0.194)
llvmlite (0.15.0)
locket (0.2.0)
lxml (3.7.2)
MarkupSafe (0.23)
matplotlib (2.0.0)
mistune (0.7.3)
mpmath (0.19)
multipledispatch (0.4.9)
munch (2.1.1)
nbconvert (4.2.0)
nbformat (4.2.0)
networkx (1.11)
nltk (3.2.2)
nose (1.3.7)
notebook (5.0.0)
numba (0.30.1+0.g8c1033f.dirty)
numexpr (2.6.1)
numpy (1.12.1)
numpydoc (0.6.0)
odo (0.5.0)
openpyxl (2.4.1)
osmapi (0.8.1)
overpy (0.4)
pandas (0.19.2)
partd (0.3.7)
pathlib2 (2.2.0)
patsy (0.4.1)
pep8 (1.7.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (3.4.2)
pip (9.0.1)
planet (1.0.0)
ply (3.10)
prompt-toolkit (1.0.9)
protobuf (3.2.0)
psutil (5.0.1)
psycopg2 (2.6.2)
ptyprocess (0.5.1)
py (1.4.32)
pyasn1 (0.1.9)
PyAudio (0.2.7)
pycosat (0.6.1)
pycparser (2.17)
pycrypto (2.6.1)
pycurl (7.43.0)
pyflakes (1.5.0)
Pygments (2.1.3)
pylint (1.6.4)
pymongo (3.2.1)
pyOpenSSL (16.2.0)
pyparsing (2.2.0)
pyproj (1.9.5.1)
PySAL (1.13.0)
pyshp (1.2.10)
pytest (3.0.5)
python-dateutil (2.6.0)
pytz (2016.10)
PyYAML (3.12)
pyzmq (16.0.2)
QtAwesome (0.4.3)
qtconsole (4.3.0)
QtPy (1.2.1)
rasterio (1.0a8)
redis (2.10.5)
requests (2.12.4)
requests-futures (0.9.7)
rope (0.9.4)
Rtree (0.8.2)
scandir (1.4)
scikit-image (0.12.3)
scikit-learn (0.18.1)
scipy (0.18.1)
seaborn (0.7.1)
setuptools (27.2.0)
Shapely (1.5.17)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
snuggs (1.4.1)
sockjs-tornado (1.0.3)
Sphinx (1.5.1)
spyder (3.1.3)
SQLAlchemy (1.1.5)
statsmodels (0.6.1)
subprocess32 (3.2.7)
sympy (1.0)
tables (3.3.0)
terminado (0.6)
toolz (0.8.2)
tornado (4.4.2)
traitlets (4.3.2)
unicodecsv (0.14.1)
urllib3 (1.21.1)
utm (0.4.2)
virtualenv (15.1.0)
wcwidth (0.1.7)
Werkzeug (0.11.15)
wheel (0.29.0)
widgetsnbextension (2.0.0)
wrapt (1.10.8)
xlrd (1.0.0)
XlsxWriter (0.9.6)
xlwings (0.10.2)
xlwt (1.2.0)

**and using osgeo version 2.1.0**

**Comment by sgillies** [comment]
Anaconda, I see. You cannot use the Shapely or Fiona wheels on PyPI with Anaconda. You must use the packages in the conda-forge channel.

**Comment by davidbernat** [comment]
This did not resolve the problem for me, sgillies. 

Furthermore, I am somewhat surprised by the fragmented instructions a Google searcher finds on installing Shapely, GEOS, GDAL, etc. These are core utilities to GIS. Here, you mention another detail, that packages need to be installed from one (none primary) package resource than another. 

It is not uncommon to find many pages spread throughout 2014-2016 each suggesting various different install solutions. Quite a lot of voodoo for my taste.

Could you recommend a clean install pathway or tutorial for these services?

**Comment by snorfalorpagus** [comment]
There are two "official" ways to install Shapely/Fiona: either building from source, or using the binary packages available on PyPI. The binary packages include the required binary dependencies for GEOS and GDAL, and are only available for Linux and macOS. We don't currently produce binary packages for Windows, although this is something I'd like to improve in the future.

The best way to install will vary between users, depending on their operating system and how they have installed Python.

Linux tends to have a mature package management system so the best way is usually to install the GEOS/GDAL packages through that, then install Shapely/Fiona from source. Your package manager may even include a binary for Shapely/Fiona, although from experience these can lag behind quite some way (favouring stability over new features).

The story is more complicated for macOS, which doesn't have an official package manager. In this case you can either build everything (including GEOS/GDAL) from source, or use the binaries from PyPI. An intermediate option is to install binaries for GEOS/GDAL (such as those provided by KyngChaos) and install Fiona/Shapely from source.

Installing on Windows is a particular pain, as generally users do not have a working C compiler installed as they do on Linux/macOS. In this case you must either install MSVC and build from source or find a binary distribution (such as those produced by Christoph Gohlke).

Another option is to install everything using Anaconda Python. This project provides a package manager with a consistent interface across Windows, Linux and macOS. Anaconda provides binary packages and manages dependencies (such as GEOS/GDAL) for you. You can't just install a few modules with Anaconda: it's all or nothing, as it's a full python distribution / environment manager. You're also reliant on them building the packages for you, so releases may lag behind the official releases. The "conda-forge" project is a community-driven effort to build as many packages for Anaconda as possible, and to keep things as current as possible. Personally this is the route I've chosen, as I find working on multiple operating systems it's nice to have some consistency. However, this is something completely outside the control of the Shapely/Fiona projects.

**Comment by sgillies** [comment]
See also #553.
