### ISSUE TITLE
Simplify result on polygons depends on the cyclic order of the vertices

### ISSUE THREAD

**Issue by vins31** [Toblerity/Shapely#491]
## Expected behavior and actual behavior.

I noticed the results of the simplify() method on polygons depends on the cyclic order of the vertices.
Take a polygon, shift the order of the vertices in the initialization, it is the same polygon (poly1 and poly2 in the example below). But the application of the Ramer–Douglas–Peucker algorithm through  the simplify() method on these two identical polygons will lead to simplified polygons with different number of vertices.

Note: I know this problem is more related to Geos than Shapely, but the registration on their Trac requires a registration on Osgeo which looks like a long process :(

## Steps to reproduce the problem.

```Python
from shapely.geometry import Polygon

#In poly2, the vertices 0, 1 and 2 are perfectly aligned 
# along the  line -0.35001187*x + -0.0756343*y + 0.64449771
poly2 = Polygon([[1.341343356332423, 2.313918776834345], [1.344881773910638, 2.297544087047788], [1.416996781165046, 1.963818389997046], [0.06662927567958832, 0.002057790756225586]])

# For poly1, we shifted the vertex 0 to put it at the end 
poly1 = Polygon([[1.344881773910638, 2.297544087047788], [1.416996781165046, 1.963818389997046], [0.06662927567958832, 0.002057790756225586], [1.341343356332423, 2.313918776834345]])

# Our polygons are identical
poly1.difference(poly2).area
>> 0.0

# As expected, we get a simplified polygon with 3 vertices
# the first one is repeated in a line ring, so 3+1=4
poly2_simplified = poly2.simplify(0.001, False)
print len(poly2_simplified.exterior.coords)
>> 4

# Here get the original polygon, no simplification occurred while some points were perfectly aligned 
poly1_simplified = poly1.simplify(0.001, False)
print len(poly1_simplified.exterior.coords)
>> 5
```

## Operating system

Mac OS X 10.11.6

## Shapely version and provenance

1.5.17 installed from PyPI using pip

**Comment by sgillies** [comment]
I appreciate you bringing this issue up @vins31. I did not know that this was the case. I'm not going to change the GEOS algorithm, but I will see that Shapely's docs are updated.

**Comment by sgillies** [comment]
Documentation updated by 197b052.
