### ISSUE TITLE
Updated manual?

### ISSUE THREAD

**Issue by bladeoflight16** [Toblerity/Shapely#496]
[Shapely's PyPI page](https://pypi.python.org/pypi/Shapely) links to [this version of the manual](http://toblerity.org/shapely/manual.html). That version states that it's for Shapely 1.2 and 1.3. It does appear to be somewhat out of date, or at least incomplete. For example, there's no mention of the `snap` or `hausdorff_distance` methods, even though the [repository's manual.rst](https://github.com/Toblerity/Shapely/blob/master/docs/manual.rst) does mention them.

Is there an updated version anywhere on the web? If not, could one be published, and could the PyPI doc be updated to link to it?

**Comment by sgillies** [comment]
Updating the manual is part of the 1.6 release effort. Until then, https://github.com/Toblerity/Shapely/blob/master/docs/manual.rst is the best we have.

I'd love to be able to use a service like readthedocs, but we're blocked by that service's need to import Shapely to publish and that it has no way to build this kind of C extension module.
