### ISSUE TITLE
Release GIL while calling into compiled libraries

### ISSUE THREAD

**Issue by mrocklin** [Toblerity/Shapely#497]
When calling into compiled codebases shapely may way want to consider releasing the global interpreter lock.  

This would allow shapely to be used in parallel by many Python threads to speed up operations.  It would also let it play more nicely with concurrency frameworks like asyncio or Tornado.

I ran into this explicitly when supporting a user who was calling `shapely.wkb.loads` in a separate thread alongside a Tornado application and grew confused why the tornado application became completely unresponsive during this period.

This documentation page may be of interest: https://docs.python.org/3/c-api/init.html#thread-state-and-the-global-interpreter-lock

Downstream issue: https://github.com/dask/distributed/issues/1225

**Comment by sgillies** [comment]
GEOS's WKB serializer doesn't do any I/O and doesn't (in my experience) run long like the compression algorithms mentioned in the note at the end of https://docs.python.org/3/c-api/init.html#releasing-the-gil-from-extension-code. Are the WKB blobs very big? Is there some other I/O going on?

It looks like the way to do it is sort of explained at https://docs.python.org/3/library/ctypes.html#function-prototypes. It's fairly complicated.

**Comment by mrocklin** [comment]
I don't think that I/O is related here.  Compression in that document is only used as an example for "long-running C functions called in external code, which in this case is operations within GEOS.

I think that in this case the user passed a large string to the deserializer function which then churned for a while producing the result.  During that time all other concurrent Python threads were frozen.  

If you're using ctypes then it looks like you can release the GIL by using the `ctypes.CFUNCTYPE` function prototype.

If you switch to using Cython (such as is hinted at in https://github.com/geopandas/geopandas/issues/430 ) then there are other mechanisms, such as the `with nogil:` contextmanager or other function annotations.

**Comment by snorfalorpagus** [comment]
My read of the ctypes docs suggests the GIL *is* released already. I may be misinterpreting it though. https://docs.python.org/3.6/library/ctypes.html#loading-shared-libraries

**Comment by sgillies** [comment]
@snorfalorpagus yes, that's my take too.

> Instances of this class behave like CDLL instances, except that the Python GIL is not released during the function call

Will close this one for now.
