### ISSUE TITLE
esri JSON format for geometry objects

### ISSUE THREAD

**Issue by achapkowski** [Toblerity/Shapely#499]
Hello,

I was  hoping to get some guidance on how to enhance the shapely package before I go mucking about.

I want to add support for inputting/outputting esri JSON to/from the shapely.geometry objects.
Can anyone provide guidance on what would need to be updated to support this?

Thank you

**Comment by sgillies** [comment]
@achapkowski I've no desire to build support for Esri JSON into Shapely. Shapely supports a GeoJSON-based geospatial protocol https://gist.github.com/sgillies/2217756 and that's plenty. Support for Esri JSON is best provided by a different module.
