### ISSUE TITLE
Polygon's docs __init__ arguments mismatch 

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [Toblerity/Shapely#500]
On the [docs website](http://toblerity.org/shapely/manual.html#polygons) it says to created a polygon with the arguments **exterior** and **interiors** `class Polygon(exterior[, interiors=None])` but in [Shapely/shapely/geometry/polygon.py](https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/polygon.py#L189) the arguments are actually **shell** and **holes** `def __init__(self, shell=None, holes=None):`.

**Comment by sgillies** [comment]
@BebeSparkelSparkel thanks for flagging this!

**Comment by sgillies** [comment]
Resolved by #527.
