### ISSUE TITLE
Faster alternative to geometryType()?

### ISSUE THREAD

**Issue by Zoodinger** [Toblerity/Shapely#508]
Hello,

My application deals with a lot of data and binary operations. I need to check for the geometry type of the results in order to extract specific geometries from it. A lot.

Doing that was no issue, but there's one caveat: Using `geometryType() == 'X'`, where X is a geometry type (e.g. Polygon) adds a significant overhead. Using `type(geom) == X` or `isinstance(geom, X)` isn't any faster either. However, using `__class__ == X` is significantly faster than anything else.

It might not sound like it should make a difference, but I'm doing a lot of processing and it does build up to a difference of approximately 50 more files processed per hour when I use `__class__` instead of the alternatives.

I can use `__class__` for now, but this won't work if I encounter any subclasses of geometry types that I'm not aware of. This wouldn't have been an issue if Shapely had provided an integer id for geometries.

Is it possible for this to be a feature? Are there any possibly faster alternatives I'm not aware of?

Thanks!

**Comment by sgillies** [comment]
No, I don't know of faster alternatives for Shapely. It could be that Shapely is just not fast enough for this situation.

If `geom.__class__ == 'Point'` is faster than `isinstance(geom, Point)` by all means use it.

If you'd rather work with instances of a single `Geometry` class that had type as an integer, you could try the GDAL Python bindings or the GeoDjango geometry module.
