### ISSUE TITLE
Failing geopandas tests related to empty collection

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Shapely#510]
With the release of 1.6.0, the geopandas tests started failing (we should really test with shapely master, or at least with beta/rc versions, sorry!)

I didn't look yet into detail what is going wrong, but I could already pin it down to:

```
In [6]: from shapely.geometry import Point

In [7]: from geopandas import GeoSeries

In [8]: s = GeoSeries([Point(1, 1), None])

In [9]: s.fillna(Point())
Out[9]: 
0                 POINT (1 1)
1    GEOMETRYCOLLECTION EMPTY
dtype: object

In [10]: import shapely

In [11]: shapely.__version__
Out[11]: '1.5.16'
```

vs

```
In [7]: from shapely.geometry import Point

In [8]: from geopandas import GeoSeries

In [9]: s = GeoSeries([Point(1, 1), None])

In [10]: s.fillna(Point())
Out[10]: 
0    POINT (1 1)
1           None
dtype: object

In [11]: import shapely

In [12]: shapely.__version__
Out[12]: '1.6.0'
```

So the `fillna` method is no longer filling with an empty collection. 

I have to further drill down into the fillna implementation to see where the difference happens, and what actual shapely behaviour changed(will try to do that tomorrow). But already putting this issue, in case anybody has an idea where it could be coming from.

**Comment by jorisvandenbossche** [comment]
I could already drill it down to a non-geopandas reproducible example, but with numpy. Apparently, `np.putmask` no longer wants to put an empty geometry inside an array:

```
In [2]: import numpy as np

In [3]: from shapely.geometry import Point

In [4]: a = np.array([Point(1, 1), None], dtype=object)

In [5]: mask = np.array([False, True])

In [6]: fill_value = Point()

In [7]: print(fill_value)
GEOMETRYCOLLECTION EMPTY

In [9]: np.putmask(a, mask, fill_value)

In [10]: a
Out[10]: 
array([<shapely.geometry.point.Point object at 0x7f6299f1ae10>,
       <shapely.geometry.point.Point object at 0x7f6299f202e8>], dtype=object)

In [13]: shapely.__version__
Out[13]: '1.5.16'
```

vs 

```
In [4]: a = np.array([Point(1, 1), None], dtype=object)

In [5]: mask = np.array([False, True])

In [6]: fill_value = Point()

In [7]: print(fill_value)
GEOMETRYCOLLECTION EMPTY

In [8]: np.putmask(a, mask, fill_value)

In [9]: a
Out[9]: array([<shapely.geometry.point.Point object at 0x7f0463aeeb38>, None], dtype=object)

In [15]: shapely.__version__
Out[15]: '1.6.0'
```

**Comment by jorisvandenbossche** [comment]
So further drilling down, the difference lies in how the provided value is broadcasted (in `np.repeat`), which boils down to a difference in the array interface:

```
>>> shapely.__version__
'1.5.16'

>>> np.asarray(Point(1, 1))
array([ 1.,  1.])

>>> np.asarray(Polygon([(1, 1), (2, 2), (2, 1)]))
array(<shapely.geometry.polygon.Polygon object at 0x7f77e56a56a0>, dtype=object)

>>> np.asarray(Point())
array(<shapely.geometry.point.Point object at 0x7f77e6421eb8>, dtype=object)

>>> np.asarray(Polygon())
array(<shapely.geometry.polygon.Polygon object at 0x7f77e56a56a0>, dtype=object)
```

vs
```
>>> shapely.__version__
'1.6.0'

>>> np.asarray(Point(1, 1))
array([ 1.,  1.])

>>> np.asarray(Polygon([(1, 1), (2, 2), (2, 1)]))
array(<shapely.geometry.polygon.Polygon object at 0x7f8c5641f470>, dtype=object)

>>> np.asarray(Point())
array([], dtype=float64)

>>> np.asarray(Polygon())
array(<shapely.geometry.polygon.Polygon object at 0x7f8c5641f470>, dtype=object)
```

So is related to https://github.com/Toblerity/Shapely/issues/403 (and PR https://github.com/Toblerity/Shapely/pull/442). 
So the change was deliberate, and I agree that for a empty Point it now looks more consistent with a non empty Point. 

So we will have to work-around that ourselves I suppose.

The fact that Polygon has no array interface, however has the consequence that eg `np.repeat` works very differently between a Point and empty Point or with Polygon:

```
In [3]: np.repeat(Point(1, 1), 2)
Out[3]: array([ 1.,  1.,  1.,  1.])

In [4]: np.repeat(Polygon([(1, 1), (2, 2), (2, 1)]), 2)
Out[4]: 
array([<shapely.geometry.polygon.Polygon object at 0x7f0520318710>,
       <shapely.geometry.polygon.Polygon object at 0x7f0520318710>], dtype=object)
```

(and an empty Point previously behaved like a Polygon, and that was the behaviour we relied upon)

So it comes down to the question whether numpy should treat geometries like scalars or not (as geometries have both notions). And by providing the array interface to only some of the geometries, numpy does it differently for different geometry types. 
When storing geometries in numpy arrays (what we do in geopandas), you typically want the scalar behaviour

**Comment by sgillies** [comment]
@jorisvandenbossche thanks for the explanation! I would love to help GeoPandas out by making `Point()` and `Polygon()` consistent. I've got a few things to learn about `np.repeat` and `np.asarray` and am open to suggestions.

**Comment by jdmcbr** [comment]
@sgillies As a workaround for `geopandas`, would it be a bad idea to use `BaseGeometry()` to fill na values? @jorisvandenbossche expressed reservations about using `Polygon()`, which behaves the same as `Point()` had before, but could also have its `__array_interface__` behavior change. I thought `BaseGeometry` would not be likely to have such a change occur, but don't know if there are other reasons not to do that.

**Comment by sgillies** [comment]
@jdmcbr yes, `BaseGeometry()` is a good work-around for now. We could add a derived `Empty` class to make the interface more permanent.

```python
class Empty(BaseGeometry):
    """An empty geometry"""
```

What would you think about that @jorisvandenbossche?

**Comment by jdmcbr** [comment]
Thanks, @sgillies. An explicit `Empty` class seems useful to me as a way to avoid the differences in behavior for empty geometries of different types, and would certainly make its meaning more transparent when used in other projects.

**Comment by sgillies** [comment]
Closing. Let's continue in #513.
