### ISSUE TITLE
Url link in github repo's "short description" still points to old docs

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Shapely#511]
When you go to the github repo home page https://github.com/Toblerity/Shapely, the link at the top of the page in the short description of the project is http://toblerity.github.com/shapely/, which still points to docs of version 1.2 / 1.3.

I would do a PR to update the link to the new readthedocs (https://shapely.readthedocs.io/en/latest/) location, but that description is something only a maintainer can do :-)

**Comment by sgillies** [comment]
Fixed!
