### ISSUE TITLE
User manual about shapely.geometry.Polygon is misleading

### ISSUE THREAD

**Issue by michelbl** [Toblerity/Shapely#526]
(Shapely version 1.6.1 installed from PyPI using pip)

User manuel about Polygons (https://shapely.readthedocs.io/en/latest/manual.html#polygons) defines the constructor with parameters `exterior` and `interiors`. However the true parameters are `shell` and `holes` (https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/polygon.py#L208)

I think the problem lies in https://github.com/Toblerity/Shapely/blob/master/docs/manual.rst#polygons (https://raw.githubusercontent.com/Toblerity/Shapely/master/docs/manual.rst)

Also, documentation in the user manual and in the source file seems redundant (https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/polygon.py#L198 vs https://shapely.readthedocs.io/en/latest/manual.html#polygons)

**Comment by michelbl** [comment]
Oops this issue is a duplicate of #500

**Comment by sgillies** [comment]
I'd like to keep the interior and exterior attributes and bring the constructor in sync. In 1.7 we could add interior and exterior keyword arguments and mark the future deprecation of shell and holes, using them as aliases for the former.
