### ISSUE TITLE
Cannot install on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by winash12** [Toblerity/Shapely#545]
I am trying to install Shapely on Ubuntu 16.04 LTS and I have geos installed and I am getting these errors when I type python3.5 setup.py install. Shapely version is 1.6.2 and the geos library is installed under /usr/local/lib and the LD_LIBRARY_PATH does have this this value as part of it.

cannot open shared object from 'geos-config --clibs': '-L/usr/local/lib -lgeos_c'
there were 2 guess(es) for this path:
	/usr/local/lib/libgeos_c.so
	/usr/local/lib/libgeos_c.so.1
Failed `CDLL(libgeos_c.so.1)`
Failed `CDLL(libgeos_c.so.1)`
Failed `CDLL(libgeos_c.so)`
Traceback (most recent call last):
  File "setup.py", line 80, in <module>
    from shapely._buildcfg import geos_version_string, geos_version, \
  File "/home/winash12/libPython/Shapely-master/shapely/_buildcfg.py", line 167, in <module>
    fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
  File "/home/winash12/libPython/Shapely-master/shapely/_buildcfg.py", line 161, in load_dll
    libname, fallbacks or []))
OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so

## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.

(For example: the area of my geometry is `1.417` when it should be `1.414`.)

## Steps to reproduce the problem.

(For example, a script with required data)

## Operating system

(For example, Mac OS X 10.12.3)

## Shapely version and provenance

(For example, 1.6b4 installed from PyPI using pip)

**Comment by winash12** [comment]
I was able to fix this by running this command sudo apt-get install libgeos-dev

**Comment by sgillies** [comment]
I can confirm that shapely fails to install on a fresh ubuntu 16.04 server without the libgeos package installed.

```
# pip3 install --no-binary shapely shapely
Collecting shapely
  Downloading Shapely-1.6.2.post1.tar.gz (221kB)
    100% |################################| 225kB 1.5MB/s
    Complete output from command python setup.py egg_info:
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bl3nvdpk/shapely/setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/tmp/pip-build-bl3nvdpk/shapely/shapely/_buildcfg.py", line 167, in <module>
        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
      File "/tmp/pip-build-bl3nvdpk/shapely/shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bl3nvdpk/shapely/
```

This is to be expected – shapely's readme and install docs say that you need the GEOS lib before installation – though the error message isn't great.

The geos dev package isn't strictly required, installing only libgeos-c1 is sufficient. Getting libgeos-dev would be best.

```
root@0ca930cfc2c4:/# apt-get install libgeos-c1v5
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libgeos-3.5.0
The following NEW packages will be installed:
  libgeos-3.5.0 libgeos-c1v5
0 upgraded, 2 newly installed, 0 to remove and 4 not upgraded.
Need to get 530 kB of archives.
After this operation, 2258 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libgeos-3.5.0 amd64 3.5.0-1ubuntu2 [477 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libgeos-c1v5 amd64 3.5.0-1ubuntu2 [52.4 kB]
Fetched 530 kB in 1s (464 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libgeos-3.5.0.
(Reading database ... 13952 files and directories currently installed.)
Preparing to unpack .../libgeos-3.5.0_3.5.0-1ubuntu2_amd64.deb ...
Unpacking libgeos-3.5.0 (3.5.0-1ubuntu2) ...
Selecting previously unselected package libgeos-c1v5.
Preparing to unpack .../libgeos-c1v5_3.5.0-1ubuntu2_amd64.deb ...
Unpacking libgeos-c1v5 (3.5.0-1ubuntu2) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up libgeos-3.5.0 (3.5.0-1ubuntu2) ...
Setting up libgeos-c1v5 (3.5.0-1ubuntu2) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
```

After this you can install shapely from the source distribution on PyPI.

```
root@0ca930cfc2c4:/# pip3 install --no-binary shapely shapely
Collecting shapely
  Using cached Shapely-1.6.2.post1.tar.gz
Skipping bdist_wheel for shapely, due to binaries being disabled for it.
Installing collected packages: shapely
  Running setup.py install for shapely ... done
Successfully installed shapely-1.6.2.post1
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@0ca930cfc2c4:/# python
bash: python: command not found
root@0ca930cfc2c4:/# python3
Python 3.5.2 (default, Sep 14 2017, 22:51:06)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shapely
>>> shapely.__version__
'1.6.2.post1'
```
