### ISSUE TITLE
R-Tree Query Details?

### ISSUE THREAD

**Issue by ablakey** [Toblerity/Shapely#549]
It is not obvious to me what the R-Tree's query considers a match. Is it intersection, equality, contains? Especially when mixing point, line, polygon types.  By digging in and finding [this reference](http://geos.refractions.net/ro/doxygen_docs/html/classgeos_1_1index_1_1strtree_1_1STRtree.html#a4), I believe a match is made when the querying geometry `intersects` an element in the tree.

Is this correct? If so, is it worth it for me to make a PR updating the documentation to reflect this useful detail?

**Comment by sgillies** [comment]
@ablakey sorry for the confusion! Yes, the shapely R-tree has the same semantics as the one in GEOS, and yes, we'd gratefully accept a doc update.

**Comment by ablakey** [comment]
Great! PR is up. Closing this issue.
