### ISSUE TITLE
shapely.ops.substring not in release 1.6.3

### ISSUE THREAD

**Issue by aka863** [Toblerity/Shapely#552]
It was described in the manual。
[https://shapely.readthedocs.io/en/latest/manual.html#shapely.ops.substring](https://shapely.readthedocs.io/en/latest/manual.html#shapely.ops.substring)

**Comment by snorfalorpagus** [comment]
Looks like it was originally intended for 1.6, but was merged into master instead.

https://github.com/Toblerity/Shapely/pull/459

The documentation needs correcting to "New in version 1.7.0".

**Comment by sgillies** [comment]
Resolved in ad06bf8.
