### ISSUE TITLE
Centroid for polygonZ

### ISSUE THREAD

**Issue by ocni-dtu** [Toblerity/Shapely#554]
Is possible to have the centroid method return a POINTZ, when applied to a PolygonZ object?

Or is there a easy workaround?

**Comment by sgillies** [comment]
@ocni-dtu no, it is not possible. The Z type geometries are not true 3D figures and the z value is only along "for the ride", so to speak.

In my opinion, it was a mistake for GIS software to introduce the Z types. The values are ignored and contradicted by software in many situations. Polygons with non-overlapping z values will still intersect, etc. The flattening of centroids is like that.
