### ISSUE TITLE
prepared_geom.contains memory leak

### ISSUE THREAD

**Issue by pryabchuk** [Toblerity/Shapely#556]
I am using prepared geometry to check multiple points against it. Home grown special geo_coder

First around 300 shapes are put in "borders" variable as prep() shapes
...
for feature in data['features']:
	poly = shape(feature['geometry'])
	borders.append((prep(poly), country_code))

The borders list is around 180MB in memory

then i Use RTree index by bboxes to limit geos and then "contains" method

It seems that testing 15000 points -> running 15000 "contains" leaks for 569 MB

```
Line #    Mem usage    Increment   Line Contents
 73262  186.000 MiB  186.000 MiB   @profile\n
 73263                             def check():'n
 73264  754.715 MiB    0.004 MiB   	for i, pt in enumerate(points):
 73265                             
 73266  754.715 MiB    0.000 MiB   		point = Point(pt['longitude'], pt['latitude'])
 73267  754.715 MiB    0.000 MiB   		found = []
 73268  754.715 MiB    0.152 MiB   		for j in idx.intersection(point.coords[0]):
 73269  754.715 MiB  568.559 MiB   			if borders[j][0].contains(point):
 73270  754.715 MiB    0.000 MiB   				found.append(borders[j][1])
 73271  754.715 MiB    0.000 MiB   		if found:
 73272  754.715 MiB    0.000 MiB   			for found_one in found:
 73273  754.715 MiB    0.000 MiB   				if found_one != pt['country']:
 73274  754.500 MiB    0.000 MiB   					print('buu: ', found_one, pt['country'])
 73275                             		else:
 73276  723.051 MiB    0.000 MiB   			print('No :', pt['country'])
```

Mac OS X 10.13.1, Python 3.6

Shapely 1.6.3 from PyPI using pip

**Comment by sgillies** [comment]
@pryabchuk there have been reports of memory leaks in the GEOS prepared polygon, but not for a while. See https://trac.osgeo.org/geos/ticket/342 for example. This would be a GEOS regression.

Does that 569 MB remain allocated even after the the objects in your `borders` array go out of scope and get garbage collected? If not, I think that may be the actual working size of the GEOS objects.

**Comment by pryabchuk** [comment]
actually "borders" are garbage collected then, but i think you are right... it's the actual woking size 
Thanks for the hint in any case!
