### ISSUE TITLE
Wrong result when query using STRtree

### ISSUE THREAD

**Issue by Chenhuajie** [Toblerity/Shapely#558]
## Expected behavior and actual behavior.

Construct a rtree with two linestrings, for example (0 0, 2 0) and (0 1, 2 0), and then query with a buffer (like Point(0, 0.5).buffer(0.01) ), the result should be empty but I got the linestring(0 1, 2 0)

## Steps to reproduce the problem.

```pycon
>>> tree=STRtree([LineString([(0,0),(2,0)]),LineString([(0,1),(2,0)])])
>>> [o.wkt for o in tree.query(Point(0,0.5).buffer(0.01))]
['LINESTRING (0 1, 2 0)']
```

## Operating system

Mac OS X 10.13.2
Python 2.7.10
shapely 1.6.3

**Comment by snorfalorpagus** [comment]
The STRtree checks for intersections in the bounding box of the geometries _only_.

The bounding box of the second geometry does intersect the Point, as illustrated below.

```pycon
>>> box(*LineString([(0,1),((2,0))]).bounds).intersects(Point(0, 0.5).buffer(0.01))
True
```

You can use the STRtree to narrow the search, but you'd need to do an additional check to see if the geometries actually intersected.
