### ISSUE TITLE
Inconsistency between nearest_points and intersection

### ISSUE THREAD

**Issue by MikeTho16** [Toblerity/Shapely#561]
One would expect nearest_points() to always return points (although not necessarily vertices) that are part of the geometries that it is given, and that performing an intersection() between a point from nearest_points() and its corresponding input geometry would yield that point.  This is not always the case (see specifics below to reproduce the problem).

## Expected behavior and actual behavior.
When an intersection() is performed between a point returned by nearest_points() and its corresponding geometry, the result should be that point.

Expected: POINT (2 3.333333333333334)
Actual: GEOMETRYCOLLECTION EMPTY

Note: It depends on the specific point along the segment one chooses, sometimes the expected result is obtained.

## Steps to reproduce the problem.
    from shapely.geometry import LineString
    from shapely.geometry import Point
    from shapely.ops import nearest_points
    linestring = LineString([(3, 5), (0, 0)])
    point = Point(2, 10.0/3.0)
    print linestring.intersection(point)
    #GEOMETRYCOLLECTION EMPTY - not surprising, probably due to precision issues, however...
    pt_on_linestring = nearest_points(linestring, point)[0]
    print linestring.intersection(pt_on_linestring)
    # Actual result: GEOMETRYCOLLECTION EMPTY
    # Expected result: POINT (2 3.333333333333334)
    # Related observation
    # intersects() also gives an answer that is not expected
    linestring.intersects(pt_on_linestring)
    # Actual: False
    # Expected: True

## Operating system

Windows 10 Enterprise 10.0.15063 Build 15063

## Shapely version and provenance

1.6.4.post1 from https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

**Comment by snorfalorpagus** [comment]
This is due to floating point rounding errors. I don't think there is much we can do about it.

**Comment by sgillies** [comment]
Agreed @snorfalorpagus, point and line intersection with the GEOS floating point precision model is problematic.

**Comment by MikeTho16** [comment]
@snorfalorpagus, @sgillies 

First of all, thanks for the quick replies.

> This is due to floating point rounding errors
I would agree if I had computed the point outside of Shapely/Geos, but this is a case where one part of Shapely (nearest_points) is saying 'this is a point that is part of geometry x', and another part (intersection) is saying 'no it is not.'  It should be internally consistent.

The bigger thing I am trying to achieve is to correct for the precision issue by having nearest_points() find a point that is actually part of the other geometry, and then use that in the intersection operation. The Point / LineString is just the simplest example. In the case of something more complex, such as two LineStrings, one would visit every vertex, find the nearest point on the other geometry, and if within a specified tolerance, move that vertex to the point returned by nearest_points, and then finally perform the intersection.

**Comment by MikeTho16** [comment]
Here is another example of an example of internal inconsistency which could be related to the original issue:

    from shapely.geometry import LineString
    linestring = LineString([(3, 5), (0, 0)])
    linestring2 = LineString([(0, 68.0/15.0), (340.0/45.0,0)])
    # Above two LineStrings should intersect at Point(2, 10.0/3.0)
    inter = linestring.intersection(linestring2)
    inter.wkt
    # 'POINT (2 3.333333333333333)'
    linestring.intersects(inter)
    # False
    linestring2.intersects(inter)
    # False

So it is possible that the intersection of two LineStrings yields a geometry (a point) which is not part of either of the LineStrings.
