### ISSUE TITLE
Result of Polygon Z Intersection doesn't Always Close

### ISSUE THREAD

**Issue by MikeTho16** [Toblerity/Shapely#565]
When intersecting a polygon with z values with another polygon (with or without z values), the result does not always have rings whose first and last vertex are the same, they can differ in their z values.

Note that while polygon.intersection(polygon_with_zs) sometimes exhibits this problem, polygon_with_zs.intersection(polygon) seems to always give an acceptable result.

## Expected behavior and actual behavior.

Expected: First and last vertex of a polygon that results from the intersection of two polygons should have rings whose first and last vertices are the same, including z values. 

Actual: In some cases the z values of the first and last vertices differ.

## Steps to reproduce the problem.

        polygon1 = Polygon([(14, 18),     
                            (13, 18), 
                            (13, 20), 
                            (14, 20), 
                            (14, 18)])
        polygon2 = Polygon([(12, 20, 0), 
                            (14, 20, 3), 
                            (14, 17, 0), 
                            (12, 17, 0), 
                            (12, 20, 0)])                            
        print polygon1.intersection(polygon2).wkt
        # POLYGON Z ((140 18 0.75, 138 18 0.75, 138 20 3, 140 20 3, 140 18 1))

## Operating system

Windows 10 Enterprise 10.0.15063 Build 15063

## Shapely version and provenance

1.6.4.post1 from https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

**Comment by sgillies** [comment]
@MikeTho16 z values are inert in Shapely and we say so in the manual. They have no affect on any predicate evaluation or geometry construction.

**Comment by MikeTho16** [comment]
@sgillies Thanks for the quick response! It appears that they are not completely inert because they are being manipulated (not simply passed through). For example, in my original example, there are no z values of 0,75 in the inputs, but it appears in the output.  If they are truly 'inert' they should be left as is, or if a new vertex is generated, populated with some documented default value. In fact, the vertex at 14, 20 has a z of 3 in one input, and 1.5 in the output, so it is not inert.  In any event, if polygon1.intersection(polygon2) produces a polygon, that polygon should have rings that close when considering x,y and z. 

Another example of that z's are not really inert:
    Point(1,2,3).equals(Point1,2,4)
    #False
