### ISSUE TITLE
Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r

### ISSUE THREAD

**Issue by balzer82** [Toblerity/Shapely#566]
```
Geometry must be a Point or LineString
Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3991.
Abort trap: 6
```

## Steps to reproduce the problem.

```
from shapely.geometry.polygon import LinearRing
ring = LinearRing([(0, 0), (1, 1), (1, 0)])
list(ring.coords)
```
## Operating system

Mac OS X 10.12.6

## Shapely version and provenance

1.6.4.post1 installed from PyPI using pip

**Comment by sgillies** [comment]
@balzer82 I can't reproduce the problem

```
$ python
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely.geometry.polygon import LinearRing
>>> ring = LinearRing([(0, 0), (1, 1), (1, 0)])
>>> list(ring.coords)
[(0.0, 0.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0)]
```

I'm using the binary wheel from PyPI (`pip install shapely`).

```
$ pip list | grep Shapely
Shapely (1.6.4.post1)
```

Did you, by chance, install from an sdist using the GEOS library installed on your system by running `pip install --no-binary shapely shapely`?

**Comment by balzer82** [comment]
You are right! Uninstalled it, reinstalled it with `pip install shapely` and now it works.
