### ISSUE TITLE
Docs unclear about collection slicing

### ISSUE THREAD

**Issue by kannes** [Toblerity/Shapely#569]
The docs say "Homogeneous collections can also be sliced, resulting in a new object of the same type." but I have no trouble slicing a heterogeneous GeometryCollection (MultiPoint plus Polygon) with Shapely==1.6.1.

http://shapely.readthedocs.io/en/stable/manual.html#collections

**Comment by sgillies** [comment]
Thanks for pointing this out. I'll strike the word "homogenous" and the part about "same type".
