### ISSUE TITLE
Problem with left parallel_offset 

### ISSUE THREAD

**Issue by debjan** [Toblerity/Shapely#575]
Hi,

it seems like there is a problem with parallel offset on a left side.

For example:

```python
import shapely
from shapely.geometry import LineString
```

```python
shapely.__version__
```

    '1.6.4.post1'

```python
line = LineString([
    (0.702227727277449, 52.2684403575796),
    (0.702466731559753, 52.2682730142646),
    (0.702620641169389, 52.2681525832661),
    (0.703069913619352, 52.2678275454922),
    (0.703098095398922, 52.2678089143778),
])
```

```python
line
```

![output_3_0](https://user-images.githubusercontent.com/1919296/38062074-5602b29a-32f2-11e8-911b-1ead4e2651d4.png)

```python
line.parallel_offset(.003, side='left')
```

![output_4_0](https://user-images.githubusercontent.com/1919296/38062098-757792d0-32f2-11e8-9c5e-28b4ba1bf2d0.png)

and then resulting buffer:

```python
line.parallel_offset(.003, side='left').buffer(.003, cap_style=2)
```

![output_5_0](https://user-images.githubusercontent.com/1919296/38062103-815cdf38-32f2-11e8-8a15-37a3748f7007.png)

This does not happen with parallel offset on a right side.

If I remove last (or penultimate) point, this also does not happen:

```python
line = LineString([
    (0.702227727277449, 52.2684403575796),
    (0.702466731559753, 52.2682730142646),
    (0.702620641169389, 52.2681525832661),
    (0.703069913619352, 52.2678275454922),
#     (0.703098095398922, 52.2678089143778),
])

line.parallel_offset(.003, side='left').buffer(.003, cap_style=2)
```

![output_6_0](https://user-images.githubusercontent.com/1919296/38062108-87e0f6e6-32f2-11e8-8626-32191c4e9e05.png)

Jupyter notebook: https://gist.github.com/debjan/7acd28aac065e5827bd8a17dae2b181f

Any ideas?

**Comment by sgillies** [comment]
@debjan I've seen other reports of one sided buffer oddities. I think the algorithm is not very robust around the end of lines and that the nearness of the last two points is triggering some instability.

We're working on the next Shapely release (1.7) and won't be able to address this bug until after. It may need to be resolved in GEOS. Until then, I can only suggest work arounds like simplification of your line (with `simplify()`) to remove vertices that are too near.

**Comment by debjan** [comment]
Ok, thanks

**Comment by debjan** [comment]
AFAIU, you could try with using less points aka simplify the lines

**Comment by jeueblah** [comment]
@debjan Thanks, that's what I ended up doing per your/Sean's earlier postings. I just wanted to let it be known that others still have the issue.
