### ISSUE TITLE
pip install shapely - No matching distribution found for shapely

### ISSUE THREAD

**Issue by lambertkuang** [Toblerity/Shapely#578]
## Expected behavior and actual behavior.
Expected to be able to install using `pip install shapely`

## Steps to reproduce the problem.
Running `pip install shapely` gives:
```
Could not find a version that satisfies the requirement shapely (from versions: )
No matching distribution found for shapely
```

## Operating system
Mac OS X 10.12.6
python 2.7.10
pip 9.0.1

**Comment by sgillies** [comment]
@lambertkuang It looks like you need to update to pip 9.0.3. See https://mail.python.org/pipermail/distutils-sig/2018-April/032114.html for the explanation.
