### ISSUE TITLE
question about precision of polygon

### ISSUE THREAD

**Issue by ShigeruNakagaki** [Toblerity/Shapely#579]
there is a column of `geometry_type='Polygon', srid=4326`.
inserted data is `128.22707423580786`.

- [shaply.geometry.base.py#  to_wkt](https://github.com/Toblerity/Shapely/blob/bed28170140429d58e4079c57cc2480c5e5ff6ab/shapely/geometry/base.py#L359) method returns `128.2270742358078621`  
 (this is not same as original value)
- [shaply.geometry.base.py#  wkt](https://github.com/Toblerity/Shapely/blob/bed28170140429d58e4079c57cc2480c5e5ff6ab/shapely/geometry/base.py#L365) property returns `128.2270742358079`  
 (this value is rounded at 15)

How can I get original value correctly?

**Comment by sgillies** [comment]
I'm sorry but this is not an issue for the Shapely tracker. Floating point values can not generally be represented in computers with perfect precision and there is almost always some loss of precision or gain of false precision when serializing them to and from WKT.
