### ISSUE TITLE
Invalid convexhull polygon for Multipoint objext

### ISSUE THREAD

**Issue by hosseinahm** [Toblerity/Shapely#580]
## Expected behavior and actual behavior.
I am trying to generate convex hull for a MultiPoint object but the returned polygon is an invalid polygon object.

## Steps to reproduce the problem.

```
from shapely.wkt import loads
mps = loads('MULTIPOINT (0.09176166386719853 -0.4594509958047714, 0.0964919595889223 -0.4613185215258491, -0.07720854327505063 -0.3893774144175335, -0.514132735196233 0.4844243124571844, -0.5157563919220147 0.4883439730483261, -0.4438154792984115 0.6620323790359064, -0.44378845454982 0.6620355239884737, -0.4430558191117821 0.6617320714344408, -0.4425193476523399 0.6629710114442775, -0.2750532183528819 0.5968552076395059, -0.2676620363052705 0.5937936520564248, 0.4616312579331061 -0.1299616117871567, 0.4652079369036946 -0.1371183617095489, 0.4668376557292508 -0.141042820548618, 0.4665494319079306 -0.1427098330519487, 0.4665629024181607 -0.1427344571104113, 0.3918467226125127 -0.315278746283741, 0.3861846650602798 -0.3209365927118177, 0.09649195958892229 -0.4613185215258491, 0.09176166386719853 -0.4594509958047714)')
mps.convex_hull.is_valid
```
![shapely_error](https://user-images.githubusercontent.com/5801794/38907478-47dde19a-42ff-11e8-8df0-2612ff8f22ba.png)

## Operating system

Ubuntu 16.0  

## Shapely version and provenance

shapely 1.6b4 installed from PyPI using pip

**Comment by snorfalorpagus** [comment]
I can't reproduce this problem. It's possible this is a bug in an older version of GEOS. What do you have installed?

Python 3.6.3 (64-bit), Windows 10, Shapely master, GEOS 3.6.2

![convex_hull](https://user-images.githubusercontent.com/3883947/40622598-4e682182-629a-11e8-980e-4777e87d861b.png)

**Comment by sgillies** [comment]
Closing for lack of response.
