### ISSUE TITLE
WKTWriter with trim=True and rounding_precision=N misbehaves

### ISSUE THREAD

**Issue by IvKor** [Toblerity/Shapely#586]
Hi, 

I might discovered a suspicious behavior of the WKTWriter.

I did test with the following Point:

```
from shapely.wkt import dumps
from shapely.geometry import Point

p = Point(527626.9300000001, 0.00)
```

"dumps" the point with the "trim=True" should remove trailing zeros (it happens).

```
print(dumps(p, trim=True))
```

> POINT (527626.9300000001 0)

"dumps" the point with the "rounding_precision=4" round the point to 4 decimal places. In this case it removes 000001 from X coordinate and adds 00 to Y coordinate (it happens).

```
print(dumps(p, rounding_precision=4))
```

> POINT (527626.9300 0.0000)

The potential error happens when both trim=True" and "rounding_precision=4" are applied to the point. It seems to me that the coordinates are converted to a scientific notation on which the rounding_precision is applied.

```
print(dumps(p, trim=True, rounding_precision=4))
```

> POINT (5.276e+05 0)

I did tests on both Windows and Linux operating systems.

**Comment by sgillies** [comment]
@IvKor thanks for the report. I'm surprised by the scientific notation, too, and would have expected `527600`. However, I don't think `5.276e+05` is wrong, and since this behavior is determined by the GEOS library, we're not going to fix it in Shapely.

**Comment by mwtoews** [comment]
I blame C++ for this one, and it's default decimal formatter implemented in libgeos' WKTWriter. The string `527626.93` is the shortest decimal representation which uniquely identifies this value as a `double`. It's also much more aesthetically appealing than the long version of the same number (with `00000001`).

It would be really nice for libgeos to upgrade to a better way to format these numbers. I've bumped a feature request [geos #868](https://trac.osgeo.org/geos/ticket/868#ticket), so I guess we'll see where that goes. As mentioned within that ticket, I've been using [numpy 1.14.0](https://github.com/numpy/numpy/releases/tag/v1.14.0)'s enhancement to use [Ryan Juckett's Dragon4 algorithm](http://www.ryanjuckett.com/programming/printing-floating-point-numbers/).

**Comment by IvKor** [comment]
@sgillies than you for a reply. I appreciate this is the GEOS issue rather than Shapely. 

I agree with you that `527600` is equal to `5.276e+05`. I am also fine with the scientific notation. Where I cannot agree (hence I still think it is incorrect) is that `527600` is far from the input point. I was expecting `527626.93` instead.

Changing rounding_precision from 4 to 1 results in:

```
from shapely.wkt import dumps
from shapely.geometry import Point

p = Point(527626.9300000001, 0.00)

print(dumps(p, trim=True))
print(dumps(p, rounding_precision=1))
print(dumps(p, trim=True, rounding_precision=1))
```

> POINT (527626.9300000001 0)
> POINT (527626.9 0.0)
> POINT (5e+05 0)

which, in my opinion is wrong. The last point (5e+05 = 500000) is obviously wrong in particular when compared to the behavior of rounding without the trim option.

I have tested this on Windows 10 and Ubuntu 18.04 (libgeos-3.6.2) and got the same outputs.

Interestingly enough, when I set rounding_precision=0 I got different outputs from Windows

> POINT (527626.9300000001 0)
> POINT (527627 0)
> POINT (527627 0)

when compared to the outputs from Ubuntu 18.04

> POINT (527626.9300000001 0)
> POINT (527627 0)
> POINT (5e+05 0)
 
which is ridicules :).

**Comment by sgillies** [comment]
Oh, I see what you mean now. Following your example, I have

```
>>> print(dumps(Point(math.pi * 1000000, math.pi * 1000000), trim=True, rounding_precision=1))
POINT (3e+06 3e+06)
```

This looks like a GEOS bug to me. I'm surprised I didn't see any related issues in the GEOS tracker. We must not be using trim and rounding_precision together very often, or it could be a fairly new bug. I won't have time to look into it very soon, unfortunately.

**Comment by mwtoews** [comment]
the C++ that I blamed above that is currently implemented in WKTWriter::writeNumber is essentially just using [std::setprecision](http://en.cppreference.com/w/cpp/io/manip/setprecision):
```
#include <iostream>
#include <iomanip>
#include <sstream>

int main()
{
    int rounding_precision = 1;
    double x = 527626.93;
    std::cout << std::setprecision(rounding_precision) << x << std::endl;
}
```
Which prints `5e+005`, which is a poor outcome. This has one digit of [significant figure](https://en.wikipedia.org/wiki/Significant_figures), rather than (I suppose) rounding decimals in [positional notation](https://en.wikipedia.org/wiki/Positional_notation).

**Comment by IvKor** [comment]
@sgillies I was also surprised with this bug so decided to use only rounding_precision instead although it is a bit annoying to have trailing zeros.

@mwtoews Thank you for your comments, although I have to admit they are a bit beyond my IT/programming knowledge :).

**Comment by sgillies** [comment]
Let's close this one and reopen if it's still a problem with GEOS 3.9.

**Comment by mwtoews** [comment]
FYI, this may potentially change with GEOS 3.10 (or current master), which uses [Ryū](https://github.com/libgeos/geos/tree/2376cd6bf5d0743b02b588af17d2e9067c1874de/src/deps/ryu) (via https://github.com/libgeos/geos/commit/2376cd6bf5d0743b02b588af17d2e9067c1874de) for string formatting/rounding stuff.
