### ISSUE TITLE
shp1 == shp2 is True but shp1.equals(shp2) is False

### ISSUE THREAD

**Issue by Juanlu001** [Toblerity/Shapely#587]
## Expected behavior and actual behavior.

I expected `shp1.equals(shp2)` to return `True` in all cases where `shp1 == shp2`, but I found a case where the latter is `True` and the former is `False`.

## Steps to reproduce the problem.

```
coords = [
 (-57.64813907181611, -27.387472879648747),
 (-57.64813907181611, -27.387455126209556),
 (-57.64823176725435, -27.387455126209556),
 (-57.64823176725435, -27.387440428723046),
 (-57.64819869850847, -27.387441351750372),
 (-57.64816660022662, -27.38744338022161),
 (-57.648144664439585, -27.387449005906134),
 (-57.64813737405543, -27.387459611732552),
 (-57.64813907181611, -27.387472879648747)
]
shp1 = Polygon(coords)
shp2 = Polygon(coords)

print(shp1 == shp2)  # True
print(shp1.equals(shp2))  # False
```

## Operating system

Linux Mint 18.3

## Shapely version and provenance

1.6.4.post1 installed with pip.

**Comment by Juanlu001** [comment]
I should have checked this before opening the issue, but

```
>>> shp1.is_valid
False
```

**Comment by sgillies** [comment]
@Juanlu001 it's normal for `equals` and `==` to differ in a lot of very common cases. For example:

```python
>>> Point(0, 0).equals(MultiPoint([(0, 0)]))
True
>>> Point(0, 0) == MultiPoint([(0, 0)])
False
```

This is because `equals` only considers the sets of points in space described by the Python objects and `__eq__` compares the coordinate sequences of the Python objects.

**Comment by Juanlu001** [comment]
Thanks for the response @sgillies -- I'm still not sure about the conceptual difference in the opposite case (`.equals` False but `__eq__` True) so for now I will "use with care".
