### ISSUE TITLE
shared_paths() behavior

### ISSUE THREAD

**Issue by Ricyteach** [Toblerity/Shapely#590]
## Expected behavior and actual behavior.

The `ops.shared_paths` function seems to have some issues. Three different cases are demonstrated below in which two polygon boundaries that should partially coincide are calculated erroneously.

[See behavior example on nbviewer.](http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/iw3qdewwt8zpshx/shared_paths%20behavior.ipynb)

## Steps to reproduce the problem.

see nbviewer link

## Operating system

Windows 10

## Shapely version and provenance

1.6.4 from [Chris Gohlke's whl file page](https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely)

**Comment by sgillies** [comment]
@Ricyteach I think that much of the discrepancy between what we observe and expect comes down to the approximation of buffered geometries. Ideally: smooth buffers of the lines in your first example intersect only at two points, right? We can start to see this when we increase the density of points around the corners of the buffer from 16 (the default) to 128. At the other end of the spectrum, when we decrease the density to 1, the roughly approximated buffers do share short paths.

![untitled](https://user-images.githubusercontent.com/33697/44000725-9030dc8c-9e25-11e8-84fa-47c06066da6d.png)

I believe that shared_paths is returning the correct result in the second case: the geometries only intersect at two points and there are no shared paths.

The shared_paths function isn't very useful for analyzing these particular geometries, I am sorry to say.

I'm unable to reproduce the topology exception. I think this may be specific to the version of GEOS in Gohlke's wheels.
