### ISSUE TITLE
[BUG?] LineString difference between bounds and boundary 

### ISSUE THREAD

**Issue by okomarov** [Toblerity/Shapely#591]
## Expected behavior and actual behavior.
Why is the LineString boundary different from bounds? 

It seems coordinates are sparsely sampled before calling boundary (with e.g. np.linspace), which might skip on minimums and maximums contained in the middle of the line.

## Steps to reproduce the problem.
```python
from shapely.geometry import LineString

x = [-106.97248045, -106.97028913, -106.96809781, -106.96590649,
       -106.97248045, -106.96371517, -106.95248231, -106.96152384,
       -106.95933252, -106.9571412 , -106.95494988, -106.95275856]
y = [39.18759405, 39.18964863, 39.19170321, 39.19375778, 39.1874456 ,
       39.19581236, 39.20610735, 39.19786694, 39.19992151, 39.20197609,
       39.20403067, 39.20608524]
line = LineString(zip(x,y))

print("xmin,ymin,xmax,ymax\n",min(line.coords.xy[0]),min(line.coords.xy[1]),
                              max(line.coords.xy[0]),max(line.coords.xy[1]))
print("bounds\n",             *line.bounds)
print("boundary\n",           line.boundary[0].x, line.boundary[0].y,
                              line.boundary[1].x, line.boundary[1].y)
```

The result

```
xmin,ymin,xmax,ymax
 -106.97248045 39.1874456 -106.95248231 39.20610735
bounds
 -106.97248045 39.1874456 -106.95248231 39.20610735
boundary
 -106.97248045 39.18759405 -106.95275856 39.20608524
```
## Operating system
OSx 10.13.4

## Shapely version and provenance
1.6.4.post1 conda-forge

**Comment by sgillies** [comment]
@okomarov the topological boundary of a curve is its two *end* points, while the bounds is the limits of the minimum bounding rectangle. In general they will differ.

**Comment by okomarov** [comment]
@sgillies Thanks for your answer, that makes sense.
 
I later found the boundary definition right at the beginning, under the **Spatial Data Model**.  I did not see it immediately because I was searching for the `LineString.boundary()` method, and hence was always skipping to the relevant section. It might be one of those trivial notions, but I feel that people just getting into spatial analysis would benefit from a bit of repetition.
