### ISSUE TITLE
Implement wkb.dumps(geom, srid=XXX)

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Shapely#592]
In #132 @sgillies suggested an `srid` keyword argument to the `wkb.dumps` function.

Currently dumps has a `include_srid` keyword argument, which defaults to False. If set to True it does work as intended, although there is no way in Shapely to set the SRID of a geometry without poking the GEOS internals (GEOSSetSRID/GEOSGetSRID).

Are you still amenable to an `srid=4326` style argument to dumps? If so, does it need to clone the geometry before exporting, otherwise the function will not be idempotent (although not in any way visible from Shapely).

**Comment by sgillies** [comment]
@snorfalorpagus yes, cloning sounds like the right approach. I'm all for this 👍
