### ISSUE TITLE
Failed `CDLL(/opt/local/lib/libgeos_c.dylib)` message seems misplaced.

### ISSUE THREAD

**Issue by dxgeorge** [Toblerity/Shapely#596]
## Expected behavior and actual behavior.

Expected behavior is to NOT see this error message:
Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
While that load failed, a 'fallback' load succeeded.

## Steps to reproduce the problem.

from shapely.geometry import Point

--

I am able to get around the issue with this patch to geos.py:
+    warnList = [] # keep warn list
     if not dll and fallbacks is not None:
         for name in fallbacks:
             try:
                 LOG.debug("Trying `CDLL(%s)`", name)
                 dll = CDLL(name, mode=mode)
             except OSError:
                 # move on to the next fallback
-                LOG.warn("Failed `CDLL(%s)`", name)
+                warnList.append(name)                # do NOT warn, save them up
+                #LOG.warn("Failed `CDLL(%s)`", name)
                 pass
 
     if dll:
         LOG.debug("Library path: %r", lib or name)
         LOG.debug("DLL: %r", dll)
         return dll
     else:
+        for warn in warnList:                   # do warnings now
+            LOG.warn("Failed `CDLL(%s)`", warn)

## Operating system

Mac OS 10.13.4 (High Sierra)

## Shapely version and provenance

Shapely            1.6.1    (via PIP3)

**Comment by sgillies** [comment]
@dxgeorge would you be willing to `pip install -U shapely` to see if the problem persists in 1.6.4?

**Comment by dxgeorge** [comment]
I did the pip install -U shapely.
python(2) fails, while python(3) is ok. Seems weird, but whatever.

mac-mini:$ pip list
Package            Version     
------------------ ------------
altgraph           0.15        
appnope            0.1.0       
backcall           0.1.0       
bleach             2.1.3       
certifi            2018.1.18   
chardet            3.0.4       
click              6.7         
click-plugins      1.0.3       
cligj              0.4.0       
cycler             0.10.0      
decorator          4.3.0       
descartes          1.1.0       
entrypoints        0.2.3       
fastkml            0.11        
Fiona              1.7.11.post1
Flask              1.0         
future             0.16.0      
GDAL               2.2.4       
geojson            2.3.0       
geopandas          0.3.0       
geos               0.2.1       
gpxpy              1.2.0       
html5lib           1.0.1       
idna               2.6         
ipykernel          4.8.2       
ipython            6.3.1       
ipython-genutils   0.2.0       
ipywidgets         7.2.1       
itsdangerous       0.24        
jedi               0.12.0      
Jinja2             2.10        
jsonschema         2.6.0       
jupyter-client     5.2.3       
jupyter-console    5.2.0       
jupyter-core       4.4.0       
kiwisolver         1.0.1       
lxml               4.2.1       
macholib           1.9         
MarkupSafe         1.0         
matplotlib         2.2.2       
mistune            0.8.3       
munch              2.3.1       
nbconvert          5.3.1       
nbformat           4.4.0       
notebook           5.4.1       
numpy              1.14.2      
osmapi             1.1.0       
OWSLib             0.16.0      
pandas             0.22.0      
pandocfilters      1.4.2       
parso              0.2.0       
pefile             2017.11.5   
pexpect            4.5.0       
pickleshare        0.7.4       
pip                10.0.1      
prompt-toolkit     1.0.15      
psycopg2           2.7.4       
ptyprocess         0.5.2       
pygeoif            0.7         
Pygments           2.2.0       
PyInstaller        3.3.1       
pyparsing          2.2.0       
pyproj             1.9.5.1     
pyshp              1.2.12      
python-dateutil    2.7.2       
pytz               2018.3      
PyYAML             3.12        
pyzmq              17.0.0      
qtconsole          4.3.1       
requests           2.18.4      
Send2Trash         1.5.0       
setuptools         39.0.1      
Shapely            1.6.4.post1 
simplegeneric      0.8.1       
six                1.11.0      
terminado          0.8.1       
testpath           0.3.1       
tornado            5.0.2       
traitlets          4.3.2       
tz                 0.2.2       
urllib3            1.22        
wcwidth            0.1.7       
webencodings       0.5.1       
Werkzeug           0.14.1      
widgetsnbextension 3.2.1       

mac-mini:$ python z.py 
Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
mac-mini:$ python3 z.py 
mac-mini:$

**Comment by dxgeorge** [comment]
When I ran 'python -v z.py' vs 'python3 -v z.py',
it seems that python3 goes through the "if hasattr(sys, 'frozen'):" code path,
hence the different behavior.

**Comment by dxgeorge** [comment]
With 1.6.4, the warning is gone.
My python2 was using an old version of shapely (not sure which version).
I would think that this problem could be closed out with 1.6.4 fixing the issue!

**Comment by sgillies** [comment]
Thanks for the follow up @dxgeorge !
