### ISSUE TITLE
import shapley causing MemoryError

### ISSUE THREAD

**Issue by avipersin** [Toblerity/Shapely#602]
### Description

I am unable to make sense of this traceback.

#### Code to reproduce
```
import shapely.geometry as sgeom
```

#### Traceback 
A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.

 /web3a/www/data/cgi-bin/rocke3d/amaps_model.cgi in ()
=>   12 import shapely.geometry as sgeom
shapely undefined, sgeom undefined

 /usr/local/lib/python3.4/site-packages/Shapely-1.6.4.post1-py3.4.egg/shapely/geometry/__init__.py in ()
=>    4 from .base import CAP_STYLE, JOIN_STYLE
CAP_STYLE undefined, JOIN_STYLE undefined

 /usr/local/lib/python3.4/site-packages/Shapely-1.6.4.post1-py3.4.egg/shapely/geometry/base.py in ()
=>   17 from shapely.coords import CoordinateSequence
shapely undefined, CoordinateSequence undefined

 /usr/local/lib/python3.4/site-packages/Shapely-1.6.4.post1-py3.4.egg/shapely/coords.py in ()
=>    8 from shapely.geos import lgeos
shapely undefined, lgeos undefined

 /usr/local/lib/python3.4/site-packages/Shapely-1.6.4.post1-py3.4.egg/shapely/geos.py in ()
=>  226 error_h = EXCEPTION_HANDLER_FUNCTYPE(error_handler)

error_h undefined, EXCEPTION_HANDLER_FUNCTYPE = &lt;class 'ctypes.CFUNCTYPE &lt;locals>.CFunctionType'>, error_handler = &lt;function make_logging_callback.&lt;locals>.callback>

MemoryError:
      args = ()
      with_traceback = &lt;built-in method with_traceback of MemoryError object> 

<details>
 <summary>Full environment definition</summary>

### Operating system
Linux

### Shapely version
Shapely         1.6.4.post1

### pip list

```
basemap         1.1.0
Cartopy         0.16.0
cycler          0.10.0
Cython          0.23
Django          1.8.4
geojson         1.2.0
geopy           1.10.0
h5py            2.5.0
Jinja2          2.8
MarkupSafe      0.23
matplotlib      1.5.1
mpld3           0.3git
netCDF4         1.2.7
nose            1.3.7
numpy           1.10.4
pandas          0.16.2
patsy           0.4.0
pip             10.0.1
pyparsing       2.1.10
pyproj          1.9.5.1
pyshp           1.2.12
python-dateutil 2.6.0
pytz            2016.10
requests        2.11.1
scipy           0.16.1
setuptools      39.2.0
Shapely         1.6.4.post1
six             1.10.0
statsmodels     0.8.0rc1


GEOS 3.3.3
proj Rel. 5.1.0, June 1st, 2018
```

</details>

**Comment by sgillies** [comment]
Importing shapely loads a dynamic library and if you don't have adequate RAM available, you will get a MemoryError. The library itself isn't very big, ~4-5 MB, but might incur some other loads.

I'm going to close this if you don't mind, because there is nothing to be done in Shapely.
