### ISSUE TITLE
AsMultiLineString(cascaded_union(list of one LineString)) raises a TypeError

### ISSUE THREAD

**Issue by nick-parker** [Toblerity/Shapely#603]
## Expected behavior and actual behavior.
I'm intersecting a MultiLineString of several parallel lines with several Polygons in a list, then doing a cascaded_union on the results. This is different from creating a MultiPolygon and intersecting the MultiLineString with that, because I want the result to be ordered such that all the LineString segments intersecting a given polygon are sequential in the final MultiLineString. I'm starting to realize shapely might not preserve order like that, but that's not really relevant to this bug:

I'd like to be able to treat the output as a MultiLineString whether there are multiple lines which pass through the Polygons or not, so I put the cascaded_union through asMultiLineString afterward. That works fine when there are multiple polygons which intersect the grid, or when one polygon intersects multiple grid lines so the result is a list with one MultiLineString in it, but if it's a single LineString in a list I hit a
`TypeError: object of type 'LineString' has no len()` when later trying to check if the result is empty. See code below.

## Steps to reproduce the problem.
```
from shapely.geometry import asMultiLineString, LineString
from shapely.ops import cascaded_union


if __name__ == "__main__":
  line = LineString([(-7.4, -5), (7.4, -5)])
  line_list = [line]
  line_output = asMultiLineString(cascaded_union(line_list))
  foo = line_output.is_empty
```

## Operating system
Ubuntu 16.04, or according to uname -a:
`Linux nick-P34 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

## Shapely version and provenance
1.6.3 installed with anaconda

**Comment by nick-parker** [comment]
This turned out to be a simple and known issue, read about it here: http://community.gispython.narkive.com/LSsXSVUf/cascaded-union-linestring-has-no-len

It didn't occur to me to test this but simply doing

```
line_output = asMultiLineString(line)
foo = line_output.is_empty
```
Yields identical behavior. So asMultiLineString just doesn't like receiving single LineStrings. If you wrap them in a list it works fine. So the fix to handle both cases is as follows:
```
from shapely.geometry import asMultiLineString, LineString
from shapely.ops import cascaded_union


if __name__ == "__main__":
  line = LineString([(-7.4, -5), (7.4, -5)])
  line2 = LineString([(-7.4, -4), (7.4, -4)])
  line3 = LineString([(-7.4, -3), (7.4, -3)])
  # line_list = [line]
  line_list = [line, line2, line3]
  combined = cascaded_union(line_list)
  if isinstance(combined, LineString):
    line_output = asMultiLineString([combined])
  else:
    line_output = asMultiLineString(cascaded_union(line_list))
  # line_output = asMultiLineString([line])
  foo = line_output.is_empty
```

It'd be nice to handle this issue somewhere in the shapely interface code to lgeos, because it was definitely a headscratcher for a couple days over here. But this issue can probably be closed because there's a perfectly good workaround.

**Comment by sgillies** [comment]
Thanks for the follow up @nick-parker !
