### ISSUE TITLE
[Request] python3.7 support

### ISSUE THREAD

**Issue by pydo** [Toblerity/Shapely#608]
**Description**
Consider supporting python3.7.
Shapely currently supports the following platforms:
- python2.7
- python3.4
- python3.5
- python3.6

source: https://pypi.org/project/Shapely/#files

**Repro steps**:
When a user tries to `pip install shapely` using a python3.7 interpreter, PYPI defaults to using the source package `Shapely-1.6.4.post1.tar.gz` since no wheels are available. 

**Actual behavior**
Shapely fails to install since the source package doesn't come with `libgeos`
```
Collecting shapely
  Using cached https://files.pythonhosted.org/packages/7d/3c/0f09841db07aabf9cc387662be646f181d07ed196e6f60ce8be5f4a8f0bd/Shapely-1.6.4.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dvsq7fc3/shapely/setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/tmp/pip-install-dvsq7fc3/shapely/shapely/_buildcfg.py", line 167, in <module>
        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
      File "/tmp/pip-install-dvsq7fc3/shapely/shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
```

**Expected behavior**
Package installs correctly because a python37 wheel is available.

**Note**
I can probably help with packaging python37

**Comment by sgillies** [comment]
@pydo thank you for bringing this up. I will schedule a 1.6.4.post2 release.

**Comment by sgillies** [comment]
Closing, see #612.
