### ISSUE TITLE
Crash with invalid LineString -> LinearRing

### ISSUE THREAD

**Issue by dopplershift** [Toblerity/Shapely#609]
```python
In [1]: import shapely.geometry as sgeom

In [2]: ls = sgeom.LineString([(0, 0), (0, 0), (0, 0)])

In [3]: lr = sgeom.LinearRing(ls)
IllegalArgumentException: Invalid number of points in LinearRing found 3 - must be 0 or >= 4

In [4]: lr.is_ccw
[1]    16446 segmentation fault  ipython
```
I see this on my Mac with Shapely 1.6.4 from conda-forge. I've also had the problem reported from users on other OSes.

**Comment by sgillies** [comment]
This is invalid usage of Shapely. Please see https://shapely.readthedocs.io/en/stable/manual.html#linearrings:

> The LinearRing constructor takes an ordered sequence of (x, y[, z]) point tuples.

**Comment by dopplershift** [comment]
Fair enough. What was head scratching about it is that:
```python
from shapely.geometry import LineString, LinearRing
line = LineString([(0, 0), (1, 0), (0, 1)])
ring = LinearRing(line)
ring.is_ccw
```
works just fine.

**Comment by dopplershift** [comment]
Actually @sgillies I'm going to disagree with you; the docs also say
> The LinearRing constructor also accepts another LineString or LinearRing instance, thereby making a copy.

**Comment by sgillies** [comment]
@dopplershift correct!
