### ISSUE TITLE
Distance between two 3D point object won't work properly.

### ISSUE THREAD

**Issue by Neavrys** [Toblerity/Shapely#613]
Problem:
Distance between two 3D point object won't use Z coordinates.

**Example:**

Point(0,0).distance(Point(1,1))
1.4142135623730951

Point(0,0,0).distance(Point(1,1,1))
1.4142135623730951

Point(0,0,0).distance(Point(1,1,2))
1.4142135623730951

Point(0,0,0).distance(Point(1,1,3))
1.4142135623730951

Point(0,0,0).distance(Point(1,1,4))
1.4142135623730951

## Env. spec.

Python 2.7 
Pycharm 2018-1
Shapely 1.5.7 via Enthought Canopy.

**Comment by sgillies** [comment]
Please see the note under https://shapely.readthedocs.io/en/stable/manual.html#geometric-objects. Shapely is a 2D library.

**Comment by nyxaria** [comment]
did you find an implementation somewhere which can handle a 3D LineString and a distance to a 3D point?
