### ISSUE TITLE
Breaking change: Point object is no longer hashable

### ISSUE THREAD

**Issue by odedfos** [Toblerity/Shapely#614]
I've upgraded shapely from 1.5.12 to 1.6.4.post2 and there was a breaking change introduced.
Using a Point instance as a dict key is not longer possible.

previously you could do:
```
from shapely.geometry.point import Point
p = Point(1, 2)
d = {p: 123}
```

But now it will raise:
```
TypeError: unhashable type: 'Point'
```

**Comment by snorfalorpagus** [comment]
This was a deliberate change introduced in #320. See the comments therein.

> Shapely's geometries are mutable, but we're providing a hash function. These two features are inconsistent. Rather than remove mutability (for now) we'll remove the hashability.

**Comment by sgillies** [comment]
@snorfalorpagus 👍 on immutability. Would allow us to delete a lot of code, too. It's a rather breaking change, though.

**Comment by sgillies** [comment]
Closing this issue. Immutability should be an issue of its own.
