### ISSUE TITLE
STRTree.query that returns index instead of geometry object

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Shapely#615]
This is not really a bug report or direct feature request, rather a relatively advanced question on the implementation of the STRTree / ctypes. 
(and since I don't know of a good mailing list to ask such questions, opening an issue here. But if that is not appropriate, feel free to close).

---

I am interested in having a STRTree version that returns the index of the geometries instead of the geometry itself when querying the tree. 

Looking at the [implementation of the STRTree](https://github.com/Toblerity/Shapely/blob/master/shapely/strtree.py), I would have thought I could achieve that by using a custom version of it, with the following minimal change (so storing the integer index in the tree instead of the geometry):

```patch
diff --git a/shapely/strtree.py b/shapely/strtree.py
index 121b740..497c7ca 100644
--- a/shapely/strtree.py
+++ b/shapely/strtree.py
@@ -36,8 +36,8 @@ class STRtree:
         self._n_geoms = len(geoms)
         # GEOS STRtree capacity has to be > 1
         self._tree_handle = lgeos.GEOSSTRtree_create(max(2, len(geoms)))
-        for geom in geoms:
-            lgeos.GEOSSTRtree_insert(self._tree_handle, geom._geom, ctypes.py_object(geom))
+        for i, geom in enumerate(geoms):
+            lgeos.GEOSSTRtree_insert(self._tree_handle, geom._geom, ctypes.py_object(i))
 
         # Keep references to geoms.
         self._geoms = list(geoms)
```

This *seems* to work, however sometimes one of the returned integers when querying is a faulty one (big random number that does not fit in the range of number of geoms), and this seems to happen somewhat randomly (not on each run, and for some of the geometries)

Example notebook illustrating it: http://nbviewer.ipython.org/1ed26fda7fd0abf50d152b754f82f5fb

Does somebody have any idea what would be wrong about the above modification of the STRTree code?

**Comment by snorfalorpagus** [comment]
The problem you've hit is related to reference counting and garbage collection. When the reference count for a Python object reaches zero the object can be garbage collected. If you pass a pointer to the object into C and don't increment the reference count there is a risk the object is garbage collected before you dereference the pointer. The solution is either to manually increment the reference count, or in this case we just keep a reference to the geometries in a list (the line below the one you edited).

I can see some value in storing something other than the geometry as the userdata in the tree. Storing the index might look something like this:

```python
self._idxs = list(range(len(geoms)))
for idx, geom in zip(self._idxs, geoms):
    lgeos.GEOSSTRtree_insert(self._tree_handle, geom._geom, ctypes.py_object(idx))
````

A more generic solution might take an iterable of userdata as an argument, e.g.

```python
userdata = range(len(geoms))
tree = STRtree(geoms, userdata)
```

```python
for geom in geoms:
    if userdata:
        datum = next(userdata)
    else:
        datum = geom
    self._userdata.append(datum)
    lgeos.GEOSSTRtree_insert(self._tree_handle, geom._geom, ctypes.py_object(datum))
```

**Comment by jorisvandenbossche** [comment]
@snorfalorpagus ah, yes, thanks a lot for that explanation! Keeping the iterator as an attribute indeed solves the problem.

**Comment by sgillies** [comment]
@jorisvandenbossche I've noted a handy work around in #618.

**Comment by sgillies** [comment]
Closing since we're working on the details for 2.0.
