### ISSUE TITLE
distance of Polygons always 0.0. nearest_points always two identical points.

### ISSUE THREAD

**Issue by paulocheque** [Toblerity/Shapely#628]
## Expected behavior and actual behavior.

`distance` of Polygons always 0.0
`nearest_points` always returns two identical points

## Steps to reproduce the problem.

```
>>> from shapely.ops import nearest_points
>>> from shapely.geometry.polygon import Polygon
>>> triangle = Polygon([(0, 0), (1, 0), (0.5, 1), (0, 0)])
>>> square = Polygon([(0, 2), (1, 2), (1, 3), (0, 3), (0, 2)])
>>> [o.wkt for o in nearest_points(triangle, square)]
['POINT (0.5 1)', 'POINT (0.5 2)']
>>> a = Polygon([(-16.0447, -33.6399), (-21.1562, -33.6399), (-21.1562, -30.325), (-16.0447, -30.325), (-16.0447, -33.6399)])
>>> b = Polygon([(-28.4283, -31.8875), (-20.1377, -25.9855), (-6.99585, -32.6618), (4.73425, -24.0754), (2.02204, -41.6133), (-39.5908, -42.0918), (-37.9966, -23.754), (-28.4283, -31.8875)])
>>> nearest_points(a, b)
(<shapely.geometry.point.Point object at 0x11e182ac8>, <shapely.geometry.point.Point object at 0x11e1985f8>)
>>> [x.wkt for x in nearest_points(a, b)]
['POINT (-16.0447 -33.6399)', 'POINT (-16.0447 -33.6399)']
```

## Operating system

Mac OS X 10.12.3

## Shapely version and provenance

`shapely==1.6.4`

**Comment by paulocheque** [comment]
One polygon contains the other, so I believe this is expected, right?

**Comment by sgillies** [comment]
The triangle and the square do not intersect. Shapely says the distance between them is 1.0 and the distance between their nearest points is also computed to be 1.0. Expectation and observation are the same, as far as I can see. Yes?

Polygons `a` and `b` do intersect. The distance between them is 0.0 and their nearest points are consistent with that distance: the distance between the nearest points is also 0.0. I don't think there is any expectation we can have of what the nearest points would be in this case. 

I don't see any difference between expectation and results here. Can you point out what I might be missing?
