### ISSUE TITLE
ValueError: Prepared geometries cannot be operated on

### ISSUE THREAD

**Issue by atlefren** [Toblerity/Shapely#631]
## Expected behavior and actual behavior.

My script throws a ValueError: Prepared geometries cannot be operated on in a LineString intersects call

This only happens when the following conditions are met:
1. the method performing the intersects  call is called several (100?) times
2. the linestrings used in the intersects call are generated using a random function

## Steps to reproduce the problem.

See https://gist.github.com/atlefren/d106fb2cc470844d9006fd0e4f580950

## Operating system
Windows subsystem Ubuntu 16.04.5 LTS

## Shapely version and provenance
1.6.4.post2 installed from PyPI using pip

**Comment by sgillies** [comment]
The exception comes from https://github.com/Toblerity/Shapely/blob/4433a841d379044bdca0a891f8fe79c6eed4e06d/shapely/topology.py#L19-L20. The exception is misleading in your case. I think that if you filter out the objects that aren't geometries (have no `type`) you can avoid this error.

**Comment by atlefren** [comment]
@sgillies Thanks! That cleared it up somewhat, as I could not understand what prepared geoms had to do with this.

However, if I change the intersetcs call in my sample (line 30), to this:

    intersects = True
    if hasattr(line_so_far, 'type') and hasattr(new_segment, 'type'):
        intersects = line_so_far.intersects(new_segment)i

I still get the error. It's like the type gets erased somehow between my call to intersetcs and the check in topology.py.

Not sure if this is a Shapely bug or my code. Tried replacing the recursive call with a while-loop, then the type is always set. Does Python do something strange with recursion?
