### ISSUE TITLE
New wheel building system based on multibuild

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#636]
I've created https://github.com/sgillies/shapely-wheels to automate building of wheels for linux and macosx. The way it works is that we make a PR to that project that updates the Shapely tag, merge the PR, and it builds wheels that end up in a `frs-wheels` bucket on S3. I would download them from S3 and upload them to PyPI.

Once this is stabilized, we can take next steps:

* Adding AppVeyor configuration to get Windows wheels
* Moving the repo to the Toblerity org?
* More automation

**Comment by sgillies** [comment]
It's working: https://travis-ci.com/sgillies/shapely-wheels/builds/84373725. These jobs are building 1.7a1 (already released) wheels, installing and testing them, and then uploading them to S3.

![untitled](https://user-images.githubusercontent.com/33697/45366600-680ce000-b59c-11e8-845d-fcad1e18d099.png)

**Comment by mikedh** [comment]
This is awesome! Is the build system bundling the shared library (`geos`) by any chance? I think it would be really nice if a `pip install shapely` was the only thing needed, without having to use conda or apt to get `geos`. 

As an aside, a similar thing to `multibuild` I've been using that works pretty well is [cibuildwheel](https://github.com/joerick/cibuildwheel).

**Comment by axelande** [comment]
How is going with the windows wheels?
