### ISSUE TITLE
Shapely wont install on Windows 10 64

### ISSUE THREAD

**Issue by FrancoisMoolman51** [Toblerity/Shapely#637]
To Whom it May Concern:

I am using Window 10 64 with Python 3.7 and Shapely simply won't install on my system with following error code: 

I have notice that Shapely is only availabile from:  https://pypi.org/project/Shapely/

as linux downloads and no windows download version.

Please see screen shot

![screenshot_2](https://user-images.githubusercontent.com/6871602/45487759-91299e00-b75f-11e8-8c23-88236be9d171.png)

**Comment by sgillies** [comment]
Please see https://github.com/Toblerity/Shapely#built-distributions.
