### ISSUE TITLE
Simple bowtie LinearRing has is_valid == True

### ISSUE THREAD

**Issue by lappu** [Toblerity/Shapely#643]
## Expected behavior and actual behavior.

A minimal bowtie `LinearRing` has `is_valid` `True` while it should be `False`

## Steps to reproduce the problem.

```
>>> from shapely.geometry import LinearRing
>>> LinearRing([[2, 0], [1, 1], [2, 1], [0, 0], [2, 0]]).is_valid
True
```

Slightly adjusting the ring makes it `False`, while the topology doesn't really change:

```
>>> LinearRing([[2, 0], [0, 1], [2, 1], [0, 0], [2, 0]]).is_valid
False
```

So does reversing the original vertices:

```
>>> LinearRing(list(reversed([[2, 0], [1, 1], [2, 1], [0, 0], [2, 0]]))).is_valid
False
```

With shapely 1.6.1 and before they all return `False`:

```
>>> LinearRing([[2, 0], [1, 1], [2, 1], [0, 0], [2, 0]]).is_valid
False
>>> LinearRing([[2, 0], [0, 1], [2, 1], [0, 0], [2, 0]]).is_valid
False
>>> LinearRing(list(reversed([[2, 0], [1, 1], [2, 1], [0, 0], [2, 0]]))).is_valid
False
```

Shapely 1.6.1 bundles GEOS 3.5.0, while starting from 1.6.2 the bundled GEOS version is 3.6.2. Is this related?

## Operating system

Ubuntu 18.04, Ubuntu 16.04

## Shapely version and provenance

PyPi: 1.6.4, 1.6.3, 1.6.2 
Python 2.7 & 3.5

**Comment by fieldawarepiotr** [comment]
I am having similar issue.
Distro: Alpine 3.8
Python: 2.7.15
geos (3.7.0) https://git.alpinelinux.org/cgit/aports/plain/testing/geos/APKBUILD

```
In [3]: from shapely import geometry

In [4]: ps
Out[4]: [(0, 0), (0, 4), (2, 4), (-2, 2), (2, 0)]

In [5]: geometry.LinearRing(ps).is_valid
Out[5]: True

```

**Comment by WhatWheatleySaid** [comment]
got the same issue, made a new one before i found this one 

#933

**Comment by sgillies** [comment]
Validity is a property of two dimensional geometries, polygons and multi-polygons. is_valid is always True for points, linestrings, and linear rings. See also https://postgis.net/docs/using_postgis_dbmanagement.html#OGC_Validity.

**Comment by LostFan123** [comment]
This contradicts with the [documentation](https://shapely.readthedocs.io/en/latest/manual.html#object.is_valid):

> object.**is_valid**
> Returns `True` if a feature is “valid” in the sense of [1].
> 
> A valid `LinearRing` may not cross itself or touch itself at a single point...

**Comment by sgillies** [comment]
@LostFan123 we have removed the incorrect information from the docs today: https://github.com/Toblerity/Shapely/commit/e4afcf5d0b497c407ba8a1115e423628cbbfe337.
