### ISSUE TITLE
3D affine_transform return Y=0

### ISSUE THREAD

**Issue by gork-ekb** [Toblerity/Shapely#647]
## Expected behavior and actual behavior.
The documentation from help(affine_transform) seems clear that the 3D version of affine_transform should correctly transform 3D coordinates.
When trying to swap Y and Z coordinates always return Y=0.0
## Steps to reproduce the problem.
`from shapely.geometry import Point`
`from shapely.affinity import affine_transform`
`p = Point(0, 100, 1000)`
`m = [1,0,0, 0,0,1, 0,1,0, 0,0,0]`
`out = affine_transform(p, m)`

`print(out)`
`POINT Z (0 0 100)`

expected result is `POINT Z (0 1000 100)`
## Operating system
Windows 10
## Shapely version and provenance
1. Shapely 1.6.4.post1, python 2.7.12 32 bit
2. Shapely 1.6.4.post1, python 3.7.0 64 bit

**Comment by mwtoews** [comment]
I can confirm this bug with `[ana|mini]conda[23]` for 64-bit versions of Windows 10 and Linux. But I see the expected behaviour with the current master version 1.7a1, or with older versions packaged with (e.g.) Ubuntu's packages, which is reassuring.

Was this bug from either Anaconda or Miniconda? And if so, which channel?

**Comment by sgillies** [comment]
At least, we should get some tests in the master branch to confirm the report by @mwtoews that Shapely behaves as expected.

**Comment by loganbyers** [comment]
I can replicate the report by @mwtoews.
Original bug occurs with `shapely 1.6.4.post2` from PyPI on Linux and `ipython 7.2.0`.
Bug does not occur with `shapely 1.7.1a1`.

Directly copying the code from `affinity.py` (both tested versions) into a new function produces expected result.
