### ISSUE TITLE
Throw error when creating a MultiPoylgon with infinite edges

### ISSUE THREAD

**Issue by asmith26** [Toblerity/Shapely#649]
## Expected behavior and actual behavior.
As per [the doc](http://toblerity.org/shapely/manual.html#MultiPolygon):

>Figure 7. ... on the right, a MultiPolygon that is invalid because its members touch at an infinite number of points (along a line).

Thus shapely should throw an error when creating a MultiPoylgon with infinite edges. (I caught this error when trying to save such a geometry with GeoPandas, and it would always convert the MultiPolygon into a single Polygon.)

## Steps to reproduce the problem.

This test should throw an error: 

```
from shapely.geometry import Polygon, MultiPolygon

polygon1 = Polygon(((0, 0), 
                    (0, 1), 
                    (1, 1),
                    (1, 0),
                    (0, 0)))

polygon2 = Polygon(((1, 0), 
                    (1, 1), 
                    (2, 1),
                    (2, 0),
                    (1, 0)))

multipolygon = MultiPolygon([polygon1, polygon2])
```

## Operating system
Linux/Ubuntu

## Shapely version and provenance
Shapely 1.6.4.post2
Python 3.5

**Comment by sgillies** [comment]
@asmith26 can you give a few more details, such as the provenance of your Shapely package and GEOS library version? Support for Shapely 1.6.4 is very limited as we are working on the 1.7 version now. If you can show that this is an issue in 1.7, we're more likely to get to work on it soon.

**Comment by asmith26** [comment]
Hi @sgillies,

As you can see this is a problem in Shapely 1.7:

![image](https://user-images.githubusercontent.com/6988036/47615737-0a304b00-daab-11e8-9022-a20022e69d81.png)

Not entirely sure how to check my GEOS version, but running the following returns:
```
$ geos-config --version
3.5.0
```

**Comment by asmith26** [comment]
Hi @sgillies,

As you can see this is a problem in Shapely 1.7:

![image](https://user-images.githubusercontent.com/6988036/47615737-0a304b00-daab-11e8-9022-a20022e69d81.png)

Not entirely sure how to check my GEOS version, but running the following returns:
```
$ geos-config --version
3.5.0
```

Hope this helps, and thanks for your help!

**Comment by asmith26** [comment]
Thank @kannes thanks for this information.

Perhaps there could be a configuration option that one could add to the start of their script to e.g. automatically check validity of all geometries created by the script (and perhaps throw an error instead of just saying "False"). (I appreciate such configurations may add unwanted complications, but I thought I would ask in case something similar already exists or if it inspires other suggestions.)

**Comment by sgillies** [comment]
@asmith26 the GEOS library used by Shapely has a global context but that context doesn't give us anything to strictly require valid geometries. We'd need to do this entirely in Python. If you want it to be entirely transparent, so that `Polygon(..)` raises an exception when invalid, I think the thing to do would be to write a Python context manager that patches all the Shapely geometry constructors when `__enter__()` is called and then restores them when `__exit__()` is called. I like writing code like this, but I'm not keen to include it in Shapely. Adding features to the library requires more tests and more documentation and I'm super short on time right now.
