### ISSUE TITLE
Performance tips when transforming larger number of shapes

### ISSUE THREAD

**Issue by kmkolasinski** [Toblerity/Shapely#652]
## Expected behavior and actual behavior.

Hi, I'm working on a geometry project in which I'm will have to operate on a larger number of different shapes. Those operation will usually involve: translation, scaling, homography mapping, custom transforms, filtering etc.  Most of them when implemented in pure numpy can be easily vectorized, however with shapely I have encountered a basic performance issues: a large fraction of time is consumed by shape construction. Additionally, wrapping shapes with `GeometryCollection` introduces another notable delay in the processing, same for conversion from geometry to numpy array (this was actually a surprise for me). 

My question is then: what is the recommended solution for my issue ? 

## Steps to reproduce the problem.

Here is some benchmark I made to check different options, note that this benchmark is tested only for Point class, my expectation for more complex shapes like Polygon is that it will go even worse.

```python
        import time
        from shapely.geometry import Point, MultiPoint, GeometryCollection
        import numpy as np
        import shapely.ops as shapely_ops

        objs = [Point(0.3, i / 10.0) for i in range(100000)]
        print("Point creation:", time.time() - start_time)
        start_time = time.time()

        transform_fn = lambda x, y: (100.0*x*(y - 1), 200*(y - x))
        new_objs = [shapely_ops.transform(transform_fn, o) for o in objs]
        print("Time #1 (points in loop)", time.time() - start_time)
        start_time = time.time()
        coll = GeometryCollection(objs)
        print("Time #2 (collection creation):", time.time() - start_time)
        start_time = time.time()
        new_objs = shapely_ops.transform(transform_fn, coll)
        print("Time #2 (collection transform):", time.time() - start_time)
        start_time = time.time()
        np_objs = np.concatenate([o.coords for o in objs])
        print("Time #3 (convert to numpy):", time.time() - start_time)
        start_time = time.time()
        x, y = transform_fn(*np_objs.T)
        new_objs = np.vstack([x, y]).T
        print("Time #3 (numpy transform):", time.time() - start_time)
        start_time = time.time()
        new_objs = GeometryCollection(MultiPoint(new_objs).geoms)
        print("Time #3 (convert numpy to points):", time.time() - start_time)
        start_time = time.time()
```
Output:
```
Point creation: 0.7066037654876709
Time #1 (points in loop) 3.342881917953491
Time #2 (collection creation): 0.3173365592956543
Time #2 (collection transform): 4.738433837890625
Time #3 (convert to numpy): 1.3321762084960938
Time #3 (numpy transform): 0.013933897018432617
Time #3 (convert numpy to points): 2.368988513946533
```
Numpy is fast as expected, but I don't gain so much since I lose a lot of time on types conversion.

## Operating system

Ubuntu 16.04LTS

## Shapely version and provenance

```
numpy==1.14.3
Shapely==1.6.4.post2 
```

**Comment by sgillies** [comment]
@kmkolasinski I regret that we don't have a support mailing list or forum for this kind of question. The Shapely issue tracker is not really the right place. I'm becoming 👎 on GIS Stack Exchange these days and don't spend much time there.

Basically, the creation of GEOS coordinate sequences by Shapely is slow. I think I've got an issue deep in this tracker about creating a new GEOS C++ class that can read directly from numpy arrays, but haven't acted on it and don't know when I will have the time. I think that's about the only thing that will solve this problem. Until then, we just have to deal with the slowness.

**Comment by kmkolasinski** [comment]
Hi, thanks for the answer, I realized that shapely is good for the case with small number of shapes but when those shapes contain a larger number of points. My requirement  is opposite, small shapes but in a larger number of them. For me the solution for now is to implement a custom library in python and not using shapely.

**Comment by Haitham-Khedr** [comment]
@kmkolasinski How did you fix this performance issue?

**Comment by jorisvandenbossche** [comment]
@Haitham-Khedr in the meantime, the internals of Shapely have been refactored to tackle (among other things) the performance, see https://shapely.readthedocs.io/en/latest/release/2.x.html#version-2-0-0-in-progress
There is currently an alpha release you can test -> https://github.com/shapely/shapely/discussions/1464 (and beta will be out soon)

To take the first example of the code snippet in the top post to illustrate the improvement:

```python
# with the manual for loop
In [11]: %timeit [shapely_ops.transform(transform_fn, o) for o in objs]
5.47 s ± 1.02 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

# using a new vectorized method (the transform function needs a small rewrite 
# to work on a 2D array instead of separate x, y
def transform_fn2(xy):
    x = xy[:, 0]
    y = xy[:, 1]
    xy[:, 0], xy[:, 1] = (100.0*x*(y - 1), 200*(y - x))
    return xy

In [23]: %timeit shapely.transform(objs, transform_fn2)
102 ms ± 3.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
