### ISSUE TITLE
segmentation fault from LineString.interpolate()

### ISSUE THREAD

**Issue by jGaboardi** [Toblerity/Shapely#653]
@snorfalorpagus, here you go:

## Expected behavior and actual behavior.
Should throw a traceback or warning when attempting to interpolate a point along a `LINESTRING EMPTY` object, but instead crashes the kernel.

## Steps to reproduce the problem
  - [gist in notebook](https://gist.github.com/jGaboardi/812a7a46c889a4d25aeb1c78e74563ae) that results in a dead kernel (and see `.png` end of issue report)
  - this code chunk (below) results in a segmentation fault:
```python
# python shapely_interpolate_segmentation_fault.py
import faulthandler
faulthandler.enable()
from shapely.geometry import Point, LineString
test_line = LineString(((0,0), (1,1), (2,1)))
print(test_line)
empty_line = test_line.parallel_offset(10., side='right')
print(empty_line)
empty_line.interpolate(.5, normalized=True)
```

```
$ python shapely_interpolate_segmentation_fault.py
LINESTRING (0 0, 1 1, 2 1)
LINESTRING EMPTY
Fatal Python error: Segmentation fault

Current thread 0x000000010ce7f5c0 (most recent call first):
  File "/Users/user/miniconda3/envs/py3_at1866/lib/python3.6/site-packages/shapely/linref.py", line 22 in __call__
  File "/Users/user/miniconda3/envs/py3_at1866/lib/python3.6/site-packages/shapely/geometry/base.py", line 777 in interpolate
  File "/Users/user/miniconda3/envs/py3_at1866/lib/python3.6/site-packages/shapely/impl.py", line 37 in wrapper
  File "shapely_interpolate_segmentation_fault.py", line 9 in <module>
Segmentation fault: 11
```
## Operating system
  - Mac OS X 10.14

## Shapely version and provenance
  - 1.6b4 installed from `conda`

-----------------------------------

![dead_kernel](https://user-images.githubusercontent.com/8590583/47740305-d5a8c480-dc4d-11e8-8bc3-a15a03f7280c.png)

**Comment by kannes** [comment]
Hm, there is a exceptNull decorator but it does not seem to be used a lot. Might be perfect here?

https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/base.py#L160

https://github.com/Toblerity/Shapely/search?q=exceptnull&unscoped_q=exceptnull

**Comment by snorfalorpagus** [comment]
@kannes I think the `excepNull` decorator is the right thing to use. Do you want to submit a PR?

**Comment by jGaboardi** [comment]
@snorfalorpagus @kannes I can submit the PR. Would it simply be adding the `exceptNull` decorator to `interpolate`?

**Comment by jGaboardi** [comment]
OK. I will try to get it submitted today. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
