### ISSUE TITLE
offset is error, linestring become multilinestring 

### ISSUE THREAD

**Issue by guyanf** [Toblerity/Shapely#656]
## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.

(For example: the area of my geometry is `1.417` when it should be `1.414`.)

## Steps to reproduce the problem.

parallel_offset 
input is linestring, but output is multilinestring.

line = 'LINESTRING(106.53257704 29.59640979,106.53257676 29.59628336,106.53257785 29.59612684,106.53257378 29.59551025,106.53257374 29.59541766)'

offset = 0.0006
parallel_offset(offset, side="left", resolution=16, join_style=1, mitre_limit=1)

output is multilinestring:
MULTILINESTRING((106.533177038529 29.5964084612047,106.533176764627 29.596284784772,106.533177835451 29.5961310182784,106.533177836929 29.5961228795939),(106.533173779145 29.5955081401746,106.533173739944 29.5954174007927))

but if offset = 0.0005  or offset=0.0007, output is linestring,why?

Thanks!

## Operating system
Ubuntu18.04

## Shapely version and provenance
1.6.4.post2  installed from PyPI using pip
(For example, 1.6b4 installed from PyPI using pip)

**Comment by javarouldbou** [comment]
Hi @guyanf 
I am facing the same issue, did you solve it from your side ?

Many thanks in advance
Javar

**Comment by sgillies** [comment]
It's a quirk of the GEOS library's offset algorithm, that's all. There's nothing we can do about it in this project.
