### ISSUE TITLE
contains and within - including boundaries

### ISSUE THREAD

**Issue by floggle** [Toblerity/Shapely#657]
If I create two identical Polygon geometries with bounding boxes of 1,1,2,2 (minx, miny, maxx, maxy), and then do the following, I get Four "trues" printed:

```

	a = shape(geom)
	b = shape(geom)

	print(a.contains(b))
	print(b.contains(a))
	print(a.within(b))
	print(b.within(a))
```
According to the docs and what I'd expect, these should all be False. The bounds intersect in all cases.

The docs clearly state for contains `and their boundaries do not touch at all.`
and for within `intersect only with the interior of the other (not its boundary or exterior).`

**Comment by floggle** [comment]
@sgillies - Thanks for the reply. here's the link - http://toblerity.org/shapely/manual.html - although I see now at the top of the page it's only for 1.2 and 1.3. That's the top result for "shapely manual" googling on two different engines (google-based and bing-based). Looking for it, I can see your linked version as number ~6 or so in the results.

But looking at your quote, maybe my spatialness is a bit rusty, but:
`at least one point of the interior of other lies in the interior of object.` - surely that's false for this situation?

In the 1.6 docs, the "within" docs say:
"Returns True if the object’s boundary and interior intersect only with the interior of the other (not its boundary or exterior)." - so appears to still be incorrect.

I can see from the linked PostGIS docs that they explicitly state this nuance (although even theirs could be clearer) and then have a ST_ContainsProperly function which does what you'd expect and would provide a False for this one. So this is a docs issue.

**Comment by dr-jts** [comment]
For a detailed explanation of the subtleties of OGC Contains, see [Quirks of the "Contains" Spatial Predicate](http://lin-ear-th-inking.blogspot.com/2007/06/subtleties-of-ogc-covers-spatial.html).

Shapely is behaving correctly for the example in this issue.  The "quirk" only shows up when evaluating LineStrings against Polygons.
