### ISSUE TITLE
Additional information for vertices

### ISSUE THREAD

**Issue by AndreasAZiegler** [Toblerity/Shapely#664]
The issue I would like to report is rather a question than an actual issue.

I'm wondering if it would be possible to add some additional information to vertices as e.g. in https://doc.cgal.org/latest/Triangulation_3/classCGAL_1_1Triangulation__vertex__base__with__info__3.html

I need this for a project I'm currently working on where I have to keep track of the polygon vertices of two polygons before a polygon union and the unified polygon after the union. I basically want to know, which point from which of the two polygons ends up in the unified polygon and perhaps which additional points were inserted into the unified polygon.

**Comment by sgillies** [comment]
No, this won't be possible. Shapely uses the GEOS library and I'm not aware that it's extendable in such a way. I think the best option would be to map vertices to attributes in a different data structure.
