### ISSUE TITLE
Buffer crashes: ValueError: No Shapely geometry can be created from null value

### ISSUE THREAD

**Issue by RuiR** [Toblerity/Shapely#665]
## Expected behavior and actual behavior.

I encountered **"ValueError: No Shapely geometry can be created from null value"** when I tried to get the buffer area of a sequence of locations (represented as pair of [grid_x, grid_y]). 

## Steps to reproduce the problem.

(For example, a script with required data)
Here is the link of test input.
[test.csv](https://github.com/RuiR/Leetcode/blob/master/test.csv)
And error happens after running the following script.
`df = pd.read_csv("test.csv")
grid_path = df.loc[:, ['grid_x','grid_y']].values.tolist()
path = LineString(grid_path)
print("path is valid?", path.is_valid)
buffer_path = path.buffer(2, cap_style=1)`

## Operating system

Mac OS X 10.13.6 

## Shapely version and provenance

I used 1.6.4. post 2 from PyPI using pip

Thank you for any help!

**Comment by jGaboardi** [comment]
Many of your coordinates are duplicates, which seems to lead to issue. When duplicates are removed, the issues resolves itself ([see my gist here](https://gist.github.com/jGaboardi/fb2fadbc352be7bc7bd621c2f9d1f8bc)).

**Comment by RuiR** [comment]
> Many of your coordinates are duplicates, which seems to lead to issue. When duplicates are removed, the issues resolves itself ([see my gist here](https://gist.github.com/jGaboardi/fb2fadbc352be7bc7bd621c2f9d1f8bc)).

Hi, James. Thanks a lot for your help. Do you think there is some way to solve the problem without moving duplicates? Because these index pairs are part of a trace. I've removed the consecutive duplicates in this test case, but I think it can not be treated as a trace if we remove overall duplicates.

**Comment by jGaboardi** [comment]
@RuiR I do not think this is valid behavior for `shapely`, though I may be totally wrong. However, what if you treat each path node pair as an individual segment then buffer each path segment? I will update [my gist](https://gist.github.com/jGaboardi/fb2fadbc352be7bc7bd621c2f9d1f8bc) to demonstrate.

**Comment by sgillies** [comment]
I'm happy to see that there is not an actual crashing bug here: you can recover from an exception, but not from a true crash.

@jGaboardi thanks for your help! Nodes that are very close to each other, closer than our computers' precision, are a problem for some of the algorithms in GEOS. Simplifying geometries has helped in some cases.

@RuiR I'm happy to look into this and even to take it upstream to GEOS if needed, but I need a less complicated example to see if I can reproduce the problem. Can you paste here a representation (WKT, for example) of a geometry that can't be buffered?

**Comment by RuiR** [comment]
Thank you both @jGaboardi @sgillies. I think @jGaboardi  's suggestion is a great solution if we couldn't solve it directly. And the following is the LineString generated from the csv file. I'm not sure if it's the representation you need @sgillies . Please tell me if you need other representation. Thanks a lot!
LINESTRING (143 113, 150 113, 146 113, 139 117, 131 135, 113 139, 103 130, 99 129, 88 134, 78 139, 83 146, 86 138, 92 128, 87 121, 83 116, 87 118, 85 121, 87 121, 91 121, 98 121, 101 121, 101 121, 101 121, 100 121, 99 121, 90 116, 83 119, 88 121, 88 119, 88 109, 88 117, 94 123, 94 123, 96 123, 101 121, 101 121, 100 121, 100 121, 98 122, 89 116, 77 119, 67 115, 61 104, 61 94, 62 81, 65 68, 74 65, 80 53, 75 39, 64 35, 70 44, 74 61, 83 80, 80 91, 79 101, 84 112, 93 117, 99 121, 100 122, 101 121, 101 121, 100 120, 93 118, 77 119, 76 123, 86 121, 97 121, 98 121, 99 121, 106 128, 119 129, 119 128, 106 103, 89 99, 83 108, 84 110, 83 110, 84 110, 83 110, 83 110, 83 110, 83 110, 75 94, 65 91, 75 94, 80 104, 77 117, 85 115, 85 115, 85 115, 83 123, 76 131, 81 123, 85 115, 85 115, 85 115, 98 111, 110 111, 127 104, 134 101, 142 99, 147 111, 146 113, 139 117, 128 136, 111 139, 104 131, 96 123, 90 117, 89 121, 88 116, 84 121, 85 121, 88 121, 90 117, 89 116, 87 119, 97 121, 101 121, 101 121, 100 120, 96 115, 93 105, 86 96, 84 94, 82 90, 81 87, 81 87, 81 87, 81 87, 81 87, 81 87, 81 87, 81 88, 79 94, 81 105, 85 114, 93 118, 100 122, 101 121, 101 121, 100 120, 101 122, 101 121, 101 121, 100 120, 97 122, 85 115, 83 111, 78 97, 79 101, 83 111, 90 115, 104 111, 113 111, 117 109, 111 112, 100 118, 101 121, 100 120, 99 121, 92 128, 81 133, 83 123, 87 122, 90 122, 99 121, 101 121, 96 120, 89 116, 84 116, 85 115, 85 115, 85 115, 85 115, 85 115, 85 115, 85 115, 85 115, 83 119, 81 136, 76 151, 73 140, 82 119, 85 121, 96 111, 99 96, 88 72, 89 53, 86 72, 80 91, 82 107, 84 112, 73 124, 61 131, 66 126, 72 124, 74 125, 94 129, 103 135, 118 149, 133 152, 143 114, 141 115, 130 135, 112 139, 103 131, 101 128, 101 128, 101 128, 101 128, 104 120, 105 112, 103 114, 91 118, 91 116, 88 121, 97 119, 99 120, 101 121, 100 121, 100 120, 100 120, 98 122, 88 123, 85 128, 87 123, 88 121, 95 120, 99 121, 101 121, 101 121, 100 120, 100 120, 99 128, 100 137, 100 135, 103 124, 101 120, 101 120, 96 120, 88 124, 85 123, 85 123, 86 123, 86 123, 84 123, 80 133, 80 137, 87 133, 98 129, 101 123, 91 122, 96 123, 101 121, 101 121, 101 120, 103 127, 113 129, 120 129, 115 132, 107 134, 87 132, 80 138, 83 123, 87 122, 84 121, 80 140, 79 134, 82 119, 82 119, 82 119, 85 119, 83 116, 85 104, 87 89, 84 75, 80 67, 81 88, 82 97, 92 113, 101 121, 100 120, 99 121, 54 116, 51 116, 48 112, 56 112, 70 118, 82 116, 94 118, 99 120, 86 115, 84 116, 95 120, 97 121, 85 115, 93 114, 101 110, 99 118, 89 124, 84 128, 87 119, 150 113, 144 111, 138 123, 119 139, 108 135, 96 124, 90 117, 81 114, 78 118, 88 116, 87 119, 87 120, 92 114, 93 106, 94 96, 89 99, 94 111, 99 118, 101 121, 101 121, 101 121, 101 121, 100 120, 93 117, 87 118, 91 121, 97 121, 101 121, 101 121, 100 120, 96 120, 88 116, 76 120, 74 116, 75 106, 71 117, 82 116, 85 115, 86 115, 88 110, 92 105, 97 102, 98 102, 103 100, 103 101, 98 102, 96 111, 93 113, 95 117, 86 123, 81 124, 76 124, 70 125, 79 124, 85 123, 85 123, 85 123, 84 123, 81 138, 80 153, 81 160, 82 162, 84 144, 88 131, 87 142, 96 150, 107 153, 113 150, 119 129, 103 127, 91 122, 84 123, 77 115, 83 111, 87 124, 88 122, 87 119, 85 115, 85 115, 87 115, 93 125, 92 124, 85 115, 85 115, 88 114, 98 120, 98 118, 87 124, 73 142, 72 153, 45 147, 73 151, 81 127, 88 116, 84 112, 74 118, 53 116, 46 111, 59 112, 51 119, 51 143, 75 155, 118 145, 143 113, 141 115, 140 116, 130 135, 112 139, 102 129, 101 128, 101 128, 96 123, 90 122, 85 121, 85 121, 87 120, 95 119, 96 116, 88 116, 89 121, 98 121, 101 121, 101 121, 101 121, 100 121, 98 122, 95 131, 93 139, 90 138, 86 137, 86 137, 86 137, 86 137, 84 143, 87 134, 98 129, 101 121, 100 121, 100 120, 100 120, 97 124, 89 130, 79 139, 77 146, 81 137, 89 130, 103 125, 101 121, 101 121, 101 121, 101 120, 98 122, 92 128, 80 132, 69 127, 64 128, 58 135, 57 134, 62 129, 67 125, 76 124, 84 123, 95 119, 97 121, 87 120, 87 123, 85 123, 93 125, 93 126, 94 124, 87 117, 90 121, 87 122, 87 119, 85 115, 85 115, 85 115, 85 115, 83 115, 82 127, 84 125, 88 118, 85 115, 85 115, 92 113, 102 117, 101 120, 95 127, 84 129, 70 131, 77 129, 83 120, 80 124, 67 124, 53 116, 46 113, 65 114, 81 116, 91 117, 105 128, 123 126, 126 119, 112 129, 92 128, 87 115, 88 115, 100 111, 99 118, 86 115, 85 115, 93 117, 83 116, 85 115, 85 115, 85 115, 92 116, 99 120, 97 111, 96 109, 88 116, 81 121, 91 114, 105 112, 106 123, 91 116, 78 118, 87 121, 147 110, 144 114, 129 121, 123 127, 107 129, 91 128, 82 124, 82 119, 83 116, 79 118, 82 116, 82 116, 83 116, 87 119, 88 121, 90 116, 89 115, 94 108, 94 107, 97 98, 94 78, 75 64, 16 42, 1 39, 13 41, 67 60, 84 76, 83 79, 83 79, 80 89, 79 101, 82 107, 87 114, 95 116, 89 123, 89 123, 89 123, 88 123, 93 122, 102 115, 110 112, 100 118, 105 112, 107 107, 103 110, 97 111, 88 118, 89 123, 88 123, 87 123, 84 128, 84 124, 85 123, 85 123, 86 123, 83 126, 80 155, 81 145, 86 137, 97 140, 90 136, 92 128, 93 126, 93 126, 93 126, 93 126, 93 126, 92 128, 80 131, 69 129, 74 127, 82 123, 85 123, 75 140, 72 153, 58 154, 72 154, 74 138, 83 123, 88 122, 87 122, 93 125, 90 121, 85 115, 85 115, 85 115, 85 115, 85 115, 75 120, 76 124, 87 121, 95 127, 105 136, 104 141, 96 131, 88 121, 86 123, 82 119, 82 119, 83 120, 81 129, 76 130, 81 121, 84 117, 91 122, 92 116, 85 115, 83 119, 82 128, 71 136, 71 136, 72 130, 79 123, 85 115, 85 115, 83 123, 74 141, 79 154, 67 170, 45 188, 35 193, 52 188, 107 198, 147 111, 140 116, 131 130, 119 130, 103 127, 101 122, 101 121, 101 121, 101 121, 101 121, 100 121, 101 121, 101 121, 101 121, 101 121, 101 121, 100 120, 101 121, 100 120, 101 120, 101 120, 100 120, 100 120, 99 121, 102 132, 101 139, 104 141, 104 141, 103 139, 96 131, 96 128, 97 122, 97 122, 98 121, 97 116, 96 116, 95 114, 91 102, 87 88, 83 79, 77 65, 71 65, 68 61, 56 58, 48 48, 97 122, 7 40, 49 55, 67 59, 75 64, 84 75, 81 87, 81 87, 80 94, 80 102, 81 105, 82 107, 83 108, 88 114, 95 119, 100 123, 101 120, 98 123, 97 126, 101 121, 101 121, 100 120, 100 120, 99 115, 97 107, 95 110, 96 107, 96 111, 96 115, 100 120, 101 121, 101 120, 96 121, 81 116, 73 121, 73 121, 73 124, 82 123, 86 126, 84 128, 84 128, 84 128, 84 128, 89 127, 101 121, 103 127, 115 128, 146 112, 145 114, 136 132, 121 128, 103 127, 100 120, 100 120, 101 120, 101 121, 101 120, 101 120, 101 120, 100 120, 101 120, 101 120, 101 120, 101 120, 100 120, 100 121, 101 120, 100 120, 100 120, 98 122, 97 132, 96 139, 104 140, 104 141, 104 141, 108 140, 109 136, 106 133, 102 129, 104 130, 104 128, 99 122, 91 116, 77 119, 71 119, 60 114, 51 116, 50 116, 56 115, 62 117, 69 124, 77 123, 86 123, 88 121, 88 118, 76 120, 78 123, 86 123, 91 121, 101 121, 100 120, 99 118, 110 113, 126 104, 138 99, 148 94, 162 84, 154 82, 146 93, 150 114, 134 123, 124 122, 123 127, 113 129, 103 127, 101 121, 101 121, 100 120, 100 120, 99 121, 89 116, 77 119, 71 119, 68 117, 81 116, 85 115, 85 115, 88 118, 87 125, 85 124, 81 135, 77 144, 88 145, 110 154, 145 114, 137 127, 129 129, 109 130, 103 125, 101 121, 101 120, 101 121, 101 121, 101 121, 101 121, 101 121, 100 121, 101 121, 101 121, 101 120, 101 121, 101 121, 101 121, 101 120, 100 120, 96 127, 91 129, 80 132, 71 134, 73 132, 75 132, 75 132, 77 128, 82 128, 99 129, 119 129, 120 129, 120 129, 118 127, 132 130, 144 141, 164 151, 167 152, 177 152, 164 151, 149 146, 136 132, 126 128, 119 129, 120 129, 114 132, 110 134, 118 130, 117 138, 102 167, 104 197, 108 208, 102 174, 106 151, 103 140, 104 140, 98 134, 99 126, 101 121, 100 120, 98 129, 99 127, 100 122, 101 121, 101 121, 98 123, 96 127, 95 124, 100 123, 99 121, 88 115, 86 108, 81 103, 83 111, 92 116, 97 121, 101 121, 101 121, 100 120, 96 120, 85 115, 83 122, 146 113, 141 116, 133 131, 116 128, 103 124, 101 120, 101 120, 101 120, 101 120, 100 120, 101 120, 100 120, 100 120, 100 120, 100 120, 100 120, 95 120, 88 124, 93 123, 93 123, 96 123, 101 121, 101 121, 101 121, 101 121, 100 121, 101 121, 100 120, 100 120, 103 114, 106 109, 103 109, 100 118, 101 121, 101 121, 100 120, 93 118, 82 116, 85 115, 85 115, 85 115, 85 115, 85 115, 85 115, 96 111, 104 111, 117 112, 128 113, 124 124, 119 129, 114 136, 120 129, 119 130, 109 129, 102 127, 90 121, 88 117, 84 117, 87 120, 89 115, 96 119, 101 120, 98 123, 92 126, 98 125, 101 121, 101 120, 100 120, 105 130, 103 125, 103 125, 101 123, 101 121, 101 121, 101 121, 101 121, 100 120, 87 127, 82 128, 76 125, 78 126, 86 122, 91 121, 100 122, 101 121, 100 120, 100 120, 104 131, 147 111, 139 117, 127 128, 109 130, 100 122, 101 121, 101 120, 101 121, 101 121, 101 121, 100 121, 100 121, 100 120, 100 121, 100 120, 100 121, 100 120, 100 120, 100 120, 100 120, 102 125, 94 118, 84 123, 72 124, 81 124, 86 123, 86 123, 86 123, 86 123, 92 124, 106 128, 117 129, 115 128, 107 129, 103 127, 100 122, 90 123, 80 129, 75 125, 79 124, 87 120, 96 119, 101 121, 101 121, 100 120, 91 121, 82 123, 86 122, 94 118, 100 122, 101 120, 100 120, 96 120, 88 121, 95 119, 98 120, 85 116, 86 115, 94 116, 94 118, 95 119, 101 121, 101 120, 100 120, 99 117, 101 109, 97 108, 96 110, 94 114, 100 120, 101 121, 101 121, 101 120, 100 120, 96 111, 99 96, 95 78, 84 64, 141 106, 140 115, 132 134, 113 139, 102 130, 101 121, 101 121, 101 121, 101 121, 101 121, 101 120, 101 120, 93 118, 88 118, 90 121, 99 121, 100 121, 97 124, 92 128, 84 127, 85 121, 93 126, 99 135, 100 127, 99 119, 97 111, 98 97, 99 83, 86 70, 91 64, 82 82, 81 87, 80 92, 83 99, 88 108, 89 116, 88 117, 90 123, 80 129, 70 127, 68 132, 76 131, 79 124, 79 124, 79 124, 82 127, 97 129, 111 129, 126 128, 126 128, 111 129, 103 125, 103 125, 100 122, 101 121, 101 121, 101 121, 100 120, 99 128, 100 136, 105 143, 109 147, 111 139, 106 139, 95 140, 97 135, 101 137, 106 143, 103 134, 102 124, 101 121, 101 121, 101 121, 101 121, 101 121, 100 120, 95 127, 93 126, 100 123, 101 121, 100 120, 100 120, 91 116, 87 120, 92 127, 112 129, 123 126, 120 129, 111 134, 101 129, 97 121, 89 116, 94 114, 87 111, 87 119, 89 121, 89 121, 94 112, 88 110, 90 114, 98 117, 101 120, 101 121, 101 121, 101 121, 101 121, 100 120, 96 123, 95 122, 95 122, 102 127, 108 124, 108 127, 107 124, 100 122, 101 121, 101 120, 100 120, 100 120, 90 122, 86 123, 85 122, 91 121, 97 121, 101 121, 101 121, 100 120, 100 120, 102 116, 106 109, 110 104, 112 102, 106 109, 101 119, 101 121, 100 121, 101 121, 101 120, 100 120, 99 121, 88 124, 84 126, 84 123, 88 117, 81 105, 82 106, 82 107, 83 110, 76 120, 75 125, 78 126, 85 122, 95 119, 101 121, 101 121, 100 121, 97 122, 89 116, 88 110, 84 105, 76 96, 78 97, 83 108, 87 114, 87 111, 87 120, 93 125, 91 128, 101 121, 101 120, 100 120, 100 120, 95 128, 83 130, 74 141, 73 148, 74 149, 70 156, 68 157, 66 157, 77 161, 78 159, 75 163, 144 114, 141 115, 137 129, 116 139, 104 132, 101 128, 101 128, 101 128, 95 124, 87 121, 83 122, 82 123, 85 120, 88 121, 88 121, 88 121, 88 121, 88 121, 89 121, 88 121, 88 121, 88 121, 92 122, 102 125, 101 121, 100 121, 100 120, 100 120, 96 111, 94 100, 100 84, 94 72, 110 65, 104 83, 99 90, 88 110, 89 116, 97 121, 101 120, 97 121, 83 116, 75 119, 62 115, 51 109, 63 108, 71 118, 71 118, 72 118, 76 122, 82 126, 85 123, 86 123, 87 125, 84 127, 85 123, 86 123, 86 122, 93 112, 102 110, 105 108, 106 103, 102 102, 101 102, 97 108, 92 113, 100 120, 101 121, 101 121, 100 120, 97 124, 90 130, 79 139, 76 148, 78 145, 87 141, 87 134, 96 123, 101 121, 101 121, 101 120, 100 120, 100 120, 99 128, 103 134, 105 138, 103 125, 105 116, 110 113, 144 113, 141 114, 138 126, 116 139, 103 131, 97 124, 93 122, 89 116, 89 116, 88 116, 83 122, 79 138, 80 141, 86 134, 91 122, 90 121, 90 121, 90 122, 90 121, 91 121, 94 118, 87 122, 87 121, 87 122, 87 120, 87 121, 87 121, 94 118, 96 119, 100 125, 110 130, 111 139, 104 140, 104 150, 103 142, 104 141, 101 135, 91 144, 89 138, 94 135, 95 129, 95 133, 94 135, 94 135, 91 127, 88 120, 90 121, 99 121, 101 121, 100 121, 100 120, 90 123, 81 129, 78 127, 79 124, 82 123, 83 130, 95 128, 99 135, 105 139, 104 141, 104 141, 104 141, 104 140, 104 140, 104 140, 103 137, 100 128, 96 123, 88 120, 94 123, 117 139, 107 134, 98 125, 91 122, 86 121, 93 126, 98 128, 103 133, 110 145, 108 141, 104 132, 102 129, 112 140, 113 141, 103 131, 84 130, 82 131, 92 128, 100 122, 101 121, 101 121, 101 120, 101 120, 101 120, 100 120, 100 120, 90 122, 84 129, 85 123, 86 123, 86 123, 88 116, 87 107, 88 95, 86 84, 81 68, 34 45, 0 39, 11 41, 67 60, 83 60, 83 60, 83 60, 83 60, 83 60, 83 60, 83 60, 83 60, 83 60, 86 67, 94 73, 99 78, 99 90, 94 104, 94 114, 99 121, 101 121, 101 121, 100 120, 91 121, 84 123, 74 124, 74 124, 79 125, 82 123, 85 123, 87 123, 87 120, 90 114, 96 116, 97 119, 98 120, 101 122, 101 121, 101 121, 101 121, 100 120, 97 122, 88 124, 86 122, 92 123, 93 128, 98 129, 115 128, 121 127, 115 128, 92 128, 92 128, 92 128, 88 121, 84 115, 93 105, 108 103, 109 106, 93 113, 84 123, 97 129, 100 120, 100 120, 100 120, 100 120, 100 120, 101 120, 101 120, 101 120, 100 120, 100 120, 100 125, 111 138, 122 155, 117 148, 104 131, 101 120, 101 120, 100 120, 101 120, 101 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 89 116, 88 109, 88 96, 84 79, 72 66, 11 41, 1 39, 29 44, 41 45, 50 51, 86 67, 81 88, 80 93, 80 92, 79 101, 81 112, 82 119, 89 116, 96 120, 99 120, 93 119, 86 123, 90 121, 94 119, 101 121, 101 120, 100 120, 91 121, 89 122, 93 126, 88 121, 82 116, 80 116, 81 120, 83 129, 93 126, 93 126, 93 126, 96 123, 101 121, 94 126, 94 126, 96 123, 101 121, 95 127, 90 136, 87 132, 93 126, 93 126, 93 125, 93 112, 90 108, 85 115, 85 115, 83 121, 85 122, 90 122, 88 122, 107 128, 115 128, 140 134, 146 145, 140 147, 143 143, 131 139, 118 148, 79 155, 60 152, 73 151, 79 132, 92 128, 93 126, 101 121, 105 111, 119 95, 136 66, 159 34, 156 38, 136 69, 119 95, 108 106, 100 118, 101 120, 100 120, 100 120, 101 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 101 121, 101 120, 101 120, 100 120, 100 120, 87 116, 72 122, 79 123, 79 123, 88 121, 87 119, 72 120, 78 118, 88 116, 88 121, 90 117, 71 119, 85 115, 95 124, 101 121, 100 120, 100 120, 100 120, 100 120, 97 111, 89 98, 87 100, 89 115, 93 125, 101 121, 102 118, 99 121, 102 132, 103 143, 105 147, 99 135, 102 129, 101 123, 101 123, 99 119, 94 109, 88 117, 93 125, 100 122, 101 121, 99 121, 106 133, 113 133, 108 129, 100 122, 101 121, 100 120, 100 120, 89 116, 77 119, 72 121, 79 124, 86 123, 85 122, 88 115, 85 103, 88 93, 84 76, 53 59, 0 39, 86 123, 2 39, 57 33, 150 112, 146 112, 139 121, 123 128, 105 128, 100 120, 100 120, 101 120, 101 121, 101 120, 101 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 94 119, 81 122, 86 123, 86 123, 83 123, 72 122, 79 123, 79 124, 82 123, 95 124, 101 121, 101 121, 101 121, 101 121, 101 120, 101 120, 101 120, 97 122, 93 121, 91 116, 88 108, 83 107, 78 96, 81 86, 81 85, 84 76, 90 59, 92 46, 91 31, 93 35, 94 42, 89 56, 83 78, 81 87, 84 94, 94 96, 96 110, 94 114, 100 118, 100 122, 101 121, 99 121, 89 116, 86 119, 88 121, 95 119, 98 121, 99 121, 101 121, 101 120, 100 120, 95 127, 87 134, 79 157, 67 164, 60 160, 78 163, 78 157, 87 144, 91 142, 89 138, 92 128, 101 122, 101 121, 101 121, 100 120, 98 122, 95 130, 98 136, 106 128, 119 129, 120 122, 146 111, 146 113, 138 125, 121 128, 103 127, 101 123, 101 123, 101 123, 101 120, 100 120, 101 120, 100 120, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 100 115, 99 124, 106 128, 119 129, 116 128, 115 128, 115 128, 108 129, 103 125, 101 121, 101 121, 101 121, 101 121, 100 121, 100 120, 100 120, 99 121, 99 128, 100 137, 105 149, 101 182, 102 194, 103 198, 107 190, 127 167, 123 159, 122 152, 111 140, 102 129, 101 123, 91 116, 86 115, 76 120, 75 124, 82 123, 89 121, 89 116, 94 111, 88 110, 93 113, 96 114, 102 117, 98 115, 87 116, 72 121, 69 125, 75 123, 79 123, 79 123, 85 122, 92 123, 96 129, 100 124, 100 121, 99 121, 88 116, 76 120, 74 115, 72 116, 100 120, 98 122, 95 129, 95 129, 109 130, 121 126, 123 121, 146 111, 138 122, 123 127, 103 126, 100 120, 100 120, 100 120, 101 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 127, 111 138, 122 152, 119 150, 110 137, 101 128, 103 125, 103 125, 101 121, 100 121, 101 121, 101 121, 101 121, 101 121, 101 120, 100 120, 100 120, 100 120, 97 122, 91 118, 100 123, 101 120, 101 120, 101 120, 101 120, 98 122, 96 126, 87 133, 83 140, 86 137, 86 137, 86 137, 89 137, 103 133, 104 140, 104 141, 101 135, 103 125, 101 121, 100 120, 95 129, 83 136, 83 152, 89 170, 81 167, 80 151, 90 142, 90 142, 91 140, 87 135, 103 125, 101 121, 100 120, 97 124, 96 134, 97 135, 100 125, 102 117, 111 112, 122 103, 118 108, 108 113, 101 119, 100 122, 101 121, 101 120, 99 122, 87 121, 83 120, 81 121, 85 123, 86 123, 86 123, 86 123, 87 121, 97 121, 99 121, 100 120, 103 125, 139 117, 133 122, 119 128, 103 126, 101 120, 101 120, 101 121, 101 120, 101 121, 100 120, 100 120, 101 128, 112 136, 101 123, 101 120, 101 120, 101 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 100 120, 98 123, 90 130, 76 140, 72 153, 52 144, 50 149, 76 151, 85 144, 86 143, 86 143, 86 138, 86 137, 86 137, 86 137, 86 137, 86 137, 86 134, 92 124, 98 120, 98 122, 97 122, 98 118, 98 109, 97 108, 96 110, 93 113, 99 117, 97 121, 95 129, 94 126, 93 126, 93 126, 94 125, 90 116, 78 118, 72 121, 80 124, 85 123, 86 123, 83 121, 78 123, 70 126, 69 132, 69 132, 72 132, 75 128, 78 127, 87 130, 94 121, 100 122, 101 120, 98 122, 93 128, 82 132, 79 133, 83 123, 86 123, 81 135, 80 152, 78 160, 77 159, 80 140, 81 127, 86 123, 85 123, 86 123, 83 122, 82 136, 95 137, 96 132, 91 122, 85 121, 88 121, 147 111, 140 116, 124 123, 107 128, 100 120, 101 120, 100 120, 100 120, 100 120, 100 120, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 122, 97 117, 87 119, 93 123, 94 123, 101 123, 101 121, 101 121, 101 121, 101 121, 101 121, 101 121, 100 120, 100 120, 97 123, 94 129, 87 137, 86 137, 86 137, 86 137, 86 137, 85 137, 94 135, 97 135, 100 125, 101 121, 100 120, 93 119, 84 123, 78 128, 73 134, 67 132, 71 132, 77 129, 85 130, 107 129, 122 128, 121 128, 115 128, 114 128, 116 131, 120 129, 120 129, 120 129, 120 129, 120 129, 123 127, 126 119, 119 129, 120 129, 120 129, 120 129, 117 142, 101 155, 91 154, 76 155, 50 141, 43 141, 49 151, 51 144, 51 143, 51 144, 51 144, 52 150, 63 143, 61 132, 67 125, 77 124, 85 123, 86 123, 86 123, 87 119, 91 113)

**Comment by jGaboardi** [comment]
@RuiR @sgillies Although not a solution to the actual issue, with a bit less or a bit more buffer the operation runs successfully on the full `LineString` ([trace_buffer.ipynb gist](https://gist.github.com/jGaboardi/6b36188c7d5346f83bea07ec812005f7)).

**Comment by jGaboardi** [comment]
Also buffer of `1` throws the following exception:
```
TopologyException: assigned depths do not match at 101.347427 119.06324000000001
```

**Comment by RuiR** [comment]
@jGaboardi Yep. I tried that before. That works for some examples but may fail sometimes. Actually, I also remove some points before I posted this issue, that help some examples go through the operation, but some still fail (like the example I posted here). Don't quite understand the TopologyException.

**Comment by RuiR** [comment]
As @jGaboardi suggested, I buffered each segment path and dissolve all buffer using cascaded_union imported from shapely.ops. This works fine and runs quickly. 

But the result is not the same with the previous method (buffering the long LineString of the whole path). I'm curious about the process of buffering the whole path.
