### ISSUE TITLE
Plotly only works for shapes on x-y plane even though they have z-coord

### ISSUE THREAD

**Issue by connorferster** [Toblerity/Shapely#671]
I am making polygons on planes other than the x-y plane and have noticed that Shapely does not seem to support these polygons at all.

![image](https://user-images.githubusercontent.com/38441489/51350621-7cd31600-1a5d-11e9-9e56-13faa1437246.png)

The rectangle is drawn on the y-z plane but Shapely interprets it as a line constructed with a Polygon constructor, it seems. It has 0 Area and is shown from the x-y plane in the graphical repr().

Will Shapely be supporting geometry in arbitrary orientations within 3-space?

Shapely installed on Python 3.6 via Pypi (Ubuntu 18.04LTS) - Shapely v. 1.6.4.post 2

**Comment by mwtoews** [comment]
See https://shapely.readthedocs.io/en/stable/manual.html#geometric-objects
> Shapely is a planar geometry library and z, the height above or below the plane, is ignored in geometric analysis

Shapely may store the `z` data, but processing of things like area and length are only done with the 2D data (on the x-y plane only), thus this type of library is called "2.5D".

If you really need to have the 3D operators, you either need to apply these calculations outside of shapely using the 3D coordinate data, or perhaps use a 3D library like CGAL.
