### ISSUE TITLE
Bounds does not provide Z dimension bounds.

### ISSUE THREAD

**Issue by akadouri** [Toblerity/Shapely#677]
## Expected behavior and actual behavior.

Bounds provides only min/max in the X and Y dimension. For a 3D point, I expected it to provide a min/max in X,Y and Z. 

I believe [coords.py](https://github.com/Toblerity/Shapely/blob/master/shapely/coords.py#L164) could be updated to check for existence of Z values and return the bounds for that coordinate as well. I would be happy to submit a PR if this is indeed functionality that should be updated.

## Steps to reproduce the problem.

```
>>> from shapely.geometry import Point
>>> p = Point(1,2,3)
>>> p.bounds
(1.0, 2.0, 1.0, 2.0)
```

## Operating system

Mac OSX 10.14.3

## Shapely version and provenance

1.6.4.post2

**Comment by sgillies** [comment]
@akadouri Shapely is not a 3D geometry package. None of the operations or predicates analyze the Z dimension. I don't think that 3D bounds will be worth pursuing.

**Comment by akadouri** [comment]
That makes sense. Thank you for the response.
