### ISSUE TITLE
contains() gives mixed results for adjacent test points in Polygon

### ISSUE THREAD

**Issue by wbbroyles** [Toblerity/Shapely#681]
## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.

I am doing a loop over the Polygons in the "urban areas" shapefile collection cb_2017_us_ua10_500k at catalog.data.gov, using contains() to determine if a point is/is not in each shape.  For my test points, I expect to have the New York--Newark urban areas (number 3094 in the collection) identified as containing the test point(s).  But for two of my three adjacent test points, the contains() test fails.  Even if I don't do the loop and focus just on shpe 3094, of my three test points (Freedom Tower, friend's apartment, Crisler Bldg) only the Freedom Tower returns True.  Plotting it is even more confusing because all three adjacent points are drawn inside the Polygon in question.

Other test points from across the US work fine, but because the NYC result is important to my project, I need to figure out why that test is giving unexpected results.  Using the example code to loop through shapes and use the contains() function, plus example code to plot the shape and the points in question, show that the result should be True for all three.  Why are two of them returning False?

## Steps to reproduce the problem.

fred = Point(-73.99709779999999, 40.7359057) #returns False
crisler = Point(-73.975311, 40.751652) #returns False
freedom = Point(-74.013126, 40.713277) #returns True
#Urban areas
shp_file_base='cb_2017_us_ua10_500k'
dat_dir='C:/[path]/Downloads/cb_2017_us_ua10_500k/'
sf = shapefile.Reader(dat_dir+shp_file_base)
shape = sf.shape(3094)
poly = Polygon(shape.points)
print(sf.record(3094).as_dict())
if poly.contains(crisler): # swap out other points to see other results
    print("True!")
else:
    print("False!")    
npoints=len(shape.points) # total points
nparts = len(shape.parts) # total parts
if nparts == 1:  
  x_lon = np.zeros((len(shape.points),1))
  y_lat = np.zeros((len(shape.points),1))
  for ip in range(len(shape.points)):
      x_lon[ip] = shape.points[ip][0]
      y_lat[ip] = shape.points[ip][1]

  plt.plot(x_lon,y_lat,'k') 
else:
  for ip in range(nparts): # loop over parts, plot separately
      i0=shape.parts[ip]
      if ip < nparts-1:
         i1 = shape.parts[ip+1]-1
      else:
         i1 = npoints
      seg=shape.points[i0:i1+1]
      seg2 = Polygon(shape.points[i0:i1+1])
      x_lon = np.zeros((len(seg),1))
      y_lat = np.zeros((len(seg),1))
      for ip in range(len(seg)):
          x_lon[ip] = seg[ip][0]
          y_lat[ip] = seg[ip][1]
      plt.plot(x_lon,y_lat) 
plt.plot(freedom.x, freedom.y, 'bo')
plt.plot(fred.x, fred.y, 'yo')
plt.plot(crisler.x, crisler.y, 'ro')
plt.xlim(-74.2,-73.9)
plt.ylim(40.5,40.8)

![image](https://user-images.githubusercontent.com/42277856/53201257-866a1380-35f1-11e9-96d6-fd8daf8c52ae.png)

(Blue dot is Freedom tower, yellow is apartment, red is Crisler.  Large blue shape is Staten Island, Orange shape outlines mainland part of urban area with some waterways included.  All three points are obviously in the orange shape, but only the blue dot returns True from the contains() test.)

## Operating system

Windows 10

## Shapely version and provenance

Shapely 1.6.4

**Comment by kannes** [comment]
Please provide just the data needed to reproduce this and format your code properly. ;)

**Comment by raphael-sch** [comment]
```
from shapely.geometry import Point, Polygon
import shapefile
import matplotlib.pyplot as plt
import numpy as np
import os


fred = Point(-73.99709779999999, 40.7359057) #returns False
crisler = Point(-73.975311, 40.751652) #returns False
freedom = Point(-74.013126, 40.713277) #returns True
#Urban areas
shp_file_base='cb_2017_us_ua10_500k'
dat_dir = './data/cb_2017_us_ua10_500k/'
sf = shapefile.Reader(os.path.join(dat_dir, shp_file_base))
shape = sf.shape(3094)
poly = Polygon(shape.points)
print(sf.record(3094).as_dict())
for q_point in [fred, crisler, freedom]:
    if poly.contains(q_point): # swap out other points to see other results
        print("True!")
    else:
        print("False!")


npoints=len(shape.points) # total points
nparts = len(shape.parts) # total parts
if nparts == 1:
    x_lon = np.zeros((len(shape.points),1))
    y_lat = np.zeros((len(shape.points),1))
    for ip in range(len(shape.points)):
        x_lon[ip] = shape.points[ip][0]
        y_lat[ip] = shape.points[ip][1]

    plt.plot(x_lon,y_lat,'k')
else:
    for ip in range(nparts): # loop over parts, plot separately
        i0=shape.parts[ip]
        if ip < nparts-1:
            i1 = shape.parts[ip+1]-1
        else:
            i1 = npoints
        seg=shape.points[i0:i1+1]
        seg2 = Polygon(shape.points[i0:i1+1])
        x_lon = np.zeros((len(seg),1))
        y_lat = np.zeros((len(seg),1))


        for ip in range(len(seg)):
            x_lon[ip] = seg[ip][0]
            y_lat[ip] = seg[ip][1]
        plt.plot(x_lon,y_lat)
        plt.plot(freedom.x, freedom.y, 'bo')
plt.plot(fred.x, fred.y, 'yo')
plt.plot(crisler.x, crisler.y, 'ro')
plt.xlim(-74.2,-73.9)
plt.ylim(40.5,40.8)
plt.show()
```

shapefile is available after "pip install PyShp"

Data can be downloaded here: 
https://www.census.gov/geographies/mapping-files/2017/geo/carto-boundary-file.html
https://www2.census.gov/geo/tiger/GENZ2017/shp/cb_2017_us_ua10_500k.zip

I can reproduce the problem. Same behaviour with: `if q_point.intersects(poly):`

**Comment by sgillies** [comment]
I'm sorry @raphael-sch , but what we need is a test case that can demonstrate the problem exists without pyshp or matplotlib being involved. For example, the orange polygon and the three points exported in WKT form and then attached to this issue.
