### ISSUE TITLE
Why many example figures do not show up on the shapely user manual page

### ISSUE THREAD

**Issue by zyxue** [Toblerity/Shapely#684]
I am reading https://shapely.readthedocs.io/en/stable/manual.html.

For example, the linestrings figure shows up, but most others don't, e.g. in the linearrings section, only a link for downloading source code appears.

I wonder if it's a bug? If not, I would be interested in improving the doc.

**Comment by Arkangus** [comment]
I have been wondering the same. About a month ago it was showing fine and then the next day most figures were not displayed anymore.

**Comment by zyxue** [comment]
Could be due to the build process, some images may not have been generated properly.

e.g. this figure exists
https://shapely.readthedocs.io/en/stable/_images/linestring.png

But those don't
https://shapely.readthedocs.io/en/stable/_images/linearring.png
https://shapely.readthedocs.io/en/stable/_images/multipolygon.png

The owner @sgillies  may have a better idea.

**Comment by sgillies** [comment]
Thanks for pointing this out! The doc builds are indeed broken: https://readthedocs.org/projects/shapely/builds/. And it looks like the last "passed" builds were incomplete (missing images). We'll try to get this sorted out soon.

**Comment by sgillies** [comment]
I've restored the builds and made "latest" the default. We won't fix the builds for the 1.6 branch, which will soon not be supported.
