### ISSUE TITLE
Possibly wrong matrix multiplication

### ISSUE THREAD

**Issue by zyxue** [Toblerity/Shapely#685]
I am looking at the matrix multiplication equations at 

https://shapely.readthedocs.io/en/latest/manual.html#shapely.affinity.affine_transform

It looks to me that the second matrix should've been transposed in order to obtain equality equations following the matrix multiplication.

**Comment by mwtoews** [comment]
Thanks @zyxue you are correct, the matrix multiplication in the docs was incorrect. While it is possible to transpose the coefficient matrix, this would require several other documentation changes to the coefficient matrices for the other operations. A much simpler change is to re-order the order of the matrix multiplication, as is done with #688

**Comment by mwtoews** [comment]
Bad math strikes again :1234: !

@KolesovDmitry has identified that the other coefficients need to be transposed to allow the dimensions to be aligned for correct matrix multiplication.
