### ISSUE TITLE
How to include SRID in wkb_hex

### ISSUE THREAD

**Issue by thesteve0** [Toblerity/Shapely#686]
Documentation Issue
So I know there was supposedly a pull request merged to handle the issue mentioned in the title. And I see the code here
https://github.com/Toblerity/Shapely/blob/master/shapely/geos.py#L461

But I can't find any doc on how to actually set the SRID when exporting WKB hex encoded. 
Can you please let us know how to actually use this?

@snorfalorpagus @sgillies

**Comment by thesteve0** [comment]
If I try this
output.write(dumps(the_point, hex=True, srid=4326) + ",")
I get this
raceback (most recent call last):
  File "/home/spousty/git/crunchydemodata/county_boundaries/python/main.py", line 30, in <module>
    output.write(dumps(the_point, hex=True, srid=4326) + ",")
  File "/home/spousty/cdev/src/github.com/crunchydata/crunchy-containers/venv/lib64/python3.7/site-packages/shapely/wkb.py", line 28, in dumps
    writer = geos.WKBWriter(geos.lgeos, **kw)
  File "/home/spousty/cdev/src/github.com/crunchydata/crunchy-containers/venv/lib64/python3.7/site-packages/shapely/geos.py", line 466, in __init__
    setattr(self, name, applied_settings[name])
  File "/home/spousty/cdev/src/github.com/crunchydata/crunchy-containers/venv/lib64/python3.7/site-packages/shapely/geos.py", line 474, in __setattr__
    (self.__class__.__name__, name))
AttributeError: 'WKBWriter' object has no attribute 'srid'

**Comment by thesteve0** [comment]
Looks like it might be like this?
output.write(dumps(the_point, hex=True, include_srid=True) + ",")

**Comment by thesteve0** [comment]
Still doesn't work because no SRID is defined.

**Comment by sgillies** [comment]
@thesteve0 see the function definition at https://github.com/Toblerity/Shapely/blob/master/shapely/wkb.py#L24 but note that this is only available in the 1.7a1 pre-release: https://github.com/Toblerity/Shapely/blob/f0d3f61bc3572085de74a974840b8dde9bc57ff8/CHANGES.txt#L29. 1.7a1 works fine, if you really need this do `pip install shapely==1.7a1`.

**Comment by snorfalorpagus** [comment]
See below for demonstration of the new functionality.

```python
>>> import shapely
>>> shapely.__version__
'1.7a1'
>>> from shapely.geometry import Point
>>> from shapely.wkb import dumps
>>> p = Point(1, 2)
>>> dumps(p)
b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@'
>>> dumps(p, srid=4326)
b'\x01\x01\x00\x00 \xe6\x10\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@'
```

**Comment by tstxni97** [comment]
from https://geoalchemy-2.readthedocs.io/en/0.2.6/shape.html

We can do 

```
from geoalchemy2.shape import from_shape
from shapely.geometry import Point

wkb_element = from_shape(Point(5, 45), srid=4326)
```
