### ISSUE TITLE
polygon union bug

### ISSUE THREAD

**Issue by duanjianguo** [Toblerity/Shapely#689]
## Please note
from shapely import geometry
from shapely import wkt
from shapely.ops import cascaded_union
from shapely.ops import unary_union

a = geometry.Polygon([(0,0),(10,0),(10,10),(0,10)],[[(6,6),(6,8),(8,8),(8,6)], [(2,2),(2,4),(4,4),(4,2)]])
b = geometry.Polygon([(10,0),(11,0),(11,10),(0,10)])
c = b.union(a)
d = cascaded_union([b, a])
e = unary_union([a,b])
print a.wkt
print c.wkt
print d.wkt
print e.wkt

## Expected behavior and actual behavior.
a polygon with two holes, when union, one of the holes was disappeared
actual behavior
POLYGON ((0 0, 10 0, 10 10, 0 10, 0 0), (6 6, 6 8, 8 8, 8 6, 6 6), (2 2, 2 4, 4 4, 4 2, 2 2))
POLYGON ((10 10, 11 10, 11 0, 10 0, 0 0, 0 10, 10 10), (2 2, 4 2, 4 4, 2 4, 2 2))
POLYGON ((10 10, 11 10, 11 0, 10 0, 0 0, 0 10, 10 10), (2 2, 4 2, 4 4, 2 4, 2 2))
POLYGON ((10 0, 0 0, 0 10, 10 10, 11 10, 11 0, 10 0), (2 2, 4 2, 4 4, 2 4, 2 2))
expected behavior
POLYGON ((0 0, 10 0, 10 10, 0 10, 0 0), (6 6, 6 8, 8 8, 8 6, 6 6), (2 2, 2 4, 4 4, 4 2, 2 2))
POLYGON ((10 10, 11 10, 11 0, 10 0, 0 0, 0 10, 10 10), (6 6, 6 8, 8 8, 8 6, 6 6), (2 2, 4 2, 4 4, 2 4, 2 2))
POLYGON ((10 10, 11 10, 11 0, 10 0, 0 0, 0 10, 10 10),(6 6, 6 8, 8 8, 8 6, 6 6),  (2 2, 4 2, 4 4, 2 4, 2 2))
POLYGON ((10 0, 0 0, 0 10, 10 10, 11 10, 11 0, 10 0), (6 6, 6 8, 8 8, 8 6, 6 6), (2 2, 4 2, 4 4, 2 4, 2 2))

## Operating system
Linux

## Shapely version and provenance
1.6.4

**Comment by Jeremiah-England** [comment]
Hey @duanjianguo, 

Here are your two original polygons, with a pinkish **a** underneath a light colored **b**. 

![image](https://user-images.githubusercontent.com/34973839/96378221-7d2fa200-1158-11eb-98ba-1fe50f8384db.png)

And here is a purple overlay of the union(s) (they are all the same) which shapely produces in your example: 

![image](https://user-images.githubusercontent.com/34973839/96378286-ef07eb80-1158-11eb-979e-e213e7259bcf.png)

This, to me, is the expected result of a union here.
