### ISSUE TITLE
Add documentation how side is determined of parallel_offset

### ISSUE THREAD

**Issue by Davidswinkels** [Toblerity/Shapely#692]
### Expected documentation: 
object.parallel_offset(distance, side, resolution=16, join_style=1, mitre_limit=5.0)
Returns a LineString or MultiLineString geometry at a distance from the object on its right or its left side.

Distance must be a positive float value. The side parameter may be ‘left’ or ‘right’. **Left and right is determined by following the direction of given geometric points of the LineString**. The resolution of the offset around each vertex of the object is parameterized as in the buffer method.

The join style is for outside corners between line segments. Accepted integer values are 1 (round), 2 (mitre), and 3 (bevel). See also shapely.geometry.JOIN_STYLE.

Severely mitered corners can be controlled by the mitre_limit parameter (spelled in British English, en-gb). The ratio of the distance from the corner to the end of the mitred offset corner is the miter ratio. Corners with a ratio which exceed the limit will be beveled.

### Actual documentation: ([link](https://shapely.readthedocs.io/en/stable/manual.html>))
object.parallel_offset(distance, side, resolution=16, join_style=1, mitre_limit=5.0)
Returns a LineString or MultiLineString geometry at a distance from the object on its right or its left side.

Distance must be a positive float value. The side parameter may be ‘left’ or ‘right’. The resolution of the offset around each vertex of the object is parameterized as in the buffer method.

The join style is for outside corners between line segments. Accepted integer values are 1 (round), 2 (mitre), and 3 (bevel). See also shapely.geometry.JOIN_STYLE.

Severely mitered corners can be controlled by the mitre_limit parameter (spelled in British English, en-gb). The ratio of the distance from the corner to the end of the mitred offset corner is the miter ratio. Corners with a ratio which exceed the limit will be beveled.

## Steps to reproduce the problem.

from shapely.geometry import LineString
import matplotlib.pyplot as plt

def plot_line(ax, ob, color, zorder=1, linewidth=3, alpha=1):
    x, y = ob.xy
    ax.plot(x, y, color=color, linewidth=linewidth, solid_capstyle='round', zorder=zorder, alpha=alpha)

fig = plt.figure()
ax = fig.add_subplot(121)
base = LineString([(1, 1.2), (1, 1), (0, 1.5), (0, 1.2)])
left_offset = base.parallel_offset(0.1, 'left', join_style=2, mitre_limit=5.0)
right_offset = base.parallel_offset(0.1, 'right', join_style=2, mitre_limit=5.0)
plot_line(ax, base, alpha=0.7, color='green')
plot_line(ax, left_offset, alpha=0.7, color='red')
plot_line(ax, right_offset, alpha=0.7, color='blue')
plt.show()

**Comment by snorfalorpagus** [comment]
@Davidswinkels Could you submit this as a merge request?

**Comment by Davidswinkels** [comment]
Done :)
