### ISSUE TITLE
OSError: exception: access violation reading 0x0000000000000000

### ISSUE THREAD

**Issue by skyfully** [Toblerity/Shapely#694]
## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.

(For example: the area of my geometry is `1.417` when it should be `1.414`.)

## Steps to reproduce the problem.

(For example, a script with required data)

## Operating system

(For example, Mac OS X 10.12.3)

## Shapely version and provenance

(For example, 1.6b4 installed from PyPI using pip)

c = fiona.open(shp_path)    #打开路网数据
    coord_feature_dict = {}
    geom_list = []
    for feature in c:
        geometry = feature['geometry']  
        geom = shape(geometry)        
        geom_list.append(geom)      
        coord_key = geom.coords[0] + geom.coords[-1]  
        assert(coord_key not in coord_feature_dict)    
        coord_feature_dict[coord_key] = feature

Traceback (most recent call last):
  File "C:/Users/guanhuizhen/Desktop/map-match-master/get_od_path.py", line 161, in <module>
    road_rtree, coord_feature_dict = get_road_rtree('./shp/input/connected_road.shp')
  File "C:/Users/guanhuizhen/Desktop/map-match-master/get_od_path.py", line 47, in get_road_rtree
    coord_key = geom.coords[0] + geom.coords[-1]  #首末点
  File "D:\software\anaconda\lib\site-packages\shapely\geometry\base.py", line 322, in _get_coords
    if self.is_empty:
  File "D:\software\anaconda\lib\site-packages\shapely\geometry\base.py", line 643, in is_empty
    return (self._geom is None) or bool(self.impl['is_empty'](self))
  File "D:\software\anaconda\lib\site-packages\shapely\predicates.py", line 25, in __call__
    return self.fn(this._geom)
OSError: exception: access violation reading 0x0000000000000000

**Comment by sgillies** [comment]
I think this is very likely to be either of 1) a problem with your conda environment or 2) a problem with a particular feature geometry. I can't help with #1.

Can you share the value of `geometry` when the exception occurs?

**Comment by skyfully** [comment]
This is value of ###geometry  :{'type': 'LineString', 'coordinates': [(818021.4062999999, 2496252.202299999), (818037.9342999998, 2496258.6306)]}.
I have no idea of this error .Can you help me ? Thanks a lot.

**Comment by skyfully** [comment]
I just try upgrade the versions of shapely,then i solve this problem.

**Comment by sgillies** [comment]
@skyfully thanks for following up! I'm happy that the problem is solved.

**Comment by uloma07** [comment]
Updating shapely worked for me too.
