### ISSUE TITLE
WKT loads finish with Segmentation fault for positive integers for python2

### ISSUE THREAD

**Issue by tbicr** [Toblerity/Shapely#695]
## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.

`shaply.wkt.loads ` never should down with `Segmentation fault` and just raise `TypeError`, `UnicodeError`, `WKTReadingError` or other for incorrect input.

For python3 you will get `AttributeError: 'int' object has no attribute 'encode'`, but `TypeError` more appropriate there.

## Steps to reproduce the problem.

    import shapely.wkt
    shapely.wkt.loads(4)

## Operating system

Ubuntu 16.04.6 LTS

## Shapely version and provenance

1.6.4.post2 installed to venv from PyPI using pip for python 2.7.13

**Comment by snorfalorpagus** [comment]
I can reproduce this. It looks like the behaviour is different on Python 2 vs Python 3.

```
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely.wkt import loads
>>> loads(4)
[1]    1483 segmentation fault (core dumped)  python
```

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely.wkt import loads
>>> loads(4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snorf/Desktop/venv36/lib/python3.6/site-packages/shapely/wkt.py", line 10, in loads
    return geos.WKTReader(geos.lgeos).read(data)
  File "/home/snorf/Desktop/venv36/lib/python3.6/site-packages/shapely/geos.py", line 250, in read
    text = text.encode('ascii')
AttributeError: 'int' object has no attribute 'encode'
```

**Comment by tbicr** [comment]
Fixed
