### ISSUE TITLE
Disable handling of self-intersection on parallel_offset

### ISSUE THREAD

**Issue by paulo-raca** [Toblerity/Shapely#698]
## Expected behavior and actual behavior.

Thanks for the excellent library.

I'm working on a script that draws a puzzle made of many windings paths.
This will eventually be laser-etched, so I'm actually drawing each path with multiple parallel lines to make a seemingly thicker stroke, and I use `parallel_offset` to achieve this.

This works very nicely, but there is a gotcha: The appearence is different when a path overlaps itself and when it overlaps a distinct LineString:

![Screenshot_20190403_221704](https://user-images.githubusercontent.com/1072660/55523146-41101b80-565e-11e9-8676-86424771db8a.png)

Is it possible to get overlaped lines instead of the concentric rings on the self-intersection too?

(Also, the inner loop should become a LinearRing instead of a LineString?)

## Steps to reproduce the problem.

Here is the code that produces the image above
```
from shapely.geometry import *

paths = MultiLineString([
    [ (0, -1), (0, 1), (-1, 1), (-1, 0), (3,0) ],
    [(1, -1), (1, +1)],
])
display(paths)

parallels = []
for offset in [-.2, .0, .2]:
    for line in paths.geoms:
        parallels.append(line.parallel_offset(offset))       
display(GeometryCollection(parallels))

```

## Operating system

Ubuntu 18.10 x64

## Shapely version and provenance

1.6.4.post2 installed from PyPI using pip

**Comment by sgillies** [comment]
@paulo-raca what an interesting application! I'm afraid that shapely's parallel offset can not do what you need. Could you use paths.buffer instead?

![Untitled](https://user-images.githubusercontent.com/33697/55572125-296b7e00-56c4-11e9-9af7-f05cfc276b9e.png)

**Comment by paulo-raca** [comment]
That was my original approach, but turns out that drawing "solids" with the laser is much slower and messier than a bunch of parallel lines. 

(Also it turns out I liked the parallel lines aesthetic more!)

**Comment by paulo-raca** [comment]
Also, right now I'm using buffer to get a consistent look on all intersects:

```
parallels_2 = [paths]
for offset in [.15, .3]:
    parallels_2.append(paths.buffer(offset).boundary)
display(GeometryCollection(parallels_2))
```

![Screenshot_20190404_134647](https://user-images.githubusercontent.com/1072660/55573379-35653900-56e0-11e9-8a6f-c454e5ce99a9.png)

**Comment by paulo-raca** [comment]
Just so that you know what I was talking about, here is how the puzzle looks like
![visualização](https://user-images.githubusercontent.com/1072660/55573542-a0af0b00-56e0-11e9-9472-dd99b40fa0c4.png)

**Comment by sgillies** [comment]
@paulo-raca that's a clever use of the geometry collection. Is this what you're looking for? Can we close this issue?

**Comment by sgillies** [comment]
@paulo-raca that's a clever use of the geometry collection and a lovely puzzle. Is this what you're looking for? Can we close this issue?

**Comment by paulo-raca** [comment]
If there is no easy fix, let's close it.

Thank you

**Comment by paulo-raca** [comment]
O

Em qui, 4 de abr de 2019 14:07, Sean Gillies <notifications@github.com>
escreveu:
