### ISSUE TITLE
Request: Make Shapely PEP 561 compliant to include it in type checking

### ISSUE THREAD

**Issue by Imanflow** [Toblerity/Shapely#710]
I'm trying to add type check to several projects, and it would be really beneficial if I could do typechecking of shapely geometry types. In the [mypy docs](https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports) it says that in order to include third party libraries they should be PEP 561 compliant or you should do your own stub files. 

Is it possible to make shapely compliant? In case is it too much work, has anyone done or know where to find stub files for it? I could not find anything related.

**Comment by sgillies** [comment]
I'm not aware of any stub files. If someone created them and they added sgnificant value to other projects, I'd be mildly interested in adding typing to Shapely, but not in the current or next version. There are a bunch of more pressing issues: fixed precision, switching from ctypes, test modernization.
