### ISSUE TITLE
An exterior of an empty Polygon is None, but probably should be an empty GeometryCollection

### ISSUE THREAD

**Issue by LostFan123** [Toblerity/Shapely#712]
Creating an empty `Polygon` and taking its `exterior` will give `None`:
```python
>>> from shapely.geometry import Polygon
>>> print(Polygon().exterior)
None
```
But shouldn't it give an empty `GeometryCollection`?
So, expected behavior would be:
```python
>>> from shapely.geometry import Polygon
>>> print(Polygon().exterior)
GEOMETRYCOLLECTION EMPTY
```
I couldn't find anything specific to this behavior in the docs.

---

Shapely version: 1.6.4.post1, installed from conda.

**Comment by sgillies** [comment]
@LostFan123 very good point. It would be best if the exterior of an empty polygon was equivalent to `LinearRing()`.
