### ISSUE TITLE
Please add up-to-date "master" docs to readthedocs

### ISSUE THREAD

**Issue by kannes** [Toblerity/Shapely#714]
As I just stupidly spent too much time improving outdated documentation as it is found on https://fiona.readthedocs.io/en/latest/manual.html could we get a "master" development version there? This would be great to see the up-to-date state of Shapely and its documentation online.

**Comment by jorisvandenbossche** [comment]
On readthedocs, "latest" is normally already the master version. So if something is not up to date, there is something else going wrong. 
Can you point to an example that was not up to date?

(I suppose you meant to link the shapely docs?)

**Comment by kannes** [comment]
Oops, yes of course I meant Shapely docs.

Huh, this is awkward as I can not reproduce my confusion from earlier. I have to check on my other machine again in 3 days.

**Comment by sgillies** [comment]
"Latest" is documentation from master, see https://readthedocs.org/projects/shapely/builds/9082023/. There is a problem in that the version says "1.6" for latest. I'll see about fixing that now.

**Comment by sgillies** [comment]
There we go, "latest" now says "1.7a1": https://shapely.readthedocs.io/en/latest/.

**Comment by kannes** [comment]
Could not reproduce, maybe I was indeed confused by the version number. Thanks!
