### ISSUE TITLE
wrong color 

### ISSUE THREAD

**Issue by euhruska** [Toblerity/Shapely#719]
## Actual behavior
I plot points in light blue color and 99% it works, but a couple of the points are full blue color. This is unexpected since every single point I draw has alpha=0.5, as seen in the code.
![transparent_fail](https://user-images.githubusercontent.com/9983894/58352181-78b26d00-7e30-11e9-9e48-ee43bc842b40.PNG)

## code
```
n_here=all_Y1.shape[0]
size = 0.02
polygons1=[]
for i in range(n_here):
  polygon1=Point(all_Y1[i, 0], all_Y1[i, 1]).buffer(size)
  polygon1=shapely.affinity.scale(polygon1,1,ratioxy, origin=(all_Y1[i, 0], all_Y1[i, 1]))
  polygons1.append(polygon1)#_here)]

polygons1 = cascaded_union(polygons1)
for polygon1 in polygons1:
    #polygon1 = shapely.affinity.scale(polygon1,1,ratioxy)
    polygon1 = matplotlib.patches.Polygon(np.array(polygon1.exterior), facecolor="blue", lw=0, alpha=0.5)
    res[1].add_patch(polygon1)
```
## Expected behavior 
There is no error message, but I'm plotting 5 million points, so maybe that's causing it.
When I'm not using shapely, but otherwise similar setting that area looks like below. One can identify the wrong-colored points as the point which are encircled by other points. Shapely also colored in that white area, so that's another error.
![no_transparent_correct](https://user-images.githubusercontent.com/9983894/58352379-fa09ff80-7e30-11e9-8651-e0201ac247c8.PNG)

## Shapely version and provenance

shapely 1.6.4 installed with conda, python 3.7.3, linux

**Comment by jGaboardi** [comment]
This appears to be a `matplotlib` issue, not `shapely`.

**Comment by sgillies** [comment]
This is not a shapely bug.
