### ISSUE TITLE
distance from LineString to Point always returns nan

### ISSUE THREAD

**Issue by paulguerrero** [Toblerity/Shapely#725]
The distance from a LineString to a Point always seems to return nan for me. For example:

```python
from shapely.geometry import *
LineString([(0, 0), (1, 1)]).distance(Point((1, 2)))
```
results in `nan`, but the correct results is `1.0`. Whereas this:

```python
from shapely.geometry import *
Point((1, 2)).distance(LineString([(0, 0), (1, 1)]))
```
gives the correct result `1.0`. This was tested in Ubuntu 16.04 with Shapely 1.6.4.post1.

**Comment by jorisvandenbossche** [comment]
I cannot reproduce this (Ubuntu 16.04, Shapely1.6.4.post2):

```
In [16]: from shapely.geometry import * 
    ...: LineString([(0, 0), (1, 1)]).distance(Point((1, 2)))
Out[16]: 1.0
```

How did you install shapely?

**Comment by paulguerrero** [comment]
Thanks for the very quick response, it turns out I had installed both the 1.6.4.post1 version in conda and the 1.6.4.post2 version from pip at the same time, which seemed to have caused the issue. Reinstalling both separately gives me the correct result in both versions. Sorry for the false alarm.
