### ISSUE TITLE
Support for single sided buffer

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Shapely#727]
GEOS is able to do "single sided" buffers, but I don't think this is possible to do through shapely?

The [GEOS C++ reference docs on this](https://geos.osgeo.org/doxygen/classgeos_1_1operation_1_1buffer_1_1BufferOp.html#aaa8c47fc49faef0cafeb3865d8785f31) and the [C API](https://github.com/libgeos/geos/blob/f7315189af5400fb6e4e2cfd2595ac2584e647be/capi/geos_c.h.in#L436) indicate this is possible (since GEOS 3.3: https://github.com/libgeos/geos/commit/da545b516f02bdded2a1bfe3d02438d411df8ac8). 

From what I quickly looked at, the current buffer is implemented using `GEOSBufferWithStyle_r`, which does not expose the single sided option. It is exposed in `GEOSBufferWithParams_r`, but this is probably a bit more complex to expose in shapely with ctypes, as it takes a `BufferParameters` objects, instead of simply the different parameters as arguments.

Would it be possible to use this `GEOSBufferWithParams_r` in shapely instead? 
(but not sure why GEOS does not expose the `singleSided` param in `GEOSBufferWithStyle_r`, it could maybe also be an improvement there)

**Comment by sgillies** [comment]
@jorisvandenbossche Shapely's API has been lagging behind GEOS's. Anything in the GEOS 3.4 API (or later, maybe) is welcome in Shapely, in my opinion.

**Comment by sgillies** [comment]
Resolved.
