### ISSUE TITLE
Confused at 'Overlapping features do not therefore touch'

### ISSUE THREAD

**Issue by district10** [Toblerity/Shapely#729]
I'm confused at these lines in the manual (https://github.com/Toblerity/Shapely/blob/master/docs/manual.rst):

> Overlapping features do not therefore touch, another potential "gotcha". For example, the following lines touch at (1, 1), but do not overlap.
> 
> ```python
> >>> a = LineString([(0, 0), (1, 1)])
> >>> b = LineString([(1, 1), (2, 2)])
> >>> a.touches(b)
> True
> ```

The example is more like supporting 'touching features do not therefore overlap'. But... I'm not sure, English is not my native language.

Is this a inappropriate example?

**Comment by snorfalorpagus** [comment]
The manual is correct; The use of the words "overlapping" and "touching" in the manual have specific meanings as defined in the DE-9IM model of geometric relationships.

https://en.wikipedia.org/wiki/DE-9IM

In common use of these words you would expect that if A overlaps B then it also touches B, but this is not the case in DE-9IM as touch specifically means "at least one point in common, but their interiors do not intersect".
