### ISSUE TITLE
trouble installing Shapely

### ISSUE THREAD

**Issue by WetzlerkAI** [Toblerity/Shapely#738]
I have tried 

`pip install shapely`

and got this error

> Collecting shapely
>   Downloading https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz (225kB)
>      |████████████████████████████████| 235kB 1.7MB/s
>     ERROR: Complete output from command python setup.py egg_info:
>     ERROR: Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\karlp\AppData\Local\Temp\pip-install-cruk7pdk\shapely\setup.py", line 80, in <module>
>         from shapely._buildcfg import geos_version_string, geos_version, \
>       File "C:\Users\karlp\AppData\Local\Temp\pip-install-cruk7pdk\shapely\shapely\_buildcfg.py", line 200, in <module>
>         lgeos = CDLL("geos_c.dll")
>       File "c:\users\karlp\anaconda3\lib\ctypes\__init__.py", line 348, in __init__
>         self._handle = _dlopen(self._name, mode)
>     OSError: [WinError 126] The specified module could not be found
>     ----------------------------------------
> ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\karlp\AppData\Local\Temp\pip-install-cruk7pdk\shapely\

I have since tried 
`pip install shapely==1.4.1`
and it installed straight away. 

I can use 1.4.1 fine, so I have no urgency to follow this up. But I thought I'd let you know because I can install one and not the other.

**Comment by sgillies** [comment]
@WetzlerkAI the situation is documented in the project readme. There are no versions 1.6 distributions suitable for Windows on PyPI.
