### ISSUE TITLE
Missing MANIFEST.in in 1.7a2

### ISSUE THREAD

**Issue by ocefpaf** [Toblerity/Shapely#739]
The missing `MANIFEST.in` prevents the `setup.py` logic to trigger the re-cythonization of the extensions.

If that is by design feel free to close the issue but it would be nice to have that back in the stable release.

**Comment by sgillies** [comment]
@ocefpaf we've been excluding MANIFEST.in from the sdists since 2015: https://github.com/Toblerity/Shapely/commit/6acdf835d59d2e39c9c09edf7a80d8dc010fb9b5. It's by design so we can control the Cython version used to produce the .c files in the source distribution.

**Comment by ocefpaf** [comment]
I don't really care about the MANEFIST.in file but the usually most projects let downstream packagers to remove the `.c` files and get them regenerated automatically at build time. The logic in shapely's setup.py prevents that from happening when there is [not a MANIFEST.in file](https://github.com/Toblerity/Shapely/blob/master/setup.py#L318).

**Comment by ocefpaf** [comment]
Are you opened to the idea of allowing downstream packages to re-generate the cython easily without working around the `setup.py` logic? If so I can send a PR.

**Comment by sgillies** [comment]
Sure 👍
