### ISSUE TITLE
Misbehaviour of intersection, intersects

### ISSUE THREAD

**Issue by Charlesfox1** [Toblerity/Shapely#740]
## Expected behavior and actual behavior.

In a simple test case, intersection finds the point of intersection between two lines successfully.
This intersection lies on both lines, as proved by the boolean .intersects() statements beneath. 

However, when working with a real-life example, the intersection identified between two lines does not apparently lie on either line, causing a shapely.ops.split() operation to fail. 

The point returned as the intersection in the 'Real Life Case' does not appear to lie on either line, yet it was generated by shapely's intersection function. 

What am I doing wrong?

## Steps to reproduce the problem.

print('--------TEST CASE--------')

Line1 = LineString([(0,0),(1,1)])
Line2 = LineString([(1,0),(0,1)])
intersection12 = Line1.intersection(Line2)
print('intersection12 coordinates:',intersection12)

print('\nDoes intersection12 actually intersect Line1?')
print(intersection12.intersects(Line1))
print('\nDoes intersection12 actually intersect Line2?')
print(intersection12.intersects(Line2))
print('\nIf you split Line1 by intersection12, how many geometries do you get?')
print(len(shapely.ops.split(Line1, intersection12)))

print('\n--------REAL LIFE CASE--------')

cdsA = [(-2.590619584381377, 50.65559239868293), 
       (-2.488254422945145, 50.74821165219756), 
       (-2.426104146358861, 50.81524625028088), 
       (-2.331050782168074, 50.87295758184701), 
       (-2.214062026240951, 50.8821847708454), 
       (-2.151911749654668, 50.87757140472744), 
       (-2.049546588218435, 50.86603599106331), 
       (-1.874063454327751, 50.85218972603963), 
       (-1.833848569477803, 50.85218972603963), 
       (-1.720515712173403, 50.8637285657376), 
       (-1.643741841096229, 50.88910396362621), 
       (-1.566967970019055, 50.89832795547503),
       (-1.479226403073713, 50.92829331346343), 
       (-1.369549444392036, 50.93520565636136), 
       (-1.270840181578526, 50.93520565636136), 
       (-1.153851425651403, 50.9236845141262), 
       (-0.9783682917607196, 50.92829331346343), 
       (-0.8284764482290937, 50.9628447556425), 
       (-0.6785846046974682, 51.06634504728437), 
       (-0.5871871391294036, 51.18107455445171), 
       (-0.4811660790704485, 51.22001768989269), 
       (-0.2727798575752616, 51.26121572022112), 
       (-0.192350087875365, 51.33208141192418), 
       (-0.1704146961390295, 51.40967932792278), 
       (-0.1448234057799714, 51.45070734700504), 
       (-0.1411675071572489, 51.47120754216612), 
       (-0.1594470002708619, 51.48486922352877)]

LineA = LineString(cdsA)

cdsB = [(-0.8211646509836487, 50.98126169207349),
        (-0.6200902267339068, 50.92598897086996), 
        (-0.6091225308657391, 50.92137994323022), 
        (-0.4811660790704485, 50.90755012054996),
        (-0.3934245121251069, 50.89371618790503),
        (-0.2837475534434297, 50.8637285657376),
        (-0.19966188512081, 50.85449772239485),
        (-0.04245824434373918, 50.8498816154728),
        (0.07087461296066053, 50.82448486072578), 
        (0.1732397743968927, 50.79445269343574), 
        (0.1988310647559508, 50.778273528563),
        (0.2244223551150089, 50.74821165219756),
        (0.2244223551150089, 50.74821165219756)]

LineB = LineString(cdsB)

intersectionAB = LineA.intersection(LineB)
print('intersectionAB coordinates:',intersectionAB)

print('\nDoes intersectionAB actually intersect LineA?')
print(intersectionAB.intersects(LineA))
print('\nDoes intersectionAB actually intersect LineB?')
print(intersectionAB.intersects(LineB))
print('\nIf you split LineA by the intersectionAB, how many geometries do you get?')
print(len(shapely.ops.split(LineA, intersectionAB)))

## Operating system

Windows 10

## Shapely version and provenance

'1.6.4.post2'

**Comment by sgillies** [comment]
@Charlesfox1 point and line intersection is not reliable due to issues inherent in floating point representations of real numbers. Instead, we have to rely on tests of distance to some level of precision like `point.distance(line) < 1e-8`.

**Comment by Charlesfox1** [comment]
Fair enough. Thanks so much @sgillies for the rapid response!
C
