### ISSUE TITLE
Plan for dropping Python 2 support

### ISSUE THREAD

**Issue by mwtoews** [Toblerity/Shapely#743]
Python 2 has great for many of us. But after two decades, the [sun is setting on Python 2 support](https://python3statement.org/), which will [not be maintained past 2020](https://www.python.org/dev/peps/pep-0373/).

I'll propose the following. The next release for shapely is version 1.7, which currently supports both Python 2 and 3. This support should continue for the `maint-1.7` branch for this release series. However, after this release, the `master` and development efforts for the 1.8 milestone should require Python 3.5+.

How does this seem to everyone?

**Comment by snorfalorpagus** [comment]
Sounds good to me.

Mentioned in #721.
