### ISSUE TITLE
ImportError: cannot import name 'polylabel' from 'shapely.ops'

### ISSUE THREAD

**Issue by andreynovikov** [Toblerity/Shapely#748]
## Expected behavior and actual behavior.

`polylabel` is expected to be in `shapely.ops` but it's not included in `__all__` list:
https://github.com/Toblerity/Shapely/blob/60be3f8b19506efa62a713f68707ad4e9c48beac/shapely/ops.py#L21

## Steps to reproduce the problem.

1. `python3 -m pip install shapely`
2. `from shapely.ops import polylabel`

## Operating system

Debian 10

## Shapely version and provenance

shapely-1.6.4.post2

**Comment by snorfalorpagus** [comment]
`polylabel` isn't available in Shapely 1.6. You'll need to install the pre-release 1.7 (`pip install --pre shapely`) or from Git.

**Comment by snorfalorpagus** [comment]
Sorry, I am mistaken. It is available in 1.6 but you need to import it differently:

```
from shapely.algorithms.polylabel import polylabel
```

It's available from `shapely.ops` in 1.7
