### ISSUE TITLE
Inconsistent bool value of empty geometries

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Shapely#754]
The boolean value of an "empty" geometry (`bool(geom)`) depends on how the geometry is created. 

Empty `Polygon` and `EmptyGeometry` return True, while an empty `GeometryCollection` returns False.

```
In [1]: import shapely

In [2]: shapely.__version__
Out[2]: '1.6.4.post2'

In [3]: from shapely.geometry import Polygon, GeometryCollection

In [4]: from shapely.geometry.base import BaseGeometry, EmptyGeometry

In [5]: p1 = Polygon([])

In [6]: p1
Out[6]: <shapely.geometry.polygon.Polygon at 0x7f1319e719e8>

In [7]: print(p1)
GEOMETRYCOLLECTION EMPTY

In [8]: bool(p1)
Out[8]: True

In [9]: p2 = p1.buffer(0)   # not fully sure how to create such a POLYGON EMPTY manually

In [11]: p2
Out[11]: <shapely.geometry.polygon.Polygon at 0x7f131960c7f0>

In [12]: print(p2)
POLYGON EMPTY

In [13]: bool(p2)
Out[13]: True

In [14]: p3 = GeometryCollection()

In [15]: p3
Out[15]: <shapely.geometry.collection.GeometryCollection at 0x7f13038d74e0>

In [16]: print(p3)
GEOMETRYCOLLECTION EMPTY

In [17]: bool(p3)
Out[17]: False

In [18]: p4 = EmptyGeometry()

In [19]: p4
Out[19]: <shapely.geometry.base.EmptyGeometry at 0x7f1314fa91d0>

In [20]: print(p4)
GEOMETRYCOLLECTION EMPTY

In [21]: bool(p4)
Out[21]: True
```

(shapely installed with conda from conda-forge on Ubuntu 18.04, Python 3.7)

I think this should be consistent, ideally. 
Should we change the behaviour of GeometryCollection to match Polygon, LineString and EmptyGeometry ?

**Comment by snorfalorpagus** [comment]
This is possibly related to #742.

I'm not sure what the correct behaviour is here. The general rule for falsey-ness is objects that are numerically equal to zero, or collections that are empty. For example `0` or `[]`.

I agree that the current behaviour is inconsistent and that something needs to be changed. However, I'm not sure if we should be using `bool(geom)` as a proxy for `geom.is_empty`. Maybe that is OK? Maybe it isn't?

**Comment by jorisvandenbossche** [comment]
Personally, I would try to not rely on this detail and not use `bool(geom)` in my code as a way to do `geom.is_empty`, as the lattter is much more explicit. 
Therefore, I might have a slight preference for returning `True` to have all geometries (empty or not) consistent, and to prevent surprises where at once `bool(geom)` does something different if it was empty (the reason that I opened this was such a case).

But for sure there are also good reasons to give for having it return `False`.

**Comment by jorisvandenbossche** [comment]
> or collections that are empty

Although a geometry can be seen as a collection of coordinates (and thus an empty geometry is an empty collection), I rather see it as a scalar object and not a sequence. For me, that might be an argument for `True` instead of `False` like an empty collection.

**Comment by sgillies** [comment]
We're already using `is_empty` to determine the length of geometries. I propose that `bool(geom)` should return the logical complement of `geom.is_empty`. This makes it useful for testing whether a geometry is non-empty and significant.
