### ISSUE TITLE
ImportError: cannot import name 'Point' from 'shapely'

### ISSUE THREAD

**Issue by jakeeegarcia-alb** [Toblerity/Shapely#760]
## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.

(For example: the area of my geometry is `1.417` when it should be `1.414`.)

## Steps to reproduce the problem.

(For example, a script with required data)

## Operating system

(For example, Mac OS X 10.12.3)

## Shapely version and provenance

(For example, 1.6b4 installed from PyPI using pip)

**Comment by jakeeegarcia-alb** [comment]
Hi

Everytime i install geopandas in conda and shapely, I cannot seem to import Point, Line or anything else from shapely in my environment

this comes out

`ImportError: cannot import name 'Point' from 'shapely' (/Users/jacob/anaconda3/envs/mers_gis/lib/python3.7/site-packages/shapely/__init__.py)`

The steps I took were 

1. Create an environment in Anaconda navigator 
2. installed geopandas
3. Run this in my environment

`from shapely.geometry import Point

OR

from shapely import Point`

both give the same ImportError

Any help?

**Comment by jorisvandenbossche** [comment]
Hi @jakeeegarcia-alb, are you aware that you just created 5 other issues with the title 'Hi'? I suppose this was an accident, but you can close them all. 
Also note that you can update posts. So you edit the first post to put the content of what you put in the second post here.

**Comment by jorisvandenbossche** [comment]
About the actual issue you report: can you show the full error message when doing `from shapely.geometry import Point` ? (`from shapely import Point` is expected to fail)

**Comment by snorfalorpagus** [comment]
As instructed in the template, please raise conda packaging issues in the appropriate place:

* https://github.com/ContinuumIO/anaconda-issues/issues
* https://github.com/conda-forge/shapely-feedstock

I'm going to close this issue (along with the others you created). You can re-open it if this problem is not a conda issue and something related to the package from pypi.
