### ISSUE TITLE
Recursive Voronoi

### ISSUE THREAD

**Issue by rougier** [Toblerity/Shapely#766]
This is not an issue but I wanted to share a nice picture made with shapely (+ scipy and matplotlib) and did not find where to post. Code is available from https://github.com/rougier/recursive-voronoi (it is part of an [upcoming book on matplotlib](https://github.com/rougier/scientific-visualization-book)).

![recursive-voronoi](https://user-images.githubusercontent.com/327203/63838609-f204b300-c97d-11e9-89f5-a805d9e58ce6.png)

**Comment by snowman2** [comment]
Thanks for sharing, fun to see :+1:

**Comment by sgillies** [comment]
It's beautiful, @rougier !
