### ISSUE TITLE
linestring.is_simple is wrong

### ISSUE THREAD

**Issue by shankari** [Toblerity/Shapely#768]
## Expected behavior and actual behavior.

My non-self-crossing line should return `is_simple` = True

## Steps to reproduce the problem.

```python
import polyline as pl
import shapely as shp

bart_line_pl = 'ly~iV{|ndFqHbHbJqIq@l@vFoFw@t@mCjCdEaEtAaB??NM??lCgCnMgMxG}GtLsL??vAwAdDaD??vCuCb@c@d@g@`@e@\\_@Za@Za@pF}G~@kAz@mAx@kAbAwAhBmCf@w@f@w@f@y@j@y@h@}@l@}@nAeBpAoBhBkC??rAoBzAyB??`EaGnBsCXa@zG{J|Zsn@rK{RzCaG??Vi@??hBsD??HO??R_@??HQ??Zq@zDmI|D}JjA}B~AyBhDgElDiEvGuIbNiP|AaBbBaBdByA`BkApBoAbCuA`CiAhSuIbDyAlCqAhCwAxBoAdBmAzAoAjAiA|@}@~@kAbHmJdAoAfAkArAoAtAmA`BoAfBkA`BeAlGcD`KqFjLsG`BeAxAgArAmArA_BdAwAz@sAxEiIfG{KjAgB~AkBhBgBbBqAnBqArBgAbCmAzC{AfC{AtBcBXUnAkAbBeB`DuDvIuKn@s@n@q@l@m@t@k@r@e@v@e@??fCaB??zAcAzAcA??rA}@rA_Ab@WfJsF??p@c@\\UPMNMNMNMNOJKLOLOJOJOLSJOTe@Ti@^{@??|AoD??JU\\y@Rg@Tq@R{@Ho@Fy@Bm@@o@DkFD{D@mD??@u@???oB@s@Bi@Dw@Hs@??P{@T{@v@gC??Ne@d@_BLe@Jg@Je@Hi@Di@Bk@@s@?q@BcE??BqDBoC@qD?kA?g@Ce@Ec@I_@Kc@Qg@Uc@Wa@Yc@}DeF??yEgG??k@u@??y@gAuEcG??c@i@UYYY]Ya@[a@U_@Sa@Oa@Oc@Oc@Ka@Ic@Gc@Ge@Ee@Cc@Ak@Ae@?oLB??qNBs@?q@Au@?g@Aq@Co@Cq@Em@Gk@Gm@Gi@Ko@Kk@Mm@Om@Qo@Ug@Qk@Ui@Wi@Yi@[g@[g@[c@]c@Y_CgBmBwAGGeBqAmA_Ak@a@e@a@e@a@a@]e@a@e@e@c@e@g@i@??[]_@c@Y]U_@U[W_@S_@S_@Qa@Qa@M_@Ka@Ka@Ic@Ia@??Ko@kBaRw@uF??[cC??YeBUuAYsA[iAc@eA]}@??[i@Wa@Ye@]g@c@k@e@k@m@m@i@i@g@c@e@a@k@a@m@a@m@a@k@]m@[q@]o@[s@Yq@Yu@Yu@Ww@Yw@Uw@Uy@W??{GsBmI}CuMaHsD_CsJuF}l@_]aIkGgG{IqXsf@QYISGOASA_@B[@Ur@ePd@}JpF{nAHeBRsE|@sTDaC??@gACeAKeAOeAWcA]cAe@_Ai@_Ao@{@s@w@{@u@}@s@eE{CkT}OuEgDeYwSwMuJyb@g[mHoFiE}CcAu@kDgCiDeCkBwAiBqA]U]Sa@Qa@O{PyF??ssAmd@kEqAsEgAuE{@_Fu@{Eo@uFo@i|Dm_@_Js@}Ii@{Ia@aIUsIQcKKeLFmLVw~@zD??qI^??ce@xB{BJmBLkBNcBPwAL}AP}AR_LxAw@JkSlCcBVuATuAXqA\\mA\\sBl@yLpDmK~C{Ad@sA^wA^gAVaB`@??yEp@{T|CgBXgB^}A^uA`@qAd@cBl@mBt@gKvD??i@R??{BdAu@X??a@P[L??k@Po@Nk@Ha@Dc@DU@g@Bk@B_@@??e@?e@@c@?g@A_@CWA[EYEQGsAa@kAm@_Au@q@_A??eFuJ??qJqQiQk\\Yg@Ww@Ik@Ac@?c@Dc@Lk@Rg@\\i@`@e@`H}Fb@a@\\c@^k@??Zk@Vm@Rk@Nm@Hg@Fe@Bc@Be@@i@AM?YEi@??Ee@Ea@CMCQEUMi@UeAa@eB??YgAQy@Q{@_@oBGW??QaA??Oy@??O_A??o@iD??}@_F[cB[aBYqA[{Ac@mBa@cBYgAm@eC[oAUaAKo@Ii@??UaB??[cC}@cH??OsA??AG??S}A??YkD??McA??QeB??MkAIu@??Ce@Cc@?g@???m@Bm@??Dg@Hi@Hi@Ni@Ne@??Rg@??Rc@Ta@Ta@Ze@^g@b@i@\\_@|AgBv@_At@_Aj@}@h@cAb@eA\\eAZkARiARuApGsg@NwAHaABY??Bi@D_A???}@A_A??G}AMkA[cB{DgMuCiK}Js^w@}CQiAGu@AeADaA~@cOXmEpAeV^kEr@}I'
ls = shp.geometry.LineString(pl.decode(bart_line_pl)); ls
ls.is_simple
```

Notes:
- I don't know if this is a generic issue; I only encountered it in this use case.
- If you run this in a notebook, you can display the line `ls` and confirm that it is not self-crossing (see screenshot)

<img width="536" alt="Screen Shot 2019-08-29 at 12 32 28 PM" src="https://user-images.githubusercontent.com/2423263/63970472-17b2ba80-ca59-11e9-97ea-b4fe16286057.png">

## Operating system

Mac OSX 10.14.5 

## Shapely version and provenance

Installed from conda-forge

```
$ conda list shapely
# packages in environment at ...:
#
shapely                   1.6.4            py36he8793f5_0
```

**Comment by shankari** [comment]
Uploading screenshot with scaling to show the string better.
<img width="810" alt="Screen Shot 2019-08-29 at 12 35 24 PM" src="https://user-images.githubusercontent.com/2423263/63970645-8728aa00-ca59-11e9-9430-58f6696accb3.png">

**Comment by sgillies** [comment]
@shankari green means only that the geometry is "valid", which is always the case for line strings. I suspect that your line really does self-intersect at some point, even if that is only due to floating point precision errors.

**Comment by shankari** [comment]
@sgillies I didn't even know that linestring color represented validity 😃 I just put that in to show that there are no self-intersections. As you can probably tell, that is a public transit line and when I display it on a map, I can zoom and pan. And I don't see any self-intersections or anything that might be close to a self-intersection.

Is there a way I can determine the supposed intersection point so that I can check that location?

**Comment by kannes** [comment]
You can compare the coordinates of the linestring pair-wise:

```
for a, b in zip(ls.coords, ls.coords[1:]): 
    if a == b: 
        print(a, b) 
```

You have many duplicate coordinates, which is not allowed in the Simple Features specification.

A possible automatic fix would `ls.simplify(0)`.

**Comment by sgillies** [comment]
@kannes thank you 🙏

**Comment by kannes** [comment]
Right back at you! Any time I file a bug report or voice a wish, I also look at issues to see if I can help, that's the spirit.
