### ISSUE TITLE
shapely.geometry.shape does not support Feature or FeatureCollection

### ISSUE THREAD

**Issue by Lightslayer** [Toblerity/Shapely#770]
It would be great if shapely fully supported all GeoJSON constructs, including `Feature`s and `FeatureCollection`s - would this be something that could be easily supported?

Ideally I would like to be able to place a GeoJSON dictionary with a Feature or FeatureCollection into `shapely.geometry.shape()` and get shapes out

**Comment by sgillies** [comment]
@Lightslayer features and feature collections (or layers) aren't in shapely's domain. We're going to leave that up to the user.
