### ISSUE TITLE
Test with GEOS 3.8b1

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#777]
See announcement at https://lists.osgeo.org/pipermail/geos-devel/2019-September/009267.html. At a glance, it looks like there are attempts to fix problems that have been recently reported here (triangulation, etc).

cc @snorfalorpagus

**Comment by snorfalorpagus** [comment]
Need to figure out the best way to test this on Travis.

I've run master against GEOS 3.8.0beta1 and get a single failure:

```
__________________________________________ OperationsTestCase.test_operations __________________________________________

self = <tests.test_operations.OperationsTestCase testMethod=test_operations>

    def test_operations(self):
        point = Point(0.0, 0.0)

        # General geometry
        self.assertEqual(point.area, 0.0)
        self.assertEqual(point.length, 0.0)
        self.assertAlmostEqual(point.distance(Point(-1.0, -1.0)),
                               1.4142135623730951)

        # Topology operations

        # Envelope
        self.assertIsInstance(point.envelope, Point)

        # Intersection
        self.assertIsInstance(point.intersection(Point(-1, -1)),
>                             GeometryCollection)
E       AssertionError: <shapely.geometry.point.Point object at 0x7f01783d1a20> is not an instance of <class 'shapely.geometry.collection.GeometryCollection'>

tests/test_operations.py:26: AssertionError
================================= 1 failed, 283 passed, 23 skipped, 2 xfailed in 1.34s =================================
(venv) root@b7cac5555c9d:/data/Shapely# geos-config --version
3.8.0beta1
```

**Comment by dbaston** [comment]
I think this behavior change is expected, but should have gone in the NEWS file. Will verify.

Many of the changes in 3.8 are performance enhancements. Any feedback you're able to offer about the success of that work would be appreciated.

**Comment by sgillies** [comment]
@dbaston thanks for checking in on us! I'm excited about 3.8.0.

**Comment by mwtoews** [comment]
This issue is mostly resolved by #800 and #802

However, pending work is to implement some of the new functionality from this release. I've also not checked any specific bug fixes offered by the new version (triangulation, etc.)

**Comment by mwtoews** [comment]
Opps, keep open for now ...

**Comment by sgillies** [comment]
We're testing 3.8.1 now.
