### ISSUE TITLE
Peculiar case of polygon intersection

### ISSUE THREAD

**Issue by JelleVE** [Toblerity/Shapely#787]
## Expected behavior and actual behavior.

When performing the intersection operation on two specific (but valid) polygons, I expect a very small intersection area to be returned. Instead, the returned area corresponds to the smallest of the two input polygons.

## Steps to reproduce the problem.

```
polygon1 = shapely.wkt.loads('POLYGON ((3.155129753053188 2.215167496353389, 7.491521513845953 15.66021157189911, 1.76927375048399 18.47587150773562, 1.76927375048399 1.051617607468403, 2.576975833876214 1.11076026498468, 3.155129753053188 2.215167496353389))')
polygon2 = shapely.wkt.loads('POLYGON ((17.61336976289749 2.211775496602058, 13.84626575559378 1.935935497283936, 17.98853775858879 10.49510350450873, 13.03455375880003 12.93273550644517, 7.043449752032757 1.364799495786428, 2.76927375048399 1.018815495073795, 3.155129753053188 2.215167496353388, 17.45093776285648 29.52345551550389, 26.26640871809402 24.50215322394688, 17.61336976289749 2.211775496602058))')
polygon1.intersection(polygon2)
```

![image](https://user-images.githubusercontent.com/7097667/67954515-67486a80-fbf1-11e9-97bc-2183d1aefdf8.png)

## Operating system

Ubuntu 18.04

## Shapely version and provenance

shapely-1.6.4.post2 installed from PyPI using pip
GEOS version 3.6.2

**Comment by JelleVE** [comment]
Found a second case with the same behavior:

```
polygon1 = shapely.wkt.loads('POLYGON ((2.704037308692929 57.82616811618209, 21.67074947433078 66.61133047150174, 13.89357438198024 84.15826413407922, 1.704037308692932 84.15826413407922, 1.704037308692932 59.99400223766499, 2.704037308692929 57.82616811618209))')
polygon2 = shapely.wkt.loads('POLYGON ((47.26531733572483 8.864632081240416, 46.05803365449032 11.58851657850095, 27.90301332622766 3.198968078941107, 2.704037308692932 57.82616811618209, 57.39472534507513 83.15826413407922, 82.56694936007261 28.53196009621024, 64.42879084459631 20.11635422872955, 65.73917335271835 17.40210408717394, 59.54205334186554 14.52799208462238, 47.26531733572483 8.864632081240416))')
polygon1.intersection(polygon2)
```
![image](https://user-images.githubusercontent.com/7097667/67958899-361f6880-fbf8-11e9-91ea-9a0e4dfed5a1.png)

**Comment by sgillies** [comment]
Confirmed @JelleVE. Also, in your first case, `polygon1.union(polygon2)` equals polygon2. These polygons look like they only barely intersect, yes? I think floating point precision is the problem here. We can't reliably combine shapes that are closer than we can precisely represent.

**Comment by JelleVE** [comment]
Yes, if there are intersections, they should be absolutely minimal.
Truncating the coordinates to 5 decimals seems to work for me. Thanks!
