### ISSUE TITLE
Linestring intersection function is not working properly

### ISSUE THREAD

**Issue by RituYadav92** [Toblerity/Shapely#797]
## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.

should provide an intersection point or empty 

## Steps to reproduce the problem.

#line 1
A = (1621.60, 491.88)
B = (1525.24, 489.74)

#line 2
C = (1600, 0)
D = (1600, 900)

import shapely
from shapely.geometry import LineString, Point

line1 = LineString([A, B])
line2 = LineString([C, D])

int_pt = line1.intersection(line2)
print(int_pt)

## Operating system

(For example, Mac OS X 10.12.3)

## Shapely version and provenance

(For example, 1.6b4 installed from PyPI using pip)

**Comment by mwtoews** [comment]
@RituYadav92 what does `print(int_pt)` show?

Expected output should be `POINT (1600 491.400298879203)`, not empty.

**Comment by RituYadav92** [comment]
@mwtoews  issue is resolved. it was with shapely version.
I upgraded it from 1.6.4 to 1.6.4.post2 and the code is working now.
