### ISSUE TITLE
Task: add a few GEOS versions to Travis CI matrix

### ISSUE THREAD

**Issue by mwtoews** [Toblerity/Shapely#801]
The current Travis CI test matrix only uses one version of [libgeos-dev](https://packages.ubuntu.com/xenial/libgeos-dev), but more versions should be tested in the matrix, including GEOS master.

See good inspiration in (e.g.) rasterio's [travis_gdal_install.sh](https://github.com/mapbox/rasterio/blob/master/scripts/travis_gdal_install.sh), with a cache directory to help keep subsequent tests speedy.

As a possibly strategy to reduce the number of tests in the matrix, perhaps mix older GEOS versions with older Python versions.

**Comment by sgillies** [comment]
Master branch doesn't need to test python versions < 3.6 or GEOS versions < 3.6, I think.

**Comment by mwtoews** [comment]
Perhaps keep 2.7 and 3.5+ as described in #743 for the next release? We could possibly finish 1.7 this month. Also, Python 3.5 doesn't have any planned EOL yet ([PEP 478](https://www.python.org/dev/peps/pep-0478/)).

But after `maint-1.7` is cut, just test for both Python and GEOS >= 3.6? I.e. [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) sets out a sensible policy that we can get behind.
