### ISSUE TITLE
Execution inconsistency after deployment with pyinstaller

### ISSUE THREAD

**Issue by mieszkokl** [Toblerity/Shapely#813]
## Expected behavior and actual behavior.
Intersection implementation is faulty after deployment with pyinstaller, the same code without deployment works fine.

## Steps to reproduce the problem.
1. Run code snippet (reproduction.py) and save result:
```
import math

import numpy as np
from shapely import geometry


if __name__ == "__main__":
    line_segment = geometry.LineString([(0.0, -10.0), (0.0, 10.0)])

    center = (0.0, 0.0)
    radius = 5.0
    circle = \
        geometry.LineString([[center[0] + radius * math.cos(alpha), center[1] + radius * math.sin(alpha)]
                             for alpha in np.linspace(start=0, stop=2*math.pi, num=100)])

    print(f"Line={line_segment.wkt}")
    print(f"Circle={circle.wkt}")

    intersection = circle.intersection(line_segment)
    print(f"Intersection = {intersection.wkt}")

```
2. Deploy script using pyinstaller
```
pyinstaller reproduction.py --onefile
```

3. Run deployed script and compare results
```
./dist/reproduction
```

## Operating system

Ubuntu 19.04

## Shapely version and provenance
1.6.4.post2 installed from PyPI using pip.
Works fine on 1.6.4.

**Comment by sgillies** [comment]
@mieszkokl there's not enough information here. Which Python version? Which version of pyinstaller? Have you checked this issue tracker for other issues involving pyinstaller? What are the expected and actual results using pyinstaller? Can you report them here?

**Comment by mieszkokl** [comment]
@sgillies 
Python version: 3.7.5
pyinstaller version: 3.5

I didn't find any other issues involving pyinstaller.

I found simpler minimal example reproducing bug, the code is:
```
from shapely import geometry

if __name__ == "__main__":
    line_string_a = geometry.LineString([(0.0, -1.0), (0.0, 1.0)])
    line_string_b = geometry.LineString([(-1.0, 0.0), (1.0, 0.0)])

    intersection = line_string_a.intersection(line_string_b)
    print(f"Intersection = {intersection.wkt}")
```
Using pyinstaller:
Expected intersection is a POINT (0,0).
Actual intersection is a MULTILINESTRING ((0 -1, 0 0), (0 0, 0 1))

**Comment by sgillies** [comment]
@mieszkokl I see a different error.

```
$ ./dist/test/test
UnsupportedOperationException: GeometryGraph::add(Geometry *): unknown geometry type: N4geos4geom10LineStringE
UnsupportedOperationException:
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    intersection = line_string_a.intersection(line_string_b)
  File "shapely/geometry/base.py", line 646, in intersection
  File "shapely/topology.py", line 70, in __call__
  File "shapely/topology.py", line 34, in _check_topology
  File "shapely/geometry/base.py", line 701, in is_valid
  File "shapely/predicates.py", line 25, in __call__
  File "shapely/geos.py", line 580, in errcheck_predicate
shapely.errors.PredicateError: Failed to evaluate <_FuncPtr object at 0x106000368>
[1238] Failed to execute script test
```

The GEOS libs are in the pyinstaller dist, which is good, so there must be some other problem than missing libraries.

```
$ ls dist/test/
_bisect.cpython-36m-darwin.so           _decimal.cpython-36m-darwin.so          _sha1.cpython-36m-darwin.so             include                                 mmap.cpython-36m-darwin.so
_blake2.cpython-36m-darwin.so           _hashlib.cpython-36m-darwin.so          _sha256.cpython-36m-darwin.so           lib                                     numpy
_bz2.cpython-36m-darwin.so              _heapq.cpython-36m-darwin.so            _sha3.cpython-36m-darwin.so             lib2to3                                 parser.cpython-36m-darwin.so
_codecs_cn.cpython-36m-darwin.so        _json.cpython-36m-darwin.so             _sha512.cpython-36m-darwin.so           libcrypto.1.0.0.dylib                   pyexpat.cpython-36m-darwin.so
_codecs_hk.cpython-36m-darwin.so        _lzma.cpython-36m-darwin.so             _socket.cpython-36m-darwin.so           libgcc_s.1.dylib                        readline.so
_codecs_iso2022.cpython-36m-darwin.so   _md5.cpython-36m-darwin.so              _ssl.cpython-36m-darwin.so              libgeos-3.8.0.dylib                     resource.cpython-36m-darwin.so
_codecs_jp.cpython-36m-darwin.so        _multibytecodec.cpython-36m-darwin.so   _struct.cpython-36m-darwin.so           libgeos_c.1.dylib                       select.cpython-36m-darwin.so
_codecs_kr.cpython-36m-darwin.so        _multiprocessing.cpython-36m-darwin.so  array.cpython-36m-darwin.so             libgfortran.3.dylib                     shapely
_codecs_tw.cpython-36m-darwin.so        _opcode.cpython-36m-darwin.so           base_library.zip                        libncursesw.5.dylib                     syslog.cpython-36m-darwin.so
_csv.cpython-36m-darwin.so              _pickle.cpython-36m-darwin.so           binascii.cpython-36m-darwin.so          libopenblasp-r0.3.7.dylib               termios.cpython-36m-darwin.so
_ctypes.cpython-36m-darwin.so           _posixsubprocess.cpython-36m-darwin.so  fcntl.cpython-36m-darwin.so             libquadmath.0.dylib                     test
_curses.cpython-36m-darwin.so           _random.cpython-36m-darwin.so           grp.cpython-36m-darwin.so               libssl.1.0.0.dylib                      unicodedata.cpython-36m-darwin.so
_datetime.cpython-36m-darwin.so         _scproxy.cpython-36m-darwin.so          importlib_metadata-0.18-py3.6.egg-info  math.cpython-36m-darwin.so              zlib.cpython-36m-darwin.so
```

I used the DYLD_PRINT_LIBRARIES environment variable to verify that the GEOS libraries were being loaded and discovered that on my computer extra copies were being loaded. One from the dist and one from my /usr/local directory.

```
$ DYLD_PRINT_LIBRARIES=1 ./dist/test/test
...
dyld: loaded: /usr/local/lib/libgeos_c.dylib
dyld: loaded: /usr/local/lib/libgeos-3.8.0.dylib
dyld: loaded: /private/tmp/dist/test/numpy/core/_multiarray_umath.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/core/../../libopenblasp-r0.3.7.dylib
dyld: loaded: /private/tmp/dist/test/numpy/core/../../libgfortran.3.dylib
dyld: loaded: /private/tmp/dist/test/numpy/core/../../libquadmath.0.dylib
dyld: loaded: /private/tmp/dist/test/numpy/core/../../libgcc_s.1.dylib
dyld: loaded: /private/tmp/dist/test/numpy/core/_multiarray_tests.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/linalg/lapack_lite.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/linalg/_umath_linalg.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/_decimal.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/fft/_pocketfft_internal.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/random/mtrand.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/random/_bit_generator.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/random/_common.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/random/_bounded_integers.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/random/_mt19937.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/random/_philox.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/random/_pcg64.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/random/_sfc64.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/numpy/random/_generator.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/shapely/speedups/_speedups.cpython-36m-darwin.so
dyld: loaded: /private/tmp/dist/test/shapely/speedups/../../libgeos_c.1.dylib
dyld: loaded: /private/tmp/dist/test/shapely/speedups/../../libgeos-3.8.0.dylib
UnsupportedOperationException: GeometryGraph::add(Geometry *): unknown geometry type: N4geos4geom10LineStringE
UnsupportedOperationException:
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    intersection = line_string_a.intersection(line_string_b)
  File "shapely/geometry/base.py", line 646, in intersection
  File "shapely/topology.py", line 70, in __call__
  File "shapely/topology.py", line 34, in _check_topology
  File "shapely/geometry/base.py", line 701, in is_valid
  File "shapely/predicates.py", line 25, in __call__
  File "shapely/geos.py", line 580, in errcheck_predicate
shapely.errors.PredicateError: Failed to evaluate <_FuncPtr object at 0x10478dcc8>
[1369] Failed to execute script test
```

Can you check if you're inadvertently double-loading on your computer?

**Comment by mieszkokl** [comment]
@sgillies 
Content of my dist directory:
`
 $ ls dist/main/
base_library.zip                                 libcrypto.so.1.1                     _lzma.cpython-37m-x86_64-linux-gnu.so
_bz2.cpython-37m-x86_64-linux-gnu.so             libexpat.so.1                        main
_codecs_cn.cpython-37m-x86_64-linux-gnu.so       libffi.so.6                          mmap.cpython-37m-x86_64-linux-gnu.so
_codecs_hk.cpython-37m-x86_64-linux-gnu.so       libgcc_s.so.1                        _multibytecodec.cpython-37m-x86_64-linux-gnu.so
_codecs_iso2022.cpython-37m-x86_64-linux-gnu.so  libgeos-3.7.1.so                     _multiprocessing.cpython-37m-x86_64-linux-gnu.so
_codecs_jp.cpython-37m-x86_64-linux-gnu.so       libgeos_c.so.1                       numpy
_codecs_kr.cpython-37m-x86_64-linux-gnu.so       libgfortran-ed201abd.so.3.0.0        _opcode.cpython-37m-x86_64-linux-gnu.so
_codecs_tw.cpython-37m-x86_64-linux-gnu.so       liblzma.so.5                         psutil
_contextvars.cpython-37m-x86_64-linux-gnu.so     libmpdec.so.2                        _queue.cpython-37m-x86_64-linux-gnu.so
_ctypes.cpython-37m-x86_64-linux-gnu.so          libncursesw.so.6                     readline.cpython-37m-x86_64-linux-gnu.so
_curses.cpython-37m-x86_64-linux-gnu.so          libopenblasp-r0-2ecf47d5.3.7.dev.so  resource.cpython-37m-x86_64-linux-gnu.so
_decimal.cpython-37m-x86_64-linux-gnu.so         libpython3.7m.so.1.0                 scipy
_hashlib.cpython-37m-x86_64-linux-gnu.so         libreadline.so.8                     shapely
include                                          libssl.so.1.1                        _ssl.cpython-37m-x86_64-linux-gnu.so
_json.cpython-37m-x86_64-linux-gnu.so            libstdc++.so.6                       termios.cpython-37m-x86_64-linux-gnu.so
lib                                              libtinfo.so.6                        _uuid.cpython-37m-x86_64-linux-gnu.so
lib2to3                                          libuuid.so.1
libbz2.so.1.0                                    libz.so.1
`

I suppose DYLD_PRINT_LIBRARIES is for OSX, I've used LD_DEBUG=libs on Ubuntu, you can find output here: [out.txt](https://github.com/Toblerity/Shapely/files/4086851/out.txt)

GEOS libraries are loaded only from dist directory.

**Comment by sgillies** [comment]
I'm going to close this. The entire category of errors involving dynamic loading of GEOS is going away in 2.0 and we won't be doing anything about any of them in the meanwhile.
