### ISSUE TITLE
unary_union returning different results on Mac OS Catalina

### ISSUE THREAD

**Issue by aqueiros** [Toblerity/Shapely#816]
## Description
Greetings, a unit test started failing out of the blue on my project. The difference? I moved to Mac OS version Catalina. Now, for the same input on `ops.unary_union` function, I am getting a different result than my colleagues running previous OS version. We have same python version, same Shapely version and same GEOS version, so I am at loss as what the problem could be.

## Steps to reproduce the problem.

1. Enter python console
2. from shapely import wkt, ops
3. inputWKT= https://gist.github.com/aqueiros/d6ca02166d3d8db469ddd456893324fb
4. myshape =wkt.loads(inputWKT)
5. ops.unary_union(myshape).wkt

## Expected behavior and actual behavior.

Results on my system (Catalina): https://gist.github.com/aqueiros/db925c50130b5c2fed7d47ef936d76b4
Result on other systems(Mojave): https://gist.github.com/aqueiros/157304e6b3849439a1dfc8284276d9ee

## Operating system

Mac OS X 10.15.2 (Catalina)
vs
Mac OS X 10.14.6 (Mojave) 

## Shapely version and provenance

- geos 3.8.0 installed via `brew install geos`
- python 3.7.6 installed via `brew install python3`
- Shapely 1.6.1 installed via `pip install Shapely`

Any help or ideas on how to figure this out, would be greatly appreciated. Thanks!

**Comment by sgillies** [comment]
@aqueiros to my eye, the results you report for your Catalina computer look correct: they have the input coordinates, which is what I expect.

In the GEOS change log I see a mention of changes for the unary union algorithm in GEOS version 3.8.0. Is it possible that the Shapely install on the Mojave computer uses an older version? It is easy to be confused about which GEOS version is used on a computer where there may be multiple copies of the GEOS library.

At any rate, I'm going to close this. You're getting correct results (I believe) on your new system.

**Comment by aqueiros** [comment]
@sgillies Thanks so much for you feedback. There was indeed a confusion about which GEOS was installed because `brew info geo` was returning this on the Mojaves systems:
`
geos: stable 3.8.0 (bottled)
Geometry Engine
https://trac.osgeo.org/geos
/usr/local/Cellar/geos/3.7.2 (403 files, 8.8MB) *
  Poured from bottle on 2019-08-02 at 12:27:25
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/geos.rb
...
`
so, it states 3.8.0 on the top, but it is actually 3.7.2 installed.

So I am going indeed to assume that the problem were changes done in 3.8.0.
Unfortunately, I have now spend quite a few hours trying to install a previous version of geos on my system, because `brew install geos@3.7.2` does not work and building geos from source has it's set of challenges. 🤷‍♂
