### ISSUE TITLE
Bug with shapely.intersection between polygon and line

### ISSUE THREAD

**Issue by ToYoungSekiro** [Toblerity/Shapely#821]
I have two polygons A and B, and I get their intersection polygon C.
Then I convert A to its boundary.
I hope to get the intersection line between _A_boundary_ and _C_.
However, the output intersection line is not correct. Or it is only part of the correct result.
Here is the code to reproduce this problem:

`
import shapely

Poly1_wkt = 'POLYGON ((0 0, 0 55, 16.8 55, 14.8 43, 13 43.3, 5 0, 0 0))'
Poly2_wkt = 'POLYGON ((4 45, 20 45, 20 35, 4 35, 4 45))'

Poly1_geom = shapely.wkt.loads(Poly1_wkt)
Poly2_geom = shapely.wkt.loads(Poly2_wkt)

intersect_poly = Poly1_geom.intersection(Poly2_geom)

Poly1_bound    = Poly1_geom.boundary

intersect_line = Poly1_bound.intersection(intersect_poly)
print(intersect_line)
`

The correct result shoud be:
MULTILINESTRING ((15.13333333333333 45, 14.8 43), (14.8 43, 13 43.3), (13 43.3, 11.466512702078521, 35.0))
While the current wrong result is:
MULTILINESTRING ((15.13333333333333 45, 14.8 43), (14.8 43, 13 43.3))

![DemoImage](https://user-images.githubusercontent.com/58020598/72930975-ea212300-3d11-11ea-83aa-46b0a2567bdc.png)

**Comment by ToYoungSekiro** [comment]
Sorry I don't know how to correctly insert code:
`import shapely`
`Poly1_wkt = 'POLYGON ((0 0, 0 55, 16.8 55, 14.8 43, 13 43.3, 5 0, 0 0))'`
`Poly2_wkt = 'POLYGON ((4 45, 20 45, 20 35, 4 35, 4 45))'`
`Poly1_geom = shapely.wkt.loads(Poly1_wkt)`
`Poly2_geom = shapely.wkt.loads(Poly2_wkt)`
`intersect_poly = Poly1_geom.intersection(Poly2_geom)`
`Poly1_bound = Poly1_geom.boundary`
`intersect_line = Poly1_bound.intersection(intersect_poly)`
`print(intersect_line)`

**Comment by mwtoews** [comment]
This is not a bug, but is an issue with floating point precision, since a few segments for `intersect_poly` are nearly parallel to `Poly1_bound`. Since they are not exactly parallel (requiring interpolation), they do not intersect. However, there are several other ways to avoid this type of issue.

Are you looking for `Poly1_bound.intersection(Poly2_geom)`?

    LINESTRING (15.13333333333333 45, 14.8 43, 13 43.3, 11.46651270207852 35)

![img](https://i.imgur.com/itHGFUq.png)
