### ISSUE TITLE
Where is shapely's "used by" GitHub widget?

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#824]
@mwtoews you asked in another issue why Shapely doesn't have a "used by" widget on the top of its GitHub page. Some things I've read lead me to suspect that it's the lack of a requirements.txt file. All the other projects I work on and have the widget have a requirements.txt file and/or some requirements in the setup script. I've added an empty requirements.txt and will do a little more research and asking around.

**Comment by mwtoews** [comment]
[Toblerity/rtree](https://github.com/Toblerity/rtree) has a "used by" widget, but does not have a requirements.txt file.

GitHub has a [help page](https://help.github.com/en/github/visualizing-repository-data-with-graphs/listing-the-projects-that-depend-on-a-repository) on listing dependents, which might have some clues.

**Comment by akadouri** [comment]
https://github.com/Toblerity/Shapely/network/dependents is also empty. 

I wondered if it's because Shapely has a capital `S` but Fiona uses a capital `F` and seems fine. 🤷‍♂

**Comment by shoyer** [comment]
It took contacting GitHub support for me to fix that for xarray. That might be worth a try...

**Comment by sgillies** [comment]
Email sent :email:

**Comment by sgillies** [comment]
GitHub has sorted it out.

> Hello Sean,
>
> Thanks, the package looks like it was assigned to the wrong repository. I have corrected this and can see the Used by on your repository now. Please let me know if there is anything else I can help you with.
>
> Kind regards,
> Laurel
