### ISSUE TITLE
Make version of 1.6 docs available via readthedocs.

### ISSUE THREAD

**Issue by akadouri** [Toblerity/Shapely#825]
## Expected behavior and actual behavior.

readthedocs.io provides versioning to be able to access old versions of the docs. Going to https://readthedocs.org/projects/shapely/versions/ only shows latest and stable, both of which now point to 1.7.

## Steps to reproduce the problem.

Visit 
https://shapely.readthedocs.io/en/latest/
or
https://shapely.readthedocs.io/en/stable/

Both point to 1.7 docs.

## Notes
It looks like readthedocs supports multiple versions, and should pick them up based on the tagged releases. https://docs.readthedocs.io/en/stable/versions.html

Maybe there is a setting that needs to be toggled in the admin panel? Would be happy to look into other reasons why previous versions aren't showing. 

A workaround is to build the previous docs yourself or look at https://web.archive.org/web/20190116113651/https://shapely.readthedocs.io/en/stable/manual.html

**Comment by sgillies** [comment]
@akadouri I flipped the switch but the 1.6.4 build is failing for reasons I don't understand yet https://readthedocs.org/projects/shapely/builds/10358855/. The last successfully 1.6.x build is here: https://readthedocs.org/projects/shapely/builds/10354208/.

**Comment by mwtoews** [comment]
@sgillies perhaps create a RTD version based on `maint-1.6`? My guess is that the extension line with  `matplotlib.sphinxext.only_directives` needs to be removed from `conf.py`, which can be done on the maintenance branch.

**Comment by sgillies** [comment]
See also 91099d9.

**Comment by sgillies** [comment]
https://shapely.readthedocs.io/en/maint-1.6/ 🎉
