### ISSUE TITLE
Segfault when creating polygon in new release 1.7.0

### ISSUE THREAD

**Issue by Aikhjarto** [Toblerity/Shapely#827]
Since the new version 1.7.0 of shapely, I get segmentation faults when creating a polygon.

## Command to reproduce:
```
python3 -c "import shapely.geometry; polygon=shapely.geometry.Polygon([[1,2],[3,4],[4,5]]);"
Segmentation fault (core dumped)
```
Note: The above command works fine on the same system with shapely 1.6.2

## My system:
OS: Ubuntu 18.04.3 LTS
Python Version 3.6.9
Shapely Version: 1.7.0 (installed via pip)

**Comment by sgillies** [comment]
I can't reproduce the problem using the same OS, Python 3.6, and a shapely wheel installed in a new virtual environment.

```
$ mkvirtualenv shapely170
Using base prefix '/usr'
New python executable in /home/sean/.virtualenvs/shapely170/bin/python3
Also creating executable in /home/sean/.virtualenvs/shapely170/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/sean/.virtualenvs/shapely170/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/sean/.virtualenvs/shapely170/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/sean/.virtualenvs/shapely170/bin/preactivate
virtualenvwrapper.user_scripts creating /home/sean/.virtualenvs/shapely170/bin/postactivate
virtualenvwrapper.user_scripts creating /home/sean/.virtualenvs/shapely170/bin/get_env_details
(shapely170) $ pip install shapely
Collecting shapely
  Downloading Shapely-1.7.0-cp36-cp36m-manylinux1_x86_64.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 2.4 MB/s 
Installing collected packages: shapely
Successfully installed shapely-1.7.0
(shapely170) $ python3 -c "import shapely.geometry; polygon=shapely.geometry.Polygon([[1,2],[3,4],[4,5]]);"
(shapely170) $ 
```

@Aikhjarto can you provide any more details? Where did you install shapely? Do you have other versions of GEOS on your library path?

**Comment by Aikhjarto** [comment]
Thanks for testing. I did not set up any environment, but installed with "pip --user"

Now I created a new environment as you did, and it seems to work. So it probably has nothing to do with shapely altogether.

**Comment by sgillies** [comment]
@Aikhjarto thanks for following up! The fragility of shapely installs is a real issue and we're always trying to improve.
