### ISSUE TITLE
conda package for Windows broken

### ISSUE THREAD

**Issue by fonnesbeck** [Toblerity/Shapely#828]
Installing shapely 1.6.4 using conda on Windows 10 (Python 3.7)  completes without error, but the package is not available following installation. Below is a screen shot of the successful installation and the failed import.

![image](https://user-images.githubusercontent.com/81476/73480901-5f1ed900-4360-11ea-825b-cfd3b40c22f9.png)

Note that I am using the same conda env for installation and running ipython, so there is no issue with having different envs for installation and usage.

**Comment by sgillies** [comment]
Hi @fonnesbeck. We're not tracking issues with conda packages here. Can you report this at https://github.com/conda-forge/shapely-feedstock? The conda-forge shapely package has been reliable, I'm not sure why you're having trouble with it today.

**Comment by jorisvandenbossche** [comment]
This is not an issue with conda-forge, but the main anaconda channel. So you will need to open an issue there (I think https://github.com/ContinuumIO/anaconda-issues)

**Comment by sgillies** [comment]
Oh, right, pkgs/main. I'm not familiar enough with the output. Thanks @jorisvandenbossche.
