### ISSUE TITLE
LineString.is_ring returns False even if its boundary is an empty set

### ISSUE THREAD

**Issue by LostFan123** [Toblerity/Shapely#835]
Docs on [`object.is_ring`](https://shapely.readthedocs.io/en/latest/manual.html#object.is_ring) say:

> Returns `True` if the feature is closed. A closed feature’s _boundary_ coincides with the empty set. <...> This property is applicable to _LineString_ and _LinearRing_ instances...

Nevertheless, one can see that this is not always true:
```python
>>> from shapely.geometry import LineString
>>> line = LineString([(0, 0), (1, 1), (0, 0)])
>>> line.boundary.wkt, line.is_ring
('MULTIPOINT EMPTY', False)
```
I assume, this is because this `LineString` would result in an invalid `LinearRing`, but this is not clear from the documentation.

---
Shapely version: 1.6.4.post1, installed from conda.

**Comment by sr-murthy** [comment]
A linear ring is a closed and simple line string.

https://geos.osgeo.org/doxygen/classgeos_1_1geom_1_1LinearRing.html

The docstring you've quoted, i.e. for the method `is_ring` (https://github.com/sr-murthy/Shapely/blob/master/shapely/geometry/base.py#L676) is therefore imprecise - it should read something like

    > Returns True if the feature is closed and simple ...
