### ISSUE TITLE
IndexError while reading MultiPolygon with empty coordinates

### ISSUE THREAD

**Issue by koshy1123** [Toblerity/Shapely#837]
## Expected behavior and actual behavior.

I ran into a couple of records in a geodatabase layer with an empty `coordinates` field for `MultiPolygons`. Shapely fails to create a geometry for them. I'm not sure if it's by design (bad spec of the layer provider?), but I expected it to just create empty geometries. 

If it helps, I was just using a higher level library (geopandas) to just `geopandas.read_file('file.gdb', layer='some_layer')` when it hit this error because geopandas uses `shape(f['geometry'])` where `shape` is from `shapely` and `f` is a record from the layer using `fiona`'s collection

## Steps to reproduce the problem.

These are the failing records - it's a list of lists `[[]]` for the coordinates:

```
{'type': 'Feature', 'id': '11954', 'properties': OrderedDict([('AIN', None), ('SitusFullA', None), ('UseType', None), ('UseDescrip', None), ('DesignType', None), ('YearBuilt1', None), ('EffectiveY', None), ('Units1', None), ('Bedrooms1', None), ('Bathrooms1', None), ('SQFTmain1', None), ('APN', None), ('UseCode', None), ('UseCode_2', None), ('Shape_Length', 0.0), ('Shape_Area', 0.0)]), 'geometry': {'type': 'MultiPolygon', 'coordinates': [[]]}}
{'type': 'Feature', 'id': '11955', 'properties': OrderedDict([('AIN', None), ('SitusFullA', None), ('UseType', None), ('UseDescrip', None), ('DesignType', None), ('YearBuilt1', None), ('EffectiveY', None), ('Units1', None), ('Bedrooms1', None), ('Bathrooms1', None), ('SQFTmain1', None), ('APN', None), ('UseCode', None), ('UseCode_2', None), ('Shape_Length', 0.0), ('Shape_Area', 0.0)]), 'geometry': {'type': 'MultiPolygon', 'coordinates': [[]]}}
```
It's failing when creating the geometry:
https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/geo.py#L44
with this traceback:
```
/usr/local/lib/python3.7/site-packages/shapely/geometry/geo.py in shape(context)
     42         return MultiLineString(ob["coordinates"])
     43     elif geom_type == "multipolygon":
---> 44         return MultiPolygon(ob["coordinates"], context_type='geojson')
     45     elif geom_type == "geometrycollection":
     46         geoms = [shape(g) for g in ob.get("geometries", [])]

/usr/local/lib/python3.7/site-packages/shapely/geometry/multipolygon.py in __init__(self, polygons, context_type)
     62             self._geom, self._ndim = geos_multipolygon_from_polygons(polygons)
     63         elif context_type == 'geojson':
---> 64             self._geom, self._ndim = geos_multipolygon_from_py(polygons)
     65 
     66     def shape_factory(self, *args):

/usr/local/lib/python3.7/site-packages/shapely/geometry/multipolygon.py in geos_multipolygon_from_py(ob)
    136     assert L >= 1
    137 
--> 138     N = len(ob[0][0][0])
    139     assert N == 2 or N == 3
```

## Shapely version and provenance

In a Linux based docker container using Shapely 1.7.0

**Comment by sgillies** [comment]
@koshy1123 I think it would indeed be sensible to have, for example, `shape({"type": "Point", "coordinates": []})` return `Point()`. Would you be able to help with this?
