### ISSUE TITLE
shapely Point memory usage

### ISSUE THREAD

**Issue by alex-kap** [Toblerity/Shapely#839]
How to determine the size of shapely Point object?
I have a data set with about 20 000 000 longitude, latitude coordinates. According to my observation when I make about 20 000 000 shapely Point objects (Point has 2 dimensions)  the memory usage is 4-5Gb. It's about 250 bytes for one Point. Is it close to real size?
python 3.6, shapely 1.6.4.post2, x86_64

**Comment by sgillies** [comment]
@alex-kap I think that's about the size to expect, yes. While it might seem that a Python point is just 2 floats (16 bytes), there are a few other attributes, and at some point there may be for each Shapely geometry a pointer to an instance of the GEOS Geometry class (see https://github.com/libgeos/geos/blob/master/include/geos/geom/Geometry.h#L188). There's a fair amount of Geometry overhead for all shapely objects and you'll notice it with points. For very detailed polygon geometries you may expect the size to approach 32 * N bytes, where N is the number of vertices, half of this being the coordinates in Python and the other half being the coordinates in C.

**Comment by liorweitz** [comment]
hey, sgillies (:
Im trying to understand.
Can you explain why the polygon coordinates saved once in python and once in c? are objects saved like that?
