### ISSUE TITLE
shapely.geometry.shape() can't parse coordinates in numpy arrays

### ISSUE THREAD

**Issue by nrweir** [Toblerity/Shapely#840]
## Expected behavior and actual behavior.

We've been using the `shapely.geometry.shape()` function to create geometries of multiple different types from a json string in [`solaris.utils.geo._reduce_geom_precision()`](https://github.com/CosmiQ/solaris/blob/master/solaris/utils/geo.py#L600). We pass coordinate pairs in as 2D `numpy` arrays. When the geometry corresponds to a polygon (see example below), we're suddenly getting errors that seem to boil down to problems with truthiness testing of multi-element `numpy` arrays [here](https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/geo.py#L35). I _think_ this is the result of a recent deprecation of this type of testing in `numpy` arrays, though I'm not 100% sure.

My question: should I be avoiding using arrays for coordinates, or should I make a PR to help parse arrays more effectively?

## Steps to reproduce the problem.

```python

from shapely.geometry import shape
from numpy import array

geom_dict = {
    'type': 'Polygon',
    'coordinates': array(
        [[[ 0.,  3.],
        [ 8.,  8.],
        [ 6., 21.],
        [ 5., 29.],
        [19., 38.],
        [18., 58.],
        [ 0., 54.],
        [ 0.,  3.]]]
    )
}

shape(geom_dict)
```

Error message
```
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "/opt/miniconda3/envs/solaris_021/lib/python3.7/site-packages/shapely/geometry/geo.py", line 35, in shape
    if not ob["coordinates"]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
## Operating system

MacOS 10.15.3

## Shapely version and provenance

1.6.4 or 1.7.0 (occurs in both) installed from conda-forge. python 3.7.6.

**Comment by sgillies** [comment]
I'd be happy to see numpy arrays supported. It might not be much more than testing `if len(ob["coordinates"]) == 0` instead of `if not ob["coordinates"]`. A PR would be very welcome!

**Comment by nrweir** [comment]
Awesome! I'll get that in.
