### ISSUE TITLE
import error in command line (with a workaround, which might be a potential fix)

### ISSUE THREAD

**Issue by veenstrajelmer** [Toblerity/Shapely#844]
## Expected behavior and actual behavior
Action: `import shapely.geometry`
Expected behaviour: imports without error
Actual behaviour in my Spyder with my virtual environment activated: imports without error
Actual behaviour in command line with my virtual environment activated:
> Traceback (most recent call last):
[not so relevant details ommitted]
   File "C:\Users\\[user]\AppData\Local\Continuum\anaconda3\envs\dfm_tools_env\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\\[user]\AppData\Local\Continuum\anaconda3\envs\dfm_tools_env\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found`

## My solution
Replace line 143 from geos.py such that it always goes to the else loop. Original:
>    if os.getenv('CONDA_PREFIX', ''):  

replace this by:
>    if 0:#os.getenv('CONDA_PREFIX', ''):

This method works, but when I replace `CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))` by the actual path `os.path.join(sys.prefix, 'Lib','site-packages','shapely','DLLs','geos_c.dll')`, it does not. Apperantly the else loop is the way to go to get the proper paths somewhere. Is this something that can be catched or is there something I can set for this to not happen? (preferrably something upon install of a package, I prefer not to bother users with this.)

## Operating system
Windows 10
Python 3.7

## Shapely version and provenance
1.7.0 installed from PyPI using pip

**Comment by sgillies** [comment]
@veenstrajelmer which Python version are you using?

**Comment by veenstrajelmer** [comment]
I use Python 3.7 (now also updated in my answer). It might be because I created an environment with conda (conda env create -f environment.yml), but in my opinion this should not matter. Is there any case where the if-loop on line 143 does provide a benefit? Otherwise I would propose to remove it and only keep the coe in the else-part of the loop.

**Comment by veenstrajelmer** [comment]
Any updates on this issue?

**Comment by sgillies** [comment]
It looks like this is a duplicate of the problem being worked on in #843.

**Comment by veenstrajelmer** [comment]
Great, thanks for the link! It is indeed a duplicate and I see I was a bit naive in my question formulation. I will close this issue now.
