### ISSUE TITLE
TypeError: 'LineString' object is not iterable

### ISSUE THREAD

**Issue by Aiswarya89** [Toblerity/Shapely#846]
Hello,
  While running a program, the following arises in my system but runs well with my colleague. Only difference between us is the version of Shapely. I have downloaded the most recent version of shapely and my colleague is using Shapely.1.6.4.post2. Now Iam not able to install the older version of shapely too. Any help regarding this will be appreciated.
The error is as following...

Traceback (most recent call last):
  File "E:\python\contour.py", line 128, in <module>
    giv = ps.ContourIntersection(Qm[0],Qm[1],w,d,Qback=Qm[2],gridPoints=200,nMin=nMin,nMax=nMax,kMin=kMin,kMax=kMax,axisOption=1,fig=fig1,ax=ax4)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38\lib\site-packages\PyMieScatt\Inverse.py", line 200, in ContourIntersection
    m2 = find_intersections(scaChart,backChart)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38\lib\site-packages\PyMieScatt\Inverse.py", line 587, in find_intersections
    for s in sol:
TypeError: 'LineString' object is not iterable

**Comment by sgillies** [comment]
The LineString class is not iterable and was not iterable in version 1.6.4.post2. There must be some other factors involved.

```
$ pip list | grep Shapely
Shapely            1.6.4.post2
$ python
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely.geometry import LineString
>>> list(LineString())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'LineString' object is not iterable
```

**Comment by anzixuan555** [comment]
怎么样，问题解决了吗

**Comment by mwtoews** [comment]
@anzixuan555 "how, is the problem solved?" try using the `.coords` property:
```python
from shapely.geometry import LineString

ls = LineString([(1.0, 2.0), (3.0, 4.0)])
for coord in ls.coords:
    print(coord)
```
be aware that other geometry types will store their coordinates differently, and this will only work for LineString and LinearRing types.

**Comment by anzixuan555** [comment]
> 



> @anzixuan555 "how, is the problem solved?" try using the `.coords` property:
> 
> ```python
> from shapely.geometry import LineString
> 
> ls = LineString([(1.0, 2.0), (3.0, 4.0)])
> for coord in ls.coords:
>     print(coord)
> ```
> 
> be aware that other geometry types will store their coordinates differently, and this will only work for LineString and LinearRing types.

我试着加上coords了，错误变成了
raise NotImplementedError(
NotImplementedError: Multi-part geometries do not provide a coordinate sequence.
我对shapely不了解。
