### ISSUE TITLE
Docs absent for STRTree.nearest()

### ISSUE THREAD

**Issue by Jeremiah-England** [Toblerity/Shapely#854]
Looking through the change log for 1.7.0 I noticed that STRTree now supports nearest neighbor searches (issue #668). 

I also noticed that @kannes has been working on the STRTree docs for issue #618. There was a merge attempt early January. However, there were conflicts and nothing further happened: https://github.com/Toblerity/Shapely/pull/623. ¯\\\_(ツ)_/¯  

This seems like a good first issue and I'm interested in getting involved with shapely. So maybe next weekend I could fix the conflicts with https://github.com/Toblerity/Shapely/pull/623 and add the docs for nearest neighbors, if that's OK with @kannes. 

It looks like this would also close #845?

link to function code: [STRTree.nearest()](https://github.com/Toblerity/Shapely/blob/master/shapely/strtree.py#L64-L84)

**Comment by kannes** [comment]
I am not "OK" with that, but rather I would happily jump with happiness if you did that :))

**Comment by sgillies** [comment]
@Jeremiah-England count on me for help too!

**Comment by sgillies** [comment]
Resolved by #857.
