### ISSUE TITLE
GeoJSON Mapping for Polygons in 1.7 Outputs 0 for all Coordinates

### ISSUE THREAD

**Issue by sscullen** [Toblerity/Shapely#856]
## Expected behavior and actual behavior.

Moved from shapely 1.5 to 1.7 (Gohlke no longer has packages for 1.5 for python3.7). Trying to convert WKT to a GeoJSON geometry, Polygon conversion results in all coords being 0.0, 0.0.

```
fp_temp = shapely.wkt.loads(wrs_tuple[1])
fp_output = shapely.geometry.mapping(fp_temp)
```
output:
```
fp_temp: POLYGON ((-114.542226573317 49.7176869535447, -114.543 49.7178, -114.525513493275 49.7615104086869, -114.513467206238 49.7916220906714, -113.975512499914 51.1363286371503, -113.965562536883 51.161200211407, -113.946 51.2101, -113.94504153241 51.2099596890207, -111.383 50.8349, -111.400867563036 50.7954662084955, -112.045161428052 49.373506767805, -112.054 49.354, -114.542226573317 49.7176869535447))
fp_output: {'type': 'Polygon', 'coordinates': (((0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0)),)}
```
Expect non-zero coords from the GeoJson mapping.

## Operating system

Windows 10
Python3.7

## Shapely version and provenance

1.7

I suspect it is the code change from 1.6 to 1.7 where the mapping was changed to check for the exterior being a linear ring, in which case the coords array is set to `[]`:

1.7:
```
 def __geo_interface__(self):
        if self.exterior == LinearRing():
            coords = []
        else:
            coords = [tuple(self.exterior.coords)]
            for hole in self.interiors:
                coords.append(tuple(hole.coords))
        return {
            'type': 'Polygon',
            'coordinates': tuple(coords)}
```
1.6:
```
def __geo_interface__(self):
        coords = [tuple(self.exterior.coords)]
        for hole in self.interiors:
            coords.append(tuple(hole.coords))
        return {
            'type': 'Polygon',
            'coordinates': tuple(coords)
            }
```

So my question is: what is the purpose of the above change? How can I convert my polygon geometry to GeoJson polygon coordinates? I confess I don't understand how LinearRing and Polygon relate to each other, why the check for an exterior being of type LinearRing would be necessary.

Thanks!

**Comment by sscullen** [comment]
So I'm deeply confused, my above problem is not related to 1.7 or the changes made in the geo_interface function.

Shapely 1.7 works just fine through an interactive session, but when running in a django view it outputs all 0.0's for the coordinates. All code involving the input wkt and shapely functions are the same. I have no idea why that is happening.

**Comment by sscullen** [comment]
I've figured out what is going on. If I import shapely before gdal, the problem does not occur. If I import gdal before shapely, all the coords are (0.0, 0.0). Hope this helps someone in the future.

**Comment by sgillies** [comment]
@sscullen thanks for following up! The Gohlke and PyPI packages cannot be mixed, they are not compatible. Get shapely from the Gohlke site, too, or use the equivalent functionality in the GDAL package.
