### ISSUE TITLE
PyPi cp27-cp27m wheels

### ISSUE THREAD

**Issue by mikedh** [Toblerity/Shapely#861]
Hey, apologies for the esoteric packaging issue, I'm trying to beat a test matrix into passing. 

It looks like there is one Shapely [wheel on PyPi](https://pypi.org/project/Shapely/#file) for Python 2.7  (`Shapely-1.7.0-cp27-cp27mu-manylinux1_x86_64.whl`), but for "reasons" pip in CI is looking for the image built with `cp27-cp27m`. Here's the explanation on the difference from manylinux:

> We provide both versions (e.g. /opt/python/cp27-cp27m for narrow-unicode, /opt/python/cp27-cp27mu for wide-unicode)

The [manylinux](https://github.com/pypa/manylinux) images Shapely is using definitely have that build of Python, and my quick analysis of the current wheel pipeline makes me think it *should* be building the `cp27-cp27m` image. Is it possible that wheel is getting dropped as a duplicate on upload or something?

Triple checking the manylinux image:
```
mikedh@orbital:trimesh$ docker run -it quay.io/pypa/manylinux1_x86_64:latest /bin/bash
[root@85accb3a20de /]# ls /opt/python/
cp27-cp27m  cp27-cp27mu  cp34-cp34m  cp35-cp35m  cp36-cp36m  cp37-cp37m  cp38-cp38
```

**Comment by sgillies** [comment]
We don't build shapely wheels for narrow unicode Python 2.7. This was an oversight, but now that Python 2.7 is done, we're not going to do anything about that and will follow other projects like Numpy in dropping Python 2.7 wheels from our builds entirely.
