### ISSUE TITLE
Start maint-1.7 branch

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#868]
So that we can start working on 1.8, which will be mostly about making deprecation warnings.

**Comment by sgillies** [comment]
Done!

**Comment by jorisvandenbossche** [comment]
@sgillies Thanks!
Could you also make a "shapely 2.0" branch? (I would like to start doing some preliminary PRs for that as well)

**Comment by sgillies** [comment]
@jorisvandenbossche done! https://github.com/Toblerity/Shapely/tree/shapely-2.0

**Comment by jorisvandenbossche** [comment]
Thanks! 

I am currently preparing a PR with a more detailed written-out proposal (based on the discussions in #782). Is it OK to do PR in this repo? Or do you prefer to create another repo similar to fiona-rfc ?

**Comment by sgillies** [comment]
I created a new RFC repo: https://github.com/shapely/shapely-rfc.

Thanks for keeping this moving @jorisvandenbossche !

**Comment by jorisvandenbossche** [comment]
Super! I have been working on the RFC today, so will post the first draft there in a minute
