### ISSUE TITLE
Document minimum clearance

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#874]
See #870.

**Comment by tomplex** [comment]
Hey @sgillies, I'd be happy to do this if you can give me a little direction on where to add it and what you expect.

**Comment by sgillies** [comment]
Right in this list here alongside the "area" and "length" attributes: https://github.com/Toblerity/Shapely/blob/master/docs/manual.rst#general-attributes-and-methods. It doesn't need to be more than a function definition, the brief summary copied from your new property, and an example.

**Comment by tomplex** [comment]
Awesome, I'll submit a PR later.

**Comment by sgillies** [comment]
Resolved by #875 .
