### ISSUE TITLE
Add GEOSMakeValid to Shapely

### ISSUE THREAD

**Issue by tomplex** [Toblerity/Shapely#883]
It would be nice to have this functionality available directly in Shapely. It requires [GEOS 3.8](https://github.com/libgeos/geos/blob/312c085bdc9606896281c7d0610c1a1b3931e014/NEWS#L21).

Should it live in `ops`, `validation`, or somewhere else?

**Comment by jorisvandenbossche** [comment]
Just want to note this was already added to PyGEOS recently (https://github.com/pygeos/pygeos/pull/120). Which doesn't prevent adding it to current Shapely for 1.8 as well of course, since it is a rather straightforward one to add and https://github.com/Toblerity/Shapely/issues/782 is at best still a while off.

**Comment by tomplex** [comment]
@jorisvandenbossche, thanks for pointing that out to me - I was unaware of the upcoming plans to merge. Is development on that project active yet? I'd love to be involved or help in any way I can.

**Comment by jorisvandenbossche** [comment]
The project is active, in the sense that pygeos is actively being developed (including aspects that relate to integration into geopandas and shapely). The actual integration into Shapely a bit less so. I need to update the design document linked in https://github.com/Toblerity/Shapely/issues/782, and further it also needs some more discussion and feedback. And then we actually also need to do the work (I hope to be able to spend more time on this in April). Help here is certainly welcome!

**Comment by tomplex** [comment]
Great to hear! I'll read up a bit more and check out the design document in the linked issue.

**Comment by sgillies** [comment]
@tomplex let's do this for 1.8. The validation module is the right place.

**Comment by tomplex** [comment]
Great, thanks! Does that mean it should be on master instead of maint-1.7?

**Comment by sgillies** [comment]
Yes.
