### ISSUE TITLE
Drop Python 3.5 support for Shapely 2.0

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Shapely#886]
I know we are only just dropping Python 2.7 support (#743, #884), but I would already like to bring up the timeline for keeping/dropping Python 3.5 support.

Shapely 1.8 will require >= Python 3.5, and I would propose that the future Shapely 2.0 with PyGEOS integration (#782) can require >= Python 3.6.

* It's hard to exactly plan of course, but realistically by the time that a potential Shapely 2.0 would come out, Python 3.5 will be end of life (2020-09-13, see https://devguide.python.org/#status-of-python-branches)
* In the scientific python ecosystem, many packages already dropped or are dropping Python 3.5 support (see https://numpy.org/neps/nep-0029-deprecation_policy.html, although this describes a shorter support cycle than many packages in practice do)

But the main reason that I am already bringing this up now, is that *if* this sounds good for Shapely, we would like to already start with that in PyGEOS (https://github.com/pygeos/pygeos/issues/125). Meaning we can start using Python 3.6 features in PyGEOS *now* (eg ordered default dict, f-strings, type annotations, ..). Because if not, I would prefer not do start doing that in PyGEOS to not make integration with Shapely later on more difficult.

**Comment by mwtoews** [comment]
Generally, I don't have any strong desire to hang onto Python 3.5 for much longer. I suppose shapely 1.8 could keep Python>=3.5, despite this version reaching EOL this year. We may want to target at release date for shapely 1.8 later this year (2020).

As for shapely 2.0 planning, I agree it should require Python>=3.6 to align with pygeos and much of scientific Python ecosystem lead by the NumPy folks.

**Comment by sgillies** [comment]
@jorisvandenbossche @mwtoews agreed. Python 3.6 for shapely 2.0.

**Comment by jorisvandenbossche** [comment]
Super, thanks!

**Comment by jorisvandenbossche** [comment]
This is already done for Shapely 1.8 (https://github.com/Toblerity/Shapely/commit/1b7020a8d3df40cbcfea1d5f358f335627236f7b), so closing.
