### ISSUE TITLE
Bug report: conflict with osgeo gdalnumeric

### ISSUE THREAD

**Issue by linzi1994** [Toblerity/Shapely#887]
if import gdalnumeric before LineString, it will raise ValueError: GEOSGeom_createLineString_r returned a NULL pointer.
```python
from osgeo import gdal, gdalnumeric
from shapely.geometry import LineString
LineString([[116.10524574, 39.78292819], [116.13446938, 39.77356737]])
```
but if import LineString before gdalnumeric, it will work.

**Comment by sgillies** [comment]
It's a known bug. The workaround is to use classes from the osgeo namespace instead of shapely.
