### ISSUE TITLE
two polygons with exact same coordinates behave differently

### ISSUE THREAD

**Issue by ilkkau** [Toblerity/Shapely#893]
#299  Expected behavior and actual behavior.

Polygon and its replica expected to give same result from union with other polygon. However, the results are different with Windows build code (similar with two versions). Linux gives identical polygons as expected. Polygon.wkt output is identical also in Windows.

Windows plot:
![image](https://user-images.githubusercontent.com/62253503/78540782-5550a080-77fd-11ea-85ea-458167b3fd8f.png)
## Steps to reproduce the problem.

import matplotlib.pyplot as plt
from shapely import geometry
from shapely import wkt

poly = [(25.0, 149.62243521664294), (87.213, 124.99299131589841), (87.213, 25.007008684101613), (25.0, 0.3775647833570249), (25.0, 149.62243521664294)]

ex_points = [(25.0, 150.0), (25.0, 0.0)]
p = geometry.Polygon(poly)
pr = p.buffer(-4).buffer(4)
ends = geometry.MultiPoint([ex_points[0], ex_points[-1]]).buffer(20)
ex = geometry.LineString(ex_points).buffer(5).union(ends)

not_rounded = p.intersection(ex)
not_rounded2 = wkt.loads(not_rounded.wkt)  # this should be identical to not_rounded

print(not_rounded.wkt == not_rounded2.wkt)

rv = pr.union(not_rounded)
rv2 = pr.union(not_rounded2)

plt.plot(*zip(*rv.exterior.coords[:]))
plt.plot(*zip(*rv2.exterior.coords[:]))
plt.show()

## Operating system

MS Windows 10 Pro version 10.0.18362 Build 18362

## Shapely version and provenance
1.7.0 windows (Shapely-1.7.0-cp37-cp37m-win_amd64.whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely
1.6.4 post2 (tested windows version vs. Ubuntu 18.04 LTS Anaconda)

**Comment by mwtoews** [comment]
I can't say I 100% follow what's expected or not, but I do see some differences between `rv` and `rv2` geometries with Christoph's Shapely package. Try installing re-installing Shapely using:

    pip install --force shapely

(which gets the correct file from [here](https://pypi.org/project/Shapely/1.7.0/#files)); this fixes the issue for me using the same version of Windows Python 3.7.

**Comment by ilkkau** [comment]
Thanks Mike, the problem is due to my shapely Windows installation. I had trouble to get shapely installed with pip, but in the end managed to fix the problem. Should I close the git case, I’m not familiar with the flow.

**Comment by mwtoews** [comment]
Thanks for checking back to confirm a fix. The pip install methods are new to Windows, so it's nice to see they work as expected.
