### ISSUE TITLE
Error in Point subtract operator

### ISSUE THREAD

**Issue by Red-Eyed** [Toblerity/Shapely#901]
## Expected behavior and actual behavior.
Actual behavior:
```python                  
(array('d', [4.0]), array('d', [4.0]))
```

Expected behavior:
```python
(array('d', [2.0]), array('d', [2.0]))
```

## Steps to reproduce the problem.
```python
from shapely.geometry import Point
p1 = Point((4,4)) 
p2 = Point((2,2)) 
p3 = p1 - p2 
print(p3.xy)
```

## Operating system
`Linux`

## Shapely version and provenance
`1.7.0`

## Python version
`Python 3.7.6`

**Comment by jorisvandenbossche** [comment]
I am not sure whether this is actually documented (don't directly find it in https://shapely.readthedocs.io/en/latest/manual.html), but the subtract operation actually performance a `difference` spatial operation:

```
In [4]: p1.difference(p2).xy 
Out[4]: (array('d', [4.0]), array('d', [4.0]))
```

So in that light, the result is as expected.

**Comment by Red-Eyed** [comment]
Yeah, I've found that. 
1. Could you explain me/give a link/search term, what does difference mean?
2. Is there any operator that performs distance like `p1.xy - p2.xy` ?

Thanks

**Comment by sgillies** [comment]
Shapely has some set-like properties, but they operate on the geometry point sets, not on the vertex values that parameterize the point sets. We have no operator that meets your needs for #2 @Red-Eyed . Okay if I close this?

Documentation of the set-like properties is another issue, I'll follow up.

**Comment by Red-Eyed** [comment]
Thanks.
