### ISSUE TITLE
shapely.geometry.shape is failing for polygons

### ISSUE THREAD

**Issue by invisibleroads** [Toblerity/Shapely#905]
## Expected behavior and actual behavior
- The function `shapely.geometry.shape` should not produce a segmentation fault.
- However, the function does produce a segmentation fault, unless speedups are disabled.

## Steps to reproduce the problem
The following script produces a segmentation fault.
```
from shapely.geometry import shape
shape({ "type": "Polygon", "coordinates": [ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ] ] })
```
The following script does not produce a segmentation fault.
```
from shapely import speedups
speedups.disable()
from shapely.geometry import shape
shape({ "type": "Polygon", "coordinates": [ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ] ] })
```

## Operating system
Fedora 31

## Shapely version and provenance
- shapely 1.7.0 installed via pip
- geos 3.7.1-2 installed via dnf

**Comment by invisibleroads** [comment]
shapely 1.6.4 does not have this issue even with speedups enabled!

**Comment by tomplex** [comment]
I can't replicate this on MacOS, or in the latest Python3 docker container (Debian Buster) or the latest Ubuntu docker container, either with the Shapely wheels or when compiled from source.

Did you install shapely with `--no-binary shapely`? if so, can you try installing the wheel and see if you get the same issue?

**Comment by invisibleroads** [comment]
That's strange. I retried my example and this time there was no segmentation fault using shapely 1.7.0. Is it possible that there was some kind of corrupted state of geos that was causing this to happen? Another possibility is that I had updated the kernel without rebooting? I will close this issue for now as I am not able to replicate the segmentation fault.
