### ISSUE TITLE
Simplify does not remove starting point

### ISSUE THREAD

**Issue by wikusbrinkNearmap** [Toblerity/Shapely#906]
## Expected behavior and actual behavior.

If the first point of a polygon can be removed by simplifying a polygon, it should.
Looks like this is not the case.

## Steps to reproduce the problem.

```
# Case 1: the point at (0, 0.5) is removed.
coords = [(0, 0), (0, 0.5), (0, 1), (1, 1), (1, 0)]
polygon = shapely.geometry.Polygon(coords)
simplified_polygon = polygon.simplify(0)

# Case 2: the point at (0, 0.5) is not removed.
coords = coords[1:] + [coords[0]]
polygon = shapely.geometry.Polygon(coords)
simplified_polygon = polygon.simplify(0)
```

<img width="618" alt="Screen Shot 2020-05-05 at 4 37 27 pm" src="https://user-images.githubusercontent.com/48225564/81040453-be0b6580-8eee-11ea-9d1c-a0733cd07038.png">

## Operating system

Mac OS X 10.15.3

## Shapely version and provenance

shapely==1.7.0, installed with Conda.

**Comment by tomplex** [comment]
The nature of the simplification algorithms implemented in GEOS (and exposed by Shapely) is that they use the start and end of the sequence of coordinates which they're simplifying as anchor points, and remove select coordinates in between. The animations in the [wiki article for the Douglas-Peucker algorithm](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm) are pretty demonstrative of how it works. In fact, the algorithm's instructions specify:

> The algorithm recursively divides the line. Initially it is given all the points between the first and last point. *It automatically marks the first and last point to be kept.*

Emphasis mine.

The [topology-preserving variant for simplification](http://geos.refractions.net/ro/doxygen_docs/html/classgeos_1_1simplify_1_1TopologyPreservingSimplifier.html) used by Shapely by default is a specialized case of Douglas-Peucker which ensures that the result has the same number of components and dimensionality as the input.

**Comment by wikusbrinkNearmap** [comment]
Ah, ok. Fair enough. Thanks for clearing this up for me.
