### ISSUE TITLE
Add documentation about the wkt precision

### ISSUE THREAD

**Issue by cyang-kth** [Toblerity/Shapely#910]
Currently, there are two ways to get the wkt of a geometry. 

The direct reading of `wkt` property of a geometry object returns a trimmed version of the geometry while the `dumps` function of a geometry returns a non-trimmed (high precision) of a geometry. 

https://github.com/Toblerity/Shapely/blob/c613520bc4a1fce667a18ac14ef95de62677c093/shapely/geometry/base.py#L363-L365

https://github.com/Toblerity/Shapely/blob/4433a841d379044bdca0a891f8fe79c6eed4e06d/shapely/wkt.py#L17-L22

Should this feature be documented in the official manual?

**Comment by tomplex** [comment]
Yes, I definitely feel this should be documented, especially considering with the property there's no real way to control the output, unlike when you use the serialization functions in the `wkt` module.

**Comment by apiszcz** [comment]
This may be related.

https://gis.stackexchange.com/questions/94856/wkt-precision-rounding-using-shapely

**Comment by sgillies** [comment]
@apiszcz thanks for the suggestion!

**Comment by tomplex** [comment]
@sgillies, this was resolved in 1.7.1.
