### ISSUE TITLE
Parallel Offset of a Polygon Edge with Shapely

### ISSUE THREAD

**Issue by adishavit** [Toblerity/Shapely#913]
I need to offset edges of a polygon by different amounts.
  
[`buffer()`][1] will parallel-offset all the edges by the same amount, and each in its edge-normal direction (and in both directions if applied to a `LineString`).   

[`parallel_offset()`][2] will offset a whole LineString by the same amount, but that means that if given only some edges of a polygon, the result is disconnected from the other neighboring polygon edges which were not offset. It will take care of the corners/joints only within the LineString and not on the sides.

Is there a way to nicely offset polygon edges with different amounts while still getting nice correct corners? 

[cross posted [here](https://gis.stackexchange.com/q/361496/156635)]

  [1]: https://shapely.readthedocs.io/en/latest/manual.html#object.buffer
  [2]: https://shapely.readthedocs.io/en/latest/manual.html#object.parallel_offset

**Comment by sgillies** [comment]
Sorry, @adishavit, those are the two buffering methods and they buffer entire geometries.
