### ISSUE TITLE
When will next version come out?

### ISSUE THREAD

**Issue by ssantichaivekin** [Toblerity/Shapely#917]
Hi Shapely team, I'm planning to use Shapely in my project that I will ship via PyInstaller. The current version has some bug that makes it not work with PyInstaller on computers with conda installed #916. The problem is fixed in pull request #843. I want to use a version with the fix and I wonder what is the planned release date for the next version. :)

**Comment by sgillies** [comment]
We don't have a 1.8.0 release on our roadmap yet. Can you use a patched version of shapely in your project as a work around? This is one of the advantages of pyinstaller, right, that your users won't need to install anything other than your package?

**Comment by ssantichaivekin** [comment]
The problem I have is that PyInstaller only packs the dylib/dll files correctly if I install Shapely from pypi. If I install Shapely from source (say, from my fork of the repo), Shapely will be installed in a different way and PyInstaller will not pack `libgeos_c.dylib` with my executable (except if I write a hook for PyInstaller for it to pack this correctly, which I still haven't learned how to do). The current workaround I'm using is installing Shapely from pypi and then modify the package directly before packing it by PyInstaller. I don't think that's clean. Do you have any suggestions on this?
