### ISSUE TITLE
pip install shapely does not work on Windows

### ISSUE THREAD

**Issue by FenryrMKIII** [Toblerity/Shapely#924]
Using an anaconda environment, doing `pip install shapely` does not work. It throws the error that `geos_c.dll` is not found.

Shapely version : 1.7.0
pip version : 20.1.1
Python version : 3.8.3

**Comment by jorisvandenbossche** [comment]
If you are using ananconda, you can do `conda install shapely` ?

See https://github.com/Toblerity/Shapely/pull/843 for  some discussion on pip installing in a conda environment on Windows (this was broken, and is fixed now in master, but not yet released)

**Comment by FenryrMKIII** [comment]
for some reasons, I would like to use pip

**Comment by jorisvandenbossche** [comment]
Note this is supported in master (and will be in the next release), so that quoted comment is no longer up to date (in practice of course it's still the case with the releaed version of shapely, but not the intention of the comment)
