### ISSUE TITLE
DOC: confusing note about numpy.asarray not copying the coordinate values

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Shapely#925]
The docs at https://shapely.readthedocs.io/en/latest/manual.html#numpy-and-python-arrays about the interaction with numpy say:

> The `numpy.asarray()` function does not copy coordinate values – at the price of slower Numpy access to the coordinates of Shapely objects.

I find this a bit confusing or misleading. 

First, it is still copying the original coordinate values  (it's not a view on the original GEOS coordinates), although it is true it does one copy less (it keeps the ctypes array as "base" of the numpy array, instead of taking a copy of the input, since`numpy.array()` has a `copy=True` default)

Second, I also don't really understand "at the price of slower Numpy access". What exactly becomes slower?

**Comment by sgillies** [comment]
Ah, that sentence is ancient. I must have had misconceptions about asarray being a view.

**Comment by jorisvandenbossche** [comment]
Thanks! 
I also updated the section on the array interface in the RFC: https://github.com/shapely/shapely-rfc/blob/df79554e19aa7182796eaa3fed22e0e7084607ef/rfc/0001-shapely-2.0-roadmap.md#the-array-interface-and-ctypes-attribute
