### ISSUE TITLE
.touches() function doesn't work with 2 ellipses/circles

### ISSUE THREAD

**Issue by brahmakulkarni** [Toblerity/Shapely#938]
## Expected behaviour and actual behaviour.

If I give one circle (ell) of radius 4 with centre at (0,0) and another circle (ell2) of radius 2 with centre at (6,0), they do touch each other at the point (4,0). However, when poly1.touches(poly2) is called, "false" is returned, when the correct return value should be "true".

## Steps to reproduce the problem.
```

from matplotlib import pyplot
from shapely.geometry.point import Point
import shapely.affinity
from descartes import PolygonPatch
from shapely.figures import SIZE, GREEN, GRAY, set_limits

BLUE = '#6699cc'

# 1st elem = center point (x,y) coordinates
# 2nd elem = the two semi-axis values (along x, along y)
# 3rd elem = angle in degrees between x-axis of the Cartesian base
#            and the corresponding semi-axis
ellipse = ((0, 0), (4, 4), 0)
ellipse2 = ((6, 0), (2, 2), 0)

# Let create a circle of radius 1 around center point:
circ = shapely.geometry.Point(ellipse[0]).buffer(1)
circ2 = shapely.geometry.Point(ellipse2[0]).buffer(1)

# Let create the ellipse along x and y:
ell  = shapely.affinity.scale(circ, ellipse[1][0], ellipse[1][1])
ell2  = shapely.affinity.scale(circ2, ellipse2[1][0], ellipse2[1][1])

print("Do the two ellipses touch? :-", ell2.touches(ell))
```

## Operating system

Ubuntu 20.04 LTS

## Shapely version and provenance

1.7.0 installed from PyPI using pip

**Comment by sgillies** [comment]
@brahmakulkarni I see what you mean. Mathematically they touch. The problem is with the floating point representations in our computers. Until shapely supports a fixed precision model, `touches` is not entirely reliable for geometries that theoretically touch only at one point. I hope this explanation helps.

**Comment by gbene** [comment]
Hello,

I am trying the same approach with lines that theoretically touch but the .touches() function sometimes still returns false. Has the fixed precision model been implemented or it is still a work in progress? 

Thanks!

**Comment by sgillies** [comment]
@gbene Shapely 2.0 can set geometries to a fixed precision: https://shapely.readthedocs.io/en/stable/reference/shapely.set_precision.html?highlight=set_precision#shapely.set_precision. Can you try this on your lines?

There's more to the circle case than I explained before. Buffering a Point produces not a true circle, but a many-sided polygon that is inscribed in the circle. Such buffers may not touch as expected due solely to the fact that they are a little smaller than the true circles.
