### ISSUE TITLE
Question on getting the index of line segment (two consecutive coordinates in LineString)

### ISSUE THREAD

**Issue by Luvata** [Toblerity/Shapely#940]
Thank you for your powerful library, it helps me a lot when processing geometry 

I have a question on getting the index of line segment  

My input:
 - A long list of Point, called it `Ps`
 - A LineString `L`
 - I have a Polygon made by buffering `L`, called it `B`

After `prep` the buffer, I can efficiently select which point of `Ps` that lies inside `B` by using `contains`. I called these inside points are `P_inside`

Since I have a LineString with many coords (64k coords) and huge number of points (20k points)
My question is for each point of  `P_inside`, how can I efficiently find out which is its corresponding line segment (index of two consecutive coords in `L`) ?

**Comment by sgillies** [comment]
@Luvata this issue tracker isn't for usage questions, please see https://github.com/Toblerity/Shapely#support. 

In practice, we cannot rely on mapping between the input coordinates of a geometry and the coordinates of the created geometry object, especially after operations like `prep` and `buffer`. The GEOS library may reorder coordinates as part of its implementation.
