### ISSUE TITLE
Is there a guarantee on the order of `envelope` points?

### ISSUE THREAD

**Issue by adishavit** [Toblerity/Shapely#942]
We noticed that the `.envelope` polygon seems to start from (minx, miny) then proceed counter clockwise to (maxx, maxy) and close.  
Is this order guaranteed? 

If so if should be mentioned in the docs.

**Comment by sgillies** [comment]
No, the order is not guaranteed.

**Comment by mwtoews** [comment]
@adishavit use the `.bounds` method to return `xmin, ymin, xmax, ymax,` [as is documented](https://shapely.readthedocs.io/en/latest/manual.html#object.bounds). You can use this with [`box`](https://shapely.readthedocs.io/en/latest/manual.html#shapely.geometry.box) to toggle `ccw` as required.
