### ISSUE TITLE
voronoi_diagram for polygons

### ISSUE THREAD

**Issue by longavailable** [Toblerity/Shapely#948]
@tomplex Hi Tom, `voronoi_diagram` is really useful. I was trying to create Voronoi diagrams for some polygons.  

Input geometries:

<img src="https://user-images.githubusercontent.com/24582280/88407754-de064300-cdd2-11ea-89bb-be33404a2f90.png" width="360" height="335">

Geometries `voronoi_diagram` returned:

<img src="https://user-images.githubusercontent.com/24582280/88407908-1ad23a00-cdd3-11ea-8bde-36999c220d28.png" width="360" height="335">

I don't think they are ideal Voronoi polygons. 

Although I can make it by a few tricks, I am wondering if it's possible to improve it in-place.

<img src="https://user-images.githubusercontent.com/24582280/88408085-5836c780-cdd3-11ea-9ce2-809f957c61b7.png" width="360" height="335">

**Comment by tomplex** [comment]
Hi @longavailable, `shapely`'s implementation of this algorithm comes directly from the GEOS library; it's simply wrapping it and making it available through the Python API. We don't do anything special other than validate inputs to avoid known error cases.

If I were you I would try using the centroids of your polygons as input to the `voronoi_diagram` function and see if that gives you better results.

**Comment by tomplex** [comment]
P.S. at least the result in the first image looks pretty cool! =)

**Comment by longavailable** [comment]
> Hi @longavailable, `shapely`'s implementation of this algorithm comes directly from the GEOS library; we're simply wrapping it and making it available through the Python API. We don't do anything special other than validate inputs to avoid known error cases.
> 
> The [documentation of the function](https://shapely.readthedocs.io/en/latest/manual.html#voronoi-diagram) states:
> 
> > The source may be any geometry type. All vertices of the geometry will be used as the input points to the diagram.
> 
> If I were you I would try using the centroids of your polygons as input to the `voronoi_diagram` function and see if that gives you better results.

Got it. Points or polygons may be different needs. It was this state that gave me a clue - possible for polygons. Anyway, I can make it by a few further steps based on its output. Thanks for your explanation. I'll close this.

> P.S. at least the result in the first image looks pretty cool! =)

Completely!

**Comment by longavailable** [comment]
If anyone is interested in this output, please refer to my mini package-[voronoi-diagram-for-polygons](https://github.com/longavailable/voronoi-diagram-for-polygons).

> <img alt="" width="360" height="335" src="https://user-images.githubusercontent.com/24582280/88408085-5836c780-cdd3-11ea-9ce2-809f957c61b7.png">
