### ISSUE TITLE
 mapping(geom) includes extra comma which is not valid json

### ISSUE THREAD

**Issue by simonm3** [Toblerity/Shapely#953]
At the end of the coordinates there is an extra comma. This makes it invalid json which is rejected by some packages such as mapboxgl.

Originally reported here:

https://github.com/geopandas/geopandas/issues/1551#issuecomment-667238864

**Comment by sgillies** [comment]
@simonm3 @martinfleis `mapping()` returns a Python mapping (a dict, specifically), not JSON. A trailing comma is not a problem with the method. If you want JSON, you absolutely must do `json.dumps(mapping(geom))`, that's the only guarantee of valid JSON.
