### ISSUE TITLE
buffer() doesn't properly apply join_style at LinearRing's closing vertex

### ISSUE THREAD

**Issue by abey79** [Toblerity/Shapely#958]
## Expected behavior and actual behavior.

I'm trying to apply `buffer(0.1, join_style=2) to a simple LinearRing. I'm expecting all the corners of the resulting polygon's exterior to exhibit the desired join style. However, the corner corresponding to the first/last vertex always has join_style=1.

This might be linked to #790.

## Steps to reproduce the problem.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/49431240/89714752-552a0280-d9a1-11ea-820c-b0f1ca7c5d74.png">

Note: setting cap_style=3 appears to fix the issue in this particular case. It doesn't in the general case, when the corner at the closing vertex is not 90°.

## Operating system

Mac OS X 10.15.6

## Shapely version and provenance

Shapely 1.7.0 (installed via pip)
Python 3.8.5 (installed via MacPort)
GEOS 3.8.1_0 (installed via MacPort)

**Comment by sgillies** [comment]
@abey79 thank you for the report! This may be expected behavior for the underlying GEOS algorithm, by which I mean "cap style" applies to the ends of a line or ring even though a ring is closed and doesn't have ends.

**Comment by sgillies** [comment]
Aha, it's a known issue in GEOS (and JTS, maybe) that the developers have punted: https://trac.osgeo.org/geos/ticket/589. I'm going to mark this as an upstream issue that Shapely won't fix.
