### ISSUE TITLE
LineString().coords should return an empty CoordinateSequence, not list

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#959]
Reported at https://github.com/Toblerity/Shapely/pull/955#discussion_r467715843.

**Comment by chadwhawkins** [comment]
@sgillies I can work on this one. Wouldn't this also be true for both Points and LinearRings as well?

**Comment by jorisvandenbossche** [comment]
@chadwhawkins yes, indeed it should be done for all geometries having a coords property (which include Point and LinearRing, in addition to LineString)
