### ISSUE TITLE
STRtree Nearest method always returns one geometry

### ISSUE THREAD

**Issue by carlosg-m** [Toblerity/Shapely#967]
Create two points that are equidistant to a Line.
```
from shapely.strtree import STRtree
from shapely import wkt
from shapely.geometry import box, Point, LineString

keys = []
keys.append(Point(1.5, 3))
keys.append(Point(1, 2.5))

query = LineString([Point(1,2),Point(3,4)])

for i, g in enumerate(keys):
    bbox_intersects = box(*g.bounds).intersects(query)
    print(i, bbox_intersects, g.distance(query))

# 0 False 0.3535533905932738
# 1 False 0.3535533905932738
```
Create the tree and query for the nearest neighbor. Only one geometry will be returned.
```
tree = STRtree(keys)
result = tree.nearest(query)

print(result)

# POINT (1 2.5)
```

Does anyone know of an efficient workaround that always guarantees the nearest neighbor between two geometries and doesn't yield false negatives?

**Comment by tomplex** [comment]
The [docstrings](https://github.com/Toblerity/Shapely/blob/53c9cf6c48a7717f45581c8e40b1bf5f205ae728/shapely/strtree.py#L175) are pretty clear that the `nearest` method will only return one geometry, even if several are the same distance away. This is not mentioned in the manual, so perhaps it should be updated to include that tidbit

If you want another option, the [`rtree`](https://toblerity.org/rtree/) library allows you to query the nearest `n` geometries, but even then will not specifically return all geometries with minimum distance `d`.

**Comment by carlosg-m** [comment]
> The [docstrings](https://github.com/Toblerity/Shapely/blob/53c9cf6c48a7717f45581c8e40b1bf5f205ae728/shapely/strtree.py#L175) are pretty clear that the `nearest` method will only return one geometry, even if several are the same distance away. This is not mentioned in the manual, so perhaps it should be updated to include that tidbit
> 
> If you want another option, the [`rtree`](https://toblerity.org/rtree/) library allows you to query the nearest `n` geometries, and it [appears that](https://toblerity.org/rtree/class.html#rtree.index.Index.nearest) it has the behavior you desire.

Thank you for the answer. I was afraid someone was going to say that. Basically I've already tried this library but unfortunately their nearest neighbours method is just an approximation and can produce false negatives.

Basically if you have geometry A and B near geometry C, and A is nearest to C and doesn't intersect C, and B is farthest but intersects C, and you query for the closest to C, their implementation will keep A out of the results.

You can increase the number of neighbors but it will never guarantee you 100% recall.

I've tried discussing this issue with them but ended up annoying them.

https://github.com/Toblerity/rtree/issues/164

The only thing I can think of is interpolating the polygon exteriors to guarantee evenly spaced vertices, and use a kd-tree on the vertices. But this again is an approximation, it's time consuming and might produce hundreds of millions of points.

This is a weird problem. Does anyone know of any Python solutions?

**Comment by tomplex** [comment]
> Basically if you have geometry A and B near geometry C, and A is nearest to C and doesn't intersect C, and B is farthest but intersects C, and you query for the closest to C, their implementation will keep A out of the results.

I'm not totally sure I follow this. If one geometry is intersecting your query, how is that geometry *not* the nearest to it? Do you have an example which shows this situation? 

Either way, if our method only returns one geometry for `nearest`, why not just query the tree for intersections with the single nearest geometry which came back. If there are duplicates of that geometry in the tree, they should all be returned from the `query` method.

**Comment by carlosg-m** [comment]
> I'm not totally sure I follow this. If one geometry is intersecting your query, how is that geometry _not_ the nearest to it? Do you have an example which shows this situation?

I was talking about [rtree](https://github.com/Toblerity/rtree). 

```
from shapely import wkt
from shapely.geometry import box, Point, LineString

lines = []
lines.append(wkt.loads('LINESTRING (85.67 82832.35, 64 80858)'))
lines.append(wkt.loads('LINESTRING (85.66 82832.36, 39 80893)'))

point = wkt.loads('POINT (63.58 80913.20)')

for i, g in enumerate(lines):
    bbox_intersects = box(*g.bounds).intersects(point)
    print(i, bbox_intersects, g.distance(point))

# 0 False 1.0258003965981903
# 1 True 24.087027947634724
```
```
sindex = rtree.index.Index()

for i, g in enumerate(lines):
    sindex.insert(i, g.bounds)

# nearest 8 bounding boxes
nearest_list = list(sindex.nearest(point.bounds, num_results=1))
print(nearest_list)

# [1]
```

**Comment by carlosg-m** [comment]
> Either way, if our method only returns one geometry for `nearest`, why not just query the tree for intersections with the single nearest geometry which came back. If there are duplicates of that geometry in the tree, they should all be returned from the `query` method.

I thought of that. But look at my first example:

```
from shapely.strtree import STRtree
from shapely import wkt
from shapely.geometry import box, Point, LineString

keys = []
keys.append(Point(1.5, 3))
keys.append(Point(1, 2.5))

query = LineString([Point(1,2),Point(3,4)])

for i, g in enumerate(keys):
    bbox_intersects = box(*g.bounds).intersects(query)
    print(i, bbox_intersects, g.distance(query))

# 0 False 0.3535533905932738
# 1 False 0.3535533905932738
```
Both points are equidistant to the Line, but none of them intersects it.
```
tree = STRtree(keys)
result = tree.query(tree.nearest(query))
result = [r.wkt for r in result]

print(result)

# ['POINT (1 2.5)']
```

**Comment by tomplex** [comment]
Ah, I see what you're saying. In that case I would probably try something like:

- start by querying the tree for the bounding box of the geometry of interest
- if no results are returned, increase the size bounding box by some set amount and re-query. Figuring out the right amount will probably be the difficult part here and will depend on the density and distribution of your dataset.
- if results are returned, find all results which are the minimum distance from the geometry of interest. This will require a distance calculation for all returned results.

[this gist](https://gist.github.com/tomplex/0799e07c0a16381a32e85413be0102a7) describes what I mean. It returns both points for a couple of different symmetric situations like the one you posted above:

![Screen Shot 2020-08-18 at 10 58 31 PM](https://user-images.githubusercontent.com/8109856/90587190-c1c5ae00-e1a6-11ea-9395-11ed4de7ab9a.png)

**Comment by tomplex** [comment]
All that said, perhaps the manual could use an update to include the information in the docstrings about only returning one geometry when multiple are the same nearest distance. Otherwise I don't think there's an issue here.

**Comment by carlosg-m** [comment]
> Ah, I see what you're saying. In that case I would probably try something like:
> 
> * start by querying the tree for the bounding box of the geometry of interest
> * if no results are returned, increase the size bounding box by some set amount and re-query. Figuring out the right amount will probably be the difficult part here and will depend on the density and distribution of your dataset.
> * if results are returned, find all results which are the minimum distance from the geometry of interest. This will require a distance calculation for all returned results.
> 
> [this gist](https://gist.github.com/tomplex/0799e07c0a16381a32e85413be0102a7) describes what I mean. It returns both points for a couple of different symmetric situations like the one you posted above:
> 
> ![Screen Shot 2020-08-18 at 10 58 31 PM](https://user-images.githubusercontent.com/8109856/90587190-c1c5ae00-e1a6-11ea-9395-11ed4de7ab9a.png)

Thank you, that's a great idea! I've considered searching within a radius, similar to a BallTree, and for that I was going to use a Points and buffer operations, but your approach seems faster, simpler and generalizes to all shapes.

**Comment by carlosg-m** [comment]
@tomplex, I've adapted your fantastic solution to my problem. 

This is probably python's only rtree solution for exact nearest neighbors search that guarantees 100% recall and generalizes to multiple geometries. 

I wasn't able to test performance, but I hope it scales to couple million geometries.

Once again thank you!

Example dataset:
```
from shapely.strtree import STRtree
from shapely import wkt
from shapely.geometry import box, Point, LineString
import numpy as np

keys = []
keys.append(Point(1.5, 3))
keys.append(Point(1, 2.5))
keys.append(Point(3.3, 5.5))
keys.append(LineString([Point(-1,-2),Point(6,7)]))

query = LineString([Point(1,2),Point(3,4)])

for i, g in enumerate(keys):
    bbox_intersects = box(*g.bounds).intersects(query)
    print(i, bbox_intersects, g.distance(query))

# 0 False 0.3535533905932738
# 1 False 0.3535533905932738
# 2 False 1.5297058540778354
# 3 True 0.5262348115842175
```

- Create STRtree
- Query STRtree for the first nearest neighbor
- Get distance to first nearest neighbor
- Expand query geometry bounding box to include minimum distance
- Query STRtree for all geometries that intersect previously created bounding box
- Search for false positives, filter candidate geometries that are greater than minimum distance
```
tree = STRtree(keys)
result = tree.nearest(query)
min_distance = result.distance(query)

def _expand(geom, amt):
    amt = amt + np.finfo(np.float64).eps
    bounds = geom.bounds
    bounds = (bounds[0] - amt, bounds[1] - amt, bounds[2] + amt, bounds[3] + amt)
    return box(*bounds)

bbox_search = _expand(point, min_distance)
result = tree.query(bbox_search)

print([g.wkt for g in result])

# ['POINT (1 2.5)', 'LINESTRING (-1 -2, 6 7)', 'POINT (1.5 3)']
```
