### ISSUE TITLE
unary_union provides wrong result

### ISSUE THREAD

**Issue by Dinosaver** [Toblerity/Shapely#970]
I've been kicked out from conda github, so have to post the issue here. 

## Expected behavior and actual behavior.

The following geometry, being split into seingle segment linestrings cannot be build back by unary_union operation:
'MULTILINESTRING ((-0.6576979014845081 1.601480154089968, -0.5760076586550748 1.594118888807711), (-0.5760076586550748 1.594118888807711, -0.4943174158256414 1.586757623525453), (-0.4943174158256414 1.586757623525453, -0.412627172996208 1.579396358243196), (-0.412627172996208 1.579396358243196, -0.3309369301667746 1.572035092960939), (-0.6698736576063997 1.466362013920959, -0.5881834147769663 1.459000748638702), (-0.5881834147769663 1.459000748638702, -0.506493171947533 1.451639483356445), (-0.506493171947533 1.451639483356445, -0.4248029291180996 1.444278218074187), (-0.4248029291180996 1.444278218074187, -0.3431126862886662 1.43691695279193), (-0.6820496602460158 1.331241138068341, -0.6003594174165824 1.323879872786084), (-0.6003594174165824 1.323879872786084, -0.518669174587149 1.316518607503827), (-0.518669174587149 1.316518607503827, -0.4369789317577156 1.30915734222157), (-0.4369789317577156 1.30915734222157, -0.3552886889282822 1.301796076939312), (-0.6942256628856115 1.19612026221595, -0.6125354200561781 1.188758996933693), (-0.6125354200561781 1.188758996933693, -0.5308451772267447 1.181397731651435), (-0.5308451772267447 1.181397731651435, -0.4491549343973113 1.174036466369178), (-0.4491549343973113 1.174036466369178, -0.3674646915678779 1.166675201086921), (-0.7064014190075235 1.061002122046715, -0.6247111761780901 1.053640856764457), (-0.6247111761780901 1.053640856764457, -0.5430209333486568 1.0462795914822), (-0.5430209333486568 1.0462795914822, -0.4613306905192234 1.038918326199943), (-0.4613306905192234 1.038918326199943, -0.37964044768979 1.031557060917686), (-0.7185774216471191 0.9258812461943232, -0.6368871788176858 0.9185199809120661), (-0.6368871788176858 0.9185199809120661, -0.5551969359882524 0.9111587156298089), (-0.5551969359882524 0.9111587156298089, -0.473506693158819 0.9037974503475517), (-0.473506693158819 0.9037974503475517, -0.3918164503293856 0.8964361850652945), (-0.7307531777690311 0.7907631060250878, -0.6490629349395978 0.7834018407428307), (-0.6490629349395978 0.7834018407428307, -0.5673726921101644 0.7760405754605735), (-0.5673726921101644 0.7760405754605735, -0.485682449280731 0.7686793101783163), (-0.485682449280731 0.7686793101783163, -0.4039922064512976 0.7613180448960591), (-0.7429291804086269 0.6556422301726965, -0.6612389375791935 0.6482809648904393), (-0.6612389375791935 0.6482809648904393, -0.5795486947497601 0.6409196996081822), (-0.5795486947497601 0.6409196996081822, -0.4978584519203267 0.6335584343259251), (-0.4978584519203267 0.6335584343259251, -0.4161682090908933 0.6261971690436678), (-0.7551051830482327 0.520521354320192, -0.6734149402187993 0.5131600890379348), (-0.6734149402187993 0.5131600890379348, -0.591724697389366 0.5057988237556776), (-0.591724697389366 0.5057988237556776, -0.5100344545599326 0.4984375584734204), (-0.5100344545599326 0.4984375584734204, -0.4283442117304992 0.4910762931911632), (-0.7672809391701243 0.3854032141511831, -0.6855906963406909 0.3780419488689258), (-0.6855906963406909 0.3780419488689258, -0.6039004535112575 0.3706806835866687), (-0.6039004535112575 0.3706806835866687, -0.5222102106818243 0.3633194183044115), (-0.5222102106818243 0.3633194183044115, -0.4405199678523908 0.3559581530221543), (-0.9306610432639912 -1.427676448810457, -0.8489708004345579 -1.435037714092715), (-0.8489708004345579 -1.435037714092715, -0.7672805576051245 -1.442398979374972), (-0.7672805576051245 -1.442398979374972, -0.6855903147756911 -1.449760244657229), (-0.6855903147756911 -1.449760244657229, -0.6039000719462577 -1.457121509939486), (-0.9184850406243956 -1.292555572958066, -0.8367947977949622 -1.299916838240323), (-0.8367947977949622 -1.299916838240323, -0.7551045549655289 -1.30727810352258), (-0.7551045549655289 -1.30727810352258, -0.6734143121360955 -1.314639368804838), (-0.6734143121360955 -1.314639368804838, -0.5917240693066621 -1.322000634087095), (-0.906309284502504 -1.157437432789057, -0.8246190416730707 -1.164798698071314), (-0.8246190416730707 -1.164798698071314, -0.7429287988436373 -1.172159963353572), (-0.7429287988436373 -1.172159963353572, -0.6612385560142039 -1.179521228635829), (-0.6612385560142039 -1.179521228635829, -0.5795483131847705 -1.186882493918086), (-0.894133281862888 -1.022316556936439, -0.8124430390334546 -1.029677822218697), (-0.8124430390334546 -1.029677822218697, -0.7307527962040212 -1.037039087500954), (-0.7307527962040212 -1.037039087500954, -0.6490625533745878 -1.044400352783211), (-0.6490625533745878 -1.044400352783211, -0.5673723105451545 -1.051761618065468), (-0.881957279223282 -0.887195681083935, -0.8002670363938487 -0.8945569463661922), (-0.8002670363938487 -0.8945569463661922, -0.7185767935644153 -0.9019182116484493), (-0.7185767935644153 -0.9019182116484493, -0.6368865507349819 -0.9092794769307064), (-0.6368865507349819 -0.9092794769307064, -0.5551963079055485 -0.9166407422129637), (-0.8697815231014007 -0.7520775409150393, -0.7880912802719673 -0.7594388061972965), (-0.7880912802719673 -0.7594388061972965, -0.7064010374425339 -0.7668000714795536), (-0.7064010374425339 -0.7668000714795536, -0.6247107946131005 -0.7741613367618108), (-0.6247107946131005 -0.7741613367618108, -0.5430205517836671 -0.781522602044068), (-0.8576055204617845 -0.6169566650624215, -0.7759152776323511 -0.6243179303446786), (-0.7759152776323511 -0.6243179303446786, -0.6942250348029178 -0.6316791956269359), (-0.6942250348029178 -0.6316791956269359, -0.6125347919734844 -0.6390404609091931), (-0.6125347919734844 -0.6390404609091931, -0.530844549144051 -0.6464017261914502), (-0.8454295178221787 -0.481835789209917, -0.7637392749927453 -0.4891970544921742), (-0.7637392749927453 -0.4891970544921742, -0.6820490321633119 -0.4965583197744314), (-0.6820490321633119 -0.4965583197744314, -0.6003587893338785 -0.5039195850566885), (-0.6003587893338785 -0.5039195850566885, -0.5186685465044452 -0.5112808503389458), (-0.8332537617002769 -0.3467176490407948, -0.7515635188708435 -0.3540789143230521), (-0.7515635188708435 -0.3540789143230521, -0.6698732760414101 -0.3614401796053092), (-0.6698732760414101 -0.3614401796053092, -0.5881830332119767 -0.3688014448875664), (-0.5881830332119767 -0.3688014448875664, -0.5064927903825434 -0.3761627101698236), (-0.8210777590606811 -0.2115967731884035, -0.7393875162312478 -0.2189580384706607), (-0.7393875162312478 -0.2189580384706607, -0.6576972734018144 -0.2263193037529179), (-0.6576972734018144 -0.2263193037529179, -0.576007030572381 -0.2336805690351751), (-0.576007030572381 -0.2336805690351751, -0.4943167877429477 -0.2410418343174323), (-0.4526959704920171 0.2208372771694233, -0.4859475131545354 0.1930830793980719), (-0.4859475131545354 0.1930830793980719, -0.5191990558170538 0.1653288816267205), (-0.5191990558170538 0.1653288816267205, -0.5524505984795721 0.137574683855369), (-0.5524505984795721 0.137574683855369, -0.5857021411420905 0.1098204860840176), (-0.7794569418097506 0.2502823382984521, -0.7517027440383682 0.2170307956359595), (-0.7517027440383682 0.2170307956359595, -0.7239485462669859 0.1837792529734669), (-0.7239485462669859 0.1837792529734669, -0.6961943484956037 0.1505277103109743), (-0.6961943484956037 0.1505277103109743, -0.6684401507242214 0.1172761676484817), (-0.4821410316210357 -0.1059236941481969, -0.5098952293924154 -0.072672151485676), (-0.5098952293924154 -0.072672151485676, -0.5376494271637952 -0.0394206088231551), (-0.5376494271637952 -0.0394206088231551, -0.5654036249351749 -0.006169066160634187), (-0.5654036249351749 -0.006169066160634187, -0.5931578227065547 0.02708247650188672), (-0.8089020029387691 -0.07647863301916814, -0.7756504602762482 -0.0487244352477884), (-0.7756504602762482 -0.0487244352477884, -0.7423989176137273 -0.02097023747640865), (-0.7423989176137273 -0.02097023747640865, -0.7091473749512065 0.006783960294971095), (-0.7091473749512065 0.006783960294971095, -0.6758958322886855 0.03453815806635084), (-0.8089020029387691 -0.07647863301916814, -0.7272117601093357 -0.08383989830142534), (-0.7272117601093357 -0.08383989830142534, -0.6455215172799024 -0.09120116358368252), (-0.6455215172799024 -0.09120116358368252, -0.563831274450469 -0.09856242886593972), (-0.563831274450469 -0.09856242886593972, -0.4821410316210357 -0.1059236941481969), (-0.7794569418097506 0.2502823382984521, -0.7868182070920052 0.168592095469047), (-0.7868182070920052 0.168592095469047, -0.7941794723742599 0.08690185263964198), (-0.7941794723742599 0.08690185263964198, -0.8015407376565145 0.005211609810236939), (-0.8015407376565145 0.005211609810236939, -0.8089020029387691 -0.07647863301916813), (-0.4526959704920171 0.2208372771694233, -0.5343862133214504 0.2281985424516805), (-0.5343862133214504 0.2281985424516805, -0.6160764561508838 0.2355598077339377), (-0.6160764561508838 0.2355598077339377, -0.6977666989803172 0.2429210730161949), (-0.6977666989803172 0.2429210730161949, -0.7794569418097506 0.2502823382984521), (-0.4821410316210357 -0.1059236941481969, -0.4747797663387811 -0.02423345131879184), (-0.4747797663387811 -0.02423345131879184, -0.4674185010565264 0.05745679151061323), (-0.4674185010565264 0.05745679151061323, -0.4600572357742717 0.1391470343400183), (-0.4600572357742717 0.1391470343400183, -0.4526959704920171 0.2208372771694234), (-0.6160758280681697 -1.592239650108722, -0.5417471029329169 -0.7673907453781521), (-0.5417471029329169 -0.7673907453781521, -0.4674183777976642 0.05745815935241749), (-0.4674183777976642 0.05745815935241749, -0.3930896526624113 0.8823070640829869), (-0.3930896526624113 0.8823070640829869, -0.3187609275271585 1.707155968813557), (-0.9428367993859033 -1.562794588979693, -0.8685080742506505 -0.7379456842491232), (-0.8685080742506505 -0.7379456842491232, -0.7941793491153977 0.08690322048144639), (-0.7941793491153977 0.08690322048144639, -0.7198506239801449 0.9117521252120158), (-0.7198506239801449 0.9117521252120158, -0.6455218988448921 1.736601029942586), (-0.9993957611019492 -1.459318228223596, -0.983057575751899 -1.460790493605932), (-0.983057575751899 -1.460790493605932, -0.966719390401849 -1.462262758988268), (-0.966719390401849 -1.462262758988268, -0.9503812050517988 -1.463735024370604), (-0.9503812050517988 -1.463735024370604, -0.9340430197017486 -1.465207289752941), (-0.7196684199292575 1.644902792245065, -0.7033302345792073 1.643430526862729), (-0.7033302345792073 1.643430526862729, -0.6869920492291572 1.641958261480392), (-0.6869920492291572 1.641958261480392, -0.6706538638791071 1.640485996098056), (-0.6706538638791071 1.640485996098056, -0.6543156785290569 1.63901373071572), (-0.859531438839926 0.09279159215271227, -1.159645638350528 0.1499009901749203), (-1.159645638350528 0.1499009901749203, -1.442851736820215 0.2644624229519199), (-1.442851736820215 0.2644624229519199, -1.698266282708604 0.4320733588688825), (-1.698266282708604 0.4320733588688825, -1.916073838255332 0.6462926036558143), (-1.998004052704932 -0.2629123844577409, -1.745408824489664 -0.09108204146443584), (-1.745408824489664 -0.09108204146443584, -1.464144705809355 0.02816774525781686), (-1.464144705809355 0.02816774525781686, -1.165020519010141 0.09025427328133792), (-1.165020519010141 0.09025427328133792, -0.8595314388399259 0.09279159215271232), (-0.7196684199292575 1.644902792245065, -1.01876983555948 1.395249987913508), (-1.01876983555948 1.395249987913508, -1.317871251189702 1.145597183581952), (-1.317871251189702 1.145597183581952, -1.616972666819924 0.8959443792503951), (-1.616972666819924 0.8959443792503951, -1.916074082450146 0.6462915749188385), (-0.9993950635108855 -1.459318408544343, -1.24904735831936 -1.160217009463332), (-1.24904735831936 -1.160217009463332, -1.498699653127834 -0.8611156103823205), (-1.498699653127834 -0.8611156103823205, -1.748351947936309 -0.5620142113013092), (-1.748351947936309 -0.5620142113013092, -1.998004242744783 -0.2629128122202979), (-0.6543156785290569 1.63901373071572, -0.7242475138222298 0.862958475598555), (-0.7242475138222298 0.862958475598555, -0.7941793491154028 0.08690322048138976), (-0.7941793491154028 0.08690322048138976, -0.8641111844085757 -0.6891520346357756), (-0.8641111844085757 -0.6891520346357756, -0.9340430197017486 -1.465207289752941), (-0.7196684199292575 1.644902792245065, -0.7896002552224304 0.8688475371278995), (-0.7896002552224304 0.8688475371278995, -0.8595320905156033 0.09279228201073431), (-0.8595320905156033 0.09279228201073431, -0.9294639258087762 -0.683262973106431), (-0.9294639258087762 -0.683262973106431, -0.9993957611019492 -1.459318228223596), (-1.008188929795388 -1.556906668802002, -0.9918509297880254 -1.558378917482751), (-0.9918509297880254 -1.558378917482751, -0.9755129297806626 -1.5598511661635), (-0.9755129297806626 -1.5598511661635, -0.9591749297732999 -1.561323414844249), (-0.9591749297732999 -1.561323414844249, -0.9428369297659371 -1.562795663524999), (-0.9993950628321178 -1.459318401011847, -1.001593529572935 -1.483715467959386), (-1.001593529572935 -1.483715467959386, -1.003791996313753 -1.508112534906924), (-1.003791996313753 -1.508112534906924, -1.00599046305457 -1.532509601854463), (-1.00599046305457 -1.532509601854463, -1.008188929795388 -1.556906668802002), (-0.7108739478844331 1.742489853107766, -0.7130724146252558 1.718092786160171), (-0.7130724146252558 1.718092786160171, -0.7152708813660785 1.693695719212575), (-0.7152708813660785 1.693695719212575, -0.7174693481069012 1.66929865226498), (-0.7174693481069012 1.66929865226498, -0.7196678148477239 1.644901585317385), (-0.6455219478549822 1.736600858384769, -0.6618599478623449 1.738073107065518), (-0.6618599478623449 1.738073107065518, -0.6781979478697077 1.739545355746267), (-0.6781979478697077 1.739545355746267, -0.6945359478770704 1.741017604427017), (-0.6945359478770704 1.741017604427017, -0.7108739478844331 1.742489853107766), (-0.6543158148182729 1.639012590594388, -0.6521173480774503 1.663409657541983), (-0.6521173480774503 1.663409657541983, -0.6499188813366276 1.687806724489578), (-0.6499188813366276 1.687806724489578, -0.6477204145958049 1.712203791437174), (-0.6477204145958049 1.712203791437174, -0.6455219478549822 1.736600858384769), (-0.9428369297659371 -1.562795663524999, -0.9406384630251196 -1.53839859657746), (-0.9406384630251196 -1.53839859657746, -0.938439996284302 -1.514001529629921), (-0.938439996284302 -1.514001529629921, -0.9362415295434844 -1.489604462682383), (-0.9362415295434844 -1.489604462682383, -0.9340430628026668 -1.465207395734844), (-0.7196684199292575 1.644902792245065, -0.7033302345792073 1.643430526862729), (-0.7033302345792073 1.643430526862729, -0.6869920492291572 1.641958261480392), (-0.6869920492291572 1.641958261480392, -0.6706538638791071 1.640485996098056), (-0.6706538638791071 1.640485996098056, -0.6543156785290569 1.63901373071572), (-0.9993957611019492 -1.459318228223596, -0.983057575751899 -1.460790493605932), (-0.983057575751899 -1.460790493605932, -0.966719390401849 -1.462262758988268), (-0.966719390401849 -1.462262758988268, -0.9503812050517988 -1.463735024370604), (-0.9503812050517988 -1.463735024370604, -0.9340430197017486 -1.465207289752941), (1.972238675020841 1.541886069483511, 1.97867976299911 1.613364819515621), (1.97867976299911 1.613364819515621, 1.985120850977379 1.68484356954773), (1.985120850977379 1.68484356954773, 1.991561938955647 1.75632231957984), (1.991561938955647 1.75632231957984, 1.998003026933916 1.827801069611949), (1.671243071408027 -1.798355452444507, 1.752933071444756 -1.805716695848246), (1.752933071444756 -1.805716695848246, 1.834623071481485 -1.813077939251984), (1.834623071481485 -1.813077939251984, 1.916313071518214 -1.820439182655723), (1.916313071518214 -1.820439182655723, 1.998003071554943 -1.827800426059461), (1.968558053318982 1.50104106946526, 1.894229307841243 0.6761919389878184), (1.894229307841243 0.6761919389878184, 1.819900562363505 -0.1486571914896235), (1.819900562363505 -0.1486571914896235, 1.745571816885766 -0.9735063219670657), (1.745571816885766 -0.9735063219670657, 1.671243071408027 -1.798355452444507))' 

## Steps to reproduce the problem.

(For example, a script with required data)

## Operating system
shapely 1.7.0 py37h98ec03d_0
conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.1.final.0
       virtual packages : __glibc=2.28
       base environment : /opt/conda  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          platform : linux-64

**Comment by mwtoews** [comment]
This is an upstream bug with GEOS, see [geos#1046](https://trac.osgeo.org/geos/ticket/1046) for details.

**Comment by mwtoews** [comment]
Good news: this bug was resolved (via OverlayNG) with GEOS 3.9.0beta1 to be released soon.
