### ISSUE TITLE
parsing geometry type from WKB values returns bad values if Zs (and maybe for Ms and ZMs as well)

### ISSUE THREAD

**Issue by davidraleigh** [Toblerity/Shapely#987]
## Expected behavior and actual behavior.

when parsing binary from wkb, I would expect the 4 bytes following the endianness flag byte to be within the range described by the specification ([example](https://en.wikipedia.org/wiki/Well-known_text#Well-known_binary) from Wikipedia of values ranging from `0000` to `3024`). 

for example for a point with z values I should get 1001, but instead I'm getting 2147483649. for a multipolygon with z values I would expect 1006, but instead I get 2147483654

It looks like maybe Z isn't supported in geos for wkb?
https://github.com/libgeos/geos/blob/f43aa53d27b3889823365317fcf4ff45e60dc90f/include/geos/io/WKBConstants.h

## Steps to reproduce the problem.

```python
from shapely.wkb import dumps
from shapely.geometry import Point, MultiPolygon
point = Point(1, 2)
d_point = dumps(point)
endianness = "big"
if int.from_bytes(d_point[0:1], "big") == 1:
    endianness = "little"
self.assertEqual(1, int.from_bytes(point.wkb[1:5], endianness))

multi_polygon = MultiPolygon([(((0.0, 0.0), (0.0, 1.0), (1.0, 1.0), (1.0, 0.0)),
                               [((0.25, 0.25), (0.25, 0.5), (0.5, 0.5), (0.5, 0.25))])])
d_multi_polygon = dumps(multi_polygon)
self.assertEqual(6, int.from_bytes(d_multi_polygon[1:5], endianness))

point_z = Point(1, 2, 3)
d_point_z = dumps(point_z)
self.assertIsNotNone(d_point_z)
self.assertEqual(1001, int.from_bytes(d_point_z[1:5], endianness))

multi_polygon_z = MultiPolygon([(((0.0, 0.0, 0.0), (0.0, 1.0, 0.0), (1.0, 1.0, 0.0), (1.0, 0.0, 0.0)),
                               [((0.25, 0.25, 0.0), (0.25, 0.5, 0.0), (0.5, 0.5, 0.0), (0.5, 0.25, 0.0))])])
d_multi_polygon_z = dumps(multi_polygon_z)
self.assertEqual(1006, int.from_bytes(d_multi_polygon_z[1:5], endianness))
```

## Operating system

Mac OS X 10.15.3

## Shapely version and provenance

`Shapely==1.7.1`

**Comment by mwtoews** [comment]
GEOS only produces [EWKB](https://github.com/postgis/postgis/blob/2.1.0/doc/ZMSgeoms.txt), which is different than ISO WKB that you are expecting. These are the same for 2D, but different for higher dimensions. EWKB needs to be hex-encoded to make any sense:
```python
hex(2147483649)  # 0x80000001 or POINT Z
hex(2147483654)  # 0x80000006 or MULTIPOLYGON Z
```

To get ISO WKB support, you can get this with GDAL/OGR:
```python
from osgeo import ogr
p = ogr.CreateGeometryFromWkt('POINT Z(1 2 3)')
ewkb = p.ExportToWkb()  # this is EWKB -- same as GEOS
iwkb = p.ExportToIsoWkb()

# assume big endian
assert ewkb[0:1] == iwkb[0:1] == b'\x00'

# ISO WKB for POINT Z is 1001
int.from_bytes(iwkb[1:5], 'big')

# EWKB for POINT Z is 1 | 0x80000000 or 0x80000001
hex(int.from_bytes(ewkb[1:5], 'big'))
```
