### ISSUE TITLE
Issue splitting a triangle into two

### ISSUE THREAD

**Issue by guillaumep** [Toblerity/Shapely#989]
I'm having issues trying to split a triangle into two. See this code example:

```python
from shapely.geometry import LineString, Polygon
from shapely.ops import split
poly = Polygon(((0, 0), (10, 0), (5, 5), (0, 0)))
splitter = LineString(((0, 6), (6, 6)))
splitted = split(poly, splitter)
print([list(part.exterior.coords) for part in splitted])
```

I would expect to obtain two polygons, instead I get the original one, with order modified:
`[[(0.0, 0.0), (5.0, 5.0), (10.0, 0.0), (0.0, 0.0)]]`

Is there something I do wrong? Or is the issue with shapely?

## Operating system

Linux (debian testing using Python 3.8)

## Shapely version and provenance

1.7.1 installed from PyPI using pip

**Comment by mwtoews** [comment]
These two geometries are disjoint:
![image](https://user-images.githubusercontent.com/895458/93827219-ef79a780-fcbc-11ea-9c65-0fbc2a0124d7.png)

The splitter must cross the polygon exterior to split it.

**Comment by guillaumep** [comment]
Oh... I had drawn at hand to vizualise but made an error.

Thanks for replying.
