### ISSUE TITLE
Release docs only when pypi has a released package

### ISSUE THREAD

**Issue by dazza-codes** [Toblerity/Shapely#993]
Please update documentation (e.g. 1.8dev) for a package only when it is released to pypi.  This leads developers down a rabbit hole when the latest release cannot be installed from pypi.  For example, a recent feature to `make_valid` geometries is documented but it is not released on pypi.  Since some dev-ops systems we use rely on the binary package releases for shapely (with binary wheels bundled for libgeos), the feature is not yet available without doing a source build.  Of course, development teams will soon get wise to the problem, but it might help if the project does not release documentation for a version until it is published to pypi.

- https://shapely.readthedocs.io/en/latest/project.html is currently publishing 1.8dev, which is not available on pypi.
  - either do not publish that version of the documentation yet or
  - publish the 1.8dev release to pypi

Aside from a source build, is there any easy way to get shapely 1.8dev with a binary-wheel distribution that bundles an anylinux version of the required libgeos?

**Comment by jorisvandenbossche** [comment]
@dazza-codes you are looking at the documentation of the "latest", meaning development version in this case (I personally find this a bit confusing, but it's the standard terminology that readthedocs uses). In the right bottom there is a widget to choose the version of the docs you are looking at, and there you can get the documentation of the latest released version, which is "stable": https://shapely.readthedocs.io/en/stable/project.html

So the the documentation you are looking for is certainly available, and it's also very valuable for contributors that the documentation of the development version is online as well. 
But so maybe the question is then more about which of the two should be the default to show? Right now the home page (https://github.com/Toblerity/Shapely) About and Readme link to the "latest" docs, while it should maybe better link to the "stable" docs?

**Comment by sgillies** [comment]
Just switched the default over to "stable".
