### ISSUE TITLE
Expose GEOSNormalize

### ISSUE THREAD

**Issue by Lucidiot** [Toblerity/Shapely#994]
`GEOSNormalize_r` is the C API for [`Geometry::normalize`](https://geos.osgeo.org/doxygen/classgeos_1_1geom_1_1Geometry.html#a2ea3b58d562bc183e118e2a68f86414d), which reorganizes geometries into 'canonical forms': points in a `LineString` may be deduplicated, members of a collection are sorted by type, points in a polygon's rings or a single `LinearRing` start at the top-left-most point and go clockwise, etc. This can be useful for unit testing or geometry deduplication. This was added [in libgeos 3.0.0](https://github.com/libgeos/geos/commit/9ecb499d71c279f4713f4aa8a2c0e9d4656b0e2c).

I tried to add the method myself but I never really played with `ctypes`, so this was mostly playing around, and I always got `-1` (exception). This method updates the geometry in place and I am not sure if this is a good thing; pygeos [implemented](https://github.com/pygeos/pygeos/blob/7a2798ab8ef43acf59e2023b8cfcb49e6d9384d3/src/ufuncs.c#L257) a wrapper that clones before normalizing.

Note that the `LineString::normalize` implementation has a bug in which the first point of a `LinearRing` *was not* the top-left-most point. It was fixed in [this commit](https://github.com/libgeos/geos/commit/a807833875976a29fbcf509297f4a7a5f837aa09#diff-a6950e44d48810137ee9f1460388168dR323), which is not included in any release yet (probably will be in libgeos 3.9.0). The workaround is to create a polygon using the LinearRing as an exterior ring, normalize the polygon, and get the ring back. Assuming normalize would be added to Shapely, we would get something like this:

```python3
>>> list(Polygon(((8, 8), (8, 5), (8, 5), (5, 5), (5, 8))).normalize().exterior.coords)
[(8, 8), (8, 5), (5, 5), (5, 8), (8, 8)]
>>> list(LinearRing(((8, 8), (8, 5), (8, 5), (5, 5), (5, 8))).normalize().coords)
[(5, 5), (5, 8), (8, 8), (8, 5), (5, 5)]
```

**Comment by tomplex** [comment]
Yes, I have a branch where I was trying to implement normalize and hit a roadblock, I think the same one as you. I never really followed up but I'd love to understand better what's going on as it's blocking an improvement to simplify in #889.

**Comment by jorisvandenbossche** [comment]
Note that by having this already exposed in pygeos, it will be included in Shapely 2.0 (and so should work on shapely geometries in my branch at https://github.com/Toblerity/Shapely/pull/983). One that PR lands, a PR to add it as a method on the Geometry classes would also be very welcome!

Having it also for the next Shapely 1.8 release would also be nice of course.

**Comment by Lucidiot** [comment]
I experimented further and tried to understand the way GEOS error handling works, since it's in C++ and there are actual exceptions, not just `-1`. `errorMessageNew` is called [here](https://github.com/libgeos/geos/blob/master/capi/geos_ts_c.cpp#L286) when an error occurs in many of the functions, including `GEOSNormalize_r`, so this should in theory be caught and sent to the `shapely.geos` logger. However, no matter how hard I tried, I couldn't get anything to be logged to it, even something completely unrelated to GEOSNormalize.

@jorisvandenbossche I saw some comments in #983 about error logging, so that might be related? [Your recent comment](https://github.com/pygeos/pygeos/issues/215#issuecomment-709033349) about `GEOSProject` mentions the same type of error handling as `GEOSNormalize`.

**Comment by jorisvandenbossche** [comment]
@Lucidiot in the end, I was actually mistaken about the error handling in GEOSProject. It was using the normal error handling machinery, but it with a different return value that signals the exception (and that is still something to check in Shapely which return value triggers error checking.

**Comment by jorisvandenbossche** [comment]
Given the overlay changes in GEOS 3.9 (and the need for normalize to get comparable results for GEOS < 3.9), it might be good to still expose `normalize` in Shapely 1.8.

Do we want to add this as a method on the geometry classes? Or as a function in one of the submodules (not directly sure which one would be most fitting. `shapely.ops` ?)

**Comment by tomplex** [comment]
I personally like it as a method on the geometry classes, as there's precedence with other unary topological ops like simplify, buffer, etc. That's where I would look for it as a user of Shapely.

**Comment by sgillies** [comment]
I took this off the 1.8 milestone. Let's save it for 2.0.

**Comment by jorisvandenbossche** [comment]
@sgillies I have an open PR that is ready to merge targetting Shapely 1.8. 
I think it is very useful to add, since with GEOS 3.9 overlay changes you need `normalize` to compare results across GEOS versions (and I also already did the work :-))

**Comment by jorisvandenbossche** [comment]
->  #1090

**Comment by mwtoews** [comment]
I'd like this back on the 1.8 milestone too, as it's ready to merge. `GEOSNormalize_r` has been part of the C API for a very long time (more than a decade?)
